### ISSUE TITLE
Could model objects compute pulse frequencies?

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#100]
For several reasons, such as Doppler fitting of pulsar orbits, and computing residuals in phase units, it would be nice for model objects to have a method that returned the barycentric frequency of the pulsar at a given time (or set of times), computed according to the spin evolution and radial velocity in the binary orbit.

Currently, `resids.get_PSR_freq()` is kind of a hack, because there is no generic mechanism to get the pulsar frequency.  And, for Doppler fitting, I ended up using PRESTO's `binary_psr` code because it has a `radial_velocity` method.

Thoughts on how difficult this might be in PINT?

If this is done, it might also be nice to compute the topocentric observed frequency at an observatory as well.

**Comment by demorest** [comment]
I mentioned this in email, but there is already a TimingModel.d_phase_d_toa() method.  This was intended for making predictors/polycos so should be able to compute pulse freqs at observatories (and presumably barycenter as well).  I don't know what the status of this function (ie, working/not) is.

**Comment by scottransom** [comment]
Doesn't seem to work right now...  I'm looking into it...

Scott

On 02/10/2016 01:11 PM, Paul Demorest wrote:
> I mentioned this in email, but there is already a
> TimingModel.d_phase_d_toa() method. This was intended for making
> predictors/polycos so should be able to compute pulse freqs at
> observatories (and presumably barycenter as well). I don't know what the
> status of this function (ie, working/not) is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nanograv/PINT/issues/100#issuecomment-182508564>.Web
> Bug from
> https://github.com/notifications/beacon/AAIHIk6W0vefKJuZhXdx_RKZQ53aa_-Fks5pi3TOgaJpZM4HVEzH.gif
>

-- 
Scott M. Ransom            Address:  NRAO
Phone:  (434) 296-0320               520 Edgemont Rd.
email:  sransom@nrao.edu             Charlottesville, VA 22903 USA
GPG Fingerprint: 06A9 9553 78BE 16DB 407B  FFCA 9BFA B6FF FFD3 2989

**Comment by luojing1211** [comment]
That function was to get apparent spin frequency at any given time. It was a function to generate polycos. 
This was an early stage code. Since all the updates we have, It could out of date and not working right now. I believe it is not optimised as well. I can update it, but I would like to hear your comments.

**Comment by paulray** [comment]
@luojing1211 - I'd love to have timing model functions that compute apparent spin frequency at an observatory and at the SSB!

**Comment by paulray** [comment]
What is the status on this issue? I think `d_phase_d_toa()` does compute the topocentric apparent spin frequency.
