### ISSUE TITLE
Fix parsing of Parkes clock correction files in $TEMPO/clock/time_pks.dat

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#101]
The clock correction parsing does not handle `time_pks.dat` correctly for MJDs prior to 50844. Special case code needs to be added to deal with this.

**Comment by demorest** [comment]
I just added a function that should parse tempo1 clock files (including the parkes file) correctly.  Will check it in shortly.

**Comment by demorest** [comment]
This is fixed in pull request #103 and ready to be merged in.
