### ISSUE TITLE
Pickle loading TOAs issue

### ISSUE THREAD

**Issue by devbhakt** [nanograv/PINT#1014]
I am generating fake toas and adjusting the fake toas to simulate data. I found that whenever I save them using the save_pickle function and load them back in with load_pickle function, something is going wrong and I get a TypeError: 'NoneType' object is not iterable, when I try to adjust the toas again. Here is a sample test script of what I am doing.

import numpy as np
import astropy
import astropy.time as time
import astropy.units as u
import pint.toa
import pint.models
import pickle

test_model = pint.models.get_model("/git/PINT/examples/NGC6440E.par")
test_toas = fake_toas = pint.toa.make_fake_toas(58000, 59000, 5, model = test_model)
test_toas.adjust_TOAs(astropy.time.TimeDelta((np.random.uniform(0, 1, size = (5,))*1*u.d)))

pint.toa.save_pickle(test_toas, "test_toas.pickle")
test_toas2 = pint.toa.load_pickle("test_toas.pickle")
test_toas2.adjust_TOAs(astropy.time.TimeDelta((np.random.uniform(0, 1, size = (5,))*1*u.d)))

**Comment by luojing1211** [comment]
The pickling does not save the table group information. This is a bug.

**Comment by scottransom** [comment]
@devbhakt After seeing with @luojing1211 said, it looks like your script works if you include:
```
test_toas2.table = test_toas2.table.group_by("obs")
```
right after you load the pickle.  Maybe that is a one-line fix for the bug as well?  i.e. in the load_pickle() method?

**Comment by paulray** [comment]
Yes, that should be in `load_pickle()` I think. But it is strange that pickling a table that is grouped doesn't unpickle into a table that is grouped.  How does that happen?

**Comment by aarchiba** [comment]
The groupedness really doesn't survive pickling, though, I just wrote a test case that tests it, pickling a TOAs object's `.table` directly and unpickling it loses the groupedness:
```python
    with open(p, "wb") as f:
        pickle.dump(test_toas.table, f)

    with open(p, "rb") as f:
        new_table = pickle.load(f)

    assert len(test_toas.table.groups.keys) == 1
    assert len(new_table.groups.keys) == 1
```
```

**Comment by aarchiba** [comment]
Filed as an astropy bug: https://github.com/astropy/astropy/issues/11410
