### ISSUE TITLE
Improve clock correction process and specify whether to use PINT, TEMPO or Tempo2 files

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#102]
For clock corrections, PINT should have the option of reading Tempo2-style clock corrections from $TEMPO2/clock.  In Tempo2, the clock correction chain goes all the way from observatory time to some (specified) realization of TT.  In TEMPO, if I understand correctly, the clock corrections only go from observatory time to GPS (which is assumed to be close enough to UTC for most work, <10 ns).  So, if PINT is given an option to use the Tempo2 clock files, it should probably just use obs2gps.clk and gps2utc.clk, and not go all the way to TT.  In PINT the conversions from UTC to TT and TDB are handled differently (using astropy.time).

**Comment by paulray** [comment]
Telecon 2016 Feb 22:
* Should really make a more structured, sensible framework for clock corrections
* Should handle the case where an observatory has multiple backends, each of which require different clock corrections (e.g. Nancay)
* Should be able to tell PINT if you want to use TEMPO, Tempo2, or PINT-internal clock correction file
* Need to have different ways of updating PINT-internal clock correction files, if we implement them.  Could be kept in sync with TEMPO, or Tempo2, or whatever.

**Comment by luojing1211** [comment]
Hi @paulray,
Does the current new observatory structure fix this problem? PR #189

**Comment by paulray** [comment]
Renamed this since the original issue is solved but the general clock correction issues are still there. @aarchiba was just discussing this on Slack, in fact.

**Comment by paulray** [comment]
Related to #915

**Comment by aarchiba** [comment]
Can we consider this solved now?

**Comment by abhisrkckl** [comment]
Can this be closed?
