### ISSUE TITLE
Editing models in pintk

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1037]
In `pintk` you can edit the model, but how it works can be confusing and some cases don't seem to work.

Say you want to add F3 to a model...

What works is if you start `pintk`
 fresh, open the model editor, add a line that says "F3 0 1" and then click "Apply Changes" then click "Fit".  This is fine.

What does not work:

1. Start `pintk`, run a fit. Then edit the *prefit* model to add "F3 0 1", "Apply changes" then "Fit".  No F3 is added
2. Start `pintk`, run a fit. Then edit the *postfit* model to add "F3 0 1", "Apply changes" then "Fit".  No F3 is added

The files I used for these tests are here.  Rename all.txt to all.tim and F2.txt to F2.par:

[all.txt](https://github.com/nanograv/PINT/files/6393538/all.txt)
[F2.txt](https://github.com/nanograv/PINT/files/6393539/F2.txt)

**Comment by champagne-cmd** [comment]
I'm not sure if this will solve the above, but one problem that is contributing to the dissonance between the model editor and the PlkWidget is that after you click 'Reset' under the graph, the PlkWidget creates an entirely new pulsar object to store in 'self.psr'. When originally created in the pintk script, PlkWidget and the model editor held the same pulsar widget in each of their respective 'self.psr' attributes. Within the reset function of the PlkWidget, however, the line `self.psr = copy.deepcopy(self.base_state.psr)` (line 664 in plk.py) creates a new pulsar object based off the base state, disconnecting the pulsar controlled by the model editor from the one controlled by the rest of pintk. I'm not sure whether it would be better to return the pulsar object after this operation and route it to the model editor or update the PlkWidget pulsar without creating a new pulsar object.

**Comment by champagne-cmd** [comment]
I believe this issue can be closed @paulray ?
