### ISSUE TITLE
Can not import Cache

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#104]
Hi folks, 
I was trying to use cache in parameter.py. But if failed to import. Do you have any idea what is happening? Thank you. 

ERROR: Failure: ImportError (cannot import name Cache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jingluo/anaconda/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/jingluo/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/jingluo/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/jingluo/Research_codes/PINT/tests/test_parameters.py", line 1, in <module>
    from pint.models import parameter as p
  File "/Users/jingluo/Research_codes/PINT/pint/models/__init__.py", line 5, in <module>
    from .timing_model import TimingModel, generate_timing_model
  File "/Users/jingluo/Research_codes/PINT/pint/models/timing_model.py", line 4, in <module>
    from .parameter import strParameter
  File "/Users/jingluo/Research_codes/PINT/pint/models/parameter.py", line 16, in <module>
    from .timing_model import Cache
ImportError: cannot import name Cache

**Comment by luojing1211** [comment]
Does any have the same problem? If this issue get resolved, the parameter opt2 branch will be ready for merging.

**Comment by paulray** [comment]
Can  you give a specific code example that causes this issue?

**Comment by luojing1211** [comment]
In the parameter.py file I have
```
from .timing_model import Cache
```
But when I ran test in the tests directory,  it returns the error. 
But in the pint/models directory same directory as parameter.py, we have astrometry.py it has the line:
```
from .timing_model import TimingModel, MissingParameter, Cache
```
And it works. Is there anything I forget to setup?

**Comment by luojing1211** [comment]
I think I understand why. I was doing Circular import dependency. Timing_model imports parameter at the same time parameter is importing timeing_model.

**Comment by paulray** [comment]
That is fine with me, but @demorest wrote Cache, so he should probably weigh in

**Comment by demorest** [comment]
I don't think this has anything to do with Cache specifically, it sounds like the problem was the circular import.  As a separate issue it would be worthwhile to take a look at everywhere Cache is being used to see it it is used correctly, and if it is even needed any more.

**Comment by paulray** [comment]
I agree with @demorest - @luojing1211 can you avoid using Cache in your parameter code, or do you really need it? In general, optimizations like caches can make code more obscure and debugging more difficult so they should be avoided unless really necessary (as documented empirically by profiling, not by what the programmer "thinks" is needed). This was the case when Paul wrote Cache because of the multiple evaluations needed, but since then a different optimization was found (storing TOAs in Tables), so the current Cache mechanism may not even be needed.

My general rule is: code first for correctness, simplicity, and readability.  And, only later optimize the code for speed where needed.

**Comment by luojing1211** [comment]
I can totally avoid cache in Parameter.py. The reason why I am using it is because in prefixParameter class method
```
#@Cache.cache_result
def get_par_type_object(self):
      par_type_class = self.type_separator[self.type_match][0]
      obj = par_type_class('example')
      attr_dependency = self.type_separator[self.type_match][1]
      for dp in attr_dependency:
            if hasattr(self, dp):
                prefix_arg = getattr(self, dp)
                setattr(obj, dp, prefix_arg)
      return obj

    #@Cache.use_cach
 def set_value_prefix(self, val):
        obj = self.get_par_type_object()
        result = obj.set_value(val)
        return result
``` 
in order to call the set_value function, an example class has to be built. Using cache would make sense.

**Comment by luojing1211** [comment]
I think this can be closed.
