### ISSUE TITLE
Add observatory metadata content

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1048]
We put in a facility (#790) to allow observatories to have metadata describing where/when the info comes from.  But it looks like it isn't uniformly used.  We should have a guide for how to add an observatory and include this as part of it.

**Comment by aarchiba** [comment]
Among other things this could naturally include instructions on how to get updated clock corrections?

**Comment by aarchiba** [comment]
Oh is *that* what "origin" is supposed to be? Filling this out would be a natural addition to #1050 .

**Comment by dlakaplan** [comment]
Yes, that was my intent, although now that you mention it I can see the ambiguity (origin of information vs. coordinate origin).  

And yes, this would work well with #1050   

At some point I had hoped to move the observatory info to a non-python format (#793).  Probably should keep that separate but would be happy to discuss.

**Comment by aarchiba** [comment]
A non-python format would resolve import-time headaches, certainly, and could be done transparently to users - the file would be installed alongside PINT (there's a mechanism for this in setuptools) and would be read in upon first call of Observatory.get(). Easiest transition path would be to simply use json to store a dictionary of the arguments to the TopoObs constructor, though ultimately with such a setup one could remove the class auto-registration stuff. But a different PR would be better.

**Comment by aarchiba** [comment]
Now added `origin` strings to #1050. So far they're just human-readable, and generally just say "origin unknown" though they describe comparison with TEMPO/TEMPO2 where applicable.

**Comment by dlakaplan** [comment]
Agreed about a different PR
