### ISSUE TITLE
Objects containing Parameters cannot be pickled

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1076]
Because Parameters internally store lambda functions, they cannot be pickled, and by extension `TimingModel` objects cannot be pickled. This complicates use of multiprocessing, and there is no reason it should not be possible to pickle them.

Tests in #1071 but the fix is a bit more complicated.

**Comment by aarchiba** [comment]
The problem is that `prefixParameter` objects take function arguments to determine their descriptions and units as a function of the index. These are, in many cases, lambda functions, which cannot be pickled.

The easiest way to fix this is to just take all the lambda functions and put the code in named functions. A longer-term fix would be to improve the way prefix and mask parameters are created and used; see #1092 for thoughts on how this could be done.

**Comment by dlakaplan** [comment]
Should be closed by #1140
