### ISSUE TITLE
pintk help is double-spaced

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1078]
For some reason the "help" output (is there any way to find out from the GUI that help is available, and that it appears in the terminal?) appears double-spaced:
```
The following interactions are currently supported by the Plk pane in the PINTkinter GUI:

Left click:     Select a point

Right click:    Delete a point

r:              Reset the pane - undo all deletions, selections, etc.

k:              (K)orrect the pane - rescale the axes

f:              Perform a fit on the selected points

d:              Delete the highlighted points

u:              Undo the most recent selection

c:              Clear highlighter from map

j:              Jump the selected points, or unjump them if already jumped

v:              Jump all TOA groups except those selected

i:              Print the prefit model as of this moment

o:              Print the postfit model as of this moment (if it exists)

p:              Print info about highlighted points (or all, if none are selected)

m:              Print the range of MJDs with the highest density of TOAs

+:              Increase pulse number for selected points

-:              Decrease pulse number for selected points

>:              Increase pulse number for all points to the right of selection

<:              Decrease pulse number for all points to the right of selection

h:              Print help

```

**Comment by scottransom** [comment]
Yeah, we should definitely ditch the double spacing.  As for "can you figure out if there is help in the GUI", I'd say yes since there is a "Help" pull-down menu which let's you choose "Plk Help" (although why it says "Plk" and not "pintk" is a bit strange...).

**Comment by paulray** [comment]
And it should also give a bit of a general introduction to pintk operation before launching into the key bindings

**Comment by aarchiba** [comment]
A few notes about the "Help" menu:
- Output to the terminal from GUI programs is somewhat unusual, and many users operate windows maximized, so some indication that the help button that apparently does nothing actually produced output in the terminal you started pintk in would be good.
- The About does not include version numbers; that is the point of About boxes. They can also point to further documentation with hyperlinks.

**Comment by paulray** [comment]
This was fixed by @scottransom
