### ISSUE TITLE
Feature request for pintk to add pulse numbers

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1080]
I'd like a "Assign Pulse Numbers" button added to pintk, so you can click it to assign pulse numbers then have all subsequent fits use those assigned pulse numbers so you won't lose phase connection when tweaking model parameters.

**Comment by aarchiba** [comment]
TOAs objects already have the `toas.compute_pulse_numbers(model)` function, which `Residuals` by default respect upon construction (provided all TOAs have pulse numbers). PINT cannot currently cope with partial sets of pulse numbers - there's some complications in there related to PINT's difficulties with absolute phase. But adding pulse numbers should be just a matter of plumbing this to the GUI.

**Comment by paulray** [comment]
@scottransom is this resolved with your recent changes? Maybe no button is needed?

**Comment by scottransom** [comment]
This already works in `pintk` via selections and various key strokes ("+", "-", "<", ">").  See the help (via "h") for details.

**Comment by paulray** [comment]
Yep, I just tested by adding a big F2 to NGC6440E and indeed there were no phase wraps!  Sweet!
I do get confused about the Pre-fit/Post-fit models in the model editor and which one to change and what "Apply Changes" does.  If I change the prefit model and click "Apply" it changes the postfit residuals but not the prefit residuals. I'm not quite following what the workflow should be when iterating fits.

**Comment by scottransom** [comment]
@paulray You shouldn't need to get in the model editor at all for most things (including phase-connecting most pulsars).  But if for some reason you do, after an "Apply Changes" I think you basically always want to hit "Refit" to make sure that everything is applied as you think it should be.  I did fine something strange, though, after using "Apply Changes" (or any of the Center *epoch buttons):  some of the non-fit values in the parfile (like the next available spin-freq deriv) get turned on for fitting automatically.  And we certainly don't want that.  That will take some digging to solve as it isn't obvious to me why it is even happening, based on a quick look through the code.
