### ISSUE TITLE
setup.py not complete

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#110]
Looks like we need to update setup.py.  The list of modules it installs is not complete:

```
    py_modules = ['pint.models.timing_model', 'pint.models.model_builder',
        'pint.models.astrometry', 'pint.models.glitch',
        'pint.models.dispersion', 'pint.models.spindown',
        'pint.models.parameter', 'pint.fitter',
        'pint.ltinterface',
        'pint.models.solar_system_shapiro',
        'pint.models.btmodel', 'pint.models.polycos',
        'pint.models.bt', 'pint.models.dd',
        'pint.orbital.kepler'],
```

I hadn't noticed this since I have never installed PINT with setup.py. I just use it out of the dev directory, but non-dev  users should be able to install it with `python setup.py install --user`

**Comment by physicsranger** [comment]
I had to add the following to py_modules
'pint.models.priors','pint.models.pint_dd_model','pint.models.pulsar_binaries.DD_model','pint.models.pulsar_binaries.pulsar_binary','pint.models.pint_pulsar_binary'
however, I couldn't do this to get parfile.py or psr_utils.py, modules that some of the examples require.

**Comment by paulray** [comment]
Those last two are part of PRESTO.  I guess we should consider if it is OK for PINT examples to assume PRESTO is installed, or if we should incorporate those modules into PINT? @scottransom ?

**Comment by demorest** [comment]
I haven't looked at this yet, but do we really need to list all those modules explicitly in setup.py?  Is there not some kind of "install everything" option we should just use?

**Comment by physicsranger** [comment]
My apologies, I forgot to install presto as well.

**Comment by scottransom** [comment]
Hmmm....  I don't think that psr_utils.py or parfile.py are used anywhere in PINT itself.  But only in one or two of the examples (which is probably OK).  Would possibly be OK to have in the tests as well (since to test things properly we need to compare against TEMPO and TEMPO2 and so have extra dependencies).

**Comment by demorest** [comment]
That's funny, I was about to express the opinion that our standard set of tests should _not_ depend on any external packages.  As you say, right now many depend on tempo, tempo2, tempo_utils, libstempo.  If we want to compare against tempo/tempo2-generated data that's fine but I think the test should be self-contained and not require these extra packages be installed.  This is both for convenience and to make sure the tests are not affected by new bugs that appear in tempo/tempo2 (probably not too likely but you never know).

**Comment by luojing1211** [comment]
Currently PINT still needs tempo for the clock correction files. So PINT is
still depend on TEMPO on a very small degree.

**Comment by demorest** [comment]
Yeah, that should probably change also.

**Comment by paulray** [comment]
I agree with @demorest that if a test is comparing to results from TEMPO or Tempo2, those results should be generated and stored in a data file and not generated dynamically, so we don't depend on having those installed to run the test.

**Comment by scottransom** [comment]
I don't think I disagree with you guys at all.  I don't think our standard tests should have external dependencies.  But I think some testing code which does advanced tests could depend on other things.  And I'd prefer that it be dynamic so that it is comparing current versions of TEMPO and/or TEMPO2!  But once again, these don't need to be standard tests.

**Comment by demorest** [comment]
I just pushed a change directly into nanograv/master that fixes this and simplifies setup.py.  In short, py_modules is gone, and packages is updated to contain a list of all subdirectories that need to be installed.  This seems to work for me, but would be good if @paulray or someone could confirm on their system then we can close this.

**Comment by paulray** [comment]
Agree.  Closing.
