### ISSUE TITLE
PINT doc builds execute all notebooks

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1107]
Currently every time you do `make docs` or `(cd docs && make html)` the slowest part of the process is executing all the notebooks for inclusion in the docs by `nbsphinx`. 

Handling the notebooks better is a very good idea - it was such a blessing during the (lengthy) troubleshooting for #1105 not to have to wait for them to execute. I should say, making running the notebooks part of our CI is very valuable for catching breakages that come up in practical use but that we don't have great tests for. Also having the notebooks run during doc build means they're never out of date with respect to the code they are supposedly documenting. But providing a way for users working on the docs to save building the notebooks would be a big help.

Ideally `nbsphinx` could be persuaded not to execute the notebooks but to just include them as-is; again ideally one could use `make notebooks` to build and execute the notebooks locally, and `nbsphinx` would then include them without execution. If they were missing, still ideally, `nbsphinx` would build and execute them as it does now. This would allow users to manage notebook freshness themselves ("oops I changed the fitter messages, better rerun them") while obtaining reasonable facsimiles of the complete docs. This might well be achievable with clever Makefile authoring (Sphinx uses a Makefile build method.)

**Comment by abhisrkckl** [comment]
There is a now a `htmlnoexamples` target that does this. 
See #1519
