### ISSUE TITLE
PINT does not work with (or use) pathlib objects

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1108]
Since python 3.4, python has had Path objects that greatly facilitate many filesystem operations:
```python
(a_path / "file.par").rename(a_path / "old_file.par")
```
They are accepted by many basic Python functions (like `open`) in place of pathname strings, but they are not accepted by most PINT functions that operate on paths. Using them might also simplify many of those same PINT functions, at the least getting rid of `os.path.join` in favour of `/`.

Pathlib docs: https://docs.python.org/3/library/pathlib.html

**Comment by scottransom** [comment]
Interesting!  I did not know this.  So many features / docs, so little time...

**Comment by aarchiba** [comment]
I know. I've been vaguely aware of it for a long time but never really investigated. But more packages are using it, and I ran into a situation where PINT functions broke because they got a Path rather than a string specifying the input file.
