### ISSUE TITLE
Utils.py can break if you don't have a git config file

### ISSUE THREAD

**Issue by devbhakt** [nanograv/PINT#1109]
I ran event optimize and received this error because I did not have a git config file. After making a git config file, the code worked

![Screenshot 2021-08-02 111313](https://user-images.githubusercontent.com/70767588/127889205-f87bd7b9-e3f3-4f02-b6d5-1f21e449fc0f.png)

**Comment by paulray** [comment]
Looks like the `except` on line 1500 of utils.py should also catch `NoSectionError`

**Comment by paulray** [comment]
@devbhakt can you try the proposed fix and see if that solves the problem?

**Comment by devbhakt** [comment]
@paulray Yes, adding in ```configparser.NoSectionError``` into the ```except``` on line 1500 clears the issue. I'll submit a pull request now
