### ISSUE TITLE
Have models be able to compute orbital phase

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#111]
Model objects should be able to compute orbital phase, for example so you can plot residuals vs. orbital phase.

This requires having a clear definition of what orbital phase means.  Also, this is related to the hoped-for general capability to have binary delay models be able to work with different orbital phase specifications (e.g. PB, PBDOT vs FB0, FB1, FB2, ...)

**Comment by luojing1211** [comment]
This work has been implemented by PR #356. Can we close this issue?
