### ISSUE TITLE
Keep LICENSE.md and AUTHORS.rst up to date

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1111]
Currently `LICENSE.md` is through 2017, and author list is also old.  How to regularly update those?

**Comment by paulray** [comment]
Good question. Perhaps we could try to update LICENSE.md when we tag a release. Not sure about authors.
The current claim that the PINT paper authors are the "Development Leads" is getting increasingly out of date as many of those people have left the project.

**Comment by abhisrkckl** [comment]
AUTHORS.rst updated in #1450

**Comment by abhisrkckl** [comment]
Licence updated in 7387f337f6dbb56db863f51238411f9b5433be05
