### ISSUE TITLE
Faking TOAs: zima vs. PINT

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1122]
I'm investigating the two ways to fake TOAs: `pint.toa.make_fake_toas` and `zima`.  So far I don't see them as consistent. 

Procedure: calculate fake TOAs for a simple setup with (hopefully) identical input parameters.  Compare results.

A few notes: inside `zima`, it repeatedly calculates residuals manually via:
```
F_local = m.d_phase_d_toa(t_zima)
r_zima_manual = m.phase(t_zima).frac / F_local
```
It then uses those to adjust the TOAs.  So, just to make sure that's not the issue I am using that method together with the packaged `pint.residuals.Residuals` method.  Note that I'm doing this for the standard `'NGC6440E.par`, so a very simple model.

Commands (20 TOAs, 1 us error):
```
t_pint = make_fake_toas(55000, 58000, 20, model=m, freq=1400 * u.MHz, dm=10 * pint.dmu, obs='GBT')
t_pint.adjust_TOAs(TimeDelta(error * np.random.randn(len(t_pint))))
```
And zima:
`zima --freq 1400 --error 1.0 --ntoa 20 --startMJD 55000.00000000675 --duration 2999.9999999875 --ephem DE421 --obs GBT .../NGC6440E.par zima.tim`

Results.  Note that the 
```
PINT rms (manual calculation): 1.9251282477811997 us
ZIMA rms (manual calculation): 8240.313330113022 us
PINT rms (PINT calculation): 0.9677796770673149 us
ZIMA rms (PINT calculation): 5148.585677973798 us
```
Using the "manual" style residual calculation is worse than the standard `pint` version.  By about a factor of 2. The PINT/PINT version gives the expected 1us rms.

I also followed the `zima` script in plotting the residuals.  The PINT-generated values seem OK: with the "manual" style residuals there is an offset, but they are flat.  The zima-generated values are all over the place.  If I run zima and use `--plot` its output looks similar.

![random_toas](https://user-images.githubusercontent.com/5092062/129224296-3e317006-4631-4f0f-8e44-b0f90590e843.png)

**Comment by paulray** [comment]
Yes, I was just using zima to make some fake TOAs for testing pintk. It seems buggy. Something is broken in it. This is a very good reason to have it use `make_fake_toas()`, which can be tested in CI.

**Comment by dlakaplan** [comment]
Based on this, I don't trust `zima`.  It seems to do things roughly similar to `make_fake_toas`, but has various warnings (say about clock corrections) and alternate calculations (for the residual calculation) that make me suspicious without investigating in detail.  So I would suggest we switch the guts of `zima` to use `make_fake_toas`.  However, it's also possible that there is some user error.  Would appreciate feedback from regular users (@paulray ?)

**Comment by dlakaplan** [comment]
Note that `zima` does only the most basic error addition (no EFAC or EQUAD).  So that would be trivial to implement (optionally) in `make_fake_toas`.

**Comment by dlakaplan** [comment]
@paulray : if you agree that we should switch the guts of `zima` I can start work on that.

**Comment by paulray** [comment]
Yes, definitely
