### ISSUE TITLE
Is something wrong with calculate_random_models?

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1130]
The simple script below (adapted from the comments in the code), makes random models and plots them with the data.
This seems to show that the scatter in the model is much too large.  In the previous implementation, the variation between the models was small enough that all of the models were consistent with the data.  In this case the scatter seems much too big. Is something wrong or am I misunderstanding `calculate_random_models()`?
```
from pint.models import get_model_and_toas
from pint import fitter, toa
import pint.utils
import io
import astropy.units as u
import matplotlib.pyplot as plt
from astropy.visualization import quantity_support

quantity_support()

# the locations of these may vary
timfile = "tests/datafile/NGC6440E.tim"
parfile = "tests/datafile/NGC6440E.par"
m, t = get_model_and_toas(parfile, timfile)
# fit the model to the data
f = fitter.WLSFitter(toas=t, model=m)
f.fit_toas()

# make fake TOAs starting at the end of the
# current data and going out 100 days
tnew = toa.make_fake_toas(
    t.get_mjds().min().value, t.get_mjds().max().value + 100, 50, model=f.model
)
# now make random models
dphase, mrand = pint.utils.calculate_random_models(f, tnew, Nmodels=100)

plt.errorbar(
    f.toas.get_mjds(),
    f.resids.phase_resids,
    yerr=(f.toas.get_errors() * f.model.F0.quantity).to(u.dimensionless_unscaled).value,
    fmt=".",
)
for i in range(100):
    plt.plot(tnew.get_mjds(), dphase[i, :], color="black", alpha=0.25)

plt.show()
```
![random_models](https://user-images.githubusercontent.com/1771428/129977873-9cc61bae-c402-428f-b388-a36d4871b2c3.png)

**Comment by champagne-cmd** [comment]
Here is the working plot w/ random_models.py:
![image](https://user-images.githubusercontent.com/54611898/129978610-22652b0e-7c05-43a7-b69a-114a640e0d37.png)

**Comment by paulray** [comment]
@dlakaplan can you take a look at this?

**Comment by dlakaplan** [comment]
This is all due to uncertainties in the DM value, although I don't fully understand it yet because it does not depend on the frequency of the TOAs.

**Comment by dlakaplan** [comment]
If you set:
`m.DM.frozen = True`
before fitting, then you get a plot much like the one you are after.

**Comment by dlakaplan** [comment]
OK, I think in the fit the phase zero-point is 99% anti-correlated with DM:
```
In [39]: f.parameter_correlation_matrix
Out[39]: 

Parameter correlation matrix:
             Offset       RAJ       DECJ        DM         F0         F1     
  Offset     1.000e+00
    RAJ      2.479e-02  1.000e+00
   DECJ     -5.713e-02 -7.222e-02  1.000e+00
    DM      -9.953e-01 -4.968e-03  6.482e-02  1.000e+00
    F0      -9.094e-03 -8.730e-02  2.471e-01  6.743e-03  1.000e+00
    F1      -1.942e-02  2.943e-01 -3.439e-01  5.756e-02 -7.977e-01  1.000e+00
```
So when DM is free you are getting large fluctuations in the phase zero-point even with infinite frequency.  Those manifest as phase shifts which look like what you see above.

**Comment by dlakaplan** [comment]
Without DM, you are primarily left with the position uncertainty which leads to the annual modulation in the residuals.

**Comment by paulray** [comment]
I thought the random models method accounted for those correlations somehow?  It seems like all the realizations of random models should be consistent with the data, if it is working as we intended.

**Comment by dlakaplan** [comment]
The random models method now does account for the correlations.  I'm not sure it did in the past because of issues with how the covariance matrix was indexed.  The models looks consistent with the data to me, although I haven't looked at many of these plots.

**Comment by paulray** [comment]
My understanding is that "consistent with the data" would mean that the chisq computed for any of the random models would be about as good as the chisq for the best fit model (meaning the models can't really be distinguished).  Many of the lines in the top plot would have terrible chisq values with respect to the data points, so that seems wrong to me.

**Comment by dlakaplan** [comment]
The chi^2 from the real fit is 59.6. If I fit all of the fake models they have almost identical values.  But this is after a fit.  Once you fit out the constant phase it looks almost identical to what you are showing above, and has basically the same chi^2.

If you specify `params=['RAJ','DECJ','F0','F1']` to  `calculate_random_models` it will not include the DM terms in the covariance matrix, and will again end up with something more like what you are looking for.

**Comment by dlakaplan** [comment]
There's still something bugging me, but I have meetings coming up so will need a little time to sort through this.

**Comment by paulray** [comment]
OK, for @champagne-cmd using this in pintk, it seems like the solution is to subtract the mean residual from the random model before plotting them.

**Comment by scottransom** [comment]
That last solution idea (subtracting the mean residual from the random model) might be the right thing to do -- because we are actively fitting for the absolute phase for each model under the hood, but that absolute phase isn't plotted in the residuals (it defines the zero residual).  So perturbations away from that due to covariances in the other random models will show up as absolute phase offsets.  And we don't really want to see those!  (would be nice if there was a way to show them if you really want them).

**Comment by dlakaplan** [comment]
So what was confusing me is that we explicitly remove the phase zero-point from the random model calculation.  So I didn't understand why the DM was affecting the phase.  Still not quite there, but I found that if you set:
`m.TZRFRQ.quantity = 1e9*u.MHz`
and
`freq=1e9*u.MHz` in `make_fake_toas_uniform`
then the phase offsets go away.  But if either one of them is set as normal then the phase offsets persist.

So it's definitely due to the DM and some covariance, but I don't quite get how.

If you only allow DM to vary (`params=['DM']`) then the residual phases are constant offsets.

**Comment by scottransom** [comment]
Huh.  That is indeed strange....

**Comment by dlakaplan** [comment]
If you vary `TZRFRQ` and look at the residuals, it agrees with a nu^-2 line for low frequencies.  Above that it flattens out.
<img width="580" alt="Screen Shot 2021-08-19 at 10 50 07 AM" src="https://user-images.githubusercontent.com/5092062/130100755-1c48ef3e-6f55-4d4a-bb73-039d70771747.png">

But I can't get the value to make sense.  I am trying to compare:
`4e6 ms * DMuncertainty / f(MHz)^2`
with the residuals but it's off by a factor of 10 (too high).  Am I making an obvious error?

**Comment by dlakaplan** [comment]
And the same behavior from varying the TOA frequency (with TZRFRQ constant). However, if as TOA frequency -> TZRFRQ the residuals go to 0.

**Comment by dlakaplan** [comment]
(and `1/freq^2 - 1/TZRFRQ^2` doesn't fix the offset)

**Comment by champagne-cmd** [comment]
with the mean residual of each random model subtracted out:
![image](https://user-images.githubusercontent.com/54611898/130106324-d8c5311a-ab68-4f28-b498-bb826704b0d3.png)

**Comment by dlakaplan** [comment]
OK, the delays actually agree with what you expect.  I was using the wrong uncertainty.  So the absolute phase variations are:
`4.15e6 ms * DM_error * (1/toafreq^2 - 1/TZRFRQ^2) * F0`
If you set both of those frequencies to infinity, there is no delay.  And if they exactly agree it also cancels.  But otherwise I think this makes sense to me.

**Comment by dlakaplan** [comment]
@champagne-cmd : I'm plotting:
`plt.plot(tnew.get_mjds(), dphase[i, :] - dphase[i].mean(), color="black", alpha=0.25)` in the example from Paul above, I get smaller scatter.
<img width="582" alt="Screen Shot 2021-08-19 at 12 27 39 PM" src="https://user-images.githubusercontent.com/5092062/130115742-a34a5a97-1ccf-4837-b6fc-142077f78528.png">

**Comment by dlakaplan** [comment]
So given my (fixed) analysis above of the DM uncertainties, I think this all works as expected.  @paulray : can we close the issue?

**Comment by paulray** [comment]
Will do, as soon as we get the random models feature in pintk working with this. Thanks for digging into this!
