### ISSUE TITLE
gridutils has indexing error

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1135]
In `gridutils`/`grid_chisq`:
```
chi2 = np.zeros((len(par1_grid), len(par2_grid)))
    # Want par1 on X-axis and par2 on y-axis
    for ii, par1 in enumerate(par1_grid):
        getattr(ftr.model, par1_name).quantity = par1
        for jj, par2 in enumerate(par2_grid):
            getattr(ftr.model, par2_name).quantity = par2
            # Array index here is rownum, colnum so translates to y, x
            chi2[jj, ii] = ftr.fit_toas()
            ...
```
so it looks like `chi2` is initiated as being size (par1, par2) but then filled according to (par2, par1).  This is an easy fix, but I don't know if this was ever used (there are no tests for it).  If par1,par2 were the same size it wouldn't have come up.

**Comment by paulray** [comment]
I definitely have used the gridding utilities for the J0740 mass work

**Comment by dlakaplan** [comment]
Was it correct?  Did you verify that the row and column indexing was OK?

**Comment by paulray** [comment]
I don't recall. I think I must have used equal numbers of rows and columns.  I'll try to find my notebooks.

**Comment by paulray** [comment]
Yes, that is the case. I have a ReproduceCromartie notebook that analyzes the data from Cromartie et al with PINT and does the gridding to make the plot from her paper. I can share it if you want.

**Comment by dlakaplan** [comment]
Did you have to do any axis flips to get the plot to look right?  Or if you change one of the axes to have a different length, does it still work?

**Comment by paulray** [comment]
Also made this little benchmarking script for when I was testing in out:
```
#!/usr/bin/env python

import pint.toa
import pint.models
import pint.fitter
from pint.gridutils import grid_chisq
import numpy as np
import astropy.units as u

# Get .tim file and par file from here:
# curl -O https://data.nanograv.org/static/data/J0740+6620.cfr+19.tim
# curl -O https://data.nanograv.org/static/data/J0740+6620.par

# This will load the TOAs, compute the positions of the Earth and planets, and apply clock corrections and build the table.
thanktoas = pint.toa.get_TOAs("J0740+6620.cfr+19.tim",ephem="DE436",planets=True,
                              usepickle=False,include_gps=True, bipm_version="BIPM2017", include_bipm=True)

# Load model
thankmod = pint.models.get_model("J0740+6620.par")

# Fit one time
thankftr = pint.fitter.GLSFitter(toas=thanktoas,model=thankmod)
chisq = thankftr.fit_toas()

# Fit 5 x 5 grid of chisq values
sini_grid = np.sin(np.linspace(86.25*u.deg,88.5*u.deg,5))
m2_grid = np.linspace(0.2*u.solMass,0.30*u.solMass,5)
thankftr_chi2grid = grid_chisq(thankftr,"M2", m2_grid, "SINI", sini_grid)

print("Done")
```

**Comment by dlakaplan** [comment]
If I change:
```
sini_grid = np.sin(np.linspace(86.25*u.deg,88.5*u.deg,5))
```
to
```
sini_grid = np.sin(np.linspace(86.25*u.deg,88.5*u.deg,4))
```
I indeed get an `IndexError`

**Comment by paulray** [comment]
Gotta run now. Back to this later.

**Comment by paulray** [comment]
This script runs the MP version of the grid and it works on my machine.

The needed par and tim files are here: https://data.nanograv.org

[ReproduceCromartie.ipynb.zip](https://github.com/nanograv/PINT/files/7080057/ReproduceCromartie.ipynb.zip)

**Comment by dlakaplan** [comment]
I can't run it on my Mac using the main branch of PINT.  
```
AttributeError: Can't pickle local object 'DispersionDMX.add_DMX_range.<locals>.<lambda>'
```
which is expected (I thought).  Is there some version mismatch?

I do think that the array indexing is flipped - I could reproduce that with your little (faster) sample script.

**Comment by paulray** [comment]
I believe you that there is an indexing mess up.  
I'm using Python 3.7.10

**Comment by dlakaplan** [comment]
I can also get it to work with 3.7, but not 3.8 or 3.9.  I don't know what the expected long-term support is.

**Comment by dlakaplan** [comment]
I've changed the implementation of the MP version to use a different library and to run a single fit per process (rather than a row).  That seemed easier to allow arbitrary dimensionality.  But now I'm investigating speed questions:

| Grid | MP version | Time | 
| ---- | ----------- | ---- |
| 3x3 | python3.7/single process | 78 |
| 3x3 | python3.7/multiprocessing | 28 | 
| 3x3 | python3.8/pathos | 61 |
| 5x5 | python3.7/single process |  235 |
| 5x5 | python3.7/multiprocessing | 67 |
| 5x5 | python3.8/pathos | 159 | 

So all scale roughly with the size of the grid (at least as far as these tests go) but the old version is considerably faster.  Before I go further I'd like to understand the tradeoffs.

**Comment by paulray** [comment]
@scottransom has looked at python multiprocessing, maybe he has thoughts on this?

**Comment by scottransom** [comment]
I'm pretty surprised that multiprocessing and pathos are so different.  I'm assuming the number of procs was the same in each case?

**Comment by paulray** [comment]
The pathos times are just barely better than single process. Like it isn't really running much in parallel.

**Comment by dlakaplan** [comment]
There is a difference in approach.  

The multiprocessing did one job per column (of a 2D grid).  So the total number of jobs was closer to the number of cores.  And the actual interface sort of ran its own process stack (polling for completion).

The pathos did one job per cell, since it doesn't assume a 2D grid.  So the total number of jobs was > number of cores (I do know that at least 4 jobs were running in parallel).  And they were all started at once and managed internally (using `Pool.map`).   There was a `Pool.map` interface for the normal multiprocessing but it was slightly different, so that my quick attempt at using that for comparison didn't work.  I might try it again.

I don't know enough about the internals to know if the `Pool.map` interface is inherently better/worse than the manual stack.  

I could probably rewrite things so that the pathos interface does one job per lowest dimension (just have to change around the iterator).  That might be faster.

**Comment by dlakaplan** [comment]
https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods discusses changes in the multiprocessing module between 3.7 and 3.8 that might be responsible for the issues I'm seeing (the compatibility issues, not the speed issues).

**Comment by dlakaplan** [comment]
Also https://chrissardegna.com/blog/multiprocessing-changes-python-3-8/

**Comment by aarchiba** [comment]
I highly recommend using `concurrent.futures` and passing in an Executor (see my comments on PR #1136 ). Also we have identified the pickleability problem in #1076 and it could be fixed fairly easily.
