### ISSUE TITLE
v0.8.3 missing CHANGELOG update

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1149]
The new v0.8.3 CHANGELOG does not have an entry for the changed observatory positions. This should be added.

It has also not been uploaded to PyPI or conda-forge

**Comment by scottransom** [comment]
While it is possible to change a published tag, [it isn't recommended](https://stackoverflow.com/questions/21459540/add-new-commit-to-the-existing-git-tag). So we should just push the doc changes and tag 8.3.1 and send that to PyPi.  And we should probably do this ASAP.

**Comment by paulray** [comment]
This has now been fixed with version 0.8.4 which is tagged and released at PyPI. That should soon propagate to conda-forge.
