### ISSUE TITLE
Table-like outputs should be Markdown tables

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1152]
When pint generates table-like output, for example `model.compare(other_model)`, the formatting often fails to align properly, and can be hard to work with. If instead PINT generated Markdown tables - mostly just a question of producing `|` between columns - these would look no worse in fixed-width ASCII but could also be fed to Markdown processors and made to look like proper HTML tables in places like the Jupyter notebook.

https://www.markdownguide.org/extended-syntax/#tables

**Comment by abhisrkckl** [comment]
This feature is available in the `TimingModel.compare` method.
