### ISSUE TITLE
Observatory clock correction are not applied to the simulation.

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#1161]
https://github.com/nanograv/PINT/blob/e0cc5b9fce4f108c243ba4b5285cae4f4da746c3/src/pint/simulation.py#L83
The current simulation code does not apply the sit correction to the TOAs. If we use the PINT simulated TOAs in TEMPO/TEMPO2, the result will be wrong.

**Comment by scottransom** [comment]
Shouldn't they be wrong in PINT as well?

As for what should be happening, for the simulated observatory, we should apply clock corrections, do the calculations that create zero-residual TOAs for our input model, and then remove the clock corrections from the TOAs, right?  (Or at least that should be the default if we write out those TOAs).

**Comment by luojing1211** [comment]
I don't think we have any tests that do the round-trip-- simulate TOAs, writes to parfile, and then reads back to PINT.
