### ISSUE TITLE
If the Proper Motion parameter is zero ssb_to_psb_xyz only returns the one location, not the location for each TOA

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#1162]
https://github.com/nanograv/PINT/blob/e0cc5b9fce4f108c243ba4b5285cae4f4da746c3/src/pint/models/pulsar_binary.py#L297

**Comment by scottransom** [comment]
What does this issue mean?  What "shape" are you talking about?

**Comment by aarchiba** [comment]
This is intentional - we were spending a lot of time recomputing things for the same position.

**Comment by abhisrkckl** [comment]
> This is intentional

Closing because this is the intended behavior.
