### ISSUE TITLE
Add  HAWC and MAGIC in observatories.py

### ISSUE THREAD

**Issue by parthasarathipal** [nanograv/PINT#1171]
Hi,
   I am trying to do pulsar analysis with HAWC data. Please add HAWC and MAGIC location infotmation in the Observatories.py file.

**Comment by paulray** [comment]
This is best done via a pull request by someone with knowledge of those observatories, and it would be useful if it included information about the source of the location information, as is done for other observatories in observatories.py.

**Comment by aarchiba** [comment]
If someone has exact position information, preferably with provenance as @paulray says, I'd be happy to write the pull request.

**Comment by paulray** [comment]
As an example, HESS was just added via #1503

**Comment by abhisrkckl** [comment]
I see that MAGIC is already included in observatories.dat. HAWC is not there though.

**Comment by dlakaplan** [comment]
I emailed the HAWC spokesperson a while ago.  Just tried again.
