### ISSUE TITLE
Update README with better links to docs

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1179]
Link to wiki How To and others.

**Comment by dlakaplan** [comment]
I started this.  See:
https://github.com/dlakaplan/PINT/blob/update_readme/README.rst
We could reformat more broadly (move things around, etc). I also put the 3 of us on there with our emails for individual contact - not sure if that's the best way, or make it an exploder, or what.

**Comment by paulray** [comment]
I wonder if we could create "pinthelp@nanograv.org" that goes to people willing to help out?

**Comment by dlakaplan** [comment]
Right - don't know if that would be more or less likely (or more or less annoying)

**Comment by dlakaplan** [comment]
and if we'd need a ticketing system or whatever to make sure we didn't duplicate

**Comment by dlakaplan** [comment]
or we could just cc the list so others see what we are doing
