### ISSUE TITLE
Online unit test travis-ci

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#118]
Since we are going to have our stable version, it would be better to have a tag saying the pull request pass the test. Travis-ci is one of the package to do so. But due to the dependencies in PINT, it is kind of hard to use it right now. 

If we have our standard test and we can figure it out to handle dependencies, it will be easy for us. So we should keep looking at it.

**Comment by cdeil** [comment]
@luojing1211 - I'd like to help with setting up continuous integration and getting Python 3 working.

My suggestion would be to activate travis-ci now, and get something minimal (like `python setup.py egg_info`) working or failing, and then step by step get things working on continuous integration (like downloading data files, installing dependencies).

Which dependency do you think is hard to install? If it works locally, it works on travis-ci, no?

**Comment by demorest** [comment]
I think the main problem used to be pyspice/cspice, which had a kind of non-standard install procedure.  We got rid of these recently so it would be great to revisit continuous integration.  I think all pint dependencies are now pip-installable (?) so it should be not too difficult.

**Comment by luojing1211** [comment]
It should be not. Let me try it on my repository.

**Comment by cdeil** [comment]
@luojing1211 - Did you have time to try it out?
If not, maybe you can just enable travis on the main repo, and I make a PR adding a `.travis.yml`.
(there's no downside to enabling it and having a period where the builds aren't set up or passing yet, as far as I know)

**Comment by luojing1211** [comment]
Hi @cdeil, 
I have tried it on my repo. It is failing, I did not have time to find where it is failing. But I think make a PR on the main repo totally welcomed. We will have time to discuss the PRs today. 
Thanks for your contribution. 

-Luo Jing

**Comment by cdeil** [comment]
@luojing1211 - Can you link to the failing travis-ci build? Maybe I can have a look and help sort it out.

**Comment by luojing1211** [comment]
@demorest @cdeil  I just remember we still have dependency on TEMPO/TEMPO2 for clock correction files. I don't think travis-ci can handle that.

@cdeil I realized I did not configed it right. I was trying and learning. What I need it a right .yml file which is now need to be updated.

**Comment by cdeil** [comment]
> I just remember we still have dependency on TEMPO/TEMPO2 for clock correction files. I don't think travis-ci can handle that.

Why not?
What's the problem?
It's common to download a Gigabyte of dependencies and I think build times can be up to 30 min on travis-ci.
You should be able to fetch and build any dependencies you need and also for example data files.
The travis-ci network is very fast, you often get 50 MB / sec, so if you have stuff from slow websites you need, you can put it in an extra Github repo, like `PINT-extra` or `PINT-testdata`.

> What I need it a right .yml file which is now need to be updated.

I've written a bunch of those for Python projects.
If you link to the one you're trying to get to run and also the failing build on travis-ci, I'll have a look and try to help sort it out.

**Comment by matteobachetti** [comment]
@cdeil @luojing1211 why don't we just compile Tempo2 on a virtual machine with the same paths as the Travis containers, upload the compiled tarball to a personal server and download it during the build? This should save a lot of time, if we don't necessarily need the bleeding-edge version of Tempo2.
If needed, I can produce the clone virtual machine/container

**Comment by matteobachetti** [comment]
To clone the containers with Docker: https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

**Comment by cdeil** [comment]
> why don't we just compile Tempo2 on a virtual machine with the same paths as the Travis containers, upload the compiled tarball to a personal server and download it during the build?

I've done this for a few projects in the past (e.g. rootpy).
It's an option, but it is work for you to set up and maintain for the coming years.
Self-made binaries probably have to be updated every time travis-ci switches to a new Ubuntu release at least, maybe even more often, right?

My recommendation would be that you just build `tempo2` from source in each build, if it's possible if it takes <~ 15 min of build time.

**Comment by matteobachetti** [comment]
@cdeil @luojing1211 I thought the Tempo2 dependency was temporary?
Yes, if it has to be there for the coming years, compiling each time looks
like the best option, even if reproducing a build once every year doesn't
look that bad.
One of the reasons I say this is that I often had problems compiling new
releases of Tempo2, and this might be a source of failures in the build
process. Is the need for Tempo2 something so structural in PINT that we
absolutely need to be up to date with the current HEAD?

**Comment by paulray** [comment]
I think we should be able to install, build, and test PINT without requiring TEMPO or Tempo2. 
Any tests that compare to TEMPO/Tempo2 should be done using pre-computed output files, not run by TEMPO/Tempo2 on the fly. And, if all we need is the clock correction files from TEMPO, those should be included in our repository or downloaded on the fly from somewhere.  Probably we could include versions of the clock files in our repo that would work for all tests. When they are needed by the code, it could check in $TEMPO and in our local area and use the newer one, or something like that. (In general we need a better solution for getting up to date clock correction files)

**Comment by demorest** [comment]
Yes, I agree completely with @paulray -- tempo/tempo2 are _not_ dependencies of PINT and do not need to be built in order to run the tests.  We do need to figure out how best to handle clock correction files.  For test purposes, it might be a good idea to include the ones that are needed for tests directly in the PINT repository (perhaps under the tests area).

**Comment by paulray** [comment]
Note that clock correction strategy is discussed in Issue #102

**Comment by luojing1211** [comment]
@cdeil Is this the link? 
https://travis-ci.org/luojing1211/PINT.svg?branch=master
Please let me know if it is correct or not.

**Comment by cdeil** [comment]
The travis-ci builds from your repo are here:
https://travis-ci.org/luojing1211/PINT

This seems to be the latest build:
https://travis-ci.org/luojing1211/PINT/builds/181437574

Is it from this branch?
https://github.com/luojing1211/PINT/tree/new_fitter

I can't find your `.travis.yml` file. Did you add one?

Can't we just activate travis-ci for the main repo (someone here must have permissions, no?)
and then discuss build config and logs from https://github.com/nanograv/PINT/pull/195

(or you put up a new PR against the main repo with a `.travis.yml` file and I try to help by commenting there)

**Comment by luojing1211** [comment]
I have update my .travis.yml file in my master branch. I have not do this for new_fitter branch yet. It failed at pip install.
