### ISSUE TITLE
Allow clock files other than those built in to PINT

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1180]
Make it clear where to find the clock file(s) among $TEMPO, $TEMPO2, and PINT.

**Comment by dlakaplan** [comment]
It looks like there isn't a preference/fallback model, but this is instead defined in:
https://github.com/nanograv/PINT/blob/master/src/pint/observatory/topo_obs.py
it says:
```
        clock_dir="PINT",
```
although the doc says:
```
clock_dir : str, optional
        Location of the clock file.  Special values
        'TEMPO', 'TEMPO2', or 'PINT' mean to use the
        standard directory for the package.  Otherwise
        can be set to a full path to the directory
        containing the clock_file.  Default='TEMPO'
```

It's not clear to me if/how this can be changed when reading in TOAs.  I think it just does:
```
        site = get_observatory(obs)
```
when making a single TOA, or:
```
            site = get_observatory(
                obs,
                include_gps=include_gps,
                include_bipm=include_bipm,
                bipm_version=bipm_version,
            )
```
when doing clock corrections.  So it takes the default in both cases (and also doesn't store what it did).

Note that the logging does make this clear, but I don't think it retains a record of what it used.

Suggestions on how to proceed?  
* I could change the behavior when constructing an observatory to have a list of directories, but that still wouldn't ever be used in most cases since that isn't run explicitly by most users.  
* Could add options to `apply_clock_corrections()` so that this could be changed, but it would still have to be managed when constructing the TOAs
* It could also be done (overridden?) through an environment variable, which is more like TEMPO/TEMPO2.  Not sure if we want to replicate that behavior.

**Comment by paulray** [comment]
Regarding clock files, there are a couple of related PINT issues (#102 and #856) 
And I made a Trello card for a project to deal with the general problem across timing software:
https://trello.com/c/yzohTfIV

**Comment by dlakaplan** [comment]
Should we bring this up with the CyberI group (in terms of a data server)?

**Comment by paulray** [comment]
Bottom line is that I do NOT think distributing clock files with PINT is a good idea. I'd love to see a software-independent clock file repo that all codes could access. This seems like a GREAT IPTA project...

**Comment by dlakaplan** [comment]
Agreed

**Comment by paulray** [comment]
I think it is a straightforward project to decide on a file format and make a server, but then it will require someone with a force of personality to get (1) observatories to agree to provide their updates to the server, and (2) update TEMPO and Tempo2 to use it (PINT will be easy)

**Comment by dlakaplan** [comment]
Right (I think).

**Comment by scottransom** [comment]
We've literally been talking about this being an IPTA project for about 12 years.  The big issue, as mentioned above, is that most observatories do not have automatic handling of their clock files.  So it take a person to intervene occasionally.  And that means everyone is out of sync.  *And* there has been no agreed upon place to host/serve it.

**Comment by dlakaplan** [comment]
In terms of a mechanism:
https://docs.astropy.org/en/stable/utils/data.html
would seem to provide that.  But if there are better ways to do it that would be fine.

What do you think is the right way forward?  Should we (NANOGrav/PINT) find a server to store these files, add a module to PINT to retrieve/cache them (based on astropy), and then worry about updating it later?  Or is that likely to be seen as a takeover by the IPTA?

**Comment by swiggumj** [comment]
I will say there is broad support for this kind of effort at the IPTA level and in Data Acquisition, we've started to gather a list of contacts with expertise at all of our observatories. This WG might be able to help with syncing up efforts and developing relevant procedures for keeping things up to date. I'm interested in hearing more and would be happy to raise it at our next telecon and/or on slack.

**Comment by dlakaplan** [comment]
Yes, I think @JPGlaser was willing to help with the server resources.

**Comment by aarchiba** [comment]
In #1239 I clear up PINT's clock file handling substantially and also pull in clock files from TEMPO and TEMPO2. Sensibly handling newer clock files from elsewhere remains an open problem.

**Comment by aarchiba** [comment]
> I will say there is broad support for this kind of effort at the IPTA level and in Data Acquisition, we've started to gather a list of contacts with expertise at all of our observatories. This WG might be able to help with syncing up efforts and developing relevant procedures for keeping things up to date. I'm interested in hearing more and would be happy to raise it at our next telecon and/or on slack.

I'm planning to run up a quick test setup for the PINT/technical side of this - use a github repo to provide both software support and the TEMPO and TEMPO2 repositories. I think keeping the clock files in some sort of git repo to which updaters can obtain access makes sense, though I seem to recall that github was blocked in some places. I also think that providing TEMPO and TEMPO2-format clock directories makes using this repo easy for users of these software packages - just `git clone` and set `$TEMPO` and `$TEMPO2`. PINT would use the astropy cache to pull in up-to-date versions. It would not be terribly difficult to use PINT to produce automatically converted versions if, say, the TEMPO clock file were being updated and one wanted TEMPO2 to see the same up-to-date version.

**Comment by dlakaplan** [comment]
That sounds exactly like what we need, perhaps with a mirror on another site to provide access where GitHub is not possible.

**Comment by scottransom** [comment]
Note my comment on #1239.  I am *not* in favor of including more clock files in PINT (others have expressed similar things above), and in fact, would prefer to see us *remove* all of the ones that we have!

**Comment by dlakaplan** [comment]
I think what Anne is discussing here agrees with your other comment:

> single locations where the latest observatory clock files are kept, and we use a caching mechanism to handle them all.

right?

**Comment by aarchiba** [comment]
A document to discuss global clock files: https://docs.google.com/document/d/1St1hj0qqi8xsWpeMYUJGQ5zgITJEVoZ6bygicycROhU/edit?usp=sharing

**Comment by aarchiba** [comment]
> Note my comment on #1239. I am _not_ in favor of including more clock files in PINT (others have expressed similar things above), and in fact, would prefer to see us _remove_ all of the ones that we have!

I put a longer response on #1239, but it is meant as a short-term fix until we have a global clock corrections solution. We can discuss how PINT should handle global clock corrections - see the document I linked in the previous comment - once that is available. But in the meantime I think that pulling the clock corrections into PINT makes it more useful for more people and does not substantially increase the maintenance burden.

**Comment by aarchiba** [comment]
I think #1247 will address this, when it is ready to merge.
