### ISSUE TITLE
DMDATA causing crash when loading a model

### ISSUE THREAD

**Issue by almcewen0** [nanograv/PINT#1184]
Loading a model using the parfile below via `pint.models.get_model()` caused a failure. Removing the DMDATA line from the par file avoids the issue. It seems like it is being misinterpreted as something that should be a float.

\# Created: 2022-02-17T17:02:55.572753
\# PINT_version: 0.8.2+726.g1c89038b
\# User: aemcewen
\# Host: UWM004905
\# OS: Darwin-21.2.0-x86_64-i386-64bit
PSRJ                             J2035+36
EPHEM                               DE421
CLOCK                        TT(BIPM2019)
DILATEFREQ                              N
DMDATA N
TZRMJD             59617.7970660947467014
TZRSITE                               ssb
TZRFRQ                                inf

![Screen Shot 2022-03-14 at 10 32 10](https://user-images.githubusercontent.com/39491211/158206278-6fd76af4-e408-4f94-be5e-98f8f4b71263.png)
![Screen Shot 2022-03-14 at 10 32 19](https://user-images.githubusercontent.com/39491211/158206273-389b8f55-6a9a-4c09-b57c-743b8bb849c9.png)

**Comment by almcewen0** [comment]
ah, turns out it was a versioning issue.

**Comment by dlakaplan** [comment]
I can't reproduce this.
