### ISSUE TITLE
Implement ELL1 binary model

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#119]
Currently PINT does not work with ELL1 binary models.  This need to be implemented.  In the short term, this could be done as an independent model.

In the long term, it would be great if the parameterization of eccentricity (e, omega,T0 vs EPS1, EPS2, TASC), and the orbital phase evolution (PB, PBDOT vs FB0, FB1, ...).

**Comment by luojing1211** [comment]
We have ELL1 model now. But we do need to have the long term goal implemented. Should we close this one?

**Comment by demorest** [comment]
Closing since ELL1 has been added in PR #175 .  I think if we want to do the "long-term" goal of more flexibly binary parameterization mentioned above, that should be a separate issue.
