### ISSUE TITLE
Should PINT have an rc file?

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1223]
It's nice to not need any config, but there are some things that could benefit from a per-user setup:
* specific log messages to ignore
* clock file setup (at least until that changes)
* logging level/format (configurable via environment variable)
* any `pintk`-related settings?
Maybe there are not others, and we can stick with the current system, but I was just thinking about this a little and wondering if/when to make a switch.

**Comment by paulray** [comment]
We had a good bit of discussion of this a while back (see Issue #112), but we never came to a conclusion.
