### ISSUE TITLE
WLSFitters try to take bogus step while GLSFitters claim convergence

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1226]
If I start a `DownhillWLSFitter` at (or presumably near) a good solution, it will fail to converge and throw an exception.  The other fitters are fine.  I'm guessing this is because chi^2 is not decreasing but it should behave better.

```
import pint.fitter
import pint.models

m, t = pint.models.get_model_and_toas("DownhillWLSTest.par.txt", "DownhillWLSTest.tim.txt")
f = pint.fitter.DownhillWLSFitter(t, m)
f.fit_toas()
```
results in:
```
MaxiterReached                            Traceback (most recent call last)
~/askap/lmc/test_fitters.py in <module>
     28 m, t = pint.models.get_model_and_toas("DownhillWLSTest.par.txt", "DownhillWLSTest.tim.txt")
     29 f = pint.fitter.DownhillWLSFitter(t, m)
---> 30 f.fit_toas()

~/pythonpackages/PINT_dlakaplan/src/pint/fitter.py in fit_toas(self, maxiter, threshold, debug, **kwargs)
   1462         """
   1463         self.threshold = threshold
-> 1464         super().fit_toas(maxiter=maxiter, debug=debug, **kwargs)
   1465 
   1466     def create_state(self):

~/pythonpackages/PINT_dlakaplan/src/pint/fitter.py in fit_toas(self, m
axiter, required_chi2_decrease, max_chi2_increase, min_lambda, debug)
   1317             ) from exception
   1318         if not self.converged:
-> 1319             raise MaxiterReached(f"Convergence not detected after {maxiter} steps.")
   1320         return self.converged
   1321 

MaxiterReached: Convergence not detected after 10 steps.
```
when all other fitters converge very quickly (giving essentially the same chi^2 pre- and post-fit).

par/tim files attached:
[DownhillWLSTest.par.txt](https://github.com/nanograv/PINT/files/8621272/DownhillWLSTest.par.txt)
[DownhillWLSTest.tim.txt](https://github.com/nanograv/PINT/files/8621273/DownhillWLSTest.tim.txt)
(renamed to `.txt` so GitHub would accept them).

**Comment by aarchiba** [comment]
Can this par and tim file go into the test suite? I'd like to see what a single DownhillWLS step looks like compared to the WLS, and I think there's already a test for this.

**Comment by dlakaplan** [comment]
Sure.

**Comment by aarchiba** [comment]
Looking more closely at this, it looks like the standard WLSFitter actually worsens the chi-squared by 0.15 - which is a sign that something is wrong there too. Maybe it's just that the solution is not fully converged, or maybe the WLSFitter linear algebra is failing (although the WLS linear algebra should be more reliable than the GLS linear algebra - specifically the condition number for GLS is the square of that for the WLS). The DownhillWLSFitter would appear to be detecting this misbehaviour of the WLSFitter and trying to compensate (unsuccessfully) by taking smaller steps. But I would summarize this situation as:

* WLSFitter is failing, making the solution substantially worse, but not signalling an error.
* DownhillWLSFitter is detecting this failure but is unable to rectify it, so it is raising an exception.
* GLSFitter and DownhillGLSFitter seem content with the existing solution.

I'll investigate further.

**Comment by dlakaplan** [comment]
I've just been dealing without the updated clock files.  This is a 0.3s pulsar with a super broad pulse, so I'm assuming (hopefully not incorrectly) that they are too small to matter.

**Comment by dlakaplan** [comment]
We have been talking about a more general clock file fix (https://github.com/nanograv/PINT/issues/1180), perhaps using an astropy-like data repository.  

Would it help for testing if I sent you the pickle file?

**Comment by aarchiba** [comment]
No, it's all right, I'll chase down the right thing to do.

**Comment by dlakaplan** [comment]
Yes, this doesn't need a working TEMPO install, just the runtime directories.  #1180 was trying to do address part of this by understanding which file (PINT vs. TEMPO vs. TEMPO2) was identified for a given telescope and it wasn't clear.

**Comment by aarchiba** [comment]
#1239 resolves the clock correction nuisance. Now on to actual troubleshooting.

**Comment by aarchiba** [comment]
Sure enough, WLS suggests a ~0.1 sigma change in all the parameters, while GLS wants practically no change. The condition number is extremely modest, so round-off should not be a problem. DownhillWLS suggests the same first step as plain WLS, as one should expect. Why this step is so bad is not clear, particularly as WLS *sometimes* works.
