### ISSUE TITLE
Model phase ignores TZRMJD?

### ISSUE THREAD

**Issue by matteobachetti** [nanograv/PINT#1240]
Hi, 

I would expect that the model phase takes TZRMJD as the reference for all future phases. Instead, I see that changing TZRMJD does not seem to influence the phase calculation.

See below, the results of model.phase for when only changing TZRMJD

```
model_1_str = """PSR B0531+21
RAJ 05:34:31.97232
DECJ +22:00:52.069
EPHEM DE200
F0 29.585202275099999
F1 -3.6741058e-10
C F2 computed as F2=2.0*P1*P1/(P0*P0*P0) according to JBO ephemeris
#F2 9.12554411767868e-21
PEPOCH 59684.000000107444066
TZRSITE @
TZRFRQ 0.0
TZRMJD 59684.000000107444066
START 59668.0000
FINISH 59700.0000
UNITS TDB
CLOCK TT(TAI)
DM 56.74720
DM1 -0.34124
DMEPOCH 59684.000000107444066
TRES 200.000
"""
with StringIO(model_1_str) as f:
    model_1 = get_model(f)

model_2_str = """PSR B0531+21
RAJ 05:34:31.97232
DECJ +22:00:52.069
EPHEM DE200
F0 29.585202275099999
F1 -3.6741058e-10
C F2 computed as F2=2.0*P1*P1/(P0*P0*P0) according to JBO ephemeris
#F2 9.12554411767868e-21
PEPOCH 59684.000000107444066
TZRSITE @
TZRFRQ 0.0
  # Note the large change
TZRMJD 59688
START 59668.0000
FINISH 59700.0000
UNITS TDB
CLOCK TT(TAI)
DM 56.74720
DM1 -0.34124
DMEPOCH 59684.000000107444066
TRES 200.000
"""

with StringIO(model_2_str) as f:
    model_2 = get_model(f)

t_gro_de200 = TOAs(toalist=[TOA((59685, 0.000000327), obs="Geocenter", freq=np.inf, scale="utc", ephem="DE200")])
t_gro_de200.compute_TDBs(ephem="DE200")
t_gro_de200.compute_posvels(ephem="DE200")

print(model_1.phase(t_gro_de200).frac, model_2.phase(t_gro_de200).frac)

```

Result: `[-0.0003627] [-0.0003627]`

Is this the expected behavior?
Thanks!

**Comment by aarchiba** [comment]
No, this is not right. But our handling of absolute phase is not good at all and needs a re-write.

**Comment by matteobachetti** [comment]
Oh, ok. Thanks @aarchiba , I'll see if I can find a workaround

**Comment by paulray** [comment]
PINT handles this fine, you just have to ask it to compute the absolute phase:
```
print(model_1.phase(t_gro_de200,abs_phase=True).frac, model_2.phase(t_gro_de200,abs_phase=True).frac)
```

**Comment by paulray** [comment]
Actually, there is a missing line in your example, just before the `compute_TDBs`:
```
t_gro_de200.apply_clock_corrections(include_bipm=False)
```
With that fix, I get this answer:
```
[-0.00036264] [0.30964827]
```
Does that solve your problem @matteobachetti ?

**Comment by matteobachetti** [comment]
Hah! Thanks @paulray 
I thought clock corrections were just for radio observatories :O

**Comment by paulray** [comment]
I think the remaining question here is whether `abs_phase` should default to `True` when there are TZR params in the model.  Clearly you were expecting absolute phases, but were not getting them.

**Comment by paulray** [comment]
I think if a model has an `AbsPhase` component, it should definitely default to abs_phase=True.  If you don't, it can't do absolute phases anyway.

**Comment by aarchiba** [comment]
I believe #1261 fixes this.

**Comment by matteobachetti** [comment]
Thanks @paulray and @aarchiba !
