### ISSUE TITLE
PINT special-cases parameters

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1246]
Certain parameters, in particular DMDATA and START/FINISH are treated specially by PINT - that is, START/FINISH are explicitly checked to ensure that they are never fit for, and DMDATA is a `boolParameter` but its output (and no other `boolParameter`) is overridden to be 0/1 instead of the usual Y/N for TEMPO compatibility. These special cases should be set up as options on the Parameter objects when they are created, so that (for example) when the `START` parameter is created one can ensure that it is never fittable, without the rest of PINT needing to treat `START` specially.

These two changes are introduced in #1230, which is otherwise rather badly needed, so this issue is here to remind us to fix the temporary hack.

**Comment by abhisrkckl** [comment]
This issue was solved as a side effect of #1640.
