### ISSUE TITLE
strange high-level test failures due to PINT logging

### ISSUE THREAD

**Issue by scottransom** [nanograv/PINT#1248]
So I'm seeing something strange on nimrod using miniconda python 3.9 (and a separate install of python 3.6) that i can't replicate on other machines.

If I run "make test" from the top-level PINT directory, when `pytest` "collects" its tests, there are failures related to logging from multiple files.  Note that it is *not yet running the actual tests"!  This is just gathering which tests need to be run.  And even stranger, if I run "pytest test_density.py" (which is one of the files that it fails on), then it runs and all the tests pass.

It seems like this might be related to how the traditional warnings package is handled with our custom loguru setup.

```
/usr/local/src/miniconda3/envs/presto/lib/python3.9/site-packages/matplotlib/cbook/deprecation.py:233: in wrapper
    _warn_external(warning)
/usr/local/src/miniconda3/envs/presto/lib/python3.9/site-packages/matplotlib/cbook/__init__.py:2108: in _warn_external
    warnings.warn(message, category, stacklevel)
/usr/local/src/PINT/src/pint/logging.py:93: in warn
    and (msg.match(message) and len(args) == 0)
E   TypeError: expected string or bytes-like object
==================================== warnings summary ====================================
../../miniconda3/envs/presto/lib/python3.9/site-packages/_pytest/mark/structures.py:521
  /usr/local/src/miniconda3/envs/presto/lib/python3.9/site-packages/_pytest/mark/structures.py:521: PytestUnknownMarkWarning: Unknown pytest.mark.remote_data - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================ short test summary info =================================
ERROR test_density.py - TypeError: expected string or bytes-like object
ERROR test_determinism.py - TypeError: expected string or bytes-like object
ERROR test_downhill_fitter.py - TypeError: expected string or bytes-like object
ERROR test_event_optimize.py - TypeError: expected string or bytes-like object
ERROR test_fermiphase.py - TypeError: expected string or bytes-like object
ERROR test_fitter.py - TypeError: expected string or bytes-like object
ERROR test_model.py - TypeError: expected string or bytes-like object
ERROR test_photonphase.py - TypeError: expected string or bytes-like object
ERROR test_pintk.py - TypeError: expected string or bytes-like object
ERROR test_plk_widget.py - TypeError: expected string or bytes-like object
ERROR test_random_models.py - TypeError: expected string or bytes-like object
!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 11 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!
============================= 1 warning, 11 errors in 6.18s ==============================
```

**Comment by dlakaplan** [comment]
I'm not sure - I think this might be due to the occasional inability to download ERFA data that @paulray and I were struggling with.  Can you try one with more verbosity?

**Comment by dlakaplan** [comment]
In any case the logging is still a slightly moving target.  Based on feedback from @aarchiba and others I have another PR (#1232) which improves it more, but which needs some discussion.

**Comment by scottransom** [comment]
Every one of these is coming from the `warnings .warn` method (as propagated through loguru) and then from `msg.match(message)` in out PINT loguru handling.  Additional verbosity isn't giving any additional information.

**Comment by dlakaplan** [comment]
ok, I'll check it in a minute

**Comment by scottransom** [comment]
Some other info:  the `warnings.warn` is always coming from matplotlib.  So for some reason, each of those tests is importing matplotlib in some way (for some reason).  So maybe this is related to the matplotlib backend that is being used on nimrod (`tkagg`) compared to what I'm using on other machines....

**Comment by dlakaplan** [comment]
ok, trying a new conda env locally.

**Comment by dlakaplan** [comment]
New conda env with python 3.9.  set `export MPLBACKEND=TkAgg`.  Still no issues.

**Comment by dlakaplan** [comment]
but maybe as you said this is the difference between collecting the tests and running them

**Comment by dlakaplan** [comment]
no collection looks fine.  Is there a way for me to get on nimrod and poke at this myself?

**Comment by scottransom** [comment]
Yeah, on my laptop if I switch to `TkAgg` I also can't get it to trigger.  And yes, this is happening during test collection rather than running.  So it triggers within just a couple seconds.  Really strange...

**Comment by scottransom** [comment]
Sure.  If you can login to "ssh.cv.nrao.edu" you can then "ssh nimrod".  The conda setup that I'm using can get setup using:
```
        unset PYTHONPATH
        eval "$(/usr/local/src/miniconda3/bin/conda shell.bash hook)"
        conda activate presto
```

**Comment by dlakaplan** [comment]
(a related question is why all of those import matplotlib.  might be good to remove that when it's not actually needed.  which isn't a reason to ignore this)

**Comment by dlakaplan** [comment]
I think my account has expired, unfortunately.

**Comment by dlakaplan** [comment]
in any case, I might see a typo.  let me try a quick branch

**Comment by scottransom** [comment]
Bummer about the account.  And I totally agree about not importing matplotlib.

**Comment by dlakaplan** [comment]
Any chance you could check out https://github.com/dlakaplan/PINT/tree/fixtestcollect and try?

**Comment by vallis** [comment]
This also breaks enterprise on Python 3.6 (not 3.7, 3.8, or 3.9), with PINT 0.8.7, in a test that loads PINT first and then healpy (which loads matplotlib).

It seems that a matplotlib warning is routed through PINT (why?) and triggers the same problem (bytes vs. unicode?) Is PINT configuring logging with filters for "everyone" rather than itself only?

**Comment by scottransom** [comment]
David has a test fix (see above branch link) that fixes this issue for me.  So we need to get this merged.  But we also need to figure out why the warnings are being routed like that!  (as @vallis mentions)

**Comment by dlakaplan** [comment]
@vallis : 
* the pint logger does capture other warnings, such as matplotlib, erfa, etc.  this is done explicitly.  this was partially intentional (to provide uniform formatting etc) and partially because different warnings from different places have different sorts of data, so it wasn't always clear how to separate them.  
* https://github.com/nanograv/PINT/pull/1232 adjusts the logging interface further so you can turn off capturing of other warnings.  

personally I have found this behavior to be useful but if others do not then it can be turned off (by default or as an option): happy to discuss.

**Comment by vallis** [comment]
Thanks Scott and David. So I understand #1232 would allow a workaround, but #1251 will fix the bug itself.

Either way, I will need to wait for the PRs to be merged (if I switch enterprise to PINT master than release), or for a new release.

In other news, maybe it's time to drop Python 3.6? It's been EOLed since December. I can do it for enterprise even if PINT doesn't just yet. I will ask on Slack whether there are constraints for our operations.

**Comment by dlakaplan** [comment]
@vallis : can you provide an explicit test that fails so I can try to reproduce?

**Comment by dlakaplan** [comment]
So can we close this?

**Comment by scottransom** [comment]
Yeah, I think so.  I probably should have closed it last night when I merged your PR!  I'll close it now.
