### ISSUE TITLE
Some questions about: PINT analysis of Fermi data

### ISSUE THREAD

**Issue by zzzlllccc** [nanograv/PINT#1258]
I have successfully run the tutorial on the official website before:
Fermiphase -- plotJ0030 + 0451 _p8_15. 0 deg_239557517_458611204_ft1weights_geo_wt. Gt. 0.4 fits PSRJ0030 + 0451 _psrcat. Par CALC
But how do I create the (.fits. Par) file from another Fermi source.
Hope someone can give me some advice, or some ways for me to learn, I would be very grateful.

**Comment by paulray** [comment]
Also, note that the par file you are using for J1907+0602 ends in 2013. It can **not** be used to compute phases for more recent data for a noisy young pulsar like that.

**Comment by zzzlllccc** [comment]
Thank a lot.
