### ISSUE TITLE
Observatory data should be data, not code

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1283]
It would be good to move the `observatories.py` from installed code to a file read at run-time, presumably with some similar but different format (yaml etc).  Then it would be easier for users to update/override.

**Comment by dlakaplan** [comment]
astropy is: https://github.com/astropy/astropy-data/blob/gh-pages/coordinates/sites.json

**Comment by abhisrkckl** [comment]
I think this has already been implemented. Can this be closed?
