### ISSUE TITLE
pint.models.model_builder.parse_parfile makes all param names uppercase

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1286]
This causes case-sensitive parameter names (eg. TNRedAmp, TNRedGam) to be ignored by ModelBuilder. For example, the red noise components present in the IPTA DR2 par files are not recognized by PINT. It works if I manually create a PLRedNoise object and add it to the timing model.

**Comment by aarchiba** [comment]
The intention is that parfile parsing is case insensitive (but ideally output parfiles should preserve the input case by default). This would mean that TNRedAmp should be called TNREDAMP internally, but it should work. Can you post an example showing that it doesn't?

**Comment by abhisrkckl** [comment]
Here is an example program showing the issue along with the data.
[rnparams_test.zip](https://github.com/nanograv/PINT/files/8928388/rnparams_test.zip)
 
The data is from IPTA DR2. 
I am using the version of PINT corresponding to commit 3e802b5d358caca3a8bb07c39d93d078492bb402

**Comment by aarchiba** [comment]
Is it fair to say this is fixed? We still forcibly uppercase everything, but that now works fine?

**Comment by abhisrkckl** [comment]
Yes. I opened this issue because of the PLRedNoise bug. Since that is fixed, this is a non-issue now IMO. Also, I don't think making all parameters uppercase is a bad thing now.
