### ISSUE TITLE
PINT struggles reading the flag "tim_jump"

### ISSUE THREAD

**Issue by AstroJackson** [nanograv/PINT#1294]
When a par file has the row "JUMP    -tim_jump 1         0 0 0" and the corresponding tim file has the flag "-tim_jump 1", pintk doubles the number of JUMPs. pintempo gives an error as well. When the flag renamed to anything else, in both the par and tim files, the issue goes away. 

I recommend renaming the JUMP flag to something other than "tim_jump". Some examples may be "time_jump", "jump_tim", or "jump". 

My operating system and platform is given by: Linux-2.6.32-754.35.1.el6.x86_64-x86_64-with-glibc2.12. 
pint.__version__ = 0.8.8+175.gb8b04f5
pint.__file__ = /users/jdtaylor/Jackson/PINT/src/pint/__init__.py
I am using a virtual environment though the issue persists on my local Mac as well.

**Comment by aarchiba** [comment]
The flag `tim_jump` has a special meaning to PINT: JUMP lines in tim files result in the TOAs they surround getting a `-tim_jump N` flag. TOA lines that contain `-tim_jump N` can be produced when PINT writes out a tim file whose input version contained these JUMP lines. Therefore PINT should be able to correctly work with TOAs that contain `tim_jump` flags. 

I know pintk does some weird things with JUMPs that probably break everything, but can you give a reasonably clean example (inputs and output results) when pintempo acts on such a file? 

The correct behaviour as I understand it is that the TOAs should be loaded as-is. For the model I can see two possibilities:

1. No JUMPs are ever added. This is what happens with other flag settings. 
2. If `-tim_jump n` is present and no JUMP selects the relevant TOAs, then a`JUMP -tim_jump n` is added (it could be frozen or not).

It sounds like the current state of affairs is that we are trying to do number 2 and getting it wrong?

**Comment by AstroJackson** [comment]
I believe the issue is a `-tim_jump n` is present in both the par and tim files, but PINT wants to add a `JUMP -tim_jump n` anyway, though I am not sure. Here are the par and tim files I am using: 
[errortim.txt](https://github.com/nanograv/PINT/files/8959243/errortim.txt)
[errorpar.txt](https://github.com/nanograv/PINT/files/8959241/errorpar.txt)

I normally name them with .par and .tim but github does not accept that file type. When I run `pintempo errorpar.par errorpar.tim` I get the following: 
![Screenshot at 2022-06-22 11-37-39](https://user-images.githubusercontent.com/85646090/175073506-049dba2b-48ff-4772-8b6c-e3b9a398ecc6.png)

When I run pintk, it doubles the number of JUMPs it tries to fit for.

**Comment by aarchiba** [comment]
Yes, if I try to replicate what `pintempo` does in a notebook, it's clearly wrong. All appears fine until the function `jump_flags_to_params` is called. This modifies the TOAs object, changing all its `tim_jump` numbers, and it adds spurious new JUMPs to the model. This is just wrong behaviour for that function.

**Comment by aarchiba** [comment]
As a practical work-around, I recommend just copying the `tim_jump` flags to another name and deleting them from your TOAs. But this is definitely a bug.
