### ISSUE TITLE
Jodrell Bank needs a more complex clock chain than PINT records

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1312]
Depending on which instrument was used, Jodrell Bank data requires a two-step clock correction:

- `jbroach2jb.clk -> jb2gps.clk` for the Roach backend
- `jbdfb2jb.clk -> jb2gps.clk` for the DFB backend
- `jbafb2jb.clk -> jb2gps.clk` for the AFB backend

Currently PINT actually has observatory names to distinguish these but treats them all as aliases for the same obervatory, which only uses `jb2gps.clk`. The additional clock files mostly consist of discontinuous jumps that presumably arose from backend/receiver changes.

This could be fixed by splitting out into separate observatories with appropriate clock chains.

**Comment by abhisrkckl** [comment]
Solution: One observatory entry per backend (e.g. JBO, NCY).
