### ISSUE TITLE
Dimensionless unit error for ELL1 binaries 

### ISSUE THREAD

**Issue by imeisler** [nanograv/PINT#1316]
In `fitter.py`, using the `get_derived_params` function (line 458) on a binary with the ELL1 model gives the error message
> TypeError: Argument 'E' to function 'ELL1_check' has no 'unit' attribute. You may want to pass in an astropy Quantity instead. 

It looks like when that function calculates the eccentricity it isn't assigned dimensionless units. Changing lines 592 and 600 to `ecc.nominal_value*u.dimensionless_unscaled,` fixes the issue. I'm not sure if there are similar issues in other classes.

**Comment by scottransom** [comment]
Hmmm.  I'm not seeing this with the most recent Astropy (5.1) and PINT.  I think we kind of tried to get rid of the `u.dimensionless_unscaled` stuff over the past couple years as it is really clunky.  What is your Astropy version?

**Comment by imeisler** [comment]
I updated my Astropy and it seems to have done the trick! Thank you!!

**Comment by scottransom** [comment]
Great!  Just curious:  what version did you have before?  Maybe we should increase our Astropy version requirement...

**Comment by paulray** [comment]
Yeah, we should add a test and make sure it passes on our oldestdeps tests.

**Comment by aarchiba** [comment]
This is an attempt to replicate the problem:
```python
def test_unitless_ell1h_bug_1316():
    m = get_model(StringIO("""
    PSR J1234+5678
    ELAT 0
    ELONG 0
    PEPOCH 57000
    F0 1
    BINARY ELL1
    PB 1
    TASC 57000
    """))
    t = simulation.make_fake_toas_uniform(56000, 59000, 16, m)
    f = fitter.Fitter.auto(t, m)
    f.get_derived_params()
```
It doesn't fail in `tox -e oldestdeps`, so maybe I didn't catch the essential problem?

I'm putting this into #1305 anyway just in case.

**Comment by imeisler** [comment]
A little embarrassed to say that I think I was using version 4.0

At least now I know how to update packages!

**Comment by paulray** [comment]
Hmm. Our requirements spec is `astropy>=4.0,!=4.0.1,!=4.0.1.post1` so if you had 4.0 that version should pass our tests.

**Comment by aarchiba** [comment]
Hmm. `tox -e oldestdeps` should be running with 4.0 and the above test passes. Can you see if that's close to the code you wrote that failed?

**Comment by scottransom** [comment]
@aarchiba I'm wondering if the test that you have above is simply not hitting the appropriate code?  The parfile is quite simple and all of the parameters are frozen.  That means that it isn't entering the `if` statement that starts on `fitter.py` line 553.  Unless I'm misunderstanding something (which is certainly possible!).

**Comment by scottransom** [comment]
I actually wonder why that `if not any` frozen thing shouldn't just be removed, truthfully.  I'm not sure why that is in there....  It makes sense to test whether ELL1 makes sense whether some params are frozen or not.

**Comment by aarchiba** [comment]
Aha! Failure on `tox -e oldestdeps`:
```python
def test_unitless_ell1h_bug_1316():
    m = get_model(
        StringIO(
            """
    PSR J1234+5678
    ELAT 0
    ELONG 0
    PEPOCH 57000
    F0 1
    BINARY ELL1
    PB 1 1
    TASC 57000 1
    EPS1 0 1
    EPS2 0 1
    """
        )
    )
    t = simulation.make_fake_toas_uniform(56000, 59000, 16, m)
    f = fitter.Fitter.auto(t, m)
    f.get_derived_params()
```



> I actually wonder why that `if not any` frozen thing shouldn't just be removed, truthfully. I'm not sure why that is in there.... It makes sense to test whether ELL1 makes sense whether some params are frozen or not.

I agree. Even if all are frozen it's worth checking and warning the user.

**Comment by aarchiba** [comment]
All right. Sorted in #1324. It's a bit of a hack because we can't easily change the `@quantity_input` decorator but it does work.
