### ISSUE TITLE
PINT doesn't know how to handle clock files that are valid past their ends

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1326]
The Jodrell Bank instruments DFB and Roach have clock files that just record time offsets due to instrumental changes. These can be up to date long past the last instrumental change. This is in contrast with the main Jodrell Bank clock file, which is *not* valid past the last entry because it is a measurement of the clock drift.

How can PINT distinguish between these two situations, to let users know appropriately when they have out of date clock files?

**Comment by aarchiba** [comment]
I think the natural place to specify this, and other properties of the clock files (whose contents we don't control) is when observatories reference them. Instead of just giving a string for the clock file name, possibly part of a list of clock files, we might need to supply a dictionary with clock file properties. Or something. In particular, `bogus_last_correction` is a property of a clock file, not an observatory - in an observatory with multiple clock files in its chain, not all need have the same properties.

**Comment by kerrm** [comment]
Metadata is fine, but this particular use case could be fairly easily handled with pre-processing to append values with MJD set to 0/"begin" and 1e6/"end" along with a repeated value, thus ensuring any reasonable interpolation scheme will apply the clock correction forever.  A la tempo2.

For files where this isn't the case, such entries should be missing, and thus produce the desired behavior, whatever it may be: raise an exception, grudgingly use the last entry, extrapolate (!), ...

**Comment by aarchiba** [comment]
Our interpolation scheme already extends by holding the last value constant. Unfortunately many of the original clock files - which we do not control the content of - contain bogus last values even when they do require regular updates. So we can't rely on the presence of a far-future last value to indicate "no updates needed". 

There's also the question of when to check whether one of these files has been updated - if they do add another entry, we want to find out about it sooner or later - when we can't use "age of last entry" as a gauge.

**Comment by aarchiba** [comment]
Currently our behaviour for points past the last correction depends on the user's preference, expressed as `limits="warn"` (emit a warning and use the last/first value) or `limits="error"` (raise an exception). This seems fine for clock files that need entries bracketing every TOA (and requires us to ignore many bogus last corrections, we currently have a flag for each observatory to tell us whether they do this). For things like the `jbroach2jb.clk` this isn't a useful criterion.

**Comment by kerrm** [comment]
My thought was that the set of "permanent" clock files isn't so large that they couldn't be tweaked for use with PINT.  (Presumably the current versions work as expected in tempo and tempo2, so in the context of having a repository of clock files, the the bare repository would go for tempo/tempo2, and the pre-processed version for PINT.)

Of course, if we're doing something PINT specific, then furnishing metadata it can understand seems like just as good of a solution.

**Comment by aarchiba** [comment]
Summary of discussion in PINT meeting:

- Clock files like `jbroach2jb.clk` are issued by the observatory and occasionally updated, so modifying them means signing up to modify every future release
- The most sensible place to put the information on what kinds of update clock files get is in PINT's description of observatories/clock files
- We already have some per-clock-file parameters (`bogus_last_correction` for example), and when a GlobalClockFile object is constructed it needs some parameters set
- Probably easiest is to make `clock_file` in `observatories.json` a dictionary or list of dictionaries, providing values to be passed to the GlobalClockFile constructor
- For backwards compatibility we could interpret strings as dictionaries with just the filename
- This is an incompatible change in the format of `observatories.json` but it's easily implemented in a notebook that reads the old version in, transforms the parsed json, and writes it back out
- Probably nobody is using custom `observatories.json` yet for us to break

**Comment by aarchiba** [comment]
When do we check for updates to a clock file?

When corrections for a set of times are requested:

- If the clock file is valid for the time covered (has data points before and after the required times), don't check.
- If the clock file has been checked recently (as defined by `index.txt`), don't check.
- Otherwise, check for new clock corrections, and even if there aren't any, record when we checked for use above.

Machinery this requires from the global clock corrections machinery:

- [ ] Keep track of last (successful) check time (mtime of file in cache?)
- [ ] Report whether a new, different file was obtained when a file was requested
- [ ] Do something sensible if new data isn't available
