### ISSUE TITLE
PINT does not support DM red noise models

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1327]
An alternative to DMX is to treat DM as a red noise process that has a frequency dependence. PINT could support this the way it supports red noise processes, but it doesn't. It should, in a way as compatible with TEMPO2 as possible.

Parameters:

- TNDMAmp
- TNDMGam
- TNDMC
- TNsubtractDM

The implementation in tempo2 is at https://bitbucket.org/psrsoft/tempo2/src/9f4f29abe564a3f907f8b97cef79385011391a23/t2fit_nestlike.C#lines-28 and it specifiies various constants.

The TempoNest paper describes the model in more detail: https://ui.adsabs.harvard.edu/abs/2014MNRAS.437.3004L/abstract

It's not quite clear how best to compare PINT's implementation to TEMPO2's. Perhaps just do a fit and ensure that the best-fit value is the same (and thus the noise model is adequately similar)?

**Comment by aarchiba** [comment]
There may be more interest in Keith et al.-style DM Gaussian Processes (#1192)

**Comment by scottransom** [comment]
On that note, just to make sure you are aware, Even Keane's student Sai Susarla at Galway is working on implementing that for PINT over this summer.

**Comment by aarchiba** [comment]
Yes, I know, but thanks for the reminder. I have offered support on the Fitter side - implementing the linear algebra to handle the penalization part - if that would be helpful. I know a fair bit about how our Fittters work.

**Comment by abhisrkckl** [comment]
I would like to try my hand at this one.

**Comment by aarchiba** [comment]
I *think* it's just a matter of cloning our red noise parameter model, adding a frequency dependence to the formula, and then chasing down whether our model agrees with that used by tempo2. It is the third part that is potentially rather tricky. My suggestion would be to start with a nearly-right modet, TOAs and par file, and do a fit with tempo2 and PINT both. If the fits take you to the same point, then the noise model should be weighting things the same. You can use a super-simple par file and a modest number of TOAs, but they need both frequency and time coverage, and some wiggliness for the noise parameters to fit.

**Comment by aarchiba** [comment]
I'm also not sure how urgent it is - I had the impression that the EPTA/PPTA relied primarily on DM red noise models to handle DM variations, but I don't think that's actually the case. If no one is using this feature of tempo2, it's less essential that PINT support it.
