### ISSUE TITLE
Deepcopy of TOAs leaves shallow copy of TOA flags

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1328]
Running:
```
import copy
from pint.models import get_model_and_toas
import pint.config

m, t = get_model_and_toas(
    pint.config.examplefile("NGC6440E.par"), pint.config.examplefile("NGC6440E.tim")
)

tc = copy.deepcopy(t)
print(f"TOAs: {t is tc}")
print(f"TOA Table: {t.table is tc.table}")
print(f"Flags: {t.table[0]['flags'] is tc.table[0]['flags']}")
```
Gives:
```
TOAs: False
TOA Table: False
Flags: True
```
This is confusing: I would expect the deepcopy to yield independent flag objects, but it isn't.  This can have unexpected behavior if you e.g., manipulate the flags on a copy, you end up manipulating both sets.  The TOA object and the TOA table both seem to copy fine.

**Comment by dlakaplan** [comment]
I think this could be solved by defining `__deepcopy__` for the `TOAs` object and then iterating through the flags - not sure if that is the best way

**Comment by scottransom** [comment]
Yikes!  Yeah, that is a real potential problem.

**Comment by scottransom** [comment]
Sounds like we should test that our models and fitters (and maybe other things?) can be deepcopied properly, as well.

**Comment by aarchiba** [comment]
I think this is a bug, or at least a surprising behaviour, in Astropy tables. Perhaps an upstream bug report is in order?

**Comment by dlakaplan** [comment]
Filed https://github.com/astropy/astropy/issues/13435

**Comment by dlakaplan** [comment]
Astropy confirmed as a bug.  In the meantime #1329 fixes for us.

**Comment by dlakaplan** [comment]
I wonder if allowing the flags to behave like a mixin column would help?  Something like that described in:
https://docs.astropy.org/en/stable/table/mixin_columns.html
