### ISSUE TITLE
fit_NGC6440E_MCMC.py is broken

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1345]
Running this file throws a `FileNotFoundError` for `NGC6440E.par.good`. It works if I change the par file to `NGC6440E.par`.
The issue is that `NGC6440E.par.good` is not getting installed when I do `setup.py install`.

**Comment by aarchiba** [comment]
Can you check that this works now?

**Comment by scottransom** [comment]
This is working for me if I simply run the script from the command line while in the `docs/examples` directory

**Comment by abhisrkckl** [comment]
It works now.
