### ISSUE TITLE
Move all data files from docs/examples directory to src/data/pint/examples/

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1349]
The example data should all be collected in one place. Not having everything in one place causes some of the example scripts to break as pkg_resources can't find the correct data files. Issue #1345 is a symptom of this.

**Comment by dlakaplan** [comment]
I think this is largely done, but possibly some files escaped because they had different extensions (like `.good`, as you mention).  So I agree that it would be good to move all of them.

**Comment by abhisrkckl** [comment]
OK.. I'll move them to the correct place.

**Comment by aarchiba** [comment]
Done?
