### ISSUE TITLE
`import pint` fails when astropy version is less than 4

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1354]
Here is how to reproduce the issue:

```
>>> import astropy
>>> astropy.version.major=3
>>> import pint
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/home/abhimanyu/anaconda3/envs/pint-devel/lib/python3.9/site-packages/pint_pulsar-0.7+2686.gbfa227ef.dirty-py3.9.egg/pint/__init__.py", line 110, in <module>
     log.warning(
 NameError: name 'log' is not defined
```

**Comment by dlakaplan** [comment]
But our requirements specify `astropy>=4`

**Comment by dlakaplan** [comment]
OK, I see.  There is an error (the logger isn't defined) but this should fail in any case.  I can fix the logger issue.

**Comment by dlakaplan** [comment]
Or, maybe it's better to just eliminate that test since we don't allow it in our `requirements.txt` any more.

**Comment by abhisrkckl** [comment]
I think eliminating it is better. Installing pint via pip or conda will anyway install the correct astropy version.
