### ISSUE TITLE
Split the computation of the correlated noise basis and weights?

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1363]
At present, the correlated noise basis matrix (F) and weights (W) for PLRedNoise and EcorrNoise are computed by a single function (ecorr_basis_weight_pair and pl_rn_basis_weight_pair). This is wasteful for the following reason: the weights depend on the noise parameter values whereas the basis matrix does not. This means that while sampling the parameter space in the context of something like an MCMC run, the basis matrix needs to be computed only once in principle for a given TimingModel and TOAs. This can be quite computationally expensive for PLRedNoise since its basis matrix contains sines and cosines. 

I propose that we split this computation into two functions (e.g., pl_rn_basis and pl_rn_weight) so that only the weight function needs to be called repeatedly.

**Comment by aarchiba** [comment]
That seems quite reasonable. Is there any situation where the basis functions might need to be recomputed?

**Comment by abhisrkckl** [comment]
There is only one scenario I can think of. By default, the fundamental frequency of the red noise is taken as 1/T where T is the data time span. However, if we want to take T as a model parameter, the basis matrix needs to be re-computed for every new value of T. 

AFAIK any value of T greater than or equal to the data time span gives similar results since fitting for F0 and F1 kills all low-frequency red noise components. So this is a moot point for most use cases, except if someone is specifically investigating the effect of T on their noise estimates.

**Comment by aarchiba** [comment]
The optimization this is designed to enable would fail in that case, though. Not necessarily a serious problem but it is something to be aware of. (An alternative approach could cache the basis functions to avoid unnecessary recomputation.)

**Comment by abhisrkckl** [comment]
The use case I mentioned is a really rare one and is not currently supported by PINT. i.e., the fundamental frequency of the Fourier basis is not a parameter of PLRedNoise. Currently, it is simply taken as the data time span. The `create_fourier_design_matrix` function has an option to set an arbitrary Tspan (reciprocal of the fundamental frequency) but is not actually used. If anyone wants to use it that way, they will have to extend PLRedNoise or create a separate model. BTW, tempo2 has a TNRedFLow parameter, which I think is supposed to be the fundamental frequency.

**Comment by abhisrkckl** [comment]
The issue with the caching approach is that the toa objects are mutable. If the toa object changes between two function calls (e.g. changing the flag that ECORR is based on), then the cache must go stale.  I don't think there is any simple and reliable way to check this.

**Comment by aarchiba** [comment]
> The issue with the caching approach is that the toa objects are mutable. If the toa object changes between two function calls (e.g. changing the flag that ECORR is based on), then the cache must go stale. I don't think there is any simple and reliable way to check this.

The cache would have to be in an object that carried a TOA object and a model object - in our case, a Fitter object. The downhill fitters do some of this sort of caching themselves already.
