### ISSUE TITLE
photonphase error

### ISSUE THREAD

**Issue by matteobachetti** [nanograv/PINT#1364]
I'm running photonphase with the following command:
```
photonphase file.evt file.par --plot --polycos
```
and I get the following error:
```
Traceback (most recent call last):
  File "/Users/meo/opt/anaconda3/envs/py39/bin/photonphase", line 8, in <module>
    sys.exit(main())
  File "/Users/meo/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pint/scripts/photonphase.py", line 256, in main
    phaseogram_binned(mjds, phases, bins=100, plotfile=args.plotfile)
  File "/Users/meo/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pint/plot_utils.py", line 90, in phaseogram_binned
    years = (mjds.value - 51544.0) / 365.25 + 2000.0
AttributeError: 'numpy.ndarray' object has no attribute 'value'
```
I'm investigating the issue, but just in case someone else already found a solution...

**Comment by paulray** [comment]
Hmm. That only happens with `--polycos`

**Comment by paulray** [comment]
@sashalvna might want to look at this

**Comment by sashalvna** [comment]
Yeah, that does make sense. I had not used --polycos with the --plot argument and had not (yet) written or tested it to work with it, though I had hoped to potentially come back to it. I can see if switching `mjds = read_fits_event_mjds()` to `mjds = ts.get_mhds()` and adjusting polycos as needed may get it to work, but it will probably require a bit of testing to get it to work smoothly.

**Comment by aarchiba** [comment]
Could one not just use `read_fits_event_mjds()*u.d`?

**Comment by paulray** [comment]
I just fixed it by making the plotter more robust. If floats are passed, it assumes units of days. PR coming

**Comment by matteobachetti** [comment]
Thanks!
