### ISSUE TITLE
Changes to Polyco interface

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1376]
As part of #1371 , I changed how to instantiate/load PINT `Polyco` objects.  Previously you made a new object and then read into it.  I changed it so that the reading is done as a class method. 

Old interface:
```
from pint.polycos import Polycos
p = Polycos()
p.read_polyco_file(filename)
```
Or from a timing model:
```
from pint.models import get_model
from pint.polycos import Polycos
model = get_model(filename)
p = Polycos()
p.generate_polycos(model, mjd_start, mjd_end, obs, nspan, ncoeff, obsfreq)
```

New interface
```
from pint.polycos import Polycos
p = Polycos.read(filename)
p.eval_abs_phase(mjds)
```
Or from a PINT timing model:
```
from pint.models import get_model
from pint.polycos import Polycos
model = get_model(filename)
p = Polycos.generate_polycos(model, 50000, 50001, "AO", 144, 12, 1400)
```

I think this sort of interface is better, but I am wary of breaking people's uses.  Are there people who use PINT polycos who would be impacted by this?

**Comment by dlakaplan** [comment]
@matteobachetti : @paulray mentioned you may use this.

**Comment by paulray** [comment]
@kerrm and @sashalvna might be interested in this change. It certainly looks good to me!
One question is what happens if I don't update the API? Wil `p = Polycos()` fail in a sensible way?

**Comment by kerrm** [comment]
Definitely better, imo!  Empty constructor is kindof useless, it won't break anything for me.

**Comment by dlakaplan** [comment]
It doesn't fail.  You can do that and still do:
```
p = Polycos()
p.read_polyco_file(filename)
```
I left that in for backward compatibility.  So I guess this doesn't break this part of the API.  Right now there isn't a deprecation warning when doing it that way but I could add one.

**Comment by paulray** [comment]
Excellent! If it is backwards compatible then it is very safe and all good!
A deprecation warning would be reasonable, but not absolutely necessary

**Comment by sashalvna** [comment]
That looks good to me!

**Comment by matteobachetti** [comment]
Thanks for notifying me! I'll try this out

**Comment by dlakaplan** [comment]
> Thanks for notifying me! I'll try this out

It's not actually pushed to the main branch yet. If you want to try you can use my fork, or just wait a bit.

**Comment by aarchiba** [comment]
> It doesn't fail. You can do that and still do:
> 
> ```
> p = Polycos()
> p.read_polyco_file(filename)
> ```
> 
> I left that in for backward compatibility. So I guess this doesn't break this part of the API. Right now there isn't a deprecation warning when doing it that way but I could add one.

I think it's a positive API change, but that a deprecation warning would be helpful.

**Comment by dlakaplan** [comment]
In many cases deprecation warnings are suppressed.  But I put it in anyway.

**Comment by aarchiba** [comment]
> In many cases deprecation warnings are suppressed. But I put it in anyway.

The ideal rule would be, someone writing code sees deprecation warnings only (but always!) for functions they call directly. So someone calling PINT functions should never see deprecation warnings coming out of numpy or Astropy, or even from PINT functions called deep in the guts of PINT. Sadly, I don't know of a system that is able to do this (although Python does have the plumbing to make it possible, at least for notebook users). Nevertheless I think it's valuable to emit the deprecation warnings so that at least someone being careful *can* know that they're using an API they should move away from.
