### ISSUE TITLE
(A)chromatic red noise models as a class factory

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1386]
PINT only supports achromatic red noise at present. There is a proposal to add a DM noise as well (See #1327).

Creating a separate DM red noise class will lead to a lot of code duplication. Instead, I propose that we define a class factory that takes the chromatic index as an argument and gives DM/scattering/variable-chromatic index red noise model as output. This will be much more elegant and minimize code duplication.

**Comment by aarchiba** [comment]
I don't think a class factory is a good idea. Let's keep the machinery to a minimum. If you want to do this, I think the way to go is to create a generic class that allows the frequency dependence to be controlled by a variable, then make the achromatic and DM red noise classes subclasses that fix the value to particular values.
