### ISSUE TITLE
PLANET_SHAPIRO=Y lead to obs_jupiter_pos error

### ISSUE THREAD

**Issue by jlzhang001** [nanograv/PINT#1390]
My PINT is 'version': '0.8.2'. When I use it read the par file with PLANET_SHAPIRO=Y,  throw out KeyError: 'obs_jupiter_pos'.  I paste my code, par file and time file here.
How to solve it?

//code
import pint.models
import pint.toa as toa
parfile='mypar_all_geminga.par'
timfile='zerophase_test.tim'
model = pint.models.get_model(parfile)
toas = pint.toa.get_TOAs(timfile, ephem='DE405',include_bipm=False)
ph = model.phase(toas, abs_phase=True)
print(ph)

//par file
PSRJ           J0633+1746
RAJ            6:33:54.289                  1.3447005271606647047e-4882
DECJ           +17:46:14.38
F0             4.2175670644628366901     1  0.00000000006224759499
F1             -1.952207986512879006e-13 1  1.3314295874080242488e-18
F2             2.2356802676342520737e-25 1  1.5386903977797948412e-26
F3             1.3346279291000038312e-34 1  7.723263422059601349e-35
PEPOCH         54800
POSEPOCH       54800                        2.1013144644450584414e-4932
DMEPOCH        54800
DM             0
START          54682.652930508818827     2
FINISH         59562.209082852568827     2
TZRMJD         57117.78048391352786
TZRFRQ         1400
TZRSITE        bat
TRES           2356.100
EPHVER         5
NE_SW          4
CLK            TT(TAI)
MODE 1
UNITS          TDB
TIMEEPH        IF99
DILATEFREQ     Y
PLANET_SHAPIRO Y
T2CMETHOD      IAU2000B
CORRECT_TROPOSPHERE  N
EPHEM          DE405
NITS           1
NTOA           477
CHI2R          22.4400 472

//tim file
1               1949.609 53801.38605118223       0.1
1               1949.609 53801.38605137047       0.1
8               0000.000 53750.00000000000       0.0
8               1400.000 54926.61859913624391425072            0.1
8               0000.000 54926.61859913624391425072            0.1
8               90000000 54926.61859913624391425072            0.1
8               0000.000 58000.0000000000        0.0

//output
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-582192fc6f85> in <module>
----> 1 ph = model.phase(toas, abs_phase=True)

~/anaconda3/envs/pipthreeML/lib/python3.7/site-packages/pint/models/timing_model.py in phase(self, toas, abs_phase)
   1057         """Return the model-predicted pulse phase for the given TOAs."""
   1058         # First compute the delays to "pulsar time"
-> 1059         delay = self.delay(toas)
   1060         phase = Phase(np.zeros(toas.ntoas), np.zeros(toas.ntoas))
   1061         # Then compute the relevant pulse phases

~/anaconda3/envs/pipthreeML/lib/python3.7/site-packages/pint/models/timing_model.py in delay(self, toas, cutoff_component, include_last)
   1051         for dc in self.DelayComponent_list[:idx]:
   1052             for df in dc.delay_funcs_component:
-> 1053                 delay += df(toas, delay)
   1054         return delay
   1055 

~/anaconda3/envs/pipthreeML/lib/python3.7/site-packages/pint/models/solar_system
    113                 for pl in ("jupiter", "saturn", "venus", "uranus", "nept
    114                     delay[loind:hiind] += self.ss_obj_shapiro_delay(
--> 115                         grp["obs_" + pl + "_pos"], psr_dir, self._ss_mas
    116                     )
    117         return delay * u.second

~/anaconda3/envs/pipthreeML/lib/python3.7/site-packages/astropy/table/table.py i
   1865     def __getitem__(self, item):
   1866         if isinstance(item, str):
-> 1867             return self.columns[item]
   1868         elif isinstance(item, (int, np.integer)):
   1869             return self.Row(self, item)

~/anaconda3/envs/pipthreeML/lib/python3.7/site-packages/astropy/table/table.py i
    244         """
    245         if isinstance(item, str):
--> 246             return OrderedDict.__getitem__(self, item)
    247         elif isinstance(item, (int, np.integer)):
    248             return list(self.values())[item]

KeyError: 'obs_jupiter_pos'

**Comment by scottransom** [comment]
Your TOAs table doesn't have the planet positions calculated by default.

You either need to add a `planets=True` flag to your `pint.toa.get_TOAs()` call, or, even better, to help you make sure that you don't forget get model-dependent things when loading your TOAs, you should use `pint.models.get_model_and_toas()` to load the model and the TOAs at the same time (and get rid of the two separate model and TOA loads).

**Comment by paulray** [comment]
Maybe we can add a better error message to that KeyError, since this happens to people a lot?

**Comment by jlzhang001** [comment]
> KeyError: 'obs_jupiter_pos'



> Your TOAs table doesn't have the planet positions calculated by default.
> 
> You either need to add a `planets=True` flag to your `pint.toa.get_TOAs()` call, or, even better, to help you make sure that you don't forget get model-dependent things when loading your TOAs, you should use `pint.models.get_model_and_toas()` to load the model and the TOAs at the same time (and get rid of the two separate model and TOA loads).



> Your TOAs table doesn't have the planet positions calculated by default.
> 
> You either need to add a `planets=True` flag to your `pint.toa.get_TOAs()` call, or, even better, to help you make sure that you don't forget get model-dependent things when loading your TOAs, you should use `pint.models.get_model_and_toas()` to load the model and the TOAs at the same time (and get rid of the two separate model and TOA loads).

Thanks a lot!  I use your better way to load model ans TOAs in one line. It works well now.

**Comment by jlzhang001** [comment]
> Maybe we can add a better error message to that KeyError, since this happens to people a lot?

If it can show more details, that will be easy to find the why the error happens.

**Comment by paulray** [comment]
I added a more informative message in PR #1391
