### ISSUE TITLE
Merging TOAs just checks for consistent number of columns

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1400]
Merging TOAs does:
```
num_cols = [len(tt.table.columns) for tt in TOAs_list]
    if len(set(num_cols)) > 1:
        raise TypeError(
            f"merge_TOAs() cannot merge. Inconsistent numbers of table columns: {num_cols}\n{s}"
        )
```
so it just looks for consistent number of columns.  The actual merge via `vstack` should enforce that they are the same columns, but this exception may not be triggered.  Should we either remove this check (and let `astropy` tables handle it) or put in an additional check?

**Comment by dlakaplan** [comment]
The `astropy` tables exceptions aren't particularly user friendly....
```
Traceback (most recent call last):
  File "/Users/kaplan/pythonpackages/PINT_dlakaplan/./test_merge.py", line 28, in <module>
    tall = pint.toa.merge_TOAs(t)
  File "/Users/kaplan/pythonpackages/PINT_dlakaplan/src/pint/toa.py", line 2465, in merge_TOAs
    nt.table = table.vstack(tables, join_type="exact", metadata_conflicts="silent")
  File "/Users/kaplan/opt/anaconda3/envs/pintdev/lib/python3.9/site-packages/astropy/table/operations.py", line 651, in vstack
    out = _vstack(tables, join_type, col_name_map, metadata_conflicts)
  File "/Users/kaplan/opt/anaconda3/envs/pintdev/lib/python3.9/site-packages/astropy/table/operations.py", line 1373, in _vstack
    raise TableMergeError('Inconsistent columns in input arrays '
astropy.table.np_utils.TableMergeError: Inconsistent columns in input arrays (use 'inner' or 'outer' join_type to allow non-matching columns)
```

**Comment by scottransom** [comment]
I think that error from astropy is quite reasonable (I mean the issue really is inconsistent columns) and I'm not sure we really want to do too much hand-holding over merging tables when users can (and do) easily add columns to TOA tables on their own.  If they do that, I don't think they should have an expectation that they will be able to merge their tables.

**Comment by aarchiba** [comment]
I think we should let Astropy decide whether the merge can work, but I think that message is unhelpful - which columns don't match? - so we should catch the exception and re-issue a better message. We should also try to resolve some known, easy, reasons merges fail - for example, we already use NaN in the pulse number column to signal "no pulse number known" so why not use that to handle missing pulse number columns?
