### ISSUE TITLE
oldestdeps is using new numpy

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1401]
In spite of the details in `tox.ini`, on the CI machines at least the `oldestdeps` is using the most recent numpy. This has presumably been going on for a while but it was brought to light by the removal of the deprecated `numpy.isscalar`.

**Comment by dlakaplan** [comment]
I think it's `numpy.asscalar()` that is deprecated.

**Comment by paulray** [comment]
Indeed. I just made a virtualenv and then did `pip install numpy==1.17.5`, followed by `pip install astropy==4.0`, as is the case in our `oldestdeps` environment.  This uninstalled numpy-1.17.5 and installed the newest numpy-1.23.3. This is what is causing the problem.  Presumably installing astropy-4.0 didn't used to force an update of numpy, but now it is.

**Comment by abhisrkckl** [comment]
The issue may be that the version of numdifftools is not specified. The latest numdifftools version requires numpy>=1.9.

**Comment by paulray** [comment]
I tried to fix tox.ini with this diff, but it fails when building scipy:
```
diff --git a/tox.ini b/tox.ini
index d35d05e9..a13dd9ef 100644
--- a/tox.ini
+++ b/tox.ini
@@ -60,10 +60,11 @@ basepython = python3.8
 deps =
     numpy==1.17.*
     astropy==4.0
+    scipy<0.19
+    numdifftools==0.9.39
     pytest
     coverage
     hypothesis
-    numdifftools
 commands = {posargs:pytest}
 
 [testenv:report]
```
This fails even in my own virtualenv with just `pip install scipy==0.18.1`

**Comment by dlakaplan** [comment]
It looks like the astropy fix discussed backporting:
https://github.com/astropy/astropy/pull/12535
but I can't quite parse which version(s) that appears in.  

Should we change the astropy requirement of the oldestdeps?  Is there any intermediate step that would work?

**Comment by paulray** [comment]
I'm trying to make progress on this, but now I can't even get numpy to install at all.  I create an empty virtualenv with python 3.8, like this:
```
mkvirtualenv -p /usr/bin/python3.8 oldestdeps
```
Then in that empty environment, I just try this:
```
pip install numpy==1.17.0
```
and it crashes while doing the build. This is the case on both my Mac and my Ubuntu linux box. Is this the case for others?

**Comment by dlakaplan** [comment]
fails within conda on my Mac as well.

**Comment by dlakaplan** [comment]
numpy 1.18 goes in with no problem.  I think I can then install astropy 4.0.0 and import it without a problem.  would bumping the oldestdeps numpy to 1.18 solve this?

**Comment by paulray** [comment]
Trying now...

**Comment by dlakaplan** [comment]
no, it looks like the scipy install fails.  That's so old compared to the current version: why 0.18.1 in particular?

**Comment by paulray** [comment]
No idea. That was the version when we froze oldestdeps I guess. Should be OK to bump it up some.

**Comment by paulray** [comment]
OK, I think I fixed it. PR coming. It was matplotlib that was forcing the numpy update.

**Comment by paulray** [comment]
Hmm. It mostly works but I'm getting 2 failures. One is that `test_astropyobservatory.py` fails to find the 'keck' observatory.  The other is this error in `test_photonphase.py`:
```
tests/test_photonphase.py ......F                                                                                                                                                         [100%]

=========================================================================================== FAILURES ============================================================================================
_________________________________________________________________________________ test_nicer_result_bary_polyco _________________________________________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7f4b9e862d00>, tmp_path = PosixPath('/tmp/pytest-of-paulr/pytest-1/test_nicer_result_bary_polyco0')

    @pytest.mark.skipif(
        "DISPLAY" not in os.environ, reason="Needs an X server, xvfb counts"
    )
    def test_nicer_result_bary_polyco(capsys, tmp_path):
        "Check that barycentered NICER data is processed correctly with --polyco."
        outfile = tmp_path / "polycos-photonphase-test.evt"
        cmd = f"--polycos --outfile {outfile} {eventfile_nicer} {parfile_nicer}"
>       photonphase.main(cmd.split())

tests/test_photonphase.py:133: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/pint/scripts/photonphase.py:230: in main
    phases = p.eval_phase(mjds)
src/pint/polycos.py:914: in eval_phase
    return self.eval_abs_phase(t).frac
src/pint/polycos.py:943: in eval_abs_phase
    entryIndex = self.find_entry(t)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pint.polycos.Polycos object at 0x7f4b9792bd60>, t = array([58155.66508743, 58155.66509201, 58155.66509863, ...,
       58155.7987491 , 58155.79875422, 58155.79876067])

    def find_entry(self, t):
        """Find the right entry for the input time.
    
        Parameters
        ---------
        t: numpy.ndarray or float
           A time array in MJD.
    
        Returns
        -------
        numpy.ndarray
            Indices corresponding to the desired time(s)
    
        Raises
        ------
        ValueError
            If the input time(s) are not covered by the polycos
        """
        if not isinstance(t, (np.ndarray, list)):
            t = np.array([t])
    
        # Check if polyco table exists
>       if self.polycoTable is None:
E       AttributeError: 'Polycos' object has no attribute 'polycoTable'

src/pint/polycos.py:883: AttributeError
```
