### ISSUE TITLE
PINT should emit a helpful error message upon encountering a TCB par file

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1403]
Right not it just throws an exception "ValueError: PINT only supports 'UNITS TDB'".
This is very unhelpful, especially for beginners.

I propose we improve this error message by providing more information such as
1. A link to the page in the PINT documentation that discusses TCB vs TDB (https://nanograv-pint.readthedocs.io/en/latest/explanation.html#time-scales) 
2. A hint on converting from TCB to TDB (e.g. using tempo2 transform plugin).

**Comment by paulray** [comment]
Good suggestions
