### ISSUE TITLE
Issues with pint.utils.dmxparse 'dmxparse.out' file inconsistent with par file

### ISSUE THREAD

**Issue by LuluAgazie** [nanograv/PINT#1408]
When using dmxparse to save DMX results to a dmxparse.out file, the numbers in the columns 'DMXR1' and 'DMXR2' do not match the output in the corresponding par `file.`

Example:
Par file:
DMX_0001           -0.0010470773344601306 1 0.000123043034179296
DMXR1_0001         58646.4663725097416319
DMXR2_0001         58651.5523695789961458
DMX_0002           -0.0012261001248451537 1 0.00014812597657924183
DMXR1_0002         58656.4382857748350926
DMXR2_0002         58661.5243368757728588
DMX_0003           -0.0008169557997421842 1 0.0001986402937670069
DMXR1_0003         58663.4190430132512153
DMXR2_0003         58664.5160527116386228
DMX_0004           -0.0013291644748532243 1 0.00018892836757396813
DMXR1_0004         58677.3808724395421412
DMXR2_0004         58683.4641881236384490

dmxparse.out file:
Columns: DMXEP DMX_value DMX_var_err DMXR1 DMXR2 DMX_bin
58646.4664 -1.4676426e-03 1.204e-04 58646.4664 58646.4664 DMX_0001
58656.4383 -1.6466654e-03 1.453e-04 58656.4383 58656.4383 DMX_0002
58663.4190 -1.2375210e-03 1.964e-04 58663.4190 58663.4190 DMX_0003
58677.3809 -1.7497297e-03 1.873e-04 58677.3809 58677.3809 DMX_0004

**Comment by dlakaplan** [comment]
There's a typo: I'll fix it.
