### ISSUE TITLE
test_photonphase.py fails on my machine

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1414]
I think it works fine in the CI machine but fails on my laptop.
I am running Ubuntu in WSL2 (Windows 11).
`pint.__version__ == '0.9.0+481.g5fbac403'`

The pytest output is as follows:

> $ pytest test_photonphase.py 
> ====================================== test session starts =======================================
> platform linux -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
> rootdir: /home/susobhan/Work/pint-devel/PINT
> plugins: forked-1.4.0, cov-3.0.0, xdist-2.5.0, hypothesis-6.53.0, anyio-3.6.1
> collected 7 items                                                                                
> 
> test_photonphase.py ......F                                                                [100%]
> 
> ============================================ FAILURES ============================================
> _________________________________ test_nicer_result_bary_polyco __________________________________
> 
> capsys = <_pytest.capture.CaptureFixture object at 0x7f9da0831150>
> tmp_path = PosixPath('/tmp/pytest-of-susobhan/pytest-11/test_nicer_result_bary_polyco0')
> 
>     @pytest.mark.skipif(
>         "DISPLAY" not in os.environ, reason="Needs an X server, xvfb counts"
>     )
>     def test_nicer_result_bary_polyco(capsys, tmp_path):
>         "Check that barycentered NICER data is processed correctly with --polyco."
>         outfile = tmp_path / "polycos-photonphase-test.evt"
>         cmd = f"--polycos --outfile {outfile} {eventfile_nicer} {parfile_nicer}"
> >       photonphase.main(cmd.split())
> 
> test_photonphase.py:133: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> ../../../../miniconda3/envs/pint-devel/lib/python3.10/site-packages/pint_pulsar-0.9.0+446.g3d1edb13-py3.10.egg/pint/scripts/photonphase.py:230: in main
>     phases = p.eval_phase(mjds)
> ../../../../miniconda3/envs/pint-devel/lib/python3.10/site-packages/pint_pulsar-0.9.0+446.g3d1edb13-py3.10.egg/pint/polycos.py:914: in eval_phase
>     return self.eval_abs_phase(t).frac
> ../../../../miniconda3/envs/pint-devel/lib/python3.10/site-packages/pint_pulsar-0.9.0+446.g3d1edb13-py3.10.egg/pint/polycos.py:943: in eval_abs_phase
>     entryIndex = self.find_entry(t)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <pint.polycos.Polycos object at 0x7f9d994bab90>
> t = array([58155.66508743, 58155.66509201, 58155.66509863, ...,
>        58155.7987491 , 58155.79875422, 58155.79876067])
> 
>     def find_entry(self, t):
>         """Find the right entry for the input time.
>     
>         Parameters
>         ---------
>         t: numpy.ndarray or float
>            A time array in MJD.
>     
>         Returns
>         -------
>         numpy.ndarray
>             Indices corresponding to the desired time(s)
>     
>         Raises
>         ------
>         ValueError
>             If the input time(s) are not covered by the polycos
>         """
>         if not isinstance(t, (np.ndarray, list)):
>             t = np.array([t])
>     
>         # Check if polyco table exists
> >       if self.polycoTable is None:
> E       AttributeError: 'Polycos' object has no attribute 'polycoTable'
> 
> ../../../../miniconda3/envs/pint-devel/lib/python3.10/site-packages/pint_pulsar-0.9.0+446.g3d1edb13-py3.10.egg/pint/polycos.py:883: AttributeError
> -------------------------------------- Captured stderr call --------------------------------------
> 100%|██████████| 3/3 [00:01<00:00,  1.54it/s]
> ==================================== short test summary info =====================================
> FAILED test_photonphase.py::test_nicer_result_bary_polyco - AttributeError: 'Polycos' object ha...
> ================================== 1 failed, 6 passed in 32.07s ==================================

**Comment by paulray** [comment]
This is fixed in #1411
