### ISSUE TITLE
Bug in lcprimitives.py

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1416]
There is an undefined variable "x0" in the `LCKernelDensity.integrate` function.
![image](https://user-images.githubusercontent.com/20718391/194942860-4558d1a0-df98-4e25-84c4-80e5987f75db.png)

It seems line no 1312 is using x0 and x1 instead of x1 and x2.

I am not sure how to trigger this. I came across this during a code cleanup operation.

**Comment by dlakaplan** [comment]
I don't think I've ever used this module.  Maybe @kerrm knows more?

**Comment by kerrm** [comment]
Oof -- thanks for pointing it out, but this code is specific to Fermi timing stuff, and not really for wider use.  I am working on a big PR now, and can't really recommend it for scrutiny by others.

This particular bit of code is quite old and certainly a candidate for removal.
