### ISSUE TITLE
PINT does not test if `PLRedNoise` and `PLDMNoise` models agree with enterprise and TempoNest

### ISSUE THREAD

**Issue by blarsen10** [nanograv/PINT#1422]
Current tests for the `PLRedNoise` and `PLDMNoise` models make sure that the models can be instatiated correctly and agree with each other for monochromatic data, but no test has been added that shows the models are interpreted the same way as the corresponding models in enterprise and Tempo2/TempoNest. There is some discussion on this in PR #1396.

**Comment by abhisrkckl** [comment]
This comparison is done rigorously in https://arxiv.org/abs/2405.01977

**Comment by abhisrkckl** [comment]
Not with TempoNest though. That will be quite difficult since it's very difficult to get TN working.
