### ISSUE TITLE
ephemeris_connection CI test fails

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1423]
It complains about an expired certificate. @dlakaplan @aarchiba 
 
Here is the traceback.

> ephemeris_connection run-test: commands[0] | python check_ephemeris_connection.py
> Traceback (most recent call last):
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/urllib/request.py", line 1348, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers,
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line 1282, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line 1328, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line 1277, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line 1037, in _send_output
>     self.send(msg)
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line 975, in send
>     self.connect()
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line 1454, in connect
>     self.sock = self._context.wrap_socket(self.sock,
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
>     return self.sslsocket_class._create(
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/ssl.py", line 1071, in _create
>     self.do_handshake()
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/ssl.py", line 1342, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/runner/work/PINT/PINT/check_ephemeris_connection.py", line 5, in <module>
>     urllib.request.urlopen("https://data.nanograv.org/static/data/ephem/de405.bsp").read()
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/urllib/request.py", line 2[16](https://github.com/nanograv/PINT/actions/runs/3273707030/jobs/5386260750#step:8:17), in urlopen
>     return opener.open(url, data, timeout)
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/urllib/request.py", line 5[19](https://github.com/nanograv/PINT/actions/runs/3273707030/jobs/5386260750#step:8:20), in open
>     response = self._open(req, data)
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/urllib/request.py", line 536, in _open
>     result = self._call_chain(self.handle_open, protocol, protocol +
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
>     result = func(*args)
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/urllib/request.py", line 1391, in https_open
>     return self.do_open(http.client.HTTPSConnection, req,
>   File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/urllib/request.py", line 1[35](https://github.com/nanograv/PINT/actions/runs/3273707030/jobs/5386260750#step:8:36)1, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
> ERROR: InvocationError for command /home/runner/work/PINT/PINT/.tox/ephemeris_connection/bin/python check_ephemeris_connection.py (exited with code 1)
> ___________________________________ summary ____________________________________
> ERROR:   ephemeris_connection: commands failed

**Comment by paulray** [comment]
The issue seems to be with data.nanograv.org so probably @JPGlaser is the one to figure it out

**Comment by abhisrkckl** [comment]
Opening the link (https://data.nanograv.org/static/data/ephem/de405.bsp) in Chrome gives a NET::ERR_CERT_DATE_INVALID message. Seems to be an expired https certificate on that domain.

**Comment by dlakaplan** [comment]
@abhisrkckl : I think it's fixed.  Can you restart CI?

**Comment by abhisrkckl** [comment]
This issue is happening again. I am getting the following error in the CI machine. 

> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
