### ISSUE TITLE
Minor bug in gridding notebook examples

### ISSUE THREAD

**Issue by bwmeyers** [nanograv/PINT#1431]
In the parameter gridding notebooks linked on the PINT wiki, there seems to be a mismatch with the expected returned values from the grid functions.

Specifically, `pint.gridutils.grid_chisq(...)` returns a tuple of the chisq array and a dictionary for additional parameters requested, but the subsequent code to plot/investigate the result is expecting only the chisq numpy array. My simple solution was to just add a `[0]` to the end of the `grid_chisq` calls, after which everything worked.

Maybe it will be useful to update the notebooks to also highlight what the additional parameter dictionaries are used for?

**Comment by dlakaplan** [comment]
I think the first task is done, but please check.

As for the second, that is a little more complex.  If you have any use cases you could suggest them or contribute a notebook

**Comment by bwmeyers** [comment]
I don't have any specific examples in mind, I just thought it had been implemented for a specific reason and so maybe there was already an example case floating around. I don't think it's that important tbh, better to just make sure the basic gridding example flows without issue :)
