### ISSUE TITLE
PINT is missing the Effelsburg Asterix clock correction

### ISSUE THREAD

**Issue by gooddc** [nanograv/PINT#1432]
When loading TOAs specifically for Effelsburg Asterix (a backend), PINT claims 
"2022-11-08 11:26:30.012 | INFO     | pint.observatory.topo_obs:clock_corrections:353 - Observatory effelsberg_asterix requires no clock corrections."

This isn't actually true. Clock correction info is available here: https://ipta.github.io/pulsar-clock-corrections/T2runtime/clock/effix2gps.clk.html.

When I plot residuals from ASTERIX data right now, I get something like this: 
![image](https://user-images.githubusercontent.com/10750604/200624877-729b790a-5c51-4afd-a3e4-ca152d07728e.png)

But that's suspiciously similar to the clock correction file 
![image](https://user-images.githubusercontent.com/10750604/200624942-d5ed5365-e02c-4169-b194-bdfa8c32c62f.png)

So I'm pretty sure this is what's messing me up! I'm supplying the par & tim I used in making that figure to @aarchiba and @dlakaplan via email, as it's not technically my data to splash around publicly.

**Comment by aarchiba** [comment]
If you want to try out PR #1433 I think it'll make the problem go away?

**Comment by aarchiba** [comment]
I think that PR fixes Effelsberg/Asterix, but I don't know enough about the various telescopes PINT supports to know where there are other cases where we haven't included a needed clock correction. It might be possible to go through the list of observatory names/abbreviat8ions and the list of global clock correction files and hope to identify such cases.
