### ISSUE TITLE
pint.ltinterface is broken

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1441]
This module is broken. This issue never came up before because this has 0% test coverage (see #603). I only came across this because I was looking at which modules should have more test coverage.

What is this module used for? I could not find any open issues about this. Provided that this has probably been broken for a while and nobody noticed, I think it is safe to assume that this is not widely used.

**Comment by scottransom** [comment]
I think this is how (or used to be how) Enterprise interfaces with PINT.  "lt" is libstempo.  So it would be worth asking someone like @Hazboun6 or @vallis whether this is still used and potentially tested via tests in Enterprise or libstempo itself.

**Comment by abhisrkckl** [comment]
I think enterprise may have changed the way they interface with PINT. I could not find any reference to `ltinterface` in https://github.com/nanograv/enterprise/blob/master/enterprise/pulsar.py .

This is how enterprise imports PINT:
```
try:
    import pint
    from pint.models import TimingModel, get_model_and_toas
    from pint.residuals import Residuals as resids
    from pint.toa import TOAs
```

**Comment by abhisrkckl** [comment]
According to @Hazboun6 ENTERPRISE does not use this module.

**Comment by paulray** [comment]
I recall that this module was written by @vhaasteren 
I wouldn't be surprised if it isn't currently in use anywhere.

**Comment by scottransom** [comment]
Yeah, I think we should just zap it.

**Comment by Hazboun6** [comment]
I replied on Slack, but just for posterity, this module is not used in `enterprise`. The `enterprise.pulsar` module has specific classes for different timing packages, `Tempo2Pulsar` and `PintPulsar`, that are then wrapped by a convenience class, `Pulsar`. I think this keeps the `enterprise` developers aware of the various details of the interface that are important for the GW and noise analyses.

**Comment by vhaasteren** [comment]
Yep, I confirm that I wrote this eons ago, well before Enterprise even existed. The way Enterprise interfaces with PINT is neater this way, and I don't see any reason why you would want to have a libstempo interface.

It was used back then to patch PINT into the multiple GW detection packages in one go. But those are no longer used
