### ISSUE TITLE
Readthedocs build fails

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1458]
This issue seems to affect new updates to PRs. 
See
https://readthedocs.org/projects/nanograv-pint/builds/18794223/
https://readthedocs.org/projects/nanograv-pint/builds/18793665/

The error message is
:3: (SEVERE/4) Unexpected section title or transition.

This seems to be triggered by some change in `pint.templates.lcfitters.LCFitter` (possibly from PR #1455 ?)

**Comment by abhisrkckl** [comment]
I am getting the same error in my laptop.
The root cause seems to be a missing function in `pint.gridutils`

WARNING: autodoc: failed to import function 'grid_chisq_col' from module 'pint.gridutils'; the following exception was raised:
Traceback (most recent call last):
  File "/home/susobhan/miniconda3/envs/pint-devel/lib/python3.10/site-packages/sphinx/util/inspect.py", line 380, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pint.gridutils' has no attribute 'grid_chisq_col'

**Comment by dlakaplan** [comment]
I think the changes I made in #1459 will fix this.  Maybe when the CI there finishes you can check it and merge.
