### ISSUE TITLE
timing_model.py code review 

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#146]
This is the timing_model.py review on April 13th. 
-  Cache should be tested in another branch. If it is not working, we should consider to delete.
  The line in the file:
  https://github.com/nanograv/PINT/blob/349396b3d43930a4cad6b6b38bc4cdea618f9c7c/pint/models/timing_model.py#L20
- Docstring for TimingModel class need to be completed, example code for developers should be there. 
  Line in the file, 
  https://github.com/nanograv/PINT/blob/349396b3d43930a4cad6b6b38bc4cdea618f9c7c/pint/models/timing_model.py#L99
- Model components order see  issue #138 
- param_register should be a method that returns the parameter information. 
  Line in the file:
  https://github.com/nanograv/PINT/blob/349396b3d43930a4cad6b6b38bc4cdea618f9c7c/pint/models/timing_model.py#L112
- Function d_phase_d_tpulsar should be implemented. 
  Line in the file:
  https://github.com/nanograv/PINT/blob/349396b3d43930a4cad6b6b38bc4cdea618f9c7c/pint/models/timing_model.py#L209

*d_phase_d_toa will be changed completely, see pull request #107 
Line in the file:
https://github.com/nanograv/PINT/blob/349396b3d43930a4cad6b6b38bc4cdea618f9c7c/pint/models/timing_model.py#L216

Some other changes has been made on during the telecon.

**Comment by paulray** [comment]
Is there something needed to close this, or can it be closed now?

**Comment by luojing1211** [comment]
I think it is ok to close.
