### ISSUE TITLE
Simulated TOAs are not correctly written into a tim file

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1464]
The `pint.simulation.make_fake_toas_uniform` function generates uniformly spaced TOAs. When I plot the residuals of the simulated `TOAs` object, I get zero residuals up to some numerical error as expected. However, some modulations are seen when I write this `TOAs` object into a `tim` file and then plot the residuals from the generated tim file. 

Why does this happen? 

Here is some code to reproduce this. The difference is at the ~100 ns level.
```
from pint.config import examplefile
from pint.simulation import make_fake_toas_uniform
from pint.models import get_model, get_model_and_toas
from pint.residuals import Residuals
import astropy.units as u
import matplotlib.pyplot as plt

parfile = examplefile("NGC6440E.par")
timfile = "fake.tim"

model = get_model(parfile)

toas = make_fake_toas_uniform(
        startMJD=56000,
        endMJD=56400,
        ntoas=100,
        model=model,
        obs="ao",
        error=1 * u.microsecond,
        freq=1400 * u.MHz
    )
res = Residuals(toas, model)

plt.plot(toas.get_mjds(), res.calc_time_resids(), label="From TOAs object (before writing)")

toas.write_TOA_file(timfile, name="fake", format="TEMPO2")

model1, toas1 = get_model_and_toas(parfile, timfile)
res1 = Residuals(toas1, model1)

plt.plot(toas1.get_mjds(), res1.calc_time_resids().to("us"), label="From tim file (after writing)")
plt.xlabel("MJD")
plt.ylabel("Residuals (us)")
plt.legend()
plt.show()
```

EDIT: Here is the residual plot.
![1464](https://user-images.githubusercontent.com/20718391/207147669-08311925-c4ee-40b6-8888-14f82963baf5.png)

**Comment by dlakaplan** [comment]
I see a difference of around 27us, which is probably the BIPM TT-TAI difference?

**Comment by abhisrkckl** [comment]
It seems that this may be the same as #1161. I'll check if #1165 fixes this.

**Comment by abhisrkckl** [comment]
I tried with #1165. Here are the new residuals. While the residuals have improved (only ~0.25 ns now), there is still some modulation remaining.
![1464-2](https://user-images.githubusercontent.com/20718391/207154817-f872a35d-ab47-405f-84ba-50d1dd9c268f.png)

**Comment by scottransom** [comment]
That might be down to the level of `long double` representation precision.  And if so, those are equivalent.

**Comment by paulray** [comment]
The plot looks like 25 ns to me, not 0.25 ns. Am I confused?

**Comment by abhisrkckl** [comment]
Sorry, it's 25 ns. That was a typo.

**Comment by dlakaplan** [comment]
I tried changing the simulated site from AO to GBT and that didn't change the results, so it's not a site clock issue.  I think its a time system issue.  The test par file has:
```
CLK              UTC(NIST)
```
which PINT doesn't like: it says that it changes it internally to `TT(BIPM2021)`.  The result is:
```
Max difference: 22.984108755459136 ns
Min difference: 0.08179398135153208 ns
RMS difference: 4.636401418746137 ns
```
consistent with the plot above.

But if I change that to `TT(BIPM2021)` before generating the fake TOAs then I get:
```
Max difference: 0.6363268811334833 ns
Min difference: 0.00015147033583956578 ns
RMS difference: 0.18087531431523426 ns
```
So something in the fake TOA generation still depends on the choice of clock even when it says it doesn't. And going to one of PINT's preferred clocks make the discrepancies go away.  Or at least that's how I read this.

**Comment by dlakaplan** [comment]
OK, I think I found the issue.  Can update during the call.
