### ISSUE TITLE
PINT is missing LEAP clock corrections

### ISSUE THREAD

**Issue by blarsen10** [nanograv/PINT#1478]
Similar issue to #1432 . PINT claims "observatory leap requires no clock corrections," but it does actually need them. I found out from Kuo Liu on the IPTA slack that leap uses a two-tier correction to gps, first leap2effix, and then effix2gps (this should be similar to the way clock corrections are applied for ncyobs). Both of these files are available on the [Tempo2 clock files page on github](https://github.com/mattpitkin/tempo2/tree/master/T2runtime/clock) but I'm not sure what's the best way to get them read by PINT. It looks in particular like `leap2effix.clk` is missing from the global clock corrections repo.

Here are some residuals unique to this backend in both J0030 and J1744 showing the effect of missing the clock files:

![image](https://user-images.githubusercontent.com/60462875/208495305-f50c6467-12f4-46f9-96cf-193c2eb7ac97.png)

![image](https://user-images.githubusercontent.com/60462875/208495321-e449410d-5305-42a0-b67f-2da38f2959b7.png)

Happy to send my par and tims over to anyone interested for testing this!

**Comment by dlakaplan** [comment]
There are 2 things needed to solve this:
* Update `observatories.json` with the clock entries for LEAP (simple PR)
* Put the `leap2effix` file at https://ipta.github.io/pulsar-clock-corrections/status.html
I suspect @aarchiba can easily help with both of those.  You or others could also submit the PINT PR but we'd need @aarchiba to update the clock repo in any case.

**Comment by blarsen10** [comment]
Thanks David! I'm happy to handle the PINT PR once the clock repo is updated.
