### ISSUE TITLE
Tag-specific FD parameters

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1480]
Since different instruments may be using different templates, we may need multiple FD parameters for different telescopes, backends etc. 

One way to implement this will be as a PrefixMaskParameter which has properties of both prefix and mask parameters.

**Comment by rossjjennings** [comment]
As discussed at the PINT meeting today, a similar, but not necessarily directly related, issue is #1059 (Mask parameters have unhelpful names).
