### ISSUE TITLE
PINT example files should load without warnings

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1483]
When I load `NGC6440E.par` and the corresponding `.tim` file, I get the following warnings:
```
WARNING  (pint.logging                  ): /home/archibald/projects/pint/PINT/src/pint/models/timing_model.py:373 UserWarning: PINT only supports 'T2CMETHOD IAU2000B'
WARNING  (pint.toa                      ): CLOCK = UTC(NIST) is not implemented. Using TT(BIPM2021) instead.
WARNING  (pint.toa                      ): Unknown command MODE in line MODE 1
```

We should remove the inputs that cause these.

When PINT's example files and test files were not separate, we kept around some files with unsupported settings for testing purposes. Now that the example files are in a separate location, we should remove the settings that cause PINT to emit unnecessary warnings.

**Comment by paulray** [comment]
I agree. The "standard" example of NGC6440E that we use in our examples and walkthrough should have a fully supported parfile.

**Comment by aarchiba** [comment]
I think this logic applies to everything in `pint.config.examplefile(...)`. Should be an easy fix I think?
