### ISSUE TITLE
DownhillGLSFitter doesn't populate noise_resids

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1485]
The residuals objects produced by `GLSFitter` have a dictionary `.noise_resids` that contains information about the red noise. The `DownhillGLSFitter` does not populate this dictionary. 

This can be checked in the `docs/exampler/understanding_fitters.ipynb` notebook, by swapping in `DownhillGLSFitter` for `GLSFitter`.

**Comment by aarchiba** [comment]
There is a similar problem where `.get_noise_covariancematrix()` doesn't work on a downhill fitter either.

**Comment by abhisrkckl** [comment]
This issue no longer exists. I am closing this.
