### ISSUE TITLE
Passing an astropy Time object (with Time.value an array) to TOA and then TOAs

### ISSUE THREAD

**Issue by MRegeard** [nanograv/PINT#1504]
**Version :** 0.9.3

**Context :** 
I'm using PINT to compute phases of pulsar from H.E.S.S. data, together with Gammapy. I get the time array by calling `gammapy.data.EventList.time`, which gives me directly a `astropy.Time` object with scale, format and an array for the values. So my initial guess was that I should pass this `astropy.Time` object to `TOA`. 
For instance : `TOA(time, errors, obs, ...)`. 
This gives me a unique object `TOA`, and when calling TOA.mjd it gives me back my initial `astropy.Time`object. 
Then I pass this `TOA`object to `TOAs` (transforming it into a list of this object) to be able to compute my phases. 
But this is where the issue occurs. When calling the `build_table()`function in the `__init__`of `TOAs`, it creates a table which has only one line, with the array of mjd stored in a unique cell of the table. Therefore, it bugs. 

**Solution :**
Of course the solution to this issue is quite simple, I just loop over my `Time`array to create a list of `TOA`object. 

**Question / Suggestion :**
_Before going to this section, I'm not familiar with all the use cases of PINT, so I might question or suggest things that are irrelevant in most use case._ 

My first question is why the `TOA` / `TOAs` class is not able to take an `astropy.Time` which as an array of value within it?
My second question is why the `TOAs` class input cannot be a `TOA`object ?

My suggestion is that `TOAs`class could take a `TOA`object or a list of `TOA`object has an input, and that the `TOA.mjd`, in the unique `TOA` as well as in the list of `TOA`, could be an `astropy.Time` object with an array of value. 
I think that it would be more intuitive for the user, at least it is for me.
Moreover, it could save some computing time since the need to loop over the list of `TOA`is not alway necessarily in the `build_table()`function.

**Comment by paulray** [comment]
One of the issues preventing us from using a `Time` with an array of values is that such an object has only one `location` attribute.  So, for the  moment, you must create `TOA` objects with just a single TOA in it, not an array of times. Generally you should create a list of such objects (e.g. from your time array using list comprehension), then create your `TOAs` table with `toa.get_TOAs_llist()`.

It would be possible to write a routine that handled the case of an array-valued `Time` as a special case (e.g. `get_TOAs_TimeArray()` or something like that) but no one has done it yet.  There could be an efficiency benefit, but otherwise it would be the same as what we already have with the list of `TOA` objects.

**Comment by paulray** [comment]
Yes, that is a good example!

**Comment by dlakaplan** [comment]
@MRegeard : does this help?
https://nanograv-pint--1509.org.readthedocs.build/en/1509/user-questions.html#create-toas-from-a-list-of-times

**Comment by MRegeard** [comment]
@dlakaplan Yes this is exactly what I am currently doing in my codes ! 
I was just questioning about why not using directly `Time`object.

**Comment by dlakaplan** [comment]
But does that document help explain why?

**Comment by MRegeard** [comment]
Yes it does. 
By the way, allows me to tell you that there is a typo at the end of the first paragraph. 
"ojbect" instead of "object" I guess.

**Comment by scottransom** [comment]
We should definitely have a convenience function that allows what @MRegeard wants for single-observatory sets of data.  It seems really silly (and is almost certainly quite costly) to convert to a list comprehension of TOA objects first. We would happily accept a pull request for that @MRegeard if you wanted to do that!

**Comment by dlakaplan** [comment]
> Yes it does.
> By the way, allows me to tell you that there is a typo at the end of the first paragraph.
> "ojbect" instead of "object" I guess.

Thanks!    fixed.
