### ISSUE TITLE
Remove references to `astropy._erfa`?

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1506]
`erfa` is imported in PINT like
```
try:
    from erfa import DAYSEC as SECS_PER_DAY
except ImportError:
    from astropy._erfa import DAYSEC as SECS_PER_DAY
```

Is this really required? pyerfa is a requirement for PINT, and `astropy._erfa` has been removed from astropy since version 4.2. Is there a reason why we can't change this to simply `from erfa import DAYSEC as SECS_PER_DAY`?

**Comment by paulray** [comment]
requirements.txt says `astropy>=4.0,!=4.0.1,!=4.0.1.post1` so wouldn't we have to bump that to `>=4.2` at the same time?

**Comment by abhisrkckl** [comment]
I don't think so. Since pyerfa is a separate requirement, the import statement in the `try` block will always work and the code will never reach the `except` block. So `erfa` will always be imported from pyerfa and not from astropy.

**Comment by paulray** [comment]
Ah, I see. Well we can just delete it and see if `oldestdeps` still passes!
