### ISSUE TITLE
Doc build without examples?

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1507]
Is there a way to change the documentation makefile to just get the autofocus to build (locally) without the examples?  Since the examples have to run they take a lot longer, and when debugging this is annoying.  I looked but couldn't see any clear way of doing this.

**Comment by aarchiba** [comment]
It looks like Sphinx has room for a command-line argument to control whether parts of the document are included or not:

https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#tags

It may not even require touching `conf.py`; it would presumably just be a matter of providing an alternative "not built" message for the tutorial section.

**Comment by dlakaplan** [comment]
Thanks for the suggestion - I think I got that working in #1519
