### ISSUE TITLE
PLDMnoise tests failing with oldestdeps

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1526]
It wasn't just a matter of adjusting the test tolerance, like we tried before.

It seems the fitter is just not moving and raising an error.  This should be caught and dealt with.

**Comment by dlakaplan** [comment]
@blarsen10 : I think I can fix this, but let me know if you want to do it instead.

**Comment by blarsen10** [comment]
Seems like a strange error! Thanks for submitting a fix already. If there's still issues with this I will definitely take a look.
