### ISSUE TITLE
Event Optimize does not return optimized errors

### ISSUE THREAD

**Issue by devbhakt** [nanograv/PINT#1529]
Currently `event optimize` writes out the post fit par file with the updated model values. But it does not update the uncertainties of the parameters based off of the samples. I am working on implementing a fix that updates the uncertainties using the standard deviation of the samples, but that does not work for non gaussian samples. What would be the best way to calculate the uncertainties for samples that we expect to look like gaussians and non gaussians?

**Comment by dlakaplan** [comment]
Can you use the inter-quartile range (converted to an equivalent sigma) (https://en.wikipedia.org/wiki/Interquartile_range) or directly estimate the central 68% confidence region?

**Comment by devbhakt** [comment]
@dlakaplan I will try those! Thank you!
