### ISSUE TITLE
Loading AO data crashes on the first try 

### ISSUE THREAD

**Issue by almcewen0** [nanograv/PINT#1536]
I have a timing notebook that utilizes TimingConfiguration files (.yaml) similar to those used by NANOGrav, and a few of my pulsars have data from Arecibo. By default, the notebook loads the timing models and TOAs separately (via get_model() and get_TOAs()), as the TOAs are zapped according to information contained in their respective .yaml files. For the AO pulsars, this sometimes causes a ValueError crash: 

ValueError: Clock file time_ao.dat appears to be out of order

It seems that the error only comes up the first time that I try to load the AO data. I can re-run the same cell and it works properly.

To recreate the error, I am including a few TOAs. With these TOAs, I get the crash if I run the following:

from pint.toa import get_TOAs
get_TOAs("ao.txt")

Running the code a second time should work. I also tried using get_model_and_TOAs(), same issue (works the second time).

[ao.txt](https://github.com/nanograv/PINT/files/10769229/ao.txt)

I am running this on a Mac (Ventura 13.2.1), and my pint.__version__, pint.__file__ are '0.9.3', '/Users/aemcewen/opt/anaconda3/envs/pintk/lib/python3.9/site-packages/pint/__init__.py'. I'm using a conda environment and I installed via `conda install -c conda-forge pint-pulsar`.

**Comment by dlakaplan** [comment]
This isn't a PINT problem. This is a problem with your local clock files - you have some file that it is reading instead.  Is `$TEMPO` set?  Try unsetting that

**Comment by paulray** [comment]
Yeah, that sounds right, but I thought PINT now ignored $TEMPO and $TEMPO2 and downloaded its own clock files. Is that not the case?

**Comment by dlakaplan** [comment]
I think it does but there are still ways that it can be confused.  I remember this popped up some time in the last few weeks and that @JPGlaser fixed it somewhere else.

**Comment by almcewen0** [comment]
I checked my os.environ, and $TEMPO/$TEMPO2 are not set.

**Comment by dlakaplan** [comment]
OK, it looks like there were old versions of clock files in `data/runtime` that were not deleted by previous conda installations.

**Comment by paulray** [comment]
I don't have any clock files in my data/runtime. I thought they all are in the astropy cache dir.
I guess if they are there, it overrides astropy?

**Comment by dlakaplan** [comment]
Yes, they shouldn't be there.  I think the upgrade to PINT didn't go through or didn't erase old files (`conda install` vs. `conda update`).

**Comment by almcewen0** [comment]
thanks for the pointers!
