### ISSUE TITLE
Repeated code in fermi_toas.py

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1541]
The functions `load_Fermi_TOAs()` and `get_Fermi_TOAs()` are almost identical, except that `load` returns a list of individual `TOA` objects, while `get` returns a `TOAs` object that is constructed from an array. At minimum, the repeated code should be merged, and perhaps only one of these needs to exist?

**Comment by dlakaplan** [comment]
I think I added `get_Fermi_TOAs()` but wasn't comfortable removing or modifying the existing code in case there was some specific use-case or other aspect that I missed, or in case people had explicit code that depended on it.  It may be easy to just make `load_Fermi_TOAs()` call the other function and then just repackage the output.  But I would not want to delete that function without further consultation.
