### ISSUE TITLE
`SolarSystemShapiro` gets included in the timing model even when `Astrometry` is not present.

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1551]
Consider the following code:

```
from pint.models import get_model

par = "F0  100 1"
m = get_model(m)

print(list(m.components.keys()))
```

We get the following output:
`["SolarSystemShapiro", "Spindown"]`

Here, `m` is supposed to represent a pure rotator with no other delays. However, `PINT` adds a `SolarSystemShapiro` component even if the astrometric information is not present. Doing anything useful with `m` will fail because `SolarSystemShapiro` requires astrometric information to function.

**Comment by paulray** [comment]
I guess this might be expected to work if all the TOAs are from `BarycenterObs` but otherwise an exception is the correct result.
