### ISSUE TITLE
Possible error in ELL1 higher order terms

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1566]
Computation from Will Fiore:
[ELL1_math.pdf](https://github.com/nanograv/PINT/files/11346458/ELL1_math.pdf)

**Comment by dlakaplan** [comment]
@wcfiore

**Comment by wcfiore** [comment]
I exchanged some emails with Norbert Wex, who showed numerically that the Zhu et al. terms are correct. I then found the mistake in my own math- a e^3 which should be an e^2 in my Equation 6 is what led to this confusion.
