### ISSUE TITLE
AttributeError: Attribute PhaseComponent_list not found in TimingModel or any Component

### ISSUE THREAD

**Issue by matteobachetti** [nanograv/PINT#1580]
I have this simple par file for the Crab:
```
PSRJ            J0534+2200
RAJ             05:34:31.973
DECJ            +22:00:52.06
PEPOCH           60020.0
F0               29.5745411845952
F1               -3.67074e-10
F2               1.38e-20
TZRMJD           60020.000000132
TZRSITE          0
EPHEM           DE200
```

When I load it and then calculate `m.phase(toalist, abs_phase=True)` I get the error in the title.
What is the file missing?

**Comment by dlakaplan** [comment]
Hi, @matteobachetti .  I can run that fine with simulated TOAs:
```
import io
from pint.models import get_model
import pint.simulation
import pint.logging

pint.logging.setup("WARNING")

par = """PSRJ            J0534+2200
RAJ             05:34:31.973
DECJ            +22:00:52.06
PEPOCH           60020.0
F0               29.5745411845952
F1               -3.67074e-10
F2               1.38e-20
TZRMJD           60020.000000132
TZRSITE          0
EPHEM           DE200
"""

m = get_model(io.StringIO(par))
t = pint.simulation.make_fake_toas_uniform(59000, 60000, 100, model=m)
ph = m.phase(t, abs_phase=True)
```
I tried this using the latest git version of pint, as well as (I think) the latest version on pypi.

**Comment by matteobachetti** [comment]
@dlakaplan thanks for the lightning-quick answer! Turns out... I was looking at the wrong wrong line in the log! (Probably need to sleep more :D ). This file was fine, there was another one that had an incomplete timing model.
Thanks again and sorry for the confusion.
