### ISSUE TITLE
sampler.chain is deprecated

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1594]
Several places in event_optimize and related places, we use `sampler.chain` to get the chain. This is deprecated:
```
DeprecationWarning: 'chain' is deprecated. Use 'get_chain()' instead.
```

I *think* those could all simply be replaced with `sampler.get_chain()` but I haven't checked or tested this.
@devbhakt can you take a look?

**Comment by devbhakt** [comment]
Hi Paul, the pull request I just submitted fixes the deprecation and uses get_chain() instead.
