### ISSUE TITLE
DDH model is not available.

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1597]
Tempo2 implementation:
https://bitbucket.org/psrsoft/tempo2/src/master/DDHmodel.C

**Comment by dlakaplan** [comment]
So this is a combination of ELL1H and DD?  What sort of sources is it used for?

**Comment by abhisrkckl** [comment]
I think eccentric binaries with low inclination (almost face-on).

**Comment by dlakaplan** [comment]
Is that also similar to DDFWHE?
> Variation of DD which implements the Freire&Wex(2010) orthometric 
>        Shapiro delay parametrization in the high eccentricity case with
>        h3 and varsigma instead of m2 and sini. Implemented by
>        J. Weisberg, Y. Huang, & A. Chael.
>        References: Freire, P. C. C.& Wex, N., MNRAS 409:199 (2010)
>                    Weisberg & Huang, APJ 2016
> 

https://tempo.sourceforge.net/ref_man_sections/binary.txt

**Comment by dlakaplan** [comment]
If you have an example par file I can try to code this up.

**Comment by abhisrkckl** [comment]
> Is that also similar to DDFWHE?

I think it is the same thing.
