### ISSUE TITLE
Difference between model.phase() expected and estimated values

### ISSUE THREAD

**Issue by aplangrangian** [nanograv/PINT#1599]
Hi,

I'm trying to use model.phase to determine the phase of a pulsar at a specific time. I'm getting strange values, so I decided to test with the TZRMJD value expecting to get phase = 0. However that is not the case.

Ephemeris file:
MJDParameter(   TZRMJD              56623.1552660391321759 (d) frozen=True),

My code is simply:
times = pint.toa.get_TOAs_list([pint.toa.TOA((56623, .1552660391321759))],ephem=model.EPHEM.value)
ph=  model.phase(times, abs_phase=True)

This results in:  Phase(int=<Quantity [-818.]>, frac=<Quantity [-0.29813038]>)

I realize this is using the fit, but I'm surprised to such a large difference. Am I missing something? Attached is my 

[Vela_ephem.par.zip](https://github.com/nanograv/PINT/files/11854389/Vela_ephem.par.zip)

**Comment by dlakaplan** [comment]
Can you share the actual par file (and not the PINT printout)?

**Comment by dlakaplan** [comment]
More generally, you can look at the `test_absphase.py` routines in the PINT test suite which does this check.  You need to make sure you specify the site and frequency correctly for the TOA.  If you have a model defined you should be able to do:
```
t = pint.toa.get_TOAs_list(
    [
        pint.toa.TOA(
            model.TZRMJD.quantity, obs=model.TZRSITE.value, freq=model.TZRFRQ.quantity
        )
    ],
    ephem=model.EPHEM.value,
)
ph = model.phase(t, abs_phase=True)
```
At least for me using a different par file this works fine.

**Comment by aplangrangian** [comment]
Hi David,

I'm looking into this! Sorry I am in the process of moving - but this may very well solve my issue. I'll update asap.

Also is the .par file attached in the opening comment not the preferred format?

**Comment by dlakaplan** [comment]
Thanks for the update.  No rush if you want to keep it open.

A par file should just be ASCII, like:
```
PSR              1748-2021E
RAJ       17:48:52.75  1
DECJ      -20:21:29.0  1
F0       61.485476554  1
F1         -1.181D-15  1
PEPOCH        53750.000000
POSEPOCH      53750.000000
DM              223.9  1
SOLARN0               0.00
EPHEM               DE421
CLK              UTC(NIST)
UNITS               TDB
TIMEEPH             FB90
T2CMETHOD           TEMPO
CORRECT_TROPOSPHERE N
PLANET_SHAPIRO      N
DILATEFREQ          N
TZRMJD  53801.38605118223
TZRFRQ            1949.609
TZRSITE                  1
```
What you sent was the output in a python interpreter of the model object.  I.e., you did something like:
`model=get_model(<parfile>)` 
and we want that file, rather than what you see in the python interpreter for the `model`.  Does that make sense?

**Comment by aplangrangian** [comment]
Oh you are right! Not sure how that happened.

[J0824-4510.par.zip](https://github.com/nanograv/PINT/files/11919044/J0824-4510.par.zip)

**Comment by dlakaplan** [comment]
Thanks.  With that file I think this is all OK: you just need to make sure you set the frequency and location of the TOA corresponding to the TZRMJD.
```
import numpy as np
from astropy import units as u, constants as c
from pint.models import get_model
import pint.toa
import pint.logging

pint.logging.setup("WARNING")
model = pint.models.get_model("J0824-4510.par")

t = pint.toa.get_TOAs_list(
    [
        pint.toa.TOA(
            model.TZRMJD.quantity, obs=model.TZRSITE.value, freq=model.TZRFRQ.quantity
        )
    ],
    ephem=model.EPHEM.value,
)
ph = model.phase(t, abs_phase=True)
assert ph.int == 0
assert ph.frac == 0
```
succeeds.  Does this make sense?

**Comment by aplangrangian** [comment]
This works the way I had hoped! I see that it was just the frequency and location! Thanks!
