### ISSUE TITLE
Getting AttributeError on fitting after deleting the first JUMP from model

### ISSUE THREAD

**Issue by tgautam16** [nanograv/PINT#1603]
Getting an error when creating a new fitter object after deleting specifically the first JUMP (JUMP1) from model using: m.delete_jump_and_flags(t.table[:], '1').

f = fitter.WLSFitter(toas=t, model=m) gives

`AttributeError                            Traceback (most recent call last)
Input In [103], in <cell line: 34>()
     32 m.validate_toas(t)
     33 print(m.get_components_by_category())
---> 34 f = fitter.WLSFitter(toas=t, model=m)
     35 f.fit_toas(maxiter = 3)

File /opt/conda/lib/python3.10/site-packages/pint/fitter.py:2018, in WLSFitter.__init__(self, toas, model, track_mode, residuals)
   2017 def __init__(self, toas, model, track_mode=None, residuals=None):
-> 2018     super().__init__(
   2019         toas=toas, model=model, residuals=residuals, track_mode=track_mode
   2020     )
   2021     self.method = "weighted_least_square"

File /opt/conda/lib/python3.10/site-packages/pint/fitter.py:222, in Fitter.__init__(self, toas, model, track_mode, residuals)
    220 self.track_mode = track_mode
    221 if residuals is None:
--> 222     self.resids_init = self.make_resids(self.model_init)
    223 else:
    224     # residuals were provided, we're just going to use them
    225     self.resids_init = residuals

File /opt/conda/lib/python3.10/site-packages/pint/fitter.py:757, in Fitter.make_resids(self, model)
    756 def make_resids(self, model):
--> 757     return Residuals(toas=self.toas, model=model, track_mode=self.track_mode)

File /opt/conda/lib/python3.10/site-packages/pint/residuals.py:133, in Residuals.__init__(self, toas, model, residual_type, unit, subtract_mean, use_weighted_mean, track_mode)
    131     self.track_mode = track_mode
    132 if toas is not None and model is not None:
--> 133     self.phase_resids = self.calc_phase_resids()
    134     self.time_resids = self.calc_time_resids()
    135 else:

File /opt/conda/lib/python3.10/site-packages/pint/residuals.py:335, in Residuals.calc_phase_resids(self)
    332 # If not tracking then do the usual nearest pulse number calculation
    333 elif self.track_mode == "nearest":
    334     # Compute model phase
--> 335     modelphase = self.model.phase(self.toas) + delta_pulse_numbers
    336     # Here it subtracts the first phase, so making the first TOA be the
    337     # reference. Not sure this is a good idea.
    338     if self.subtract_mean:

File /opt/conda/lib/python3.10/site-packages/pint/models/timing_model.py:1252, in TimingModel.phase(self, toas, abs_phase)
   1250 # Then compute the relevant pulse phases
   1251 for pf in self.phase_funcs:
-> 1252     phase += Phase(pf(toas, delay))
   1254 # abs_phase defaults to True if AbsPhase is in the model, otherwise to
   1255 # False.  Of course, if you manually set it, it will use that setting.
   1256 if abs_phase is None:

File /opt/conda/lib/python3.10/site-packages/pint/models/jump.py:120, in PhaseJump.jump_phase(self, toas, delay)
    115 """This method returns the jump phase for each toas section collected by
    116 jump parameters. The phase value is determined by jump parameter times
    117 F0.
    118 """
    119 tbl = toas.table
--> 120 jphase = numpy.zeros(len(tbl)) * (self.JUMP1.units * self._parent.F0.units)
    121 for jump in self.jumps:
    122     jump_par = getattr(self, jump)

AttributeError: 'PhaseJump' object has no attribute 'JUMP1'`

It works fine when deleting other JUMP numbers from the model.

**Comment by dlakaplan** [comment]
I think #1604 fixes this.  But note that the functions you were using are really for `pintk`.  If you are not using `pintk` there are other ways to add/delete jumps.  Something like:

```
p = m.components["PhaseJump"]

par = p.maskParameter(
    name="JUMP", key="freq", value=0.2, key_value=[1440, 1700], units=u.s
)  # TOAs indexed 48, 49, 54 in NGC6440E are within this frequency range
cp.add_param(par, setup=True)
```
to add (only in the model, not in the flag table) and then:

```
m.remove_param("JUMP1")
```
and
```
m.remove_component("PhaseJump")
```
if it's the last one.

**Comment by dlakaplan** [comment]
Also see https://nanograv-pint.readthedocs.io/en/latest/user-questions.html#add-a-jump-programmatically
