### ISSUE TITLE
`get_model_and_toas()` uses the default ephemeris (DE421) to create the TOAs object instead of the timing model ephemeris

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1608]
This looks like a problematic default behavior to me, especially since DE421 is quite outdated.

There is indeed an explicit `ephem` option that lets us override this option, but it is not even included in the docstring @_@

IMO, get_model_and_toas should use the model ephemeris to calculate the ephemeris-dependent attributes of the TOAs object unless told otherwise.

**Comment by dlakaplan** [comment]
Yes, this is clearly wrong.  Will you fix or should I?

**Comment by scottransom** [comment]
In other words, your description of the issue is *not* what happens.  And this is not an issue or a problem.

**Comment by dlakaplan** [comment]
The docstring could still be updated to include the behavior when ephem is/is not specified

**Comment by abhisrkckl** [comment]
Okay this is embarrassing. 
![image](https://github.com/nanograv/PINT/assets/20718391/147993e9-9ced-4888-8361-cffb159eb569)

Definitely not an issue; closing this.

I'll update the docs.
