### ISSUE TITLE
Assigning to a Parameter can override its name

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1622]
For instance, if I have a model `m` and do:
```
m.POSEPOCH = m.PEPOCH
```
then there is still a `POSEPOCH` attribute in the model, but its name is now `PEPOCH`.  This is largely unintended but comes up accidentally.  Better would be to do:
```
m.POSEPOCH.quantity = m.PEPOCH.quantity
```

I have a fix for this but I'm not sure it's a big enough issue to deal with.  It overrides `setattr` and explicitly copies only `quantity`, `uncertainty`, `frozen` when the names don't match.

**Comment by paulray** [comment]
That is definitely a confusing behavior for a user! Nice catch!
