### ISSUE TITLE
Problem using compare() with a Wave model

### ISSUE THREAD

**Issue by LuluAgazie** [nanograv/PINT#1626]
When trying to use the` compare()` function to look at two `TimingModel`s it fails if one of the models has a `Wave` component in it. The problem seems to be that the `WAVE1` , `WAVE2`, etc. amplitude values are reported as a list/tuple and the `compare()` function is unable to handle that. 

For example, if I have the following timing models:

```
basic_par_str = """
    PSR              B1937+21
    LAMBDA   301.9732445337270
    BETA      42.2967523367957
    PMLAMBDA           -0.0175
    PMBETA             -0.3971
    PX                  0.1515
    POSEPOCH        55321.0000
    F0    641.9282333345536244  1  0.0000000000000132
    F1     -4.330899370129D-14  1  2.149749089617D-22
    PEPOCH        55321.000000
    DM               71.016633
    UNITS                  TDB
    """

wave_par = """
    PSR              B1937+21
    LAMBDA   301.9732445337270
    BETA      42.2967523367957
    PMLAMBDA           -0.0175
    PMBETA             -0.3971
    PX                  0.1515
    POSEPOCH        55321.0000
    F0    641.9282333345536244  1  0.0000000000000132
    F1     -4.330899370129D-14  1  2.149749089617D-22
    PEPOCH        55321.000000
    DM               71.016633
    WAVEEPOCH 55321.000000
    WAVE_OM 0.1 
    WAVE1 0.2 0.1
    WAVE2 0.6 0.3
    UNITS                  TDB
"""
```

And then try to compare them with the following code:
```
base_model = get_model(StringIO(basic_par_str))
wave_model = get_model(StringIO(wave_par))
wave_model.compare(base_model)
```

I get the following error:
File ~/PINT/src/pint/models/timing_model.py:2077, in TimingModel.compare(self, othermodel, nodmx, convertcoordinates, threshold_sigma, unc_rat_threshold, verbosity, usecolor, format)
   2075 for pn in self.params_ordered:
   2076     par = getattr(self, pn)
-> 2077     if par.value is None:
   2078         continue
   2079     try:

File ~/PINT/src/pint/models/parameter.py:1452, in prefixParameter.value(self)
   1450 @property
   1451 def value(self):
-> 1452     return self.param_comp.value

File ~/PINT/src/pint/models/parameter.py:2120, in pairParameter.value(self)
   2114 @property
   2115 def value(self):
   2116     """Return the pure value of a parameter.
   2117 
   2118     This value will associate with parameter default value, which is .units attribute.
   2119     """
-> 2120     return None if self._quantity is None else self._get_value(self._quantity)

File ~/PINT/src/pint/models/parameter.py:780, in floatParameter._get_value(self, quan)
    778     return quan
    779 else:
--> 780     return quan.to(self.units).value

AttributeError: 'list' object has no attribute 'to'

**Comment by LuluAgazie** [comment]
The source of the issue seems to be that using getattr(model, WAVE1).value to get the value of the WAVE parameters doesn't work.

**Comment by paulray** [comment]
Yeah, WAVE parameters are kind of a hack in PINT, since they are the only ones with multiple values. It will require some special casing of the compare code.
