### ISSUE TITLE
Only fittable parameters should have "fit" check boxes in pintk

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1640]
Things that cannot be fit also appear as check boxes in pintk, and it throws an error if they are selected. This includes non-float parameters (e.g. ECL, NHARMS), funcParameters (e.g., ECC and OM for ELL1), and parameters without derivatives (e.g., PEPOCH).

If we exclude these parameters, pintk interface will look a lot less cluttered.

**Comment by dlakaplan** [comment]
I think there is no way to check if a parameter is fittable.  We had discussed making this explicit (#1246 and maybe others) and there was some attempt at a parameter redesign, but I don't know if it went anywhere.

Can you solve this in a general way or only by specifying them explicitly?

**Comment by abhisrkckl** [comment]
We can check for the presence of derivatives. Parameters without derivatives are not fittable in practice. 
An exception to this is of course noise parameters (#1639). But other than that the above criterion should work.
