### ISSUE TITLE
More realistic simulation of narrowband TOAs of multiple frequencies

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1659]
Currently, if I simulate narrowband TOAs with `pint.simulate.make_fake_TOAs_uniform` with multiple frequencies, it distributes the frequencies across different epochs like so:

```
mjd1    freq1
mjd2    freq2
mjd3    freq1
mjd4    freq2
...
```

IMO, a more realistic thing would be to have 

```
mjd1    freq1
mjd1    freq2
mjd2    freq1
mjd2    freq2
...
```
This looks more like a real narrowband dataset with subbanded TOAs.

I think we should change the behavior of `pint.simulate.make_fake_TOAs_uniform` to the latter.

**Comment by dlakaplan** [comment]
I agree the behavior with multiple frequencies is a little weird.  But if you make this change then you will say you want N toas but get Nfreq * N.  This may not be desired.  It may be easier to just create multiple single-frequency sets and concatenate them.

**Comment by abhisrkckl** [comment]
It will be easy to make it such that the number of epochs is Ntoas/Nfreqs so that Ntoas remains the same. This way the semantics of Ntoas remains the same.
