### ISSUE TITLE
Default fitter in `pintk` should be determined using `Fitter.auto()`

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1665]
~~Right now it is always `GLSFitter`.~~

**Comment by dlakaplan** [comment]
No, not true.  It uses the same logic (but implemented separately) to select the fitter.  
e.g.,
```
pintk tests/datafile/NGC6440E.par tests/datafile/NGC6440E.tim -v 
...
INFO     (pint.pintk.pulsar             ): Since wideband=False and correlated=False, selecting fitter=WLSFitter
```

**Comment by dlakaplan** [comment]
https://github.com/nanograv/PINT/blob/master/src/pint/pintk/pulsar.py#L107

**Comment by abhisrkckl** [comment]
I don't think it is the same logic. `Fitter.auto()` will choose `DownhillWLSFitter` instead of `WLSFitter` in this case. 

(The always-GLSFitter thing was a mistake.)

**Comment by dlakaplan** [comment]
`--downhill` will choose the downhill variant.  if needed that can be made the default.

**Comment by abhisrkckl** [comment]
> --downhill will choose the downhill variant. if needed that can be made the default.

That's a better option, IMO, since the downhill fitters are supposed to be more robust.
