### ISSUE TITLE
Some observatories have bogus positions

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1669]
* JB MkIII: https://www.google.com/maps/search/?api=1&query=85.30049263825742%2C-24.38060913829412, shows up north of Greenland
* Pico Veleta: https://www.google.com/maps/search/?api=1&query=37.066190794105204%2C3.3927032851438113, shows up in the Mediterranean Sea
* Hamburg: https://www.google.com/maps/search/?api=1&query=52.04195561248269%2C16.63128954754167.  Not sure what it is supposed to be but shows up in Poland.
* CCERA: Note that this location is in Smiths Falls, ON, where the telescope was previously deployed.  [It has since moved to Rideau Ferry, ON](https://www.ccera.ca/uncategorized/ccera-leaves-smiths-falls-moves-to-rideau-ferry-on/) but the coordinates have not been updated.  I emailed info@ccera.ca to see if they have more details.

**Comment by dlakaplan** [comment]
These all have comments in `observatories.json`

**Comment by dlakaplan** [comment]
These are indeed the same as in https://bitbucket.org/psrsoft/tempo2/src/master/T2runtime/observatory/observatories.dat

**Comment by SixByNine** [comment]
David emailed me about some of these as they appear to originate in tempo2. JBMKIII and PICO_VELETA both come directly from an old obsys.dat file at JBO from what I can see.

My guess is that JBMKIII is missing a digit in the X coordinate as othewise the location is quite reasonable. I don't have any better location other than trusting wikipedia right now, but maybe one can be found. However, I'm not sure that any pulsar data exist that use this telescope.

Hamburg seems to have been added by me in 2015... though no idea where I got it from. There are some very old crab pulsar data from this observatory (https://articles.adsabs.harvard.edu/pdf/1981A%26AS...44....1L) but the paper described the coordinates in a confusing way. In any case it is definitely the optical observatory in Bergedorf, Hamburg. Maybe we should just reverse this out from google maps...

PICO_VELETA also appears in the JBO obsys.dat but I have no idea what it is I'm afraid.

**Comment by dlakaplan** [comment]
> David emailed me about some of these as they appear to originate in tempo2. JBMKIII and PICO_VELETA both come directly from an old obsys.dat file at JBO from what I can see.
> 
> My guess is that JBMKIII is missing a digit in the X coordinate as othewise the location is quite reasonable. I don't have any better location other than trusting wikipedia right now, but maybe one can be found. However, I'm not sure that any pulsar data exist that use this telescope.
> 
I'm not sure the error is only in x.  If I take the coordinates from Wikipedia and compare, I see the following differences:
```
Delta x: 3449311.137951468 m
Delta y: 347634.20742059115 m
Delta z: 335.54325250629336 m
```
So only `z` is close.  `x` is by far the worst, but `y` is still off by >300 km.  But if no data exist we can just leave this as-is.

**Comment by SixByNine** [comment]
Regarding JBMkIII
> 
> So only `z` is close. `x` is by far the worst, but `y` is still off by >300 km. But if no data exist we can just leave this as-is.

I think you put in the wrong sign for longitude - the value should be -2.5975 degrees, which I find has a y-difference only 114m different from the value in tempo2. the 'x' coordinate matches in the first 3 digits, but then diverges, so I'm pretty sure someone typed it by hand and missed out a digit!

**Comment by SixByNine** [comment]
> I think Pico Veleta is: https://es.wikipedia.org/wiki/Observatorio_IRAM_Pico_Veleta but I don't know where the incorrect data come from.
Looks like Pico Veleta has a sign missing in the 'y' coordinate, which mirrors it over the prime meridian and puts it in the right place.

I think it should be
`5088964.00    -301689.80       3825017.0        PICO_VELETA         pv`

I will update tempo2

**Comment by dlakaplan** [comment]
OK, #1672 does the same fix here.

**Comment by abhisrkckl** [comment]
Can this issue be closed? Or do some observatories still have wrong coordinates?
