### ISSUE TITLE
`test_noisefit.py::test_white_noise_refit` often fails

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1686]
Maybe this needs different tolerances?

**Comment by dlakaplan** [comment]
@abhisrkckl : is this from one of your PRs?  I can usually rerun the tests and it's OK but it may be better to adjust.

**Comment by abhisrkckl** [comment]
Yes. It sometimes fails for me too. It may be a good idea to relax the tolerance on this.
