### ISSUE TITLE
DMJUMP should provide a delay for narrow-band TOAs

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1716]
DMJUMP encodes differences in the template profile and other systematic differences that can produce constant offsets between DMs measured by different systems. In wideband TOAs, this is modeled as a DM offset without any corresponding delay since the wideband TOA measurement procedure is supposed to extract all the dispersion information into the measured DM. 

However, this is not the case for narrowband TOAs. IMO, DMJUMP should provide both a DM offset and delay offset for narrow-band TOAs. This is relevant for the IPTA DR3 data combination.

**Comment by rossjjennings** [comment]
This is what we are looking for the IPTA DR3 data combination. Actually, @blarsen10 already tried to implement this in #1542. There is some relevant discussion there, but that PR was closed, in my opinion mistakenly, because we thought that FDJUMPs would eliminate the need for this.

**Comment by abhisrkckl** [comment]
I had a discussion some time ago with BC Joshi, and it now seems to me that this is the wrong thing to do. We should leave DMJump alone and implement a new component that provides a system-dependent DM delay for narrowband TOAs. Changing the behavior of DMJump may break existing wideband analyses.

So I am closing this and opening a new issue.
