### ISSUE TITLE
Broken backward compatibility for spacecraft alias to STL_GEO special location

### ISSUE THREAD

**Issue by juliadeneva** [nanograv/PINT#1723]
When using a tim file containing spacecraft-topocentric TOAs, the alias 'spacecraft' is no longer accepted instead of STL_GEO. This breaks backwards compatibility with tim files made when this alias was the default written to tim files edited and saved with pintk, including tim files published as supplementary electronic material to papers.

**Comment by paulray** [comment]
The removal of 'spacecraft' was a side effect of PR #865  by @kerrm

**Comment by dlakaplan** [comment]
Do you have a sample tim file (or a link to a relevant paper) for testing?

**Comment by juliadeneva** [comment]
You can try any of the supplementary *.tim.nicer files from this paper:

https://arxiv.org/abs/1902.07130

**Comment by kerrm** [comment]
Here is a direct link to one of the .tim files Julia pointed to:

https://arxiv.org/src/1902.07130v1/anc/supplementary-materials/B1937-nanograv-all-frozen-dmx.tim.nicer

Is it just a matter of adding "spacecraft" as an alias here?

line 281 of special_locations.py:
T2SpacecraftObs("stl_geo", aliases=["STL_GEO"], overwrite=True)

**Comment by juliadeneva** [comment]
That, and what pintk writes when a tim file is edited and saved should not be 'spacecraft' if other programs like Tempo2 don't recognize it. I'm not sure what the pintk behavior is now but those tim files were saved with it and at the time that was the default behavior.

**Comment by dlakaplan** [comment]
Just that change is not sufficient.  I also find errors with some of the flags.  Looking further.

**Comment by dlakaplan** [comment]
Yes, that allows it to be read.  I don't think there is a downside to putting `spacecraft` back in as an alias.  That's an easy fix.  Once it's read in it is converted to `stl_geo`, so I think further reading by tempo2 etc will be OK.  And in `pintk` you can also specify the output format if needed.

**Comment by paulray** [comment]
Where does `-name nicer` come from?  `photon_toa.py` does not write a flag like that, just `-t NICER`

**Comment by juliadeneva** [comment]
It looks like pintk (or perhaps python scripts I had using PINT) changed a bunch of things when I edited the tim files to remove outliers, not just the 'spacecraft' observatory ID. 
The files made by photon_toa.py have 'photon_toa' as the first field in each line, while the ones that were included with the paper have 'pint' as the first field.

**Comment by dlakaplan** [comment]
Closed by #1724 (at least for the main part - other changes to the tim file may still need attention)
