### ISSUE TITLE
Unknown ufunc pmsafe from astrometry.py

### ISSUE THREAD

**Issue by tcromartie** [nanograv/PINT#1733]
I have provided the code that's failing (attached w/ nominal par, tim). When building an `enterprise.pulsar` Pulsar **with 'pint' selected as the timing package** (`psr = Pulsar(par, tim, timing_package='pint')`) and **when PMRA/PMDEC are included in the model** (not using `'tempo2'` or when the astrometry parameters aren't included), it fails with the following: 
`TypeError: unknown ufunc pmsafe.  If you believe this ufunc should be supported, please raise an issue on https://github.com/astropy/astropy`
After the `AstrometryEquatorial.ssb_to_psb_xyz_ICRS` call to `pmsafe` in `astrometry.py`. 
I can import erfa with no problem. `erfa.pmsafe` doesn't fail otherwise, though. 
[example.tar.gz](https://github.com/nanograv/PINT/files/15013446/example.tar.gz)

**Comment by tcromartie** [comment]
I forgot to strip a lot of unnecessary imports etc. from the example. My apologies!

**Comment by dlakaplan** [comment]
Also, this sounds more like an enterprise issue/question.  The pint-only commands work fine, right?

**Comment by tcromartie** [comment]
I'm confused though because yes, I'm not having problems with pint commands. But this only happens when enterprise is set to use pint instead of tempo2. Enterprise is calling on pint's astrometry.py for some specific astrometric transformation that then in turn fails. I guess that's why it's not obvious to me that it's enterprise. (I'm not calling erfa directly at all, I only imported/printed it in the example to confirm it wasn't broken being invoked directly.)

pint 0.9.8+175.gc50630d7
enterprise 3.3.4.dev13+gc49646c
np 1.23.5
astropy 6.0.0

I can paste the traceback if needed.

**Comment by dlakaplan** [comment]
Can you either find what the enterprise command is, or ask @Hazboun6 ?

**Comment by tcromartie** [comment]
You mean my actual enterprise call? Just what's in the example code, `psr = Pulsar(par, tim, timing_package='pint')`. Enterprise builds a pulsar through pulsar.py and when pint is specified, it uses the class PintPulsar:

`PintPulsar.__init__(self, toas, model, sort, drop_pintpsr, planets):`
`self._pos_t = model.components[which_astrometry].ssb_to_psb_xyz_ICRS(model.get_barycentric_toas(toas)).value'`
And the failure is in pint's astrometry.py: `AstrometryEquatorial.ssb_to_psb_xyz_ICRS(self, epoch)`, when `starpmout = pmsafe(...)` is defined (:446)

**Comment by dlakaplan** [comment]
So this is an enterprise error.  The usage for `ssb_to_psb_xyz_ICRS` says that the argument should be:
```
epoch : float or astropy.time.Time, optional
```
but enterprise is trying to pass a plain Quantity.  Something like:
```
model.components[which_astrometry].ssb_to_psb_xyz_ICRS(Time(model.get_barycentric_toas(toas),format='mjd')).value
```
will work instead, I think.

**Comment by dlakaplan** [comment]
Or (and maybe this was the intent):
```
model.components[which_astrometry].ssb_to_psb_xyz_ICRS(model.get_barycentric_toas(toas).value)
```

**Comment by dlakaplan** [comment]
Note that it's possible to support quantity input, it just hasn't come up.

**Comment by tcromartie** [comment]
Thanks very much @dlakaplan, I appreciate your help!

**Comment by tcromartie** [comment]
(Confirmed that the change `model.components[which_astrometry].ssb_to_psb_xyz_ICRS(model.get_barycentric_toas(toas).value)` is successful. Thank you!)

**Comment by Hazboun6** [comment]
I agree that you should submit this as an Enterprise PR @tcromartie ! I am surprised this hasn't popped up before though, since this is in the `__init__` method of the `PintPulsar` class.

**Comment by dlakaplan** [comment]
I think that using the quantity versions isn't actually supported, but works accidentally (the docstrings aren't all fully consistent, but don't claim to support units).  However, I agree that they should.
