### ISSUE TITLE
tests/test_Galactic.py::TestGalactic::test_proper_motion_identity failing

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1759]
This test evaluates a position at the POSEPOCH and compares against the baseline position.  The threshold is set to 1e-11 arcsec.  Normally this passes but I've been having intermittent failures.  I don't know why it's intermittent (it should be deterministic) and only on some architectures.  I also don't know if this is due to #1748. 

Any ideas @abhisrkckl ?

**Comment by dlakaplan** [comment]
Errors look like:
```
=================================== FAILURES ===================================
___________________ TestGalactic.test_proper_motion_identity ___________________

self = <test_Galactic.TestGalactic object at 0x7f0ba784c380>

    def test_proper_motion_identity(self):
        # sanity check that evaluation at POSEPOCH returns something very close to 0
        J0613_icrs = self.modelJ0613.coords_as_ICRS()
        J0613_icrs_alt = self.modelJ0613.coords_as_ICRS(
            epoch=self.modelJ0613.POSEPOCH.quantity.mjd
        )
        sep = J0613_icrs_alt.separation(J0613_icrs)
>       assert sep < 1e-11 * u.arcsec
E       assert <Angle 1.33203881e-14 deg> < (1e-11 * Unit("arcsec"))
E        +  where Unit("arcsec") = u.arcsec
```

**Comment by abhisrkckl** [comment]
astropy v6.1.0 was tagged two days ago. So it may be an astropy-related issue.

**Comment by abhisrkckl** [comment]
The test goes through when I restrict astropy<6.1.0.

**Comment by abhisrkckl** [comment]
The issue seems to go away if I remove the `add_dummy_distance` and `remove_dummy_distance` calls in the `get_psr_coords` function.

**Comment by dlakaplan** [comment]
Thanks for investigating.  Maybe the reason it was showing up only in some tests and not others was just a coincidence about when they started wrt when the astropy bump happened.

I think the simplest fix for now would be to increase the tolerance in the failing test.  5e-11 arcsec is still very small and it would pass.  Or we could restrict the astropy version until we understand the origin of the difference.  If those dummy functions are the issue there might be some change to the API.

**Comment by dlakaplan** [comment]
Oddly, this test compares two copies of what should be the same coordinate against each other.  But I'm finding that the distance returned is not symmetric:
`A.separation(B) = 1.3320388147503583e-14`
but
`B.separation(A) = 3.975693351829395e-16`
So one looks good, while the other isn't. 

I think we could fix this test by reversing the order of the calculation, but I'll try to understand the origin.
