### ISSUE TITLE
Logic backwards?

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1766]
https://github.com/nanograv/PINT/blob/76994bbe97cc21815e24b344a326a7d9032ed528/src/pint/toa.py#L1629-L1632

I believe this logic is backwards. It removes the clock corrections from the TOAs if clkcorr is False, when the docstring says "Whether or not to undo any clock corrections" which to me means that True is what should cause it to undo clock corrections.

The result is that the default *is* to remove clock corrections when converting a `TOAs` object back to a list of `TOA`s.

**Comment by paulray** [comment]
When this is fixed, `test_toas_tolist()` in test_toa_create.py should test both cases and make sure the clock corrections are correctly being removed when requested.

**Comment by paulray** [comment]
Note that it does not appear that this argument was ever used so all calls to `to_TOA_list()` did undo the clock corrections, since that is the default.  This might not have been what was intended in the `load_Fermi_TOAs` code but it didn't matter since the clock correction were 0.0 (no observatory clock corrections and use_bipm and use_gps were False)

**Comment by abhisrkckl** [comment]
Does #1763 fix this? If yes, we can close this.
