### ISSUE TITLE
astropy 6.1.0 bumps minimum python to 3.10

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1774]
So, astropy 6.1 now has a minimum python version of 3.10:
https://docs.astropy.org/en/stable/whatsnew/6.1.html

When it starts getting used by our CI, we will get fails.
At what point do we bump our python requirement (currently >=3.8)?

**Comment by dlakaplan** [comment]
I think this is already used.  e.g., in https://github.com/nanograv/PINT/actions/runs/9250049229/job/25442899897.  The `latest` tests use python 3.12 and astropy 6.1.0.  But `oldestdeps` still uses 3.8 and astropy 4.0.  Is there actually something that will break?

**Comment by paulray** [comment]
Hmm. I guess if we don't have a test that tries to use astropy 6.1 with python 3.8, we won't see a fail.  So maybe we don't need to do anything for now.  If a user wants to upgrade to astropy 6.1, then they will need to bump their python but if they are OK with prior astropy versions, they can stay at Python 3.8.  

I do think we should continue to support Python 3.8 as long as we can. Plenty of older machines still use it.
