### ISSUE TITLE
Tests are failing (probably due to new scipy version)

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1792]
The new scipy version was released 2 days ago.   😞

**Comment by abhisrkckl** [comment]
=========================== short test summary info ============================
ERROR tests/test_determinism.py
ERROR tests/test_mcmcfitter.py
ERROR tests/test_templates.py

**Comment by abhisrkckl** [comment]
The error is this:

../../.tox/py312-test-cov/lib/python3.12/site-packages/pint/templates/lcprimitives.py:19: in <module>
    from scipy.integrate import quad, simps
E   ImportError: cannot import name 'simps' from 'scipy.integrate'

**Comment by abhisrkckl** [comment]
I think the issue is because the simps method was renamed/replaced by the simpson method.

**Comment by dlakaplan** [comment]
Yes, just `simps` -> `simpson` is needed.

**Comment by dlakaplan** [comment]
Not sure how best to manage this.  If we should just add to the np2.0 branch, or make a new PR.

**Comment by abhisrkckl** [comment]
I just merged that branch. I think we can create a new branch?

**Comment by dlakaplan** [comment]
ok, will do

**Comment by abhisrkckl** [comment]
There will probably be another round of breakage when the astropy update comes.
