### ISSUE TITLE
Better observatory data structures

### ISSUE THREAD

**Issue by demorest** [nanograv/PINT#186]
For a while I have been thinking about adding a better framework for dealing with observatories (site locations, clock corrections, etc).  This issue is mainly to let you know that I've started doing some work on this, so we don't end up duplicating effort.  I think I have a pretty clear plan in mind already, but please send ideas if you have them.  The basic goal is to be able to remove all the special-case if statements (ie barycenter vs geocenter vs spacecraft vs standard tempo site) from toa.py and into a set of new data structures that can be extended to deal with any new special cases we come up with in the future.  This can also provide a way to add in the small GPS clock correction that we currently don't do (assuming this won't be done in astropy).

**Comment by luojing1211** [comment]
Thanks Paul. This effort wilt change the empty observator class case.

**Comment by demorest** [comment]
I am mostly done with this, but it still needs a bit more work to remove the old observatories code and clean up (fix/add tests, etc).  When this is done I'll put a pull request in.  If anyone wants to take a look ahead of time, you can see my "observatory" branch, most of the new code is under pint/observatory.
