### ISSUE TITLE
Timing Models doc page not rendering some of the component docstrings fully

### ISSUE THREAD

**Issue by mtlam** [nanograv/PINT#1870]
For this [page](https://nanograv-pint.readthedocs.io/en/latest/timingmodels.html). See for example:

> `PLChromNoise` - Model of a radio frequency-dependent noise with a power-law spectrum and
> `PLDMNoise` - Model of DM variations as radio frequency-dependent noise with a

It looks like perhaps it is printing the first line of the docstring only, see for example for `BinaryBTPiecewise` as well.

**Comment by dlakaplan** [comment]
Look at:
https://nanograv-pint--1871.org.readthedocs.build/en/1871/timingmodels.html
https://nanograv-pint--1871.org.readthedocs.build/en/1871/_autosummary/pint.models.binary_bt.BinaryBTPiecewise.html#pint.models.binary_bt.BinaryBTPiecewise
https://nanograv-pint--1871.org.readthedocs.build/en/1871/_autosummary/pint.models.noise_model.PLChromNoise.html#pint.models.noise_model.PLChromNoise
https://nanograv-pint--1871.org.readthedocs.build/en/1871/_autosummary/pint.models.noise_model.PLDMNoise.html#pint.models.noise_model.PLDMNoise
(I cleaned up some other parts too).

**Comment by mtlam** [comment]
These look great to me, thanks for tackling this.
