### ISSUE TITLE
TT(BIPM) 

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#193]
Currently we are using astropy time object to handle the TT~UTC converting, which takes TT(TAI) as default. But in our dataset, a more accurate realization TT(BIPM) is used. I did not see any option to change astropy default to TT(BIPM). Does anyone know if it exists in astropy? If not maybe we should get contact with astropy.

**Comment by paulray** [comment]
This is done in PR #223, so this probably can be closed.

I have some issues with the TT(BIPM) correction being done in TopoObs, which feels like the wrong place, as I described in this [wiki page](https://github.com/nanograv/PINT/wiki/Clock-Corrections-and-Timescales-in-PINT).  But, that can probably be opened as an issue later if we decide to move where the correction is done.
