### ISSUE TITLE
Leap Second Updates

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#202]
The following note showed up on the astropy mailing list. We should think about how this affects PINT.  Currently, if astropy 1.3 is not released soon, and PINT users do not update to it before the end of 2016, PINT will start giving wrong answers because of not knowing about the new leap second. This relates to the general issue of how PINT should keep clock correction files up to date.

```
Message: 1
Date: Mon, 19 Dec 2016 12:20:24 +0800
From: Andrew Williams <andrew@physics.uwa.edu.au>
To: Astronomical Python mailing list <astropy@scipy.org>
Subject: [AstroPy] upcoming leap second
Message-ID: <57042bc9-6e57-aafe-68df-81b8dac71ccb@physics.uwa.edu.au>
Content-Type: text/plain; charset=utf-8; format=flowed


There's a new leap second coming up in a couple of weeks, and the latest 
IERS data downloaded by astropy 1.2.1 
(http://maia.usno.navy.mil/ser7/finals2000A.all) doesn't seem to include 
it - either that, or leap second calculations don't use that downloaded 
data.

According to this thread:

https://github.com/astropy/astropy/issues/5532

Astropy 1.3 should include the new leap second - is it still due out today?

Also, we've got a few machines running Python 2.6.6, and astropy 1.0.3,
and upgrading to a Python 2.7 variant so we can use the latest astropy
will take a lot of work (and won't happen before the end of the year).
How and where can I find the relevant data table in 1.0.3 to update the
leap second data? Will I need to download astropy 1.0.3 source, edit
cextern/erfa/dat.c and compile and install manually, or can I tweak some 
other data file in the copy I have installed using 'pip'?

Andrew

```

**Comment by paulray** [comment]
astropy 1.3 has been released so all PINT users should update to it as soon as possible, and certainly before processing any TOAs taken after 2016 Dec 31.

**Comment by paulray** [comment]
This is addressed in PR #209. Once that is merged, PINT will require astropy >= 1.3 and thus will have the 2016 December 31 leap second included.

**Comment by paulray** [comment]
Also added a leap second check to the unit tests in PR #214

**Comment by shbhuk** [comment]
Hi,
Just wanted to check if PINT has a procedure to automatically update for a new leap second? Or is it that it needs users to update its Astropy? We ask since for Barycorrpy we had to write a new leap second management function.

**Comment by luojing1211** [comment]
I believe it will be updated by Astropy automatically but no need to update
astropy package.

**Comment by shbhuk** [comment]
Astropy does not automatically update it  https://github.com/liberfa/erfa/issues/43

This was the problem we faced. It would have caused errors of a few cm/s in our barycentric correction if ignored.

**Comment by scottransom** [comment]
That's not exactly correct.  When it is announced that there is a new leap second coming, SOFA generates a new release.  That release becomes ERFA, and it is incorporated into astropy.  So astropy does not *automatically* get new leap seconds, but neither does any other high-precision timing-related software that I know of....

**Comment by luojing1211** [comment]
I was looking at https://github.com/astropy/astropy/issues/350. I think I
got confused about the IERS Bulletins. So everything there is a leap second
update. We will have to update astropy is that correct, @Scott?

**Comment by scottransom** [comment]
Yes, there is talk among the astropy devs about automating this in the same way that they do IERS updates.  But that doesn't work right now since the core leap sec code is part of ERFA, and there it is hard coded.  One problem is that several people like the idea of being able to modify the leap sec table so that you can test or extrapolate things.  There really isn't a good solution for leap seconds that does what everyone wants.  Personally, I think we shouldn't worry about it too much -- if you need precision measurements, you damned well better keep your software updated and test things routinely.

**Comment by shbhuk** [comment]
Hi,
Right, As @scottransom said, there is no automatic way to do this. The reason we wanted to develop something for barycorrpy (cm/s barycentric correction for RVs), is to reduce the hassle for users of the routine, and potentially offer an alternative to the Astropy time management that works. At least till Astropy diverges from ERFA, or ERFA changes their convention 

https://github.com/shbhuk/barycorrpy/wiki/5.-Leap-Second-Management
