### ISSUE TITLE
Astropy 1.3 release

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#207]
Hi all, 
Astropy has 1.3 version released officially. Its solar system ephemeris module now returns the velocity of solar system body. We should be able to use it and remove the ephemeris download process. Since astropy will do it for us. 

-Jing

**Comment by paulray** [comment]
What exactly does this mean?  With astropy 1.3, we no longer need to call jplephem ourselves, everything is done via astropy?  That is certainly handy, but does it allow PINT users to use custom ephemeris files that may not be available in astropy?  How would that be handled?

**Comment by luojing1211** [comment]
We are not losing the flexibility of using different ephemeris, and astropy will handle the download work.  

Currently, we calculate positions using astropy, which has the flexibility to use different ephemeris. The only difference is the velocity. Astropy 1.2 did not provide an API for velocity, so we use jplephem to do the velocity calculation by ourselves. That requires us to download ephemeris separately. I means we have two copy of ephemeris in our compute, one is downloaded by astropy and on is downloaded by PINT. With the new update, position and velocity are integrated in astropy. So we do not have to deal with ephemeris download.
