### ISSUE TITLE
PINT needs a license statement

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#210]
I have put in a placeholder LICENSE.md file in the repo. We need to modify it, and the license keyword in setup.py to reflect whatever license we choose.

@vhaasteren suggested the [MIT License](https://en.wikipedia.org/wiki/MIT_License), while astropy (which we have modeled much after) uses the [BSD License](https://en.wikipedia.org/wiki/BSD_licenses).

Note that work by government employees (e.g. @paulray) [cannot be copyrighted](https://en.wikipedia.org/wiki/Copyright_status_of_work_by_the_U.S._government).  According to [this reference](http://dodcio.defense.gov/Open-Source-Software-FAQ/#Q:_Can_government_employees_contribute_code_to_open_source_software_projects.3F), this means:
> If a government employee enhances or modifies a (copyrighted) open source software program, 
> the resulting work is a “joint work” (see 17 USC § 101) which is partially copyrighted and partially public domain. 
> The resulting joint work as a whole is protected by the copyrights of the non-government authors 
> and may be released according to the terms of the original open-source license.

**Comment by cdeil** [comment]
There's a comment here discussing the core difference between MIT and BSD:
https://github.com/github/choosealicense.com/issues/413#issuecomment-243598510
It's very opinionated and is suggesting BSD for scientific Python codes.

As a practical matter, if in the future you think there will be copy & pasting of code from Astropy or other affiliated packages to `pint` or the other way, if you have the same license my understanding is that it's a bit simpler.
* If the license is different, you have to do something like https://github.com/astropy/astropy/tree/master/licenses
* If the license is the same, you just have to mention where the code came from, but not add extra license files to your repo.

But IANL and this statement about how to properly move code between packages might be wrong.

**Comment by paulray** [comment]
Adam Brazier points out that "in the PFC Data Management Plan, we say we'd have a preference for the 3-clause BSD license, where possible."

**Comment by paulray** [comment]
This is addressed by PR #315
