### ISSUE TITLE
parfile_from_line

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#211]
The routine `parfile_line_regular(self, line)` in parameter.py fails on a parfile line like:
```
F3 0 0
```
It never sets `ucty` but then tries to use it at line 338

**Comment by luojing1211** [comment]
There is a fix in the wls_fitter pull request. May be I should move it to a separate pull request.  It is kind of confusing for me. Does this mean value = 0.0 and fit is False or value = 0.0 and uncertainty = 0.0

**Comment by paulray** [comment]
It means the value = 0.0 and fit is False. To have an uncertainty, don't you need 3 values (value, fit_flag, uncertainty)?

**Comment by luojing1211** [comment]
So there is no chance to have:( NAME value uncertainty) without fit_flag?  If that is the case, the code can be little bit more clean.

**Comment by paulray** [comment]
I'm not sure if that is allowed in TEMPO or Tempo2.

**Comment by paulray** [comment]
The docstring in our line parsing code should *definitely* specify what formats are allowed.

**Comment by luojing1211** [comment]
I personally never see the usage like that. Why don't we set it like this way. If it happens, changing  this in .par file should be easy enough.

**Comment by luojing1211** [comment]
After this fix, the (Name value uncertainty) is not working. But it is easy fix.
