### ISSUE TITLE
TOA() timescale issue

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#212]
With the new code for handling observatories, the TOA() initializer now completely ignores the `scale` argument, in favor of `site.timescale`.  If this is the intent, we should remove the `scale` argument in toa.py,  line 277.

This means, for example, that geocentric TOAs must always be in the TT timescale since there is no way to override.  Maybe this is for the best. Is that what TEMPO and Tempo2 assume about geocentric TOAs?

**Comment by paulray** [comment]
Also, look at this:
```
In [25]: site = Observatory.get('coe')

In [35]: site.earth_location
Out[35]: <EarthLocation ( 6378137.,  0.,  0.) m>
```

Shouldn't the location for coe be 0,0,0?

**Comment by demorest** [comment]
About the geocenter location:  Yes, it should be (0,0,0)!  Apparently astropy's EarthLocation tries to automatically decide whether you've given it x,y,z or lat,long,height and it is choosing wrong in this case.  I hadn't noticed this before, thanks for finding it.  It's a 1-line fix, I will commit this directly (no PR) in a sec.

**Comment by paulray** [comment]
I found this issue because I grabbed .tim/.par file set from some old Fermi work I did and tried it with PINT. There was a big jump in the residuals in the PINT plot at the epoch of a leap second. I just tried changing the timescale assumed for geocentric TOAs to 'utc' and now PINT produces a residual plot that looks just like Tempo2.  So, I believe that Tempo2 assumes TOA times in .tim files are UTC, whether they are at the Geocenter or not.  Looking at the output of `tempo2 -list` confirms this. Here is a snippet where you can see the correction from SAT to TAI changing when the leap seconds change.
```
Number of observations = 30
--------------------------------------------------------------------------------
   #  | SAT                   | Clock corrections(s)     |
--------------------------------------------------------------------------------
|   1 | 54682.7 | 33            (->TAI) 32.184        (->TT(TAI))
|   2 | 54701 | 33            (->TAI) 32.184        (->TT(TAI))
|   3 | 54719.3 | 33            (->TAI) 32.184        (->TT(TAI))
|   4 | 54737.6 | 33            (->TAI) 32.184        (->TT(TAI))
|   5 | 54755.9 | 33            (->TAI) 32.184        (->TT(TAI))
|   6 | 54774.2 | 33            (->TAI) 32.184        (->TT(TAI))
|   7 | 54792.5 | 33            (->TAI) 32.184        (->TT(TAI))
|   8 | 54810.8 | 33            (->TAI) 32.184        (->TT(TAI))
|   9 | 54829.1 | 33            (->TAI) 32.184        (->TT(TAI))
|  10 | 54847.5 | 34            (->TAI) 32.184        (->TT(TAI))
|  11 | 54865.8 | 34            (->TAI) 32.184        (->TT(TAI))
|  12 | 54884.1 | 34            (->TAI) 32.184        (->TT(TAI))
|  13 | 54902.4 | 34            (->TAI) 32.184        (->TT(TAI))
|  14 | 54920.7 | 34            (->TAI) 32.184        (->TT(TAI))
|  15 | 54939 | 34            (->TAI) 32.184        (->TT(TAI))
|  16 | 54957.3 | 34            (->TAI) 32.184        (->TT(TAI))
|  17 | 54975.6 | 34            (->TAI) 32.184        (->TT(TAI))
|  18 | 54994 | 34            (->TAI) 32.184        (->TT(TAI))
```

**Comment by paulray** [comment]
I also just verified that our code that writes TOAs from Fermi data converts the TT times in the FT1 file to MJD(UTC) before generating the TOAs, so it is definitely writing TOA lines with MJD(UTC) times.
Conclusion, we should change the default timescale for Geocentric TOAs (at least when read from a .tim file) to UTC.  I agree that the TOA() constructor should allow this to be overridden if you are generating TOAs directly from data in the TT scale.
