### ISSUE TITLE
Make get_componets in model_builder work on Python 3

### ISSUE THREAD

**Issue by cdeil** [nanograv/PINT#218]
Currently `import pint.models` doesn't work with Python 3:
```
$ python3 -c 'import pint.models'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/pint-0.5.1+11.g5028af7.dirty-py3.5-macosx-10.12-x86_64.egg/pint/models/__init__.py", line 12, in <module>
    from .model_builder import get_model
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/pint-0.5.1+11.g5028af7.dirty-py3.5-macosx-10.12-x86_64.egg/pint/models/model_builder.py", line 37, in <module>
    ComponentsList = get_componets()
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/pint-0.5.1+11.g5028af7.dirty-py3.5-macosx-10.12-x86_64.egg/pint/models/model_builder.py", line 26, in get_componets
    exec('import %s as tmp' % mod)
  File "<string>", line 1, in <module>
ImportError: No module named 'astrometry'
```

As the traceback shows, the issue is that the `get_components` function in `pint/models/model_builder.py` doesn't work in Python 3.

I could try to change that code so that it simultaneously works in Python 2 and 3.
But @luojing1211 , since you've written that code (see https://github.com/nanograv/PINT/commit/bf6df0c1c2f041e747557d274a57eb24d407c954), maybe you could do it?

Usually calling `exec` is not a good way.
There are better Python coding patterns to have a model registry or dynamic class generation or ...
I haven't tried to understand what that code is doing yet, and there's no comment about that.

@luojing1211 or @paulray  - Thoughts?

**Comment by luojing1211** [comment]
Hi @cdeil,

This part is to search all the files in the 'pint' folder and find all the existing timing model classes. One way I know of is using meta class. Is it what's in your mind?

-Jing Luo

**Comment by cdeil** [comment]
@luojing1211 - So the purpose of this code is to have a registry?

Would you be OK to have to manually call "register" or add them to a global list of dict?

Or do you want auto-registry of sub-classes?
Then yes, I think using a metaclass is the common pattern.
But I'm not very familar with metaclasses or possible registry patterns, so I've put it as a question here: https://github.com/astropy/regions/issues/18#issuecomment-271410958
Maybe you could read that comment or "watch" that issue to see what other Astropy devs think.

**Comment by demorest** [comment]
I used the registry pattern with metaclass already in PINT for Observatory (pint/observatory/observatory.py).  I think it would probably be a good solution here as well.

**Comment by demorest** [comment]
PS, I think I got the idea from looking at how astropy TimeFormat is implemented, so there must be at least one astropy dev who likes it also :)

**Comment by luojing1211** [comment]
The idea is to register TimingModel classes automatically. I did some practises with mate class, inspired by @demorest and astropy Coordinate formats. If this is what we would like, I can implement it.

**Comment by cdeil** [comment]
There seem to be ~ 10 registries implemented in Astropy:
https://github.com/astropy/astropy/search?utf8=%E2%9C%93&q=registry&type=Code

Some are simple:
https://github.com/astropy/astropy/blob/master/astropy/io/registry.py
https://github.com/astropy/astropy/blob/master/astropy/coordinates/sites.py

This is the only one I could find that uses a metaclass:
https://github.com/astropy/astropy/blob/b8b621f1a2974c1ac04f44a4deeabac9149e8aba/astropy/utils/metadata.py#L72

I see you've already got a metaclass in your codebase:
https://github.com/nanograv/PINT/blob/16863f70b799f8b0e45fd90a14778db247f2ad3a/pint/observatory/clock_file.py#L11
so I guess it's an acceptable level of Python complexity for you.

@luojing1211 - Thanks for taking care of this!

**Comment by matteobachetti** [comment]
After PR #264, `import pint.models` works in Python 3.

@demorest @luojing1211 Beware of meta classes, the functionality has changed in Py3. I used a compatibility function from `six` to make them work with the same code in Py2 and Py3 (see the new `timing_model.py`)
