### ISSUE TITLE
Refactor TOA code

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#22]
@demorest suggested that we should refactor the TOA handling code to more cleanly split out the file reading/parsing from the class that holds the TOAs themselves (the split could either involve a new class or just a set of convenience functions for reading TOA files of various types). This would make it easier to add things like other TOA input formats, and special versions that read spacecraft event times and treat them as TOAs.  This issue is to capture that suggestion.

**Comment by paulray** [comment]
I think this is done and can be closed. Do you agree @demorest ?

**Comment by demorest** [comment]
I think it's much better than it used to be, but there are still a few more things I'd like to clean up at some point.  If you want to close this I can create more specific issues to track future development.  Or leave this open as a placeholder, either way is OK with me.

**Comment by paulray** [comment]
Generally I like to have enough information in an issue to know what it would take to close the issue. I'd be fine with either a comment here explaining what is still needed, or a new issue. Either is fine. I'm just doing a little issue maintenance while waiting for a travis-ci build to complete. :-)
