### ISSUE TITLE
Switch from GH wiki to Sphinx docs?

### ISSUE THREAD

**Issue by cdeil** [nanograv/PINT#221]
Have you considered using Sphinx docs and Readthedocs instead of Github wiki pages?

IMO it's much better and pleasant to maintain, e.g.
- docs in same repo as code, versioned docs, changes go through pull requests and can be reviewed
- RST much more powerful than MD (e.g. links within your docs, or to Astropy docs, plot directive, ...) even if you don't generate API 
- Get a PDF version of the docs

It's very easy to add and reformat the existing docs content you have on the wiki, overall probably a few hours of work. This is something I'd be happy to do or help with.

Thoughts?

**Comment by paulray** [comment]
Those all sound like good things.  Right now we are supposed to be using Sphinx, but not much has been done with that.  The Github wiki is only meant to document the install process and be a place for developers to use, but maybe that is all better put into Sphinx. I just don't know how to use it for general docs yet. I know it auto-generates docs out of the code, but that's it.

**Comment by paulray** [comment]
How do we get started with this?  How do you write general documentation, not just auto-generated reference stuff?  I'm happy to contribute once it gets set up.

**Comment by jellis18** [comment]
@paulray, I can help with this. I have set this up for our new data analysis code [enterprise](https://github.com/nanograv/enterprise) and its pretty simple. I do have a few tricks to get the code to autogenerate API docs automatically, without having created the html files before hand. This is something that is not default Sphinx behavior.

I can try to set this up in my fork and send a PR once I get the basics setup and then you and others can put in the non-autogenerated bits.

**Comment by jellis18** [comment]
Should we close this now?
