### ISSUE TITLE
Problem reading ephemeris files that end in *t.bsp

### ISSUE THREAD

**Issue by jellis18** [nanograv/PINT#222]
Currently PINT will fail if using DE430 or higher because while `astropy` understands DE430, the way that the ephemeris is loaded into `SPK` is not, for example

```kernel = SPK.open(datapath("%s.bsp" % ephem))```

will fail because de430t.bsp was downloaded in the `setup.py` script. Furthermore if one tries to use any ephemeris higher than DE430, that will also fail because it is not downloaded in the `setup.py` script and will also fail in `astropy` because the current `kernel_link_base` only contains older ephemerides. This should probably be updated to the JPL ftp server. I see that the separate ways of doing the position and velocity corrections are addressed in #209, but the issue of ephemerides ending in *t.bsp is still a problem. Lastly, one could image wanting to use other ephemerides in the future (not JPL).

I have added the following dictionary to `solar_system_ephemerides.py`

```
jpl_ephem_code = {'de405': 'de405.bsp', 
                  'de418': 'de418.bsp',
                  'de421': 'de421.bsp',
                  'de430': 'de430t.bsp',
                  'de435': 'de435t.bsp',
                  'de436': 'de436t.bsp'}
```

And then changed the way that the ephemeris is read in to ` jpl_ephem_code['%s'%ephem]` instead of `"%s.bsp" % ephem`. You can also add these new files to `setup.py`.

I don't want to do a pull request because this could most easily be incorporated in to #209 but I think the dictionary is the best way to go.

**Comment by luojing1211** [comment]
Hi Justin, 

Firstly, thanks for your help. PR #209 should be the future way, but it requires astropy 1.3. In PR #209, line 
```
kernel = SPK.open(datapath("%s.bsp" % ephem))
```
will not be used. So giving the name 'de430t.bsp' and any higher version of ephemeris should work. 

By the way, why do you chose to use 'de430t.bsp' other than 'de430.bsp'? Do you need a higher precision of TT-TDB?

**Comment by jellis18** [comment]
@luojing1211, 

I see that PR #209 would fix this problem by using the http site first and then the ftp (the ftp doesn't have de430.bsp for some reason). However, as the code is at the moment, it will not work with DE430 or higher. And I suppose I don't need the *t.bsp versions, I was just using that because they are on the ftp server. When do you think you will merge the pull request?

Although, in terms of PR #209, it appears that you have a spelling mismatch. You define `kerner_link_base_http` at the top but then use `kernel_link_base_http` later. Also, why do you download from the ftp server first before calling `coor.get_body_barycentric_posvel`?

Anyway, I'm trying to do some tests with ephemerides so I'll probably have more questions/issues later.

**Comment by luojing1211** [comment]
@jellis18 
* I hope this can be merged as soon as we have good test of the accuracy. 
* Thanks for the catch of miss spelling. 
* The reason I call download from the ftp server first is because it will get the timeout error for some network. I need to extend the waiting time. But once it is downloaded, this line will not run. 
* Please do not hesitate to post more issues.

**Comment by jellis18** [comment]
Ok @luojing1211, that sounds good. Although I still think a more general method (like dictionaries or something other than assuming *.bsp) would be good so that eventually other ephemerides like the french or Russian ones could be used. I suppose that can come later though.

**Comment by jellis18** [comment]
I'm pretty sure we can close this...
