### ISSUE TITLE
Consider take entire TOAs class into model.phase() and model.delay

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#226]
Hi @all, 
I currently I am optimizing PINT code. I realize sometimes a delay requires the entire TOAs class, other than the TOAs.table.  For example, JUMP can be applied to different tim files, but the file information is not in the table. 
I think it is more beneficial if we take TOAs class other than TOAs.table only. What do you think?

**Comment by scottransom** [comment]
@luojing1211  We already have a column in the table with a bunch of flags.  Why not just add a filename flag to those?  That is already how we select certain flags for certain options.

**Comment by paulray** [comment]
Yes, I think that it is not a good idea to have functions that take TOAs.table as an argument. That is breaking encapsulation by making higher level code have to know about internals of the TOAs object.

**Comment by scottransom** [comment]
That's fine, @paulray   I'm not against passing the TOA class instance rather than the table.  (Although I don't think the encapsulation argument is very strong here since these are functions and not TOA class methods).  My point is that we want to do everything we can with *tables*, because they are significantly faster.

**Comment by paulray** [comment]
I agree about tables. I just never liked having to guess whether I should pass TOAs or TOAs.table to a particular function.

**Comment by luojing1211** [comment]
@scottransom and @paulray, I think using table for computing is the way to go. But the advantage to pass a TOAs class is that we can access the convenient functions that TOAs class provides. 
For example, a jump flag column is only added when a JUMP model needs it.  it would be very handy if we just use a method like TOAs.add_column_from_table('flag', key)

**Comment by scottransom** [comment]
Yup.  I'm fine with that.
