### ISSUE TITLE
missing parfile.py module for fermiphasogram.py example?

### ISSUE THREAD

**Issue by djannati** [nanograv/PINT#229]
Hi, I'm trying to run fermiphasogram.py but it gets the following error :
```
  File "./fermiphaseogram.py", line 16, in <module>
    from parfile import psr_par
ImportError: No module named parfile
```
@paulray - Is this available somewhere? Thanks
Arache

**Comment by paulray** [comment]
Sorry, that is part of PRESTO. I guess that is an unintended dependency. We could pull parfile.py over into PINT, but maybe there is a better way.

**Comment by djannati** [comment]
I guess pulling parfile.py into PINT would be a good way, as that would avoid adding  other dependencies (e.g. pgplot in psr_utils.py).

**Comment by paulray** [comment]
This is fixed in PR #219

**Comment by djannati** [comment]
Great, thanks!

**Comment by paulray** [comment]
@djannati : I just merged that PR, so the master branch is fixed. There are many other changes, including the names of scripts, and how they are installed!  After you pull from master, you probably want to build with
`python setup.py install --user`
or 
`python setup.py develop --user`
After you do that, the script you want will be `fermiphase`, not `fermiphaseogram.py`
