### ISSUE TITLE
Make barycentered TOAs work correctly

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#23]
We should be able to have PINT ingest TOAs that are barycentered and work correctly.  Barycentered TOAs are ones that have been externally converted to the TDB time scale _and_ have had the Solar System delays applied for light travel time and Shapiro delay from the Sun and Planets.  (Question: Can they be either infinite frequency or finite frequency, or must they be infinite frequency).

When these TOAs are used in PINT, the timing model must correctly handle them, and not apply the Solar System delays a second time.

**Comment by paulray** [comment]
@paulray is working on this.

**Comment by paulray** [comment]
Currently if you call model.phase(toas.table), it tries to evaluate the full model for each TOA.  It actually should not evaluate the solar system delay terms for TOAs at the 'Barycenter'.  This needs to be fixed so that one could have TOA tables that intermix Barycentric and normal TOAs.

**Comment by scottransom** [comment]
I think it is likely a one-liner (or near one-liner) that we can put in to the solar_system_geometric_delay() method to return 0 for TOAs where the observatory is Barycenter.

**Comment by demorest** [comment]
Shouldn't this all already work out OK if the observatory position is set correctly (ie to 0,0,0) for the barycentered TOAs?

**Comment by scottransom** [comment]
Ah, but that isn't the correct barycenter position....  that is the geocenter position.  And we want that as well.

**Comment by scottransom** [comment]
(unless you meant in *barycenter* coordinates!)

**Comment by demorest** [comment]
Yes, I meant the vector stored along with pint TOAs ("toas['ssb_obs_pos']") which is relative to the barycenter.  This is what the astrometry class uses, if it's zero thing should work fine although I agree we might want a special case just to avoid unnessary calculation.

I don't know if barycentered TOAs (which as we've discussed before are kind of a hack to begin with) typically have had SS shapiro delay applied or not... depending on how this was done the shapiro delay part might need disabling, or changing as the observatory wasn't really at the barycenter.

**Comment by paulray** [comment]
It should be easy to correct, but I am having trouble figuring out the Python to make it work (elegantly).
An example of a function that needs to be modified is below.  The 'toas' argument is really the toas.table, which is grouped by observatory.  So, how do we elegantly loop over the groups and make the delay = 0.0 for the 'Barycenter' key and use the computation for the rest? 

    def solar_system_shapiro_delay(self, toas):
        """
        Returns total shapiro delay to due solar system objects.
        If the PLANET_SHAPIRO model param is set to True then
        planets are included, otherwise only the value for the
        Sun is calculated.

        Requires Astrometry or similar model that provides the
        ssb_to_psb_xyz method for direction to pulsar.

        If planets are to be included, TOAs.compute_posvels() must
        have been called with the planets=True argument.
        """
        psr_dir = self.ssb_to_psb_xyz(epoch=toas['tdbld'].astype(numpy.float64))
        delay = self.ss_obj_shapiro_delay(toas['obs_sun_pos'],
                                          psr_dir, self._ss_mass_sec['sun'])
        if self.PLANET_SHAPIRO.value:
            for pl in ('jupiter', 'saturn', 'venus', 'uranus'):
                delay += self.ss_obj_shapiro_delay(toas['obs_'+pl+'_pos'],
                                                   psr_dir, self._ss_mass_sec[pl])
        return delay

**Comment by demorest** [comment]
I believe this was fixed.  If not, someone re-open it.
