### ISSUE TITLE
Clock corrections in written TOA files?

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#230]
I think that `write_TOA_file()` should subtract out any clock corrections that have been applied to the TOAs before writing out a TEMPO or Tempo2 format TOA file. If not, they will be applied again when it is read back in.

**Comment by scottransom** [comment]
Not sure what the right behavior should be...  Yours is probably the right thing to do by default.  But it would be good to be able to turn that behavior off if requested.  I can see many reasons for wanting "clean" TOAs that are fully corrected for many effects.  This would give us a way of easily writing them.

**Comment by luojing1211** [comment]
The clock correction has been subtracted from TOAs when using write_TOA_file() in the PR #362. Should we provide a functionality for a corrected "TOA" version?
