### ISSUE TITLE
DM1 not supported in par files

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#235]
PINT does not seem to currently have support for DM1 and DMEPOCH in par files. 

```
In [2]: m = pint.models.get_model('PSR_B1937+21.par')
WARNING: Couldn't write lextab module u'angle_lextab'. [Errno 13] Permission denied: u'/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/angle_lextab.py'
WARNING: Couldn't create u'angle_parsetab'. [Errno 13] Permission denied: u'/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/angle_parsetab.py'
WARNING: Unrecognized parfile line 'DMEPOCH        54931' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'DM1            -0.0027006014359777492377 1  0.00001264632232628037' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'EPHVER         5' [pint.models.timing_model]
```

**Comment by paulray** [comment]
How is DM handled?  Is a DM polynomial added to the DMX terms, if they are present?
Do we have a solar system DM term in PINT?  Is DM generally the sum of a set of dispersion components?

**Comment by luojing1211** [comment]
Hi @paulray , DM polynomial is not added into the model yet. Right now, DM is set as the way of a set of dispersion components. If you look at file pint.models.dispersion_model.py line 63. All the dispersion components are saved at `.dm_value_funcs`. But we can expand the basic DM model to a polynomial DM calculation.

**Comment by luojing1211** [comment]
Hi @paulray, is there any reference about this? This should be easy to implement

**Comment by paulray** [comment]
See Section 2.6.1 of [Tempo2 Paper 2](http://adsabs.harvard.edu/abs/2006MNRAS.372.1549E), particularly Eqn (39).

**Comment by luojing1211** [comment]
The DM parameter is just the 0th term of total DM. DM1 is first order derivative of total DM. But in tempo2 parameter list DMX is the X'th time derivative of the dispersion measure. It sounds very confusing. I guess the X here can be replaced by any numbers. But the DMX we are using is a irreplaceable. In our documentation,  we should make this clear.

**Comment by paulray** [comment]
Sorry for the confusion.  I think the way it is implemented is that the basic DM model is a polynomial DM with parameters DM, DM1, DM2, ... that are analogous to F0, F1, F2, polynomial expansion of frequency.  Then (I believe), the DMX is a set of DM offsets that apply over a set of time ranges. So the total DM is the sum of the DM polynomial and the DMX value relevant to that TOA.

**Comment by luojing1211** [comment]
Is the DMX parameter we have is implement later? If that is the case, it make sense that tempo2 documentation has this confusion, since it is really old.

**Comment by paulray** [comment]
Yes, I think DMX was added later to Tempo2. In the paper they mention using the stridefit capability to do that kind of thing.  Eventually that must have morphed into DMX.

**Comment by luojing1211** [comment]
Do you have any parfile with DM1, DM2..

**Comment by paulray** [comment]
```
PSRJ           B1937+21
ELONG          301.9732444829211520376244238    2.6487219053348841169e-4930
ELAT           42.2967524996648554062861347   
F0             641.92823479414309529     1  0.00000000002643015112   
F1             -4.3310230780892104183e-14 1  1.3547912362302856512e-19
PEPOCH         54931                       
POSEPOCH       54931                       
DMEPOCH        54931                       
DM             71.037463200520379873     1  0.00012477509709159752   
DM1            -0.0026082708423107857579 1  0.00002030004136131922   
PMELONG        -0.083333121080888801792     0.00654179372154060131   
PMELAT         -0.30731917638486866488      0.01036005030169356335   
PX             0.3934629653127993687        0.12734894687707229433   
START          56886.050832482214901     1 
FINISH         57376.798825987250893     1 
TZRMJD         57131.374361819224713       
TZRFRQ         859.84100300000000061    
TZRSITE        gbt   
TRES           0.809        
EPHVER         5                           
CLK            TT(BIPM)
MODE 1
UNITS          TDB
TIMEEPH        FB90
DILATEFREQ     N
PLANET_SHAPIRO N
T2CMETHOD      TEMPO
NE_SW          10.000
CORRECT_TROPOSPHERE  N
EPHEM          DE421
```

**Comment by jellis18** [comment]
Hi @paulray, @luojing1211 maybe I'm reading this wrong but the quadratic DM and DMX should not be used together unless we are placing priors on DMX. DMX is simply a normal DM fit using data from a single epoch. Every DMX parameter is completely independent from the others and there are no constraints so if it is fit along with a DM quadratic (or even just a DM offset) then the parameters will be completely covariant with the Quadratic parts.

**Comment by luojing1211** [comment]
This is the residual from the B1937+21 11 yrs data:
Residual Plot MJD as x axis
![screen shot 2017-03-22 at 11 12 59 pm](https://cloud.githubusercontent.com/assets/5324931/24231953/7bec26ce-0f55-11e7-8056-2a19aeb6aabb.png)
Residual Plot Freq as x axis
![screen shot 2017-03-22 at 11 13 17 pm](https://cloud.githubusercontent.com/assets/5324931/24231960/9278d43c-0f55-11e7-9e0d-083230502c12.png)
But Tempo2 gives the residual as 
![screen shot 2017-03-22 at 11 18 54 pm](https://cloud.githubusercontent.com/assets/5324931/24232015/ff18f6bc-0f55-11e7-9e5e-ab2ec3e06827.png)

The only thing I changed is from constant DM. I use dm = DM + DM1*(tdbld - DMEPOCH). What am I missing here?

**Comment by luojing1211** [comment]
@jellis18 The confusion is coming from the TEMPO2 documentation. DMX is treated as FX and FBX in it. We would like to make it clear in PINT.

**Comment by luojing1211** [comment]
Since the DM1 model is merged. We can close this issue.
