### ISSUE TITLE
Add support for creating and writing TEMPO-style polyco.dat files

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#24]
PINT should support the creation of polyco.dat files.  Eventually, there might be a PINT-specific format for phase predictions that are rapidly evaluateable without having all of PINT installed, but the first priority is a capability compatible with TEMPO (and the produces the same results).

**Comment by luojing1211** [comment]
Should we close this?

**Comment by scottransom** [comment]
Why close it?  Can we do this?  It is something that I think we should be able to do...

**Comment by paulray** [comment]
Yeah, this should be open. I think PINT got some polyco capabilities added, but I haven't found time to test them out and make sure they are compatible with TEMPO.  This is a good small project for someone who knows TEMPO polycos and wants to contribute to PINT.
