### ISSUE TITLE
binary_bt.py questions

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#240]
The following code seems questionable (starting line 56 of binary_bt.py):
```
        # If eccentricity is zero, freeze some parameters to 0
        # OM = 0 -> T0 = TASC
        if self.ECC.value == 0 or self.ECC.value is None:
            for p in ("E", "OM", "OMDOT", "EDOT"):
                getattr(self, p).set("0")
                getattr(self, p).frozen = True
```

First, the the `getattr()` fails on "E" since the parameter is really called "ECC".  I have fixed that in my current pull request, so no need to worry about that.

But, why does it set EDOT to frozen if ECC == 0?  There is nothing wrong with E=0 and EDOT free, right?  It is fine if there is no EDOT in the par file, but would this setting be overridden if I specify `EDOT 0 1` in my parfile?  If someone doesn't specify a parameter like OM or OMDOT, shouldn't they default to 0 without having to be explicitly set, like we are doing here?  @luojing1211

**Comment by luojing1211** [comment]
>
>
>  If someone doesn't specify a parameter like OM or OMDOT, shouldn't they
> default to 0 without having to be explicitly set, like we are doing here?
> @luojing1211 <https://github.com/luojing1211>
>
​Yes, they should be set to zero as default. This setting code is from
Rutger's old BT code. It should be ok ECC is zero but EDOT is ok to be
fitted, right?

**Comment by paulray** [comment]
Yes. It is certainly a valid use case to have ECC =0 and EDOT free.

But, presumably all parameters default to a value of 0 and are not fitted, unless fitting is explicitly turned on, right?  So maybe all of that if statement can be deleted?

**Comment by luojing1211** [comment]
​I think that should be ok to remove.

-Jing Luo​
