### ISSUE TITLE
Issues with TimingModel implementation

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#242]
This is just an issue for me to note some concerns with how timing models and pulsar binaries are implemented in PINT, with the hope that it will lead to a refactoring of the code at some point.  The overriding issues are:
1. Improving on the 'L1', 'L2' scheme for delay calculations
1. Allowing for a more general model for binary orbit phase calculations than just PB, PBDOT. This should include FB0, FB1, ... as well as other models for orbital phase evolution that we someday might want like periodic wandering of T0 or red noise models for the orbital phase wander.
1. PINT timing models should easily accommodate adding models for triple systems and systems with planets
1. PINT timing models should easily accommodate Kopekin type models where astrometry and binary parameters get mixed together.

I think we might consider a different structure for the TimingModel class. Instead of every model being a subclass of TimingModel, maybe it would help to have a TimingModel class that is *composed* of a phase evolution class (i.e. `Spindown`) and a set of delay classes.

Also, currently the `PulsarBinary` model defines PB and PBDOT parameters right in its `__init__ ()` method. This suggests that the PB, PBDOT parameterization of orbital phase is 'baked in' to all PINT binary models.  It would be great if this orbital phase calculation could be refactored out.

**Comment by paulray** [comment]
A related issue was discussed today at the telecon. In some places, it is difficult to maintain the modularity of the TimingModel and the TOAs, especially when you try to cache values. Currently, DMX ranges are stored in the TOAs table, which means that if you use the same TOAs object to compute residuals using two different TimingModel objects and they have different DMX ranges, that might fail.

**Comment by jellis18** [comment]
> I think we might consider a different structure for the TimingModel class. Instead of every model being a subclass of TimingModel, maybe it would help to have a TimingModel class that is composed of a phase evolution class (i.e. Spindown) and a set of delay classes.

@paulray, I like this idea and this is basically what we are doing in `enterprise`. I think the timing model component classes should still inherit from a TimingModel base class but the overall model should be a composition of these subclasses rather than using multiple inheritance through  `type` as is happening now.

**Comment by luojing1211** [comment]
Hi all, 
Here is the a simple uml I made for the composition design. 
![screen shot 2017-04-07 at 2 43 29 pm](https://cloud.githubusercontent.com/assets/5324931/24817405/ffcaf8be-1ba1-11e7-926e-8dfca9c9dc98.png)
The main idea is to have TimingModel as a parent container. Each component will be placed in the component list in TimingModel instance. But ._parent member in the component class will point to the TimingModel instance. One component can access the parameters using this _parent member. Here is some sudo code:
```
t = TimingModel()
cp1 = DelayComponent()
cp2 = PhaseComponent()
t.component_list['cp1'] = cp1
t.component_list['cp2'] = cp2
cp1._parent = t
cp2._parent = t
# Maybe we can have a function called:
# t.add_component() to do the job above

setatter(cp1, 'P1', 10.0)
setatter(cp2, 'F0', 123.0)

# access F0 from cp1
f0 = cp1._parent['cp2'].F0
# Since ._parent is a pointer, it will get update if object t is updated. 
#For total delay, t.delay will be used to loop over all the delays. 
delay = t.delay(tos)
```
Let me know what do you think.

**Comment by paulray** [comment]
For implementing multi-threaded MCMC, we need to be able to pickle timing models. A new implementation should strive for that.

**Comment by luojing1211** [comment]
How does this multi-threaded MCMC code want the model to get pickled?

**Comment by paulray** [comment]
@luojing1211 see the Multiprocessing section here http://dan.iel.fm/emcee/current/user/advanced/

**Comment by luojing1211** [comment]
@paulray I tried to pickle the TimingModel class, but it failed. After a little googling, I realized that the bounded method in a class can not be pickled. Do you have any solution for that?

**Comment by paulray** [comment]
I don't know much about it, but @scottransom looked into pickeling model classes before. I know he found that the `dill` package was able to pickle some classes that cPickle could not.

**Comment by luojing1211** [comment]
@paulray I did a dill package test, and it works. See the screenshot below. 
![screen shot 2017-05-19 at 10 57 18 am](https://cloud.githubusercontent.com/assets/5324931/26256257/fc61fc12-3c81-11e7-91ca-b45dbfcedc70.png)

**Comment by paulray** [comment]
Great, that will be helpful for getting parallel MCMC working. Definitely a nice feature of the new TimingModel structure.

**Comment by luojing1211** [comment]
This is fixed by the new timing model style. Closing.
