### ISSUE TITLE
ERFA Warning

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#250]
I get this strange ERFA warning when reading a par file and I can't track it down. Is there some way to make `ErfaWarning` throw an exception?

```
In [1]: import pint.models
 
In [2]: m = pint.models.get_model('PSR_J0030+0451.par')
WARNING: ErfaWarning: ERFA function "dtf2d" yielded 1 of "dubious year (Note 6)" [astropy._erfa.core]
WARNING: Couldn't write lextab module u'angle_lextab'. [Errno 13] Permission denied: u'/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/angle_lextab.py'
WARNING: Couldn't create u'angle_parsetab'. [Errno 13] Permission denied: u'/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/angle_parsetab.py'
WARNING: Unrecognized parfile line 'DMEPOCH        55390' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'EPHVER         5' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'MODE 1' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'T2CMETHOD      TEMPO' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'NE_SW          0.000' [pint.models.timing_model]
```

Here is the parfile:
```
PSRJ           J0030+0451
# RAJ_deg, DECJ_deg = 7.614286327916667, 4.861022175
RAJ             00:30:27.4287187
DECJ           +04:51:39.67983
F0             205.53069911077197993
F1             -4.297983121224124778e-16
PEPOCH         55390                       
POSEPOCH       55390                       
DMEPOCH        55390                       
DM             4.332938688231533754
START          53394.85438586708915  
FINISH         57386.920654129149625 
TZRMJD         55500.083371262711534       
TZRFRQ         424                      
TZRSITE        ao   
TRES           2.610        
EPHVER         5                           
CLK            TT(TAI)
MODE 1
UNITS          TDB
TIMEEPH        FB90
DILATEFREQ     N
PLANET_SHAPIRO N
T2CMETHOD      TEMPO
NE_SW          0.000
CORRECT_TROPOSPHERE  N
EPHEM          DE405
NITS           1
NTOA           5684
```

**Comment by mdecesar** [comment]
I got the same warning when running "make test":

WARNING: ErfaWarning: ERFA function "dtf2d" yielded 1 of "dubious year (Note 6)" [astropy._erfa.core]

I don't know what test was being run that led to the warning, but I can paste the output up to that warning if it might be useful.

**Comment by paulray** [comment]
@mdecesar, yeah that is how I first saw it. The example above was the minimal way to reproduce the warning.  I'm hoping someone will know how to track down what code is causing it. It must be somewhere in the model building code.

**Comment by paulray** [comment]
@luojing1211 can you track this down?

**Comment by luojing1211** [comment]
I will track it down.

**Comment by paulray** [comment]
This is due to Time() objects being initialized with MJD = 0.0 or 99999.0.  The first cases have been fixed by @luojing1211.  The second case comes from the end time in gps2utc.clk, so it is not actually an error, just a time far in the future.  Not much we can do about that. Closing...

**Comment by paulray** [comment]
Is there a way to suppress that warning in the code, only when reading the gps2utc.clk? That would be useful, so people aren't confused by the warning, but it would still come out if someone gave Time() a bad MJD value.

**Comment by luojing1211** [comment]
This is merged. Can you double check your branch?
