### ISSUE TITLE
Make residuals plotting function

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#254]
So far, we've done very simple plotting of residuals, see [pintempo](https://github.com/nanograv/PINT/blob/master/pint/scripts/pintempo.py), starting line 48.

We need to write a nice general residuals plotting function, that takes a `resids` object (or possibly two, for plotting prefit and postfit together), and a Matplotlib `axis` object and makes a nice plot of the residuals.  It should be able to plot time or phase residuals vs. time, year, frequency, orbital phase, etc... It should also be able to easily apply averaging of the resids.  Note that this is mainly for command line use for now, so at first it does not need to be interactive.  That kind of interaction will come in the GUI, which is issue #57

**Comment by scottransom** [comment]
A lot of people have been using pyplotres.py in PRESTO to view residuals.  It should be quite simple to modify that to be used with PINT.  It is an interactive residual viewer.

**Comment by paulray** [comment]
Adapting pyplotres sounds like a good start!  For reference, it is here:
https://github.com/scottransom/presto/blob/master/bin/pyplotres.py

**Comment by jcolen** [comment]
Should this be closed now that it's implemented in the GUI?
