### ISSUE TITLE
TypeError occurs from mb.get_model(), depending on directory where I run PINT

### ISSUE THREAD

**Issue by mdecesar** [nanograv/PINT#255]
I'm getting an error that seems to depend on whether or not I'm running PINT in the directory where I've installed it.

(a)  If I run the following in the PINT installation directory, and within my PINT virtual environment:

import pint.models.model_builder as mb
parfile = 'nanograv_timing_2016/release/par/B1855+09_NANOGrav_11yv0.gls.par'
m = mb.get_model(parfile)

then I get an ERFA warning, but no errors:

WARNING: ErfaWarning: ERFA function "dtf2d" yielded 1 of "dubious year (Note 6)" [astropy._erfa.core]

(b)  If I instead run the above in a different directory (also in my PINT virtual environment), I get an ERFA warning and a TypeError; the full list of errors is below.

WARNING: ErfaWarning: ERFA function "dtf2d" yielded 1 of "dubious year (Note 6)" [astropy.\_erfa.core]

TypeError                                 Traceback (most recent call last)
<ipython-input-4-37e7c95c355b> in <module>()
----> 1 m = mb.get_model(parfile)

/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/models/model_builder.pyc in get_model(parfile)
    256     name = os.path.basename(os.path.splitext(parfile)[0])
    257 
--> 258     mb = model_builder(name,parfile)
    259     return mb.model_instance

/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/models/model_builder.pyc in __init__(self, name, parfile)
     86             self.parfile = parfile
     87             self.get_comp_from_parfile(self.parfile)
---> 88             self.get_model_instance(self.parfile)
     89 
     90     def __str__(self):

/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/models/model_builder.pyc in get_model_instance(self, parfile)
    239 
    240         if parfile is not None:
--> 241             self.model_instance.read_parfile(parfile)
    242 
    243 def get_model(parfile):

/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/models/timing_model.pyc in read_parfile(self, filename)
    603             parsed = False
    604             for par in self.params:
--> 605                 if getattr(self, par).from_parfile_line(l):
    606                     parsed = True
    607             if not parsed:

/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/models/parameter.pyc in from_parfile_line_regular(self, line)
    339             return False
    340         if len(k) >= 2:
--> 341             self.set(k[1])
    342         if len(k) >= 3:
    343             try:

/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/models/parameter.pyc in set(self, value)
    291         of the parameter.
    292         """
--> 293         self.value = value
    294 
    295     def add_alias(self, alias):

/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/models/parameter.pyc in value(self, val)
    220             else:
    221                 self.value = val
--> 222         self._quantity = self.set_quantity(val)
    223 
    224     \@property

/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/models/parameter.pyc in set_quantity_float(self, val)
    474         except AttributeError:
    475             # This will happen if the input value did not have units
--> 476             result = setfunc_no_unit(val)
    477 
    478         return result

/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/models/parameter.pyc in <lambda>(x)
    466         else:
    467             setfunc_with_unit = lambda x: data2longdouble(x.value)*x.unit
--> 468             setfunc_no_unit = lambda x:  data2longdouble(x) * self.units
    469         # First try to use astropy unit conversion
    470         try:

/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/utils.pyc in data2longdouble(data)
    356     """
    357     if type(data) is str:
--> 358         return str2longdouble(data)
    359     else:
    360         return np.longdouble(data)

/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/utils.pyc in str2longdouble(str_data)
    312     """
    313     input_str = str_data.translate(string.maketrans('Dd', 'ee'))
--> 314     return str2ldarr1(input_str)[0]
    315 
    316 

TypeError: 'NoneType' object has no attribute '\_\_getitem\_\_'

**Comment by luojing1211** [comment]
Can I see your parfile?

**Comment by paulray** [comment]
What command did you use to install PINT?

If you are using a virtualenv, you should install with `python setup.py install`. Then you should run pint in any directory BUT the top level package directory.

**Comment by mdecesar** [comment]
@luojing1211  -- sure, though I've tried it with different parfiles and got the same result.

The B1855 parfile is pasted below, but I've removed all but the first set of DMX lines for brevity.

PSR              B1855+09
LAMBDA   286.8634882741210  1     0.0000000130597
BETA      32.3214862208211  1     0.0000000210895
PMLAMBDA           -3.2728  1              0.0109
PMBETA             -5.0644  1              0.0209
PX                  0.5994  1              0.1589
POSEPOCH        55367.0000
F0    186.4940812499313552  1  0.0000000000059747
F1     -6.204549168059D-16  1  3.658792544582D-20
PEPOCH        55367.000000
START            53358.726
FINISH           57375.734
DM               13.313704
DMX               6.000000
DMX_0001   -2.75237910D-03  1      2.46990314D-03
DMXEP_0001     53358.72746
DMXR1_0001     53358.72746
DMXR2_0001     53358.77856
DMXF1_0001         424.000
DMXF2_0001        1442.000
[more DMX lines]
FD1  1.28618528D-04  1      2.37810622D-05
FD2 -1.47263148D-04  1      2.90083787D-05
FD3  8.13777023D-05  1      1.75387701D-05
SOLARN0               0.00
EPHEM               DE436
ECL                 IERS2010
CLK                 TT(BIPM2015)                    
UNITS               TDB
TIMEEPH             FB90
T2CMETHOD           TEMPO
CORRECT_TROPOSPHERE N
PLANET_SHAPIRO      N
DILATEFREQ          N
NTOA                  5634
TRES                  1.17
TZRMJD  55391.17268895300718
TZRFRQ            1410.000
TZRSITE                  3
MODE                     1
NITS                     1
INFO -f                              
BINARY            ELL1    
A1             9.230780242  1         0.000000204
PB       12.32717119159692  1    0.00000000015865
TASC       55360.513155151  1         0.000000018
EPS1         -0.0000215020  1        0.0000000232
EPS2          0.0000024372  1        0.0000000158
SINI              0.999406  1            0.000188
M2                0.241405  1            0.011404
RNAMP         0.51608D-01
RNIDX            -3.53590
T2EFAC -f 430_PUPPI   1.044
T2EFAC -f L-wide_PUPPI   1.377
T2EFAC -f 430_ASP   1.188
T2EFAC -f L-wide_ASP   1.079
T2EQUAD -f 430_PUPPI   0.74400
T2EQUAD -f L-wide_PUPPI   0.21020
T2EQUAD -f 430_ASP   0.03270
T2EQUAD -f L-wide_ASP   0.29120
ECORR -f 430_ASP   0.04420
ECORR -f 430_PUPPI   0.33040
ECORR -f L-wide_ASP   0.74950
ECORR -f L-wide_PUPPI   0.34550
JUMP -fe L-wide      -0.000016258  1       0.000006628
# Converted by make_release.py on Mon Mar  6 11:13:58 2017 by pdemores
# Original filename: 'B1855+09/B1855+09.x2e.par'
# Ran additional tempo iteration

**Comment by mdecesar** [comment]
@paulray -- Ok, maybe this is the problem then.  I thought it might be an installation issue.

I'd tried a few different things.  Originally after cloning the repository, I'd used "python setup.py install build_ext --inplace".  But the tests failed, and then instead I did "pip install -r requirements_dev.txt" and "make test", and that worked.

So, since I'm in a virtual environment, then are these the steps I should take to install PINT?:

[clone the repository]
cd PINT
pip install -r requirements_dev.txt
python setup.py install

Is it correct that I should not use "python setup.py install --inplace"?

What about running the tests?  Should I run "make test" after running "python setup.py install"?

Thanks!

**Comment by paulray** [comment]
@mdecesar, yes what you wrote looks good.  Do not use the --inplace anymore.  And make test should be the right thing to run to test.

For you case (a) and (b), can you run ipython then:
```
import pint
print pint.__file__
print pint.__version__
```
Likely you will find that you are getting a different version of PINT depending on what directory you are in.

I don't use virtualenv, but I think it installs packages in its own place and tries to set paths so those versions are gotten first.  You probably should delete other installs of PINT, like you seem to have one in `/usr/local/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg`

Also, you may have one in ~/.local as well.  To prevent confusion, remove all installs of PINT, except the one in your virtualenv.

**Comment by paulray** [comment]
@mdecesar is this solved?

**Comment by mdecesar** [comment]
Thanks a lot for the help.  I did have other installations of PINT.  Now that I've removed those and have re-run the installation steps and "make test", I do not get the errors that I reported in the original post.

I still get different results from "print pint.\_\_file\_\_" depending on the directory I'm in:

In PINT directory:

`import PINT
print pint.__file__`
pint/\_\_init\_\_.pyc
`print pint.__version__`
0.5.2+10.g3d32ace

In a different directory, the only difference is from "print pint.\_\_file\_\_":
`print pint.__file__`
/Users/decesame/Envs/pint/lib/python2.7/site-packages/pint-0.5.2+10.g3d32ace-py2.7-macosx-10.11-x86_64.egg/pint/\_\_init\_\_.pyc

However, this difference doesn't seem to affect anything, as I don't get any errors depending on which directory I'm in.  So I think that unless you see a problem with the above, this can be closed.

**Comment by paulray** [comment]
Yep, that looks fine.  As long as you have "." in your PYTHONPATH, you will import the local version if you are in the PINT directory.  Normally it is probably best to run in a different directory, but as you say it seems to work either way.

Closing.
