### ISSUE TITLE
make dist fails

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#256]
`make dist` fails with the following error message:
```
error: invalid command 'bdist_wheel'
```

It does correctly build the source distro tar file, but the second step fails. I guess this is trying to build a binary distro.  Seems like we could just delete `python setup.py bdist_wheel` from the Makefile.

**Comment by jellis18** [comment]
@paulray, all you have to do is add 
```
[bdist_wheel]
universal = 1
```
to `setup.cfg` and it will work. Its probably good to keep it in there for when we get `PINT` in `pypi`, as this is basically just a test to see if the binary files will build correctly. The `make release` command would then run the same thing but upload to `pypi`.

**Comment by paulray** [comment]
I tried that but still get the "invalid command" error.  Could I be using an old version of setuptools or distutils? Here are my versions:
```
In [1]: import setuptools

In [2]: setuptools.__version__
Out[2]: '32.3.1'

In [3]: setuptools.__file__
Out[3]: '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/__init__.pyc'

In [4]: import distutils

In [5]: distutils.__version__
Out[5]: '2.7.13'

In [6]: distutils.__file__
Out[6]: '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/__init__.pyc'

```

**Comment by jellis18** [comment]
Do you have `wheel`?

**Comment by paulray** [comment]
Nope. `pip install wheel` fixed the issue.
I will add it to `requirements_dev.txt`. Why are all of those specified with `== version`, while in `requirements.txt`, they are `>= version`?

**Comment by jellis18** [comment]
I'm not really sure why I did that. We could make them all `== version` maybe

**Comment by paulray** [comment]
Doesn't >= make more sense? Otherwise if someone has a newer version of some package won't pip then install a redundant older version?  If we use >= then we only need to change the file if we find we require a new version (such as when astropy adds a leap second)

**Comment by jellis18** [comment]
Yes that makes sense, lets go with `>=`

**Comment by paulray** [comment]
Cool, will do.
