### ISSUE TITLE
Should define set of PINT milestones

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#258]
I think we should add a set of milestones for PINT development to track the top-level path for the code. 

Some initial thoughts on what milestones might be are below.  My basic thinking is what would it take to make PINT your daily pulsar timing code, rather than TEMPO or Tempo2?  Also, are there any milestones from the PFC proposal that should be tracked?

* Generalized least-squares (GLS)  fitting implemented
* Processes and fits NANOGrav 11yr dataset with consistent results to TEMPO
* Handles photon TOAs
* Handles control commands in par files, and timing model parameters in tim files,  correctly
* MCMC fitting implemented
* Wideband TOA support
* Includes useful GUI
* Includes fitting for red noise parameters

If we add these milestones to github, then individual issues can be created to define the path to achieving them.  Do you think this is useful?

What do people think? @scottransom @demorest @luojing1211 @jellis18

**Comment by luojing1211** [comment]
I agree @paulray. I was thinking about the processing 11yr dataset as our first milestone.
By the way, is fitting for red noise parameters a part of processing 11 years data set goal?

**Comment by jellis18** [comment]
I think this is a good idea but I have some questions about the milestones. For example, what do you mean by MCMC fitting? Also in some cases, like fitting red noise there may be a lot of code duplication with detection codes. I'm not quite sure how to handle this but we should think about it.

**Comment by paulray** [comment]
Good questions. I was just trying to get some discussion started.

@luojing1211, no I don't think we need to be able to fit for red noise parameters to do the 11yr dataset. TEMPO and Tempo2 both just use the red noise parameters in the par files. They are determined by PAL2.

@jellis18, yeah I know that red noise fitting needs some thought.  We should make a plan for how it should eventually be, with a goal of minimizing duplication.  That is why PINT being very modular is nice.  Ideally, PINT would handle all the stuff it is good at, like loading and time correcting TOAs and computing delays and phases based on deterministic timing models, while PAL2 would do its fitting for the red noise parameters.  A script that "does it all" would import both pint and PAL2.  Maybe it would work out if PAL2's fitter was a subclass of of Fitter from pint, or something like that (I don't know the architecture of PAL2, so I'm just guessing here).

Also, by MCMC fitter, I meant a minimal MCMC fitter for deterministic timing model parameters, as we have already done in event_optimize, but this needs to be added to the main PINT suite of TOA fitters. For that milestone, I didn't mean a full MCMC including red noise and such.

**Comment by paulray** [comment]
We should add a milestone for full Python 3 compatibility as well.  Once we cross that, all PRs should have to pass tests on both 2.7 and 3.

**Comment by paulray** [comment]
At the telecon, we discussed a couple of other possible milestones:
* Implement good framework for specifying noise models
* Optimize PINT for speed

We also talked about a general goal of making sure we are coordinating with nanograv/enterprise so they play well together (e.g. things like Priors, which both codes implement). We should make sure that we aim for compatibility and code reuse where possible, but for most PINT users, we don't want to require installation of enterprise.

**Comment by paulray** [comment]
What are the list of timing group/PFC milestones, with dates for PINT?

**Comment by luojing1211** [comment]
Here is the PINT GOAL from timing group discussion. 
PINT
Development
* GUI to see residuals (Kevin)
* Add new binary models needed for 11-yr dataset testing (DDK, ELL1H, …) (existing PINT      developers, Tim P, others? - Feb 1, 2016)
* Fitter (Jing, Jan 31, 2017)
* Develop noise model functionality in PINT, or interface with PAL2 (Jing, Justin, Paul) - gen LS fit with preset noise model values will be done in PINT; but PAL2 will be used to determine noise model parameters
* PINT accept noise models, do GLS fitting (March 1, 2017)
* PINT/PAL2 interface (libstempo) (March 1, 2017)
* For PINT+wideband: fit for DM in addition to TOA model (June 1)

**Comment by paulray** [comment]
@luojing1211, thanks those are very useful! Is there also a set of milestones from the PFC statement of work or something?  Maybe @scottransom knows?

**Comment by jellis18** [comment]
A few questions/comments.

* Should we make official github milestones for these so that issues and Pos can reference them?
* We should not be using PAL2 as it will be phased out soon in favor of our new code `enterprise`.
* For the GUI, have you taken a look at https://github.com/vhaasteren/qtip-psp?

**Comment by paulray** [comment]
Yes, the plan is to pull to together a nice set of milestones from this discussion and put them in github as official milestones.  On the GUI, qtip is indeed the baseline plan for a PINT GUI but since Rutger left, it hasn't been worked, as far as I know. @kstovall is going to be working on that, I believe. One of the reasons for moving the PINT telecons was so that he could attend.

**Comment by mdecesar** [comment]
I also started looking into processing the 11-yr dataset with PINT.  Currently I'm removing all noise parameters, running tempo without GLS, reading the parfile output from tempo into PINT, re-fitting with PINT, and comparing the pre-fit (tempo-fit) and post-fit (PINT-fit) timing parameters.  It should be easy to re-run this with the noise parameters once you've implemented GLS fitting.
