### ISSUE TITLE
get_mjds() returns an array that is not easy to plot

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#26]
Currently, TOAs.get_mjds() returns an array of astropy.Time objects, rather than an astropy.Time object containing an array of MJDs.  The latter is probably more convenient for plotting since matplotlib fails when trying to access an array of Times.

@aarchiba suggests that we make this function return an astropy.Time object with an array of MJDs, but notes that we still do need an easy way to get out high-precision floating point MJDs.

**Comment by scottransom** [comment]
The reason for the current behavior is that you cannot have an astropy Time array if there are multiple locations.  This is why we iterate over the observatories, creating astropy.Time arrays for each for many of the current TOA calculations and transformations.  I doubt this will change either.

The point of get_mjds() (at least as I saw it) was to produce a non-high-precision set of MJDs, doubles would probably even be fine, mostly for plotting purposes.  In that case we can convert the astropy times to simple MJD doubles (in fact, get_MJDs() used to do that).

**Comment by vhaasteren** [comment]
Why not default to high_precision=False then?

**Comment by paulray** [comment]
Default is now high_precision=False, and @scottransom made other changes to improve get_mjds(), so I'm closing this issue.
