### ISSUE TITLE
Trouble running PINT_walkthrough.ipynb 

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#265]
The third line in this notebook (involving the "toa.get_TOAs" function) requires the TEMPO2 environmental variable to be set. However, this is nowhere mentioned in the documentation.

**Comment by paulray** [comment]
Thanks for reporting this!  PINT should definitely not require TEMPO2 to run.  However, I can't replicate this.  Can you provide the specific error message?

I suspect it has to do with looking for either the BIPM or GPS clock files (cc: @jellis18).  However, both of those have files in pint/datafiles that should be found first, so it should not be trying to access the TEMPO2 environment variable.

**Comment by luojing1211** [comment]
What is the CLK file you are using?

**Comment by paulray** [comment]
Another likely cause is that I added a new `TopoObs` for 'ncyobs', which uses a TEMPO2 clock file. I don't think that should cause a problem unless TOAs from that observatory are actually read, but I'm not certain.

**Comment by abhisrkckl** [comment]
Here is the screenshot of the error message:

![screenshot at 2017-03-23 21-38-41](https://cloud.githubusercontent.com/assets/20718391/24257698/71c5a0b0-0fe3-11e7-9cb2-fe9dbe1fe7e4.png)

The error goes away when I do 
`export TEMPO2=/usr/share/tempo2/`

**Comment by paulray** [comment]
Can you make a new cell in the notebook and try this:
```
from pint.config import datapath
datapath('tai2tt_bipm2015.clk')
```

What does that return?

**Comment by paulray** [comment]
Also, what command did you run to install PINT?  And, I assume you are working in the examples directory. Specify the directory if that is not the case.

**Comment by abhisrkckl** [comment]
I added those lines of code. But I am still getting the same error.
![screenshot at 2017-03-23 21-59-46](https://cloud.githubusercontent.com/assets/20718391/24258649/5438955e-0fe6-11e7-8363-b1e546393636.png)

I am working from the examples directory.

I cloned it from github and did `python setup.py install` after installing the dependencies (using pip).
I also did `make test`. It did not give any error.

**Comment by paulray** [comment]
Sorry, I meant for you to do those lines in a different cell, so the result would print.
If you don't want to add a cell then change the line to
```
print(datapath('tai2tt_bipm2015.clk'))
```
so that I can see what that call returns.

**Comment by abhisrkckl** [comment]
Here is the output:
![screenshot at 2017-03-23 22-14-11](https://cloud.githubusercontent.com/assets/20718391/24259215/286c1ffc-0fe8-11e7-8f6e-9e76acb3c045.png)

**Comment by luojing1211** [comment]
Is your PINT version up to date?

**Comment by abhisrkckl** [comment]
I installed it today.

**Comment by luojing1211** [comment]
It is very interesting that the file does not exist in your pint/datafiles. It should be downloaded if you cloned from the Nanograv/PINT git repo.

**Comment by abhisrkckl** [comment]
I just checked. tai2tt_bipm2015.clk is in the downloaded files. (where the git was cloned)

**Comment by paulray** [comment]
So, when you did the `python setup.py install` that file (and others) should have been copied into your site-packages directory with the rest of the pint package. It seems like that didn't happen for some reason.

In that notebook, what do you get from `pint.__file__`?

**Comment by abhisrkckl** [comment]
/usr/lib64/python2.7/site-packages/pint-0.5.2+68.g410a1f3-py2.7-linux-x86_64.egg/pint/__init__.pyc

**Comment by abhisrkckl** [comment]
tai2tt_bipm2015.clk is not in the corresponding datafiles directory.

**Comment by paulray** [comment]
OK, I found the bug.  Here is the diff to setup.py that will fix it:
```
diff --git a/setup.py b/setup.py
index 00519e1..77be80d 100644
--- a/setup.py
+++ b/setup.py
@@ -117,7 +117,8 @@ setup(
 
     package_data={'pint': [
         'datafiles/ecliptic.dat',
-        'datafiles/gps2utc.clk'
+        'datafiles/gps2utc.clk',
+        'datafiles/tai2tt_bipm2015.clk',
         ] + data_files},
 
     cmdclass = cmdclass,
```

I'll make the change in an upcoming pull request.

It seems that travis-ci and `make test` don't run on the installed version, but use the in-place version, so that these kinds of bugs in what files are installed are not caught.  We should try to fix that.

**Comment by abhisrkckl** [comment]
I copied the file to datafiles directory. Now it works.

Thanks.
