### ISSUE TITLE
MCMC Fitter

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#271]
It would be nice for PINT to have a Fitter that does an MCMC optimization, like event_optimize does, but for normal TOA data.

**Comment by jellis18** [comment]
@paulray, I can work on this over the next few weeks. I think we should have a basic MCMC fitter class that is then composed of the MCMC algorithm. So the MCMC algorithm would be a separate class. That way we could easily switch out different algorithms instead of coding the whole thing to use just one.

**Comment by luojing1211** [comment]
@jellis18 The fitter class is setting up the same way. But it is a inheritance not a composition. The Basic MCMC fitter can be inherited from Fitter class.

**Comment by jellis18** [comment]
@luojing1211, yes I know that but the MCMC algorithm shouldn't be built in. In other words we shouldn't have an `EmceeFitter` and `MultiNestFitter`, etc. We should have one `MCMCFitter` (or maybe something else if we want to include nested sampling) that has a set method for different MCMC samplers. To do this we would need a `Sampler` class that is subclassed to different methods. We don't have to go this way but from what I've found, this kind of setup is more flexible.

**Comment by paulthebaker** [comment]
I'm going to bump this issue, rather than start a new one.  Another way would be to have PINT include `get_likelihood()` and `get_prior()` methods.  These could be fed to the sampler of the user's choice.  

This is the way `enterprise` handles things.

**Comment by paulray** [comment]
Good timing! @jcolen is thinking about this now.
