### ISSUE TITLE
Add GLS fitter to PINT

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#273]
Add GLS fitter than does the same thing as `tempo -G`, using pre-determined noise model parameters in a generalized least squares fitter.

**Comment by jellis18** [comment]
I think we get a lot of ideas and copy some code from [libstempo](https://github.com/vallis/libstempo/blob/master/libstempo/libstempo.pyx). Take a look at the `_fit` function. All you really need is a way of reading in the noise values from the par file and the rest of the `_fit` function is the same.

**Comment by luojing1211** [comment]
What is the difference between the EQUAD and T2EQUAD. Do we need to distinguish those two parameters in PINT?

**Comment by jellis18** [comment]
@luojing1211, I'm not sure about EQUAD but we should be aware of all of the different variants. All versions of EFAC, (i.e. T2EFAC, TNEFAC) are the same. But T2EQUAD and TNEQ are both EQUADs but defined differently;

TNEQ is measured in log10 seconds and T2EQUAD is in microseconds, also they are defined as follows

TNEQ:
sigma_scaled = (EFAC^2\*sigma_old^2 + 10^(2\*TNEQ))^(1/2)

T2EQUAD:
sigma_scaled = EFAC \* (sigma_old^2 + (T2EQUAD\*1e-6)^2)^(1/2),

where sigma_old and sigma_scaled are the new and originally measured uncertainties.

In terms of ECORR, I believe the ECORR and TNECORR are the same and both measured in microseconds.

There are also lots of other components of IPTA/EPTA/PPTA data that PINT doesn't handle like the way that they do DM and the different noise parameters. We will have to talk with Lindley and others to figure it all out.

**Comment by luojing1211** [comment]
PR #334 solved this issue. Closing...
