### ISSUE TITLE
Avoid code duplication in X-ray data

### ISSUE THREAD

**Issue by matteobachetti** [nanograv/PINT#274]
`nicer_toas`, `xmm_toas` and `rxte_toas` are currently practically the same code, duplicated. I would suggest to have a generic (`Xray_FITS_TOA`?) class called by different functions that specify the correct FITS extension and keywords. This will make it easier to extend it to different satellites (e.g. NuSTAR).

**Comment by paulray** [comment]
Concur. Just have to figure out how to do it gracefully.  I did try for code reuse in putting the fits reader in fits_utils.py and the plotters in plot_utils.py. So, the individual mission codes were supposed to be what is unique to each mission, but there is still significant replication.

**Comment by matteobachetti** [comment]
One way might be to have a configuration file with entries like (just an incomplete example)
```
[rxte]
    telescop: XTE
    local_TOAs: True
    message: None

[xmm]
    telescop: XMM
    local_TOAs: False
    message: Currently only handles barycentered TOAs (produced by the SAS tool barycen)
                     Eventually should be extended to handle raw events, but that requires
                     understanding the orbit data in the XMM data products.

```
And call the relevant entries in the config in the reader

**Comment by matteobachetti** [comment]
I can work on this, if it doesn't clash with other planned PRs

**Comment by paulray** [comment]
That would be fine with me.  For photon TOAs, my focus is on getting the times correct (there are currently unresolved differences between PINT and Tempo2 answers #246 ), so I will be messing with `observatory/fermi_obs.py`.  Once I get that working, they may be some more code replication between *_obs.py that we can work on. But at the moment, I want to get it correct first, and not cause a lot of conflicts.
