### ISSUE TITLE
F2 not recognized

### ISSUE THREAD

**Issue by mdecesar** [nanograv/PINT#275]
I'm comparing the tempo and PINT 11-year results for J1024-0719.  F2 is needed for this pulsar, but is not recognized by PINT.

To read the model, I'm using model_builder:
`import pint.models.model_builder as mb`
`m = mb.get_model(parfile)`

**Comment by luojing1211** [comment]
It should be recognized.

**Comment by scottransom** [comment]
Whoa....  that shouldn't be.  I added effectively infinite freq derivs about a year ago.  Wonder what happened to those changes...  Have a bunch going on now, but will try to look into it.

**Comment by paulray** [comment]
Yep, I get the same thing when I run on the files in the 11yr release directory:
```
$ pintempo --plot par/J1024-0719_NANOGrav_11yv0.gls.par tim/J1024-0719_NANOGrav_11yv0.tim
INFO: Reading model from par/J1024-0719_NANOGrav_11yv0.gls.par [pint.scripts.pintempo]
WARNING: Unrecognized parfile line 'F2     -3.481741461371D-27  1  8.768262506078D-28' [pint.models.timing_model]

...
```

**Comment by luojing1211** [comment]
Where can I find the par files . I can fix it really quick.

**Comment by luojing1211** [comment]
I am fixing it.

**Comment by mdecesar** [comment]
Thanks @luojing1211 .  It now recognizes and fits for F2.  One small thing still to change: when I try to write the model as a parfile, it writes out all parameters except F2.

**Comment by luojing1211** [comment]
@mdecesar It has been added. Can you try it out?

**Comment by mdecesar** [comment]
@luojing1211  Strange... it is still not printing out F2 when I do `print(m.as_parfile())`.

**Comment by luojing1211** [comment]
Hmm. Could you give me the parfile?

**Comment by mdecesar** [comment]
Sure.  It's attached:
[J1024-0719_NANOGrav_11yv0.gls.par.txt](https://github.com/nanograv/PINT/files/873501/J1024-0719_NANOGrav_11yv0.gls.par.txt)

**Comment by luojing1211** [comment]
Strange, it writes out in my computer.

**Comment by mdecesar** [comment]
It's working now for me too.  Thanks!

(When I'd pulled PINT to check the first time, it said it was already up-to-date.  But I just pulled it again now and there were a few new changes.  So maybe I was just out of sync with you.)
