### ISSUE TITLE
Extracting parameter errors

### ISSUE THREAD

**Issue by mdecesar** [nanograv/PINT#285]
(1) I'm trying to extract the value and error of each parameter from the model.  To do this, I'm using "getattr":

`m = mb.get_model(parfile)`
`prefit_param_value = str(getattr(m, m.params[i]))`

Then I split the string "prefit_param_value" by "+/-" to extract the value and the error.  Is there a more straightforward way to extract these values?

(2)  If the above is the correct way to do this, then I have two suggestions:

(2a) The above works fine for most parameters.  But when writing out ELONG/ELAT, the value is written in degrees while the error is written in deg-arcmin-arcsec.  For example:

`>> m = mb.get_model(parfile)`
`>> print m.ELONG`
`ELONG (deg) 62.614061870250602 +/- 0d00m00.0001s`

I'd suggest writing out the error in degrees, or maybe in arcseconds to reduce the number of decimals needed (but in the latter case, make it clear that the error is in arcsec).  It would also help to write the error with more decimal places.  This is because currently, for some pulsars that have very small positional errors, the error on ELONG/ELAT is written out as "0d00m00.0000s".

(2b)  Have a way to extract the value of the error on any parameter.

**Comment by luojing1211** [comment]
@mdecesar 
A parameter value can be accessed by m.param.value, the error value can be accessed by m.param.uncertainty_value.

If you want to write a parameter as parfile formate. use m.param.as_parfile_line()

**Comment by paulray** [comment]
You can get the parameter value as well as the uncertainty as either an astropy `Quantity`, or a pure value like this (here f.model is a `TimingModel` object, in this case the one generated by the fit in examples/fit_NGC6440E.par):
```
In [18]: f.model.F0.quantity
Out[18]: <Quantity 61.485476554372500035 Hz>

In [19]: f.model.F0.value
Out[19]: 61.485476554372500035

In [20]: f.model.F0.uncertainty
Out[20]: <Quantity 1.8086084392781628306e-11 Hz>

In [21]: f.model.F0.uncertainty_value
Out[21]: 1.8086084392781628306e-11

```

**Comment by mdecesar** [comment]
Ok, thanks!  I'd been using f.model.F0.value, but didn't know about .quantity and .uncertainty.

I also want to be able to extract values in a loop, but you can't do something like
`f.model.params[i].quantity`
That's why I was using `str(getattr(m,m.params[i]))` -- it allows me to loop through `m.params`.  So I was wondering if there's a way to extract these values using a variable f.model.params[i] rather than specifying a single parameter like f.model.F0.  (Sorry, I think this is turning into a question that's more about python than PINT specifically!)  It's not a big deal if there's not a simple way to do this.

**Comment by paulray** [comment]
Hi @mdecesar, I just do something like this:
```
In [9]: for p in m.params:
   ...:     print(p,getattr(m,p).quantity)
   ...:     
('PSR', '1748-2021E')
('PLANET_SHAPIRO', False)
('POSEPOCH', <Time object: scale='utc' format='pulsar_mjd' value=53750.0>)
('PX', <Quantity 0.0 mas>)
('RAJ', <Angle 17.814652777777777 hourangle>)
('DECJ', <Angle -20.358055555555556 deg>)
('PMRA', <Quantity 0.0 mas / yr>)
('PMDEC', <Quantity 0.0 mas / yr>)
('DM', <Quantity 223.9 pc / cm3>)
('F0', <Quantity 61.485476554000000001 Hz>)
('F1', <Quantity -1.181e-15 Hz / s>)
('TZRMJD', <Time object: scale='tdb' format='pulsar_mjd' value=53801.3860512>)
('PEPOCH', <Time object: scale='tdb' format='pulsar_mjd' value=53750.0>)
```

**Comment by paulray** [comment]
Is there any issue left here, or can this be closed?
