### ISSUE TITLE
TypeError from model builder

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#286]
In some situations, I am getting the following error when calling `get_model()`:

```
In [11]: m2 = mb.get_model(parfile)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-ac01b13fd66d> in <module>()
----> 1 m2 = mb.get_model(parfile)

/Users/paulr/src/PINT/pint/models/model_builder.pyc in get_model(parfile)
    279     name = os.path.basename(os.path.splitext(parfile)[0])
    280 
--> 281     mb = model_builder(name,parfile)
    282     return mb.model_instance

/Users/paulr/src/PINT/pint/models/model_builder.pyc in __init__(self, name, parfile)
     86             self.parfile = parfile
     87             self.get_comp_from_parfile(self.parfile)
---> 88             self.get_model_instance(self.parfile)
     89 
     90     def __str__(self):

/Users/paulr/src/PINT/pint/models/model_builder.pyc in get_model_instance(self, parfile)
    208         """
    209         if self.model_instance is None:
--> 210             model = self.build_model()
    211 
    212         self.model_instance = model()

/Users/paulr/src/PINT/pint/models/model_builder.pyc in build_model(self)
    168             raise(RuntimeError("No timing model components selected."))
    169 
--> 170         return generate_timing_model(self.name,tuple(self.select_comp))
    171 
    172     def add_components(self,components):

/Users/paulr/src/PINT/pint/models/timing_model.pyc in generate_timing_model(name, components, attributes)
    812     attributes['components'] = cps
    813 
--> 814     return type(name, components, attributes)
    815 
    816 class TimingModelError(Exception):

TypeError: type() argument 1 must be string, not unicode
```

This actually happens for me if I start ipython in the examples directory and type `run fit_NGC6440E.py`.  The same script runs fine if I invoke it from the command line using `python fit_NGC_6440E.py`.  

The problem comes from the name being a unicode string instead of a normal string.  This results from __file__ being a normal string usually, but when run from ipython, it is a unicode string. I have no idea why.  

In any case, someone should be able to go into ipython and run our example without it failing!

**Comment by paulray** [comment]
@matteobachetti, do you know why `__file__` is a unicode string in ipython2.7? I looked at your wiki page on [python compatibility](https://github.com/nanograv/PINT/wiki/Python-Compatibility) and there is a note about adding stuff about `str()` at some point. I'm about to merge #287. When that is merged, could you test `examples/fit_NGC6440E.py` in python3 and ipython3?

**Comment by matteobachetti** [comment]
@paulray it's strange indeed. Sure, go ahead and I will test it

**Comment by paulray** [comment]
Cool.  Everything is merged now. Hopefully the examples work in Python 2 and Python 3. This is something that doesn't get tested with travis.

**Comment by matteobachetti** [comment]
@paulray everything works with both ipython and python (3.5). I'm supposed to see one window with the (sinusoidal-ish) pre-fit residuals and one with flat-ish post-fit residuals, right?

**Comment by paulray** [comment]
Yep, great!  Closing this.
