### ISSUE TITLE
Improvements to residuals.py

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#290]
Two places where the `resids()` class could be improved:
* `get_PSR_freq()` should not compute the frequency from pulling out F0 from the model, but should use `m.d_phase_d_toa()` like zima.py does.
* If you are working in ipython or a notebook, it would be nice to fiddle with the TOAs (e.g. clipping some out using the new selection API) or the model (e.g. manually changing a parameter value) and have the residuals update. Currently you have to build a new residuals class.  Should we add a `resids.update()` method that recomputes everything? Or do people prefer the current way, where resids are basically immutable?

**Comment by paulray** [comment]
This has some overlap with issue #100

**Comment by jcolen** [comment]
Was this issue solved with my July 2 commit?

**Comment by paulray** [comment]
I think it is, except maybe we want to expose the modelF0 option. Currently there is no way to use it. Maybe it could be a keyword argument when initializing a residuals object, which would default to False.

**Comment by aarchiba** [comment]
Maybe a separate bug for usability in the notebook? Immutable objects are not particularly a problem as long as creating them is convenient and not too expensive.
