### ISSUE TITLE
Add solar wind dispersion model

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#291]
PINT does not yet support a solar wind dispersion model, I believe.

I think this is specified by the `NE_SW` or `SOLARN0` parameters in par files, but I don't know what the difference between those two are.

**Comment by demorest** [comment]
`NE_SW`, `SOLARN0` and `NE1AU` are all aliases for the same thing.  They refer to a simple solar wind model that assumes electron density falls off like 1/r^2, where r is distance from the Sun.  The parameter gives the proportionality constant, in units of electrons per cc at r = 1 AU.  tempo2 accepts all three parameter names, while tempo only uses `SOLARN0`.

Tempo2 at one point had a more complex model that used some solar observatory data as input, but I don't think it's been maintained with up to date data (but note I haven't looked into this in at least a couple years).

**Comment by paulray** [comment]
Thanks for the explanation! We should make sure that PINT can easily accommodate dispersion measure contributions from the solar wind, interstellar medium and intrabinary medium in the model framework.
