### ISSUE TITLE
`make test`   fails 

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#292]
I am trying to install in Fedora 23.

`make install`  worked without any issue.

However, `make test` fails with the following error. (please see attachment - I have saved stderr output to test1_err.txt and stdout output to test1_out.txt.)

[test1_err.txt](https://github.com/nanograv/PINT/files/886062/test1_err.txt)
[test1_out.txt](https://github.com/nanograv/PINT/files/886063/test1_out.txt)

**Comment by jellis18** [comment]
Hi @abhisrkckl,

I'm not sure but after some googling it could be that you are missing `openssl`. You can get it with `yum install openssl openssl-devel`.

**Comment by paulray** [comment]
Has this been fixed?  It looks like some of it may be related to astropy, and I noticed that @abhisrkckl is running astropy 1.3.2, which I have not tried yet.  Could there be an issue there?

**Comment by abhisrkckl** [comment]
I installed `openssl` and `openssl-devel`.   I am still getting the same error messages.

I had installed PINT successfully on the same machine few days ago when it was running fedora 25. (If that is relevant)

**Comment by paulray** [comment]
Can you start python or ipython and run the following:
```
import astropy
print astropy.__version__
from astropy.coordinates.matrix_utilities import rotation_matrix
```
and also let us know what version of python you are running. When you start it, you should see a string like: `Python 2.7.13 (default, Dec 18 2016, 05:35:35)`

**Comment by paulray** [comment]
@abhisrkckl have you tracked this down? I just updated to astropy 1.3.2 and no problems cropped up, so I'm not sure what the issue is.

**Comment by abhisrkckl** [comment]
@paulray  Here is the output for the commands you mentioned.

`>>> import astropy
>>> print astropy.__version__
1.1.1
>>> from astropy.coordinates.matrix_utilities import rotation_matrix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/astropy/coordinates/matrix_utilities.py", line 9, in <module>
    from ..utils.compat.numpy import matmul
ImportError: cannot import name matmul`

It seems that I was running an older version of astropy. I tried `pip install astropy  --upgrade`. Now it works.

**Comment by paulray** [comment]
Great, glad that fixed it!

It was hard to diagnose since the test1_out.txt file attached above showed this:
```
Searching for astropy>=1.3
Best match: astropy 1.3.2
```
which led me to believe you were running 1.3.2. I guess that was just pip being confusing.
