### ISSUE TITLE
Comparing PINT and tempo:  JUMP and differences in residuals for J2234+0944

### ISSUE THREAD

**Issue by mdecesar** [nanograv/PINT#302]
This is related to issue #301.

Doing the same comparisons as in issue #301, we found that these few 430 MHz TOAs are offset from the L- and S-band TOAs of J2234+0944.  This MSP has a very large JUMP between 430 MHz and L-band, due to its template being offset in phase between these two frequency bands.  From its 11-year parfile:

`JUMP -fe 430      -0.001162866  1       0.000013803`

David Nice and I are not sure that the offset in residuals results from the value of JUMP2 in PINT vs. tempo, but it's our first guess.

How does PINT handle JUMPs?  In PINT, are JUMPs due to template offsets handled in the phase or time reference frame?

My understanding is that tempo handles all JUMPs in the time reference frame; however, it is more correct to consider cable lengths in the time frame, but template offsets in the phase frame.  Perhaps PINT is handling JUMPs more correctly than tempo, leading to this discrepancy in residuals?

I've attached the plots for J2234+0944.  To accompany the plot legends (same as for issue #301):
- The residual plots show (postfit resids - prefit resids), with frequency bands color-coded as in the legend. For long datasets, the periodic nature becomes more apparent with GUPPI/PUPPI, so we include plots that zoom in on those epochs.
- For the parameter comparison plots: (1) Blue stars show the absolute value of the PINT-fitted parameter value subtracted from the tempo-fitted parameter value, divided by the tempo-fitted parameter value's 1-sigma error bar. (2) We ran 10 iterations of tempo for isolated MSPs, and 50 iterations for binary MSPs. Orange x's show the same as the blue stars, but compared to the multiple-iteration tempo-fitted values rather than single-iteration. (3) The green crosses show the same comparison for parameter values from tempo vs. values from multiple-iteration tempo runs. We did this to check if differences between PINT and tempo are affected by tempo having been run for too few iterations, and find that this is not the case.

[tempovspint_J2234+0944.pdf](https://github.com/nanograv/PINT/files/914385/tempovspint_J2234.0944.pdf)

**Comment by luojing1211** [comment]
> How does PINT handle JUMPs? In PINT, are JUMPs due to template offsets handled in the phase or time reference frame?

PINT handles the jump only using time delay term right now. But there is a discussion to model it in phase term.

**Comment by aarchiba** [comment]
Is this a known incompatibility, then? Perhaps it could be documented? (And a known-fail test written to demonstrate it and let us know whether we've fixed it.) Then either a known-incompatibility tag could be added to this and similar bugs or we could close it and rely on the known-fail test to remind us that something needs fixing.

**Comment by abhisrkckl** [comment]
Can this be closed?
