### ISSUE TITLE
Error computing ICRS from Ecliptic coords

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#304]
In the latest PINT (0.5.2+119.g8d31238.dirty), I was trying to compute the ICRS position from a model which is defined in terms of ecliptic coords:

```
In [7]: import pint.models as models
In [8]: PSR=mb.get_model('1641+8049.par')
In [9]: PSR.coords_as_ICRS()
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-45-e8057ed5a463> in <module>()
----> 1 model.coords_as_ICRS()

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pint-0.5.2+119.g8d31238-py2.7-macosx-10.10-x86_64.egg/pint/models/timing_model.pyc in get_cached_result(*args, **kwargs)
     63             # without caching it.
     64             log.debug(" ... no cache found")
---> 65             return function(*args, **kwargs)
     66         return get_cached_result
     67 

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pint-0.5.2+119.g8d31238-py2.7-macosx-10.10-x86_64.egg/pint/models/astrometry.pyc in coords_as_ICRS(self, epoch)
    370                              "Check your pint/datafile/ecliptic.dat file.")
    371 
--> 372         pos_ecl = PulsarEcliptic(lon=self.ELONG.quantity+dELONG, lat=self.ELAT.quantity+dELAT)
    373 
    374         return pos_ecl.transform_to(coords.ICRS)

UnboundLocalError: local variable 'dELONG' referenced before assignment
```

I think the fix is quite simple:
in https://github.com/nanograv/PINT/blob/master/pint/models/astrometry.py line 372 should be moved up into the `else` block above.  Or at least that works on my local copy (sorry I'm not set up for pull requests).

This was with a pretty generic par file, which I can supply if needed.

**Comment by paulray** [comment]
I have other questions about that function.
* Does it work if the model has PMRA and PMDEC?
* Why does it need to check self.ECL.value? I presume that is needed for the transform_to statement later.  Is that not guaranteed to be set somewhere else? It seems strange for this utility method to have to check it.
* The fix seems to be to put the PulsarEcliptic line in both the if and the else, one with the dELAT/dELONG values and one without.

**Comment by paulray** [comment]
Oh, and we should rip out that old Cache code, as we've discussed on telecons before.

**Comment by paulray** [comment]
And, any PR to fix this should include unit tests using models that specify position and proper motion in RAJ/DECJ and ELONG/ELAT (and LAMBDA/BETA if PINT accepts those as synonyms)

**Comment by dlakaplan** [comment]
Regarding your 3rd question (about a proposed fix): 
Yes, the `pos_ecl` line appears twice.  So you could either include it twice or just define `dELONG` and `dELAT` to be 0 in the `if` and then only have it once.

**Comment by luojing1211** [comment]
Hi @paulray About the question you have asked. 

> - Does it work if the model has PMRA and PMDEC?

No. It only accepts PMELONG and PMELAT. Should we have a mixed system? 
> - Why does it need to check self.ECL.value? I presume that is needed for the transform_to statement later. Is that not guaranteed to be set somewhere else? It seems strange for this utility method to have to check it.
We could set this up in the setup(). But my concern is that if someone change the ECL value on the fly, we have to make sure it gets changed and report the right error message. Maybe there is a better way to do it. 
> - The fix seems to be to put the PulsarEcliptic line in both the if and the else, one with the dELAT/dELONG values and one without.

It is a good suggestion. We can fix this.

**Comment by luojing1211** [comment]
@paulray  Could you tell me more about the unittest proposal? What kind of comparisons should we do?

**Comment by paulray** [comment]
Hi,

I do not think we should allow mixed specifications. If the coordinates are specified as RAJ/DECJ then trying to set PMELONG should probably raise an exception.

Both types of Astrometry models have coords_as_ICRS defined, so my only point was that a unit test should test that coords_as_ICRS works for models in RAJ/DECJ and ELAT/ELONG, in both cases including proper motion in the model. Also, if we allow LAMBDA/BETA as synonyms, we should test that the code still works if those are used in setting up the model.

**Comment by swiggumj** [comment]
@paulray @dlakaplan I think this issue can be closed...? More development towards allowing different parameter mixtures is contained in #654 (I think) -- see my recent comment there.
