### ISSUE TITLE
"make docs" error, and installing packages with macports

### ISSUE THREAD

**Issue by mdecesar** [nanograv/PINT#311]
When installing PINT on David Nice's and our collaborator's laptops, we ran into this error with "make docs":

>> make docs
rm -f docs/pint*.rst
rm -f docs/modules.rst
sphinx-apidoc -o docs/ -M pint
make: sphinx-apidoc: No such file or directory
make: *** [docs] Error 1

Also, David uses macports for a lot of his software, so he said it would be helpful to have a section in the installation instructions with a list of which prerequisite packages are available via "mac ports", so that the user can install those before running the "pip install -r requirements.txt" command.

**Comment by paulray** [comment]
What version of Sphinx are they using?  Sphinx>=1.5.2 is specified in requirements_dev.txt. Did they install that?

**Comment by paulray** [comment]
The PINT install docs do specify which things can be installed by MacPorts:
http://nanograv-pint.readthedocs.io/en/latest/installation.html#prerequisites

**Comment by mdecesar** [comment]
Oh whoops, I guess he didn't see that -- sorry!  We'll get back to you about his Sphinx version.

**Comment by paulray** [comment]
Also, hopefully `make docs` isn't really needed.  The current docs are always available online.

**Comment by mdecesar** [comment]
Yeah, I don't think it's really needed.  Just wanted to report that they had trouble with it.

Re: Sphinx:  He has 1.5.6, installed from macports.

**Comment by paulray** [comment]
What do they get from this command?
```
% which sphinx-apidoc
/opt/local/bin/sphinx-apidoc
```

**Comment by aarchiba** [comment]
Seems like this is not, or no longer, an active bug - can it be closed?
