### ISSUE TITLE
cannot download datafile

### ISSUE THREAD

**Issue by xuhenghb** [nanograv/PINT#316]
I don’t know why I can’t download several datafile, especially the  jpl data.

So I recommend that you include all the datafile in the software, because I don’t know weather other people also encounter this problem too.

Thank you!

**Comment by luojing1211** [comment]
It is a good point. To fix this problem for now, you can download those JPL
files separately and put them in PINT/pint/datafiles directory.

By the way can you send me the error messages?

-Jing Luo

**Comment by xuhenghb** [comment]
Could you give me your email, and  I say that by email?

**Comment by paulray** [comment]
Note that I don't think we want to include large datafiles in the PINT github repo.

**Comment by paulray** [comment]
I'm going to close this, but @luojing1211 I think we should have some documentation on what files to download and where to put them for people who can't use the automatic download facility for some reason.

**Comment by luojing1211** [comment]
I agree. Maybe on the GitHub page? Or we can put a test for auto-downing.
If the runtime is too much, we can report to the user.

**Comment by paulray** [comment]
Yes, a wiki page on this would be good, so we could point people to that for instructions on how to set up to run PINT even when offline.
