### ISSUE TITLE
Can't load DE430 ephemeris

### ISSUE THREAD

**Issue by jellis18** [nanograv/PINT#326]
So I just got a new computer and have done a fresh install of PINT and for some reason get_TOAs fails when I try to use DE430, it works for DE421, DE435, etc. I just get
```python
INFO: Compute positions and velocities of observatories and Earth (planets = False), using DE430 ephemeris [pint.toa]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-b446da766370> in <module>()
----> 1 toas = toa.get_TOAs('B1855+09_NANOGrav_9yv1.tim', ephem='DE430')

/Users/jaellis/.virtualenvs/enterprise/lib/python2.7/site-packages/pint/toa.pyc in get_TOAs(timfile, ephem, include_bipm, include_gps, planets, usepickle)
     57     if 'ssb_obs_pos' not in t.table.colnames:
     58         log.info("Computing observatory positions and velocities.")
---> 59         t.compute_posvels(ephem, planets)
     60     # Update pickle if needed:
     61     if usepickle and updatepickle:

/Users/jaellis/.virtualenvs/enterprise/lib/python2.7/site-packages/pint/toa.pyc in compute_posvels(self, ephem, planets)
    781             site = get_observatory(obs)
    782             tdb = time.Time(grp['tdb'])
--> 783             ssb_obs = site.posvel(tdb,ephem)
    784             ssb_obs_pos[loind:hiind,:] = ssb_obs.pos.T.to(u.km)
    785             ssb_obs_vel[loind:hiind,:] = ssb_obs.vel.T.to(u.km/u.s)

/Users/jaellis/.virtualenvs/enterprise/lib/python2.7/site-packages/pint/observatory/topo_obs.pyc in posvel(self, t, ephem)
    171     def posvel(self, t, ephem):
    172         if t.isscalar: t = Time([t])
--> 173         earth_pv = objPosVel_wrt_SSB('earth', t, ephem)
    174         obs_topo_pv = topo_posvels(self.earth_location_itrf(), t, obsname=self.name)
    175         return obs_topo_pv + earth_pv

/Users/jaellis/.virtualenvs/enterprise/lib/python2.7/site-packages/pint/solar_system_ephemerides.pyc in objPosVel_wrt_SSB(objname, t, ephem, path, link)
    123             is_load = _load_kernel_local(ephem, path=path_str)
    124         if not is_load:
--> 125             raise ValueError("Can not load the ephemeris file '%s.bsp'. " % ephem)
    126     else:
    127         path_str = path

ValueError: Can not load the ephemeris file 'de430.bsp'. 
```
I didn't get this error before and I don't get it in `travis` testing for `enterprise`. Any thoughts?

**Comment by luojing1211** [comment]
Hi Justin, 
Do you have your internet connected. It should try to search online and than search local.

**Comment by jellis18** [comment]
Yes, it searches and downloads for all other ephemerides but not DE430. It is maybe expecting DE430t.bsp?

**Comment by luojing1211** [comment]
DE430 is not in the nasa ftp site. But it should in the NASA NAIF site. So it should work. I bet de430t.bsp should be able to work.

**Comment by jellis18** [comment]
Yes using `ephem='DE430T'` works. For some reason it isn't looking at the NAIF site on my computer. As I said this always worked before...

**Comment by paulray** [comment]
Is there anything we can do to fix this, or should we just leave it, since DE430T works?  Maybe we should emit a log.warning() if 'DE430' is specified (or any ephemeris where we know there is a "T" version but not a plain version.  When the T versions exist, they are certainly preferred, I believe.

**Comment by luojing1211** [comment]
Hi Justin, 
First of all, this never happen to me. But I know you are not the only one. The reason is that 'DE430.bsp' is in the NASA NAIF current ephemeris link, which is the default for astropy. But somehow you astropy does not look at it. So I add the link to fix this problem. Can you check out the branch I have [here](https://github.com/luojing1211/PINT/tree/fix_de430_ephemeris_issue) and test it out?

**Comment by scottransom** [comment]
@paulray Why should the "T" versions be preferred?  Do we really know that that is the case?

**Comment by paulray** [comment]
I think they are the same but just have the additional information in them (TT-TDB column), which may be useful.

**Comment by paulray** [comment]
As a note, Deepto just added support for DE430T to the barycorr tool in HEASOFT, so NICER analysis can take advantage of new ephemerides than DE405, and potentially use the TT-TDB column as well, though so far the tools don't actually use that column.

**Comment by jellis18** [comment]
I don't actually think there is any problem with PINT. It looks like it is a problem with MacOS Sierra and openssl. I'm trying to figure it out now but if I manually try to load the ephemeris I get

```python
aut.data.download_file('https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430.bsp', timeout=50)

---------------------------------------------------------------------------
URLError                                  Traceback (most recent call last)
<ipython-input-6-bf1812fa69c7> in <module>()
----> 1 aut.data.download_file('https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430.bsp', timeout=50)

/Users/jaellis/.virtualenvs/pint/lib/python2.7/site-packages/astropy/utils/data.pyc in download_file(remote_url, cache, show_progress, timeout)
   1095             e.reason.strerror = e.reason.strerror + '. requested URL: ' + remote_url
   1096             e.reason.args = (e.reason.errno, e.reason.strerror)
-> 1097         raise e
   1098     except socket.timeout as e:
   1099         # this isn't supposed to happen, but occasionally a socket.timeout gets

URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
```

**Comment by jellis18** [comment]
OK, I solved this problem. As I said its not a problem with PINT but with MacOS Sierra and openssl. The solution is to install openssl and install a non-system python.
