### ISSUE TITLE
FD fails with infinite freq TOAs

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#328]
When I feed NICER photon TOAs to a `model.phase()` where the model has an FD parameter, I get nans in the output and a warning about invalid values.  This must come from evaluating the log of the observing frequency, which is infinity.  This should be made more robust so that the FD delay is just 0.0 if the frequency is infinity.

**Comment by luojing1211** [comment]
I will fix it shortly.

**Comment by luojing1211** [comment]
PR #329 should fix this problem.
