### ISSUE TITLE
TDB times computed from spacecraft-based TOAs are wrong by a couple microseconds

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#330]
This is just a reminder that the TT to TDB conversion for spacecraft-based TOAs is still not quite correct. The results are off by a couple of microseconds because it isn't computing the topocentric term correctly.  This is supposed to be a dot product of the spacecraft barycentric velocity and the geocenter->observatory vector.  This isn't quite working as PINT currently lets astropy do the TT to TDB conversion with location=None. This needs to be fixed.

**Comment by luojing1211** [comment]
PR #335 is merged. 
@paulray  can you test it out and see if PR #335 fixes this issue?

**Comment by paulray** [comment]
I found this bug. It is in compute_TDBs() in toa.py
When it groups the TOA table by observatory, it assumes that all TOAs from the same observatory share a same location. This is NOT true for spacecraft TOAs!
Here is the offending snippet of code:
```        # Compute in observatory groups
        tdbs = numpy.zeros_like(self.table['mjd'])
        for ii, key in enumerate(self.table.groups.keys):
            grp = self.table.groups[ii]
            obs = self.table.groups.keys[ii]['obs']
            loind, hiind = self.table.groups.indices[ii:ii+2]
            site = get_observatory(obs)
            ### BUG BUG! This is wrong if the observatory is not at a fixed ITRF location!
            grpmjds = time.Time(grp['mjd'], location=grp['mjd'][0].location)
            grptdbs = site.get_TDBs(grpmjds, method=method, ephem=ephem)
            tdbs[loind:hiind] = numpy.asarray([t for t in grptdbs])
```

Now, how to fix it?

We don't want to revert to looping through every single TOA, calling t.tdb for each one. That would be horribly slow.

**Comment by paulray** [comment]
Ah, the location attribute can be an array, one for each input time. That should solve it!

**Comment by paulray** [comment]
Nope.  The docstring for `astropy.Time` says this:
```    
location : `~astropy.coordinates.EarthLocation` or tuple, optional
        If given as an tuple, it should be able to initialize an
        an EarthLocation instance, i.e., either contain 3 items with units of
        length for geocentric coordinates, or contain a longitude, latitude,
        and an optional height for geodetic coordinates.
        Can be a single location, or one for each input time.
```
but the code is this, which does not seem to support a list or array of locations:

```    
def __init__(self, val, val2=None, format=None, scale=None,
                 precision=None, in_subfmt=None, out_subfmt=None,
                 location=None, copy=False):

        if location is not None:
            from ..coordinates import EarthLocation
            if isinstance(location, EarthLocation):
                self.location = location
            else:
                self.location = EarthLocation(*location)
        else:
            self.location = None
```

**Comment by paulray** [comment]
@scottransom am I right that the above is a bug in astropy (a mismatch between the documentation for Time and the actual implementation).  Should I report this to astropy?

Given the bug, I can't figure out how to initialize a Time object with an array of times, each with their own location. If I can't do that, the t.tdb won't work for spacecraft times. The alternative might be to loop over all times calling t.tdb for every time, but that will be really slow for many photon TOAs. Any creative ideas?
