### ISSUE TITLE
error when making a polyco table

### ISSUE THREAD

**Issue by respiewak** [nanograv/PINT#338]
UnitsError raised when running Polyco.generate_polycos

polycos.py Line 496 should be 
`rdcPhase = rdcPhase.int-(dt.value*model.F0.value*60.0)*u.cycle+rdcPhase.frac` 
to match units

**Comment by paulray** [comment]
Hmm. I didn't even realize we had polyco generation implemented!  Adding that support is issue #24 that is still open.  @luojing1211 is it working?  If so, we should add an example of how to use it and make sure it has unit tests.  Checking in `examples`, there are no polyco usages in the scripts or notebooks, and in the tests dir only `test_d_phase_d_toa.py` uses polyco reading, but nothing uses polyco generation.

**Comment by luojing1211** [comment]
Good catch @respiewak. @paulray It was working but when we changed the phase unit, it gives the bug above. But I complete agree with you about the unit test and example. Maybe a script for generating and using polycos.

**Comment by respiewak** [comment]
I've been looking at this quite a bit to understand exactly how the functions work, and I've noticed a few more things that need to be changed. Most are minor, and one or two might be due to my misunderstandings of how things work, but I could potentially help with that example script.

**Comment by paulray** [comment]
@respiewak thanks! Providing a script or notebook that loads a model, computes polycos, saves them to a file, then loads the file and uses them for an example phase calculation would be great!  We could put that in the examples directory, and a similar script could compare to a polyco.dat made by TEMPO or Tempo2 as a test.  Note that at the moment PINT does not properly support TZRSITE and TZRFRQ (hmm, I don't see an explicit issue for this, so we should probably make a new one) so any comparisons should be done using a par file that has TZRSITE @ and TZRFRQ 0.0.

**Comment by luojing1211** [comment]
@respiewak It is great that you can help! If you can make pull request, it will make this a lot easy. 
Again thank you so much.

**Comment by respiewak** [comment]
@luojing1211 I'm still new to git and have never done a pull request before, but I'm trying to figure it out, and we'll see how well it goes. 

Some bugs that I haven't been able to sort out include `Polycos.write_polyco_file()` and `Polycos.read_polyco_file()`, which don't seem to work at all. I've been able to use `tempo_polyco_table_writer()` and the reader, at least. In addition, `Polycos.generate_polycos()` takes "maxha" as an argument, but doesn't use it at all, and I don't know enough about polycos to figure out how it fits in.

**Comment by paulray** [comment]
Renee, if the git stuff is too painful, feel free to just email any of us with patches, and we can commit them. If you want to try to go through the git process, this wiki page has the steps I use:
https://github.com/nanograv/PINT/wiki/Git-Workflow

**Comment by scottransom** [comment]
@respiewak  I'd recommend the git thing....  github's interface makes pull requests super simple as long as you fork the project.  So the super quick instructions are:
1.  Fork the project you are working on (i.e. press the fork button on that page)
2.  Clone your version of that project from your github page
3.  Do your work and commit it locally.
4.  git push it back to github
5.  On your github page for the project, there should now be a "Make Pull Request" green button which will basically do everything for you.

Thanks for working on PINT!  :-)

**Comment by respiewak** [comment]
@luojing1211 or someone else who might know how the current polyco module works: `Polycos.find_entry(t)` tries to grab `self.polycoTable['t_start']` and fails, and I can see that that does not exist as a column in the table. I'm not sure, however, how that column is supposed to be created or when. 'tmid' exists as a column, so maybe that could be used in the function?

**Comment by luojing1211** [comment]
Are you using tempo1 style polyco file?

**Comment by respiewak** [comment]
I just made a polyco table from a par file, using `generate_polycos()`, so I would have assumed it would have all of the necessary information, but it apparently didn't have that key. I was able to make a work-around for my purposes, but I wonder if it might be better to change the generation of the polyco table such that it includes that information.

**Comment by respiewak** [comment]
I see now that reading in a polyco file would result in the correct information in the table, so maybe I'll work on modifying `generate_polycos()` to have the same information.

**Comment by luojing1211** [comment]
Thank you Renee. I am glad you found this bug. If you have question, please leave comments on here. I will work with you to fix it tomorrow.

**Comment by respiewak** [comment]
I was able to make something that works (at least for me). Should I make a pull request now, or continue working on this module and find more bugs? I haven't yet sorted out what I *want* to be able to do, so I may spot more while I do so.

**Comment by luojing1211** [comment]
In the case of bug fixing. I think small pull request is easier to manage. So I would say a pull request now. If you push more commits, it will get updated.

**Comment by paulray** [comment]
@respiewak what happened on this?  A pull request would be most welcome.

**Comment by respiewak** [comment]
My apologies for the delay. I had to put this on hold for a while, but I can try to sort out what I had done and whether or not it worked. I'll make a pull request with what I have, though.

**Comment by luojing1211** [comment]
Thank you Renee. Once you open the pull request. We can have a discussion
there.

**Comment by luojing1211** [comment]
I think this is fixed and should be closed.
