### ISSUE TITLE
Noob problems

### ISSUE THREAD

**Issue by produit** [nanograv/PINT#341]
Hi,
I just heard about PINT in Head meeting in Sun Valley.
I am very interested to use PINT.
I want first to put my detector in PINT.
My detector is on the Tiangong 2 Chinese space station, so I will have to teach this to PINT
(help welcome).
I installed PINT but I have some intial problems explained here:

Running make test give me those warnings (do I have to worry?):
WARNING: Unrecognized parfile line 'EPHVER         5' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'MODE 1' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'T2CMETHOD      TEMPO' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'NE_SW          0.000' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'CHI2R          2.1896 637' [pint.models.timing_model]
..WARNING: Unrecognized parfile line 'SOLARN0               0.00' [pint.models.timing_model]
and some others...
later:
WARNING: Unrecognized parfile line 'NE_SW          0.000' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'CHI2R          2.1896 637' [pint.models.timing_model]
....................ERROR: String this is a string can not be converted toa time object. [pint.models.parameter]
.............WARNING: Unrecognized parfile line 'SOLARN0               0.00' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'T2CMETHOD           TEMPO' [pint.models.timing_model]

...
WARNING: Unrecognized parfile line 'T2CMETHOD           TEMPO' [pint.models.timing_model]
.
----------------------------------------------------------------------
Ran 88 tests in 568.533s

OK

Running the example:
produit@yoga$ pintempo --plot J0613-sim.par J0613-sim.tim
INFO: Reading model from J0613-sim.par [pint.scripts.pintempo]
WARNING: Unrecognized parfile line 'SOLARN0               0.00' [pint.models.timing_model]
INFO: Reading TOAs [pint.scripts.pintempo]
INFO: Applying clock corrections. [pint.toa]
INFO: Observatory gbt, loading clock file /usr/local/lib/python2.7/dist-packages/pint-0.5.3+12.g6eee96d-py2.7-linux-x86_64.egg/pint/datafiles/time.dat [pint.observatory.topo_obs]
INFO: Observatory gbt, loading GPS clock file /usr/local/lib/python2.7/dist-packages/pint-0.5.3+12.g6eee96d-py2.7-linux-x86_64.egg/pint/datafiles/gps2utc.clk [pint.observatory.topo_obs]
INFO: Observatory gbt, loading BIPM clock file /usr/local/lib/python2.7/dist-packages/pint-0.5.3+12.g6eee96d-py2.7-linux-x86_64.egg/pint/datafiles/tai2tt_bipm2015.clk [pint.observatory.topo_obs]
INFO: Getting IERS params and computing TDBs. [pint.toa]
INFO: Computing TDB columns. [pint.toa]
INFO: Computing observatory positions and velocities. [pint.toa]
INFO: Compute positions and velocities of observatories and Earth (planets = False), using DE421 ephemeris [pint.toa]
INFO: Adding columns ssb_obs_pos ssb_obs_vel obs_sun_pos [pint.toa]
INFO: Fitting... [pint.scripts.pintempo]
Best fit has reduced chi^2 of 1.05208991518
RMS in phase is 0.00168985012341 cycle
RMS in time is 5.17405761013 us
Traceback (most recent call last):
  File "/usr/local/bin/pintempo", line 9, in <module>
    load_entry_point('pint==0.5.3+12.g6eee96d', 'console_scripts', 'pintempo')()
  File "/usr/local/lib/python2.7/dist-packages/pint-0.5.3+12.g6eee96d-py2.7-linux-x86_64.egg/pint/scripts/pintempo.py", line 54, in main
    t.get_errors().to(u.us).value, fmt='o')
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1814, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 2978, in errorbar
    barcols.append(self.vlines(xo, lo, uo, **lines_kw))
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1814, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 1066, in vlines
    x = np.ravel(x)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 1487, in ravel
    return asanyarray(a).ravel(order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 533, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
ValueError: setting an array element with a sequence.

**Comment by produit** [comment]
Sorry I forgot:
produit@yoga$ python --version
Python 2.7.12
produit@yoga$ uname -a
Linux yoga 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
>>> print pint.__version__
0.5.3+12.g6eee96d
>>> print pint.__file__
/usr/local/lib/python2.7/dist-packages/pint-0.5.3+12.g6eee96d-py2.7-linux-x86_64.egg/pint/__init__.pyc

And url:
 https://travis-ci.org/nanograv/pint/pull_requests

does not work

**Comment by luojing1211** [comment]
Thanks for being interested in PINT @produit. You feed back is very important to us. I can explain the questions you had above. 
1. The Unrecognized parameter warning
    Since PINT is a very new pulsar timing software, there are some models has not built-in. So those warning in the tests are expected. But with future development, it should disappear. 

2. The Pintempo issue, 
    It is actually a bug. Thank you for reporting it. We will fix it shortly.

**Comment by luojing1211** [comment]
#342 Fixes the issue No. 2

**Comment by produit** [comment]
Hi,
thanks for the bug fix.
I don't know how to use the correction.
I did a git pull
but did not get anything.
during the make test there is also that:
WARNING: Unrecognized parfile line 'CHI2R          2.1896 637' [pint.models.timing_model]
....................ERROR: String this is a string can not be converted toa time object. [pint.models.parameter]
.............WARNING: Unrecognized parfile line 'SOLARN0               0.00' [pint.models.timing_model]

and:
WARNING: Unrecognized parfile line 'MODE                1' [pint.models.timing_model]
./usr/local/lib/python2.7/dist-packages/astropy/units/quantity.py:1059: RuntimeWarning: invalid value encountered in true_divide
  return super(Quantity, self).__truediv__(other)

**Comment by luojing1211** [comment]
We did not merge it. But try it now.

**Comment by luojing1211** [comment]
It the problem of  Pintempo issue fixed on your computer @produit ?

**Comment by produit** [comment]
Hi,
sorry.
Yes I think this specific problem is ok now.
But:
in page:
http://nanograv-pint.readthedocs.io/en/latest/contributing.html#pull-request-guidelines
The URL is still wrong, as you say it should be:
https://travis-ci.org/nanograv/PINT/pull_requests
In the make test there is still several error:
first this message:
....................ERROR: String this is a string can not be converted toa time object. [pint.models.parameter]

Some missing files ?
======================================================================
ERROR: test_astropy_ephem (test_TDB_method.TestTDBMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/produit/PINT/tests/test_TDB_method.py", line 22, in test_astropy_ephem
    t_astropy = toa.get_TOAs(self.tim, ephem='DE436t')
  File "/home/produit/PINT/pint/toa.py", line 61, in get_TOAs
    t.compute_posvels(ephem, planets)
  File "/home/produit/PINT/pint/toa.py", line 789, in compute_posvels
    ssb_obs = site.posvel(tdb,ephem)
  File "/home/produit/PINT/pint/observatory/topo_obs.py", line 216, in posvel
    earth_pv = objPosVel_wrt_SSB('earth', t, ephem)
  File "/home/produit/PINT/pint/solar_system_ephemerides.py", line 125, in objPosVel_wrt_SSB
    raise ValueError("Can not load the ephemeris file '%s.bsp'. " % ephem)
ValueError: Can not load the ephemeris file 'de436t.bsp'. 
-

Same thing later with:
ValueError: Can not load the ephemeris file 'de436.bsp'. 
ValueError: Can not load the ephemeris file 'de434.bsp'.  (several times)
