### ISSUE TITLE
Fail when loading a UNITS TCB ephemeris

### ISSUE THREAD

**Issue by kerrm** [nanograv/PINT#343]
PINT currently doesn't complain when loading an ephemeris with "UNITS TCB".  The timing model parameters will be then be interpreted incorrectly by PINT.  Until TCB is supported internally, it should check for UNITS TCB when loading a model and issue a fatal error if encountered.

**Comment by paulray** [comment]
I agree that this is important.  PINT should definitely fail if it finds UNITS TCB in a par file!

**Comment by paulray** [comment]
@jcolen can you add this check in get_model()? It should probably call log.error() saying that TCB units are not yet supported by PINT, and raise an exception.
