### ISSUE TITLE
Earth Orientation Parameters

### ISSUE THREAD

**Issue by shbhuk** [nanograv/PINT#349]
Hi,
I am looking for a way to query the IERS bulletin and obtain the Earth Orientation Parameters in Python. The analogue of the IDL [hprstatn.pro](https://harrisgeospatial.com/docs/hprstatn.html) procedure.

My end goal is to obtain the x,y,z,vx,vy,vz of an observatory wrt the barycenter taking into consideration these movements.

Just checking if you have a subroutine for just this functionality. I know that I can query the IERS bulletin and obtain the table, but is the final product already done?
I did come across the function[ gcrs_posvel_from_itrf()](https://github.com/nanograv/PINT/blob/ea1c3b9f71c06a73d6613d647770b99924f7c9bf/pint/erfautils.py) . I see that it has polar motion and rotation, but does it also consider precession & nutation ? 

My other option would be to convert the IDL codes, since Astropy does not contain. 

Thanks,
Shubham

**Comment by luojing1211** [comment]
Hi @shbhuk, PINT do have the option to get an observatory wrt the solar system barycenter. The routine is located at the solar_system_ephemerides.py module. 

I believe IERS takes the precession and nutation take into consideration. Take a look at page: https://www.iers.org/IERS/EN/Science/EarthRotation/EarthRotation.html

**Comment by shbhuk** [comment]
Hi @luojing1211 , as I understand the `solar_system_ephemerides.py` just works for giving posvel of the GC wrt the SSB, and this is by the JPL ephemerides. What would be the way to get it from GC to observatory? 

The obj name in the routines in this file has to be from `solar_system_ephemeris.bodies` .

**Comment by luojing1211** [comment]
gcrs_posvel_from_itrf()  method computes the observatory position from ITRF to GCRS coordinate. Basically, Obs_ssb = Obs_gc + gc_ssb

**Comment by shbhuk** [comment]
Write, so I should combine the two right? 
erfautils   + ssephem
Obs_gc + gc_SSB ?

**Comment by luojing1211** [comment]
Yup.

**Comment by shbhuk** [comment]
Excellent. So regarding the function gcrs_posvel_from_itrf() . I see that it has polar motion and rotation, but does it also consider precession & nutation ?

**Comment by shbhuk** [comment]
Excellent. I shall test the output and get back to you. 
Thank you :)

**Comment by luojing1211** [comment]
@shbhuk , is this issue fixed?

**Comment by shbhuk** [comment]
Hi,
We are still testing the results. I shall try to get back to you by the end of this week.

**Comment by shbhuk** [comment]
Hi,
We are writing a routine for barycentric velocity correction. The Python version of BaryCorr.pro .
We would like to use this routine for the Earth Orientation Parameter data.
