### ISSUE TITLE
Conversion between PINT coordinates and astropy?

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#364]
It seems that there should be inheritance rules to allow me to do:

```python
import pint.models as models
from astropy.coordinates import SkyCoord
m=models.get_model('0038-2501.par')
c=SkyCoord(m.RAJ,m.DECJ)
```

This fails because the RAJ and DECJ properties can't be cast to astropy quantities, but it seems like they should be able to.  Has this been discussed and rejected?  If not it would be helpful to add (for mixed astropy/PINT functionality).  Otherwise it needs to be more complicated (at least how I figured it out):
```python
if m.RAJ.unitsuffix=='h':
            psr=SkyCoord(m.RAJ.value,m.DECJ.value,unit=('hour','deg'))
 else:
            psr=SkyCoord(m.RAJ.value,m.DECJ.value,unit=('deg','deg')) 
```
I don't know if there is a better way to do this.

**Comment by paulray** [comment]
Hmm. It is surprising that that doesn't work.  It might be better for PINT to have a skycoord property of the model that would return a SkyCoord object. This should work whether the PAR file uses RAJ, DECJ or ELAT, ELON.

**Comment by dlakaplan** [comment]
Yes, I agree.  That's effectively what I wrote.

Overall the casting between PINT values and astropy quantities seems a little clumsy, but maybe I'm not doing it right.  For instance:
```python
astropy.units.quantity.Quantity(m.F0)
```
fails but:
```python
x=m.F0.value*m.F0.units
```
succeeds.  What is the expected interface method?

**Comment by luojing1211** [comment]
Hi @dlakaplan and @paulray. The parameter object has an attribute designed exactly for this propose. Try m.F0.quantity instead.

**Comment by dlakaplan** [comment]
OK - thanks!  I figured there had to be a way to do it.

**Comment by paulray** [comment]
I know that m.F0.quantity works fine, but what about the question about getting a SkyCoord object from a model?

**Comment by luojing1211** [comment]
@paulray There is a function get_psr_coords() in the astrometry model. It gives you the SkyCoord object directly.

**Comment by paulray** [comment]
Great!

**Comment by dlakaplan** [comment]
Sorry, could you explain a little more?  Starting from a .par file (and with no TOAs) is there a code snippet to do this?

**Comment by paulray** [comment]
If m is your model, then the SkyCoord is:
`m.components["AstrometryEquatorial"].get_psr_coords()`

**Comment by luojing1211** [comment]
@dlakaplan Here is a quick example
In [1]: import pint.models as model

In [2]: m = model.get_model("J0613-sim.par")
WARNING: Unrecognized parfile line 'SOLARN0               0.00' [pint.models.timing_model]

In [3]: m.get_psr_coords()
Out[3]:
<ICRS Coordinate: (ra, dec) in deg
    ( 93.43324031, -2.01311816)>

**Comment by dlakaplan** [comment]
OK, that's what I tried but it's not working for me.
```python
In [1]: import pint.models as models

In [2]: m=models.get_model('1949+3426.par')
WARNING: Unrecognized parfile line 'EPHVER         5' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'T2CMETHOD      IAU2000B' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'NE_SW          4.000' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'CHI2R          0.0000 37' [pint.models.timing_model]

In [3]: m.get_psr_coords()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-96203a07ba38> in <module>()
----> 1 m.get_psr_coords()

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pint-0.5.3+26.gd46c8a9-py2.7-macosx-10.10-x86_64.egg/pint/models/timing_model.pyc in __getattr__(self, name)
    129                     raise AttributeError(errmsg)
    130             except:
--> 131                 raise AttributeError(errmsg)
    132 
    133     @property

AttributeError: 'TimingModel' object and its component has no attribute 'get_psr_coords'.
```

**Comment by dlakaplan** [comment]
And:
```python
In [6]: m.components["AstrometryEquatorial"].get_psr_coords()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-ac1fa06c629b> in <module>()
----> 1 m.components["AstrometryEquatorial"].get_psr_coords()

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pint-0.5.3+26.gd46c8a9-py2.7-macosx-10.10-x86_64.egg/pint/models/timing_model.pyc in __getattr__(self, name)
    876             except:
    877                 raise AttributeError("'%s' object has no attribute '%s'." %
--> 878                                     (self.__class__.__name__, name))
    879 
    880     def add_param(self, param):

AttributeError: 'AstrometryEquatorial' object has no attribute 'get_psr_coords'.
```

**Comment by paulray** [comment]
What do you get for this:
```
In [11]: pint.__version__
Out[11]: '0.5.3+89.gd7c5571'
```

**Comment by dlakaplan** [comment]
```python
In [2]: pint.__version__
Out[2]: u'0.5.3+26.gd46c8a9'
```

I did a fresh pull yesterday, although if I am reading it right my version might be lower than yours

**Comment by paulray** [comment]
Yeah, if you are using your own fork of the repo, make sure you fetch and merge nanograv/master.  Assuming you are in your master branch:
```
get fetch nanograv
git merge nanograv/master
```
