### ISSUE TITLE
TDB vs TCB

### ISSUE THREAD

**Issue by scottransom** [nanograv/PINT#37]
We should be able to handle both barycentric timescales.  This is important especially since TEMPO2 used TCB by default.

**Comment by paulray** [comment]
This requires some design decisions.  Will PINT always use TDB internally, and just have timing model files converted upon reading in?  Currently the TOA tables are all written assuming that TDB is the basic time scale.  Or, do we change PINT to use "TB", which can be either TDB or TCB depending on some setting?  One issue is that this choice is kind of a global thing and might want to be known before a model is defined, so perhaps the UNITS keyword in the par file isn't the best place to make this setting. But, of course, any par file should specify UNITS so PINT knows what is being read.

**Comment by paulray** [comment]
Regarding this, as of 2006, TDB is actually defined in terms of TCB, so I guess TCB is really the more fundamental timescale. They encourage use of TCB for solar system ephemerides, though I don't think JPL has taken them up on that so far.  Here is the resolution (2-page PDF):
https://www.iau.org/static/resolutions/IAU2006_Resol3.pdf

**Comment by abhisrkckl** [comment]
Is there any interest at present in supporting TCB in PINT?

**Comment by scottransom** [comment]
@paulray How much work is it worth for that capability?  Especially given that T2 will convert for you in a single-line command?

**Comment by paulray** [comment]
Good question. It depends on how likely JPL is to change to TCB for ephemeris time in the future, I guess.
I'm not sure I trust the conversion to be exact without a re-fit, but maybe it is.

**Comment by abhisrkckl** [comment]
I tried the TCB -> TDB conversion with a few InPTA par files. Without a re-fit, there was a ~10 ns difference in residuals for some par files. I don't know if that is cause for worry or not.

**Comment by gooddc** [comment]
I hesitate to say this out loud, but I should probably volunteer for the TCB to TDB wrapper task.

**Comment by scottransom** [comment]
No good deed goes unpunished, Deborah!  :-)  But thank you for even considering!

**Comment by gooddc** [comment]
I'm pretty sure I can do it; it just probably won't be fast.

**Comment by abhisrkckl** [comment]
Are you planning to develop a TCB -> TDB converter like the transform plugin or a method to enable PINT to read TCB files? (There is probably a lot of overlap between these, I guess.)

**Comment by scottransom** [comment]
Given that I think we decided that we don't want the PINT internals to handle TCB directly, I think both of those two different solutions are effectively almost identical (which you also suggest).

**Comment by abhisrkckl** [comment]
I think that we have a consensus on this issue based on the above discussions. Shall we close this issue?

**Comment by paulray** [comment]
I'm OK with closing this
