### ISSUE TITLE
astropy 3.0 incompatibility

### ISSUE THREAD

**Issue by demorest** [nanograv/PINT#372]
I noticed the online Travis-CI tests for python3 have started pulling in astropy 3.0.  This breaks things, with the following error while using the DDK model:

`TypeError: Coordinate frame got unexpected keywords: ['d_lat', 'd_lon_coslat']`

The relevant PINT code (in `astrometry.py`) has a comment about how astropy version 2.0 is required.  For now we can require astropy<3.0, but should figure out a longer-term fix for this.

**Comment by demorest** [comment]
Not sure if we've discussed this already, but astropy 3.0 drops support for python 2 (it requires python>=3.5).  That is not the cause of this bug.. this seems due to some internal changes in the astropy coordinates classes.  I suppose as long as we don't start using any astropy-3.0-specific features we can continue to support python 2.7 in PINT and nothing needs to change immediately.  But we should probably keep in mind that this may have to change in the future.

**Comment by paulray** [comment]
Wow, dropping Python 2! I guess they are trying to drag us into the modern era.  Should we all be switching our default Python to 3?

**Comment by demorest** [comment]
Looks like probably sometime over the next ~year, we will have to, whether we like it or not.  Some more info about the astropy timeline is at https://github.com/astropy/astropy-APEs/blob/master/APE10.rst

Apparently many packages (including things like numpy and matplotlib) have pledged to stop supporting python 2 by 2020 at the latest.  This is when python 2.7 itself is now expected to stop being updated.  See http://python3statement.org/

**Comment by scottransom** [comment]
I've been looking into it for PRESTO...  it might not be as bad as we think....

**Comment by aarchiba** [comment]
Can this bug now be closed, then?
