### ISSUE TITLE
Add radial velocities?

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#374]
Would it be possible to add support for companion radial velocities into the PINT binary delay model?  This would help eliminate possible sources of error when doing simultaneous optical/timing fits.  Presumably the radial velocity of the pulsar is already present since it is needed to correct TOAs.  All that would be needed is the ability to compute velocities for the other body in the orbit.

Adding support for 3D motion would be even better.

**Comment by scottransom** [comment]
@dlakaplan I don't think that the radial velocity of the pulsar, per se, gets used to correct TOAs.  But the ability to *get* the orbital radial velocity is certainly available.  If you wanted to use that extra information to do a joint fit, it would simply mean tweaking one of the current Fitter classes.  Should be doable quite easily.

**Comment by dlakaplan** [comment]
OK, it may not be computed directly.  I wasn't necessarily thinking of using it in a joint fit: the precision and number of data points are usually so different from optical to timing that it is hard to do it at once.  But just to get the predicted RV of the companion for a given set of Time objects would define the basis function for optical fitting.

I guess the alternative is to just compute orbital phases (which I have done, although can't immediately recall) from within PINT and just fit for the amplitude.   That may ultimately be simpler.

**Comment by paulray** [comment]
This is very closely related to issue #100

**Comment by aarchiba** [comment]
Orbital radial velocities would be valuable. Would correcting them all to topocentric be of use? I guess the optical tools must already correct to barycentric velocities so all that is needed is the orbital part?

Worth noting is that we would get the radial velocity of the pulsar, and not the companion; for normal models the conversion factor may be simple (but for three- and more-body systems, for example those with planets, one would want the model itself to report companion velocities). 

More broadly, are models able to attach model-specific extra information to individual TOAs? If requested perhaps? Reflex motion of pulsar and/or companion, for example?

**Comment by paulray** [comment]
Now that Scott merged model.orbital_phase() with all the anomalies it should be easy to add a couple utilities to compute line of sight velocity and acceleration, along the lines of `los_velocity()` and `los_acceleration()` here:
https://github.com/ewanbarr/pyorbit/blob/master/pyorbit/utils.py

Great little project for a student...

**Comment by abhisrkckl** [comment]
Implemented in #1638
