### ISSUE TITLE
Builds failing on travis-ci

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#379]
For some reason the builds on travis-ci stopped working.
Some change in astropy or the build environment is making them fail when they try to read an ephemeris (e.g. de436.bsp).  I haven't been able to isolate the problem since I can't make it fail on my machines.  They all build and test just fine.

**Comment by paulray** [comment]
OK, this seems to be due to the FTP timing out on the downloads of de436 and/or de436t ephemeris files from the JPL FTP site.  I've increased the timeout and it is still failing.

**Comment by luojing1211** [comment]
It possibly because that the travis-ci server can not access the JPL FTP site somehow. I had that problem when I was in China.

**Comment by paulray** [comment]
Yeah, that seems to be the issue. I'm not sure if it is just slow or totally inaccessible from the travis servers, but either way I don't know how to solve this problem.

**Comment by paulray** [comment]
How do we fix this?  Can we host our own copies of the files at NRAO or something, and point to that? @scottransom

**Comment by paulray** [comment]
This has been fixed and builds are now passing.
