### ISSUE TITLE
astropy dependency incorrect

### ISSUE THREAD

**Issue by kerrm** [nanograv/PINT#390]
The current version of PINT requires a version of astropy more recent than 1.3.  I had that version and got the following error:

    import pint.models
  File "/home/kerrm/packages/new_PINT/pint/models/__init__.py", line 8, in <module>
    from .astrometry import AstrometryEquatorial, AstrometryEcliptic
  File "/home/kerrm/packages/new_PINT/pint/models/astrometry.py", line 13, in <module>
    from pint.pulsar_ecliptic import PulsarEcliptic, OBL
  File "/home/kerrm/packages/new_PINT/pint/pulsar_ecliptic.py", line 29, in <module>
    class PulsarEcliptic(coord.BaseCoordinateFrame):
  File "/home/kerrm/packages/new_PINT/pint/pulsar_ecliptic.py", line 48, in PulsarEcliptic
    default_differential = coord.SphericalCosLatDifferential

That class wasn't in my version of astropy.  I wasn't able to quickly identify the version it was added, but after I upgraded to version 2.06, which is what pip --upgrade gave me, this problem went away.

**Comment by paulray** [comment]
In requirements.txt, it has:
`astropy>=2.0,<3.0`
Where does it still say 1.3?

**Comment by luojing1211** [comment]
This functionality is for converting the proper motions from ICRS to the
ecliptic coordinate. Before Astropy 2.0, the transformation of proper
motion is not supported.

-Jing Luo

**Comment by luojing1211** [comment]
We did not update the requirement_dev version.

**Comment by luojing1211** [comment]
By the way, is astropy-helper one package?

**Comment by kerrm** [comment]
I was looking in setup.py specifically.  At any rate, it certainly installed happily enough with v1.3!

**Comment by paulray** [comment]
Ah, I see. I fixed that in setup.py now.
