### ISSUE TITLE
user flag to suppress warnings

### ISSUE THREAD

**Issue by paulthebaker** [nanograv/PINT#394]
Is there a way for a user to suppress warnings from a particular function call?

For my burst with memory inspired glitch fitting, I need to run a fitter for many different values of glitch epoch (since the fitter cannot fit that param).  For some pulsars the `GLSFitter` throws a warning (e.g. `WARNING: Parameter PBDOT's unit will be scaled to 1e-12  [pint.models.parameter]`) several times per fitter call.  The fitter loops where this happens takes significantly longer than those where it doesn't.

This warning message is generated in `set_quantity_float()` in `pint.models.parameter`.

I'm guessing the IO to print the warning is slowing things down.

I would like a way to suppress warning messages to cut down on the IO time?  This could be a flag to turn off warnings for a function or a global `pintrc` type flag to turn off warnings all together.

Good default behavior would be to suppress duplicate warnings from the same function call, although this seems more complicated.

**Comment by paulray** [comment]
Good question.

The simplest fix is to change your par file to give PBDOT explicitly, rather than relying on the deprecated 1e-12 scaling.

But for the more general issue, we use astropy.logging system, which has various ways to set the level that is display and to disable warnings <http://docs.astropy.org/en/stable/logging.html>.  We could demote this warning to a log.info() to make it a little easier to block without worrying that you'd miss an actual important warning.

**Comment by paulray** [comment]
This particular warning has been demoted to an info.  Is that sufficient to close this?

**Comment by paulray** [comment]
Is this dealt with sufficiently that we can close?

**Comment by aarchiba** [comment]
Astropy logging is a pain in the butt but it's built on top of python's logging module, which has a context manager LoggingContext to let you change the level of messages that are emitted for the code inside it:

https://docs.python.org/3/howto/logging-cookbook.html#using-a-context-manager-for-selective-logging

An example in the documentation would maybe be a good idea.

**Comment by paulthebaker** [comment]
Current state is good enough.

I'm going to close and label this as "won't fix".  It sounds like `astropy` handles this, so a user who wants to change the logging level needs to deal with that API not `PINT`
