### ISSUE TITLE
Finding residuals fails when more than one DM00* line.

### ISSUE THREAD

**Issue by PaulBrook** [nanograv/PINT#395]
OS: Ubuntu 16.04
pint.__version__: u'0.5.3'
pint.__file__: '/home/pbrook/.local/lib/python2.7/site-packages/pint/__init__.pyc'

----

I was running though a bunch of par/tim files and was getting the timing residuals, pulsar by pulsar. I was doing:

`timing_residuals.append(r.resids(t[i], m[i]).time_resids.to(u.us).value)`

But I found that it was failing on some small number of the pulsars. I narrowed it down, and it seems like the problem was the par files that had more than 1 DM00* line. e.g.:

```
DM              236.670923  1            0.002054
DM001  -7.217985735599D-03  1  5.686164637485D-04
DM002   1.449521255275D-03  1  2.268096526335D-04
```

I found that when I removed DM002, everything works okay.

So it seems like PINT only likes it when the par file have DM001.

**Comment by luojing1211** [comment]
I am sure if you use the format of DM1, DM2,.. it will work. Do we have any
standard for the DM format?

**Comment by luojing1211** [comment]
@PaulBrook Is this issue fixed?

**Comment by PaulBrook** [comment]
yes, thanks Jing.
