### ISSUE TITLE
Re-create BT model

### ISSUE THREAD

**Issue by vhaasteren** [nanograv/PINT#40]
I have started implementation of a new 'BT' model. It is not fully feature complete, but it already does more than the current implementation in the timing model. See pint/models/btmodel.py

Overview of progress:

[v] = Done, [x] = With errors, [ ] = Not done

Calculations
============
[v] Pulse period (Pobs)
[v] Pulse delay (delay)
[v] Derivatives of Pobs (d_Pobs_d_xxx)
[x] Derivatives of delay (d_delay_d_xxx)

Interface
=========
[v] Caching (with decorator)
[ ] Astropy units
[v] Setting & getting parameters

Code quality
============
[ ] Docstrings
[ ] Unit tests (wrt tempo2 or internally?)
[x] Formatting (pylint)

Open issues
===========
[x] In delayR(), I would think we need to use self.pbprime().
    However, tempo2 seems consistent with self.pb()
[ ] We are ignoring the derivatives of delayR() at the moment. This is a decent
    approximation for non-relativistic orbital velocities (1 part in ~10^6)

**Comment by luojing1211** [comment]
In BT model code, the d_E_d_T0 function part has no d_ecc()/d_T0 term. As we defined ecc() = ECC+(t-T0)*EDOT,d_ecc()/d_T0 should have a value of -EDOT. 

Besides, when the generic binary model has been merged. BT model should be able to work with generic binary model.

**Comment by luojing1211** [comment]
But model is in place, closing.  We need make the derivative part working.
