### ISSUE TITLE
Tests failing when trying to download ephemerides

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#411]
On Travis, and on my local machine, the tests are now failing when they try to download de434 and de436.  This was fixed previously by hosting them on the nanograv server, but this seems not to be working anymore.  For example, this fails from the command line:
```curl -O https://data.nanograv.org/static/data/ephem/de436.bsp```

@nategarver-daniels did something happen to that server that is keeping us from accessing it?

**Comment by nategarver-daniels** [comment]
I need to update the security certificate. I'll do that today.

**Comment by nategarver-daniels** [comment]
The security certificate is updated, I'm going to close this issue.
