### ISSUE TITLE
d_phase_d_toa() should not call adjust_TOAs()  (or problem with get_PSR_freq())

### ISSUE THREAD

**Issue by scottransom** [nanograv/PINT#415]
Currently, d_phase_d_toa() is called by get_PSR_freq() in residuals.py.  and get_PSR_freq() is called during calc_time_resids().  And calc_time_resids() is called every time residuals are updated, which is with every iteration in a fit.

That's a problem, because d_phase_d_toa() calls adjust_TOAs(), which deletes columns in the TOAs table and re-computes TDBs and all of the solar system positions and velocities!

This is not good at all as it means that a ton of extra work is being performed.

I'm not sure when or where this bug got added, but it was fairly recently.

You can see the effect of it in all of the INFO lines when you run "python examples/fit_NGC6440E.py"

**Comment by scottransom** [comment]
Ah.  It came in 2 months ago with commit 05c9cac4664fd5578b8d0ee607c6825a5f232147

From pull request #397

**Comment by jcolen** [comment]
In a more recent commit I changed the default behavior of get_PSR_freq to modelF0 = True, which means it takes the nominal F0 value from the model without calling d_phase_d_toa(). So the extra work is no longer being performed.

**Comment by scottransom** [comment]
Huh.  You are totally correct!  I swear I did a "git pull" before testing that, but when I just tried that now, there were recent commits.  Sorry about that!  So this is probably fine.

**Comment by paulray** [comment]
Should we close this then?

**Comment by scottransom** [comment]
I think as long as adjust_TOAs() doesn't get called on any kind of regular basis, then yes.  And it seems that that is the case given the more recent commits.
