### ISSUE TITLE
Bug in photonphase

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#427]
I just noticed that the --barytime option in photonphase is wrong.  The code looks like this:
```
            tdbs = np.asarray([t.mjd for t in ts.table['tdb']])
            data_to_add['BARY_TIME'] = [tdbs,'D']
```
This is almost certainly not what was meant to happen. This gives the photon times converted to the TDB timescale, but *without* the solar system delays applied.
I think the correct answer would be to use the `get_barycentric_toas()` method from the timing model.
@kerrm do you concur?

**Comment by kerrm** [comment]
I agree that what I would expect would be TDB + SS delays, so it sounds
like get_barycentric_toas is the ticket.  Gosh, lots of bugs.
