### ISSUE TITLE
Numpy math function longdouble precision 

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#43]
How does numpy math function handle the longdouble precision?  We have to make a short unit test for numpy math function longdouble precison keeping.

**Comment by scottransom** [comment]
So a quick test with mpmath shows that we are getting 18+ digits of precision using np.longdoubles with at least the "main" math calls (sin, cos, exp):

In [14]: import mpmath

In [15]: mpmath.mp.dps = 30

In [16]: mpmath.cos(2)
Out[16]: mpf('-0.416146836547142386997568229500778')

In [17]: np.cos(np.longdouble(2))
Out[17]: -0.41614683654714238701

In [18]: mpmath.sin(2)
Out[18]: mpf('0.909297426825681695396019865911701')

In [19]: np.sin(np.longdouble(2))
Out[19]: 0.90929742682568169538

In [20]: mpmath.exp(2)
Out[20]: mpf('7.3890560989306502272304274605753')

In [21]: np.exp(np.longdouble(2))
Out[21]: 7.3890560989306502274

In [22]: np.__version__
Out[22]: '1.9.2'

**Comment by paulray** [comment]
A unit test should be added to both verify that np.__version__ is at least some minimum value (what?), and also do an empirical calculation to prove that the code being used is actually retaining precision down to the stated goal.  What is the goal precision for PINT?  1 nanosecond? This should be documented somewhere.

**Comment by paulray** [comment]
The numpy version of >=1.11.0 is now enforced in requirements.txt.  Is there a unit test we need to verify we are getting the precision we need? Or, can this be closed?
