### ISSUE TITLE
zima duration has to be int

### ISSUE THREAD

**Issue by tcromartie** [nanograv/PINT#432]
When using zima to generate fake TOAs, it isn't possible to set --duration to anything besides integer days. It'd be helpful if you could set the duration to fractional days (for example, to simulate a 6-hour observation).

**Comment by paulray** [comment]
Oops.  Just change `type=int` to `type=float` to fix this!
If you haven't already figured out how, this would be a good opportunity to make a pull request to fix this bug! :-)

**Comment by tcromartie** [comment]
Haha I'll do it if that's best :) just wanted to open an issue to let y'all know!
