### ISSUE TITLE
Possible zima multifrequency issue (as discussed on telecon)

### ISSUE THREAD

**Issue by tcromartie** [nanograv/PINT#435]
When generating simulated TOAs with zima for multiple frequencies via something like:

`for i in {1100..1700..100}; do zima --freq ${i} --startMJD 58250 --duration 0.2 --ntoa 2 --error 1.73 J0740+6620.par ${i}.tim; done`

the residuals turn out looking like the attached plot (simulated TOAs at MJD 58250). Note that this is only an issue when trying to integrate the TOAs with another data set that needs DMX (i.e. NANOGrav). The spread in simulated TOAs is not affected by putting them in or out of an existing DMX bin. The issue of it being related to clock corrections (i.e. generating TOAs in the future) has also been ruled out. 

![j0740 6620_dmx](https://user-images.githubusercontent.com/16215017/46698596-8a1e7000-cbe5-11e8-9d63-52e51050b769.png)

The second attachment shows a more exaggerated example of the phenomenon:

![freq_spread_example](https://user-images.githubusercontent.com/16215017/46698760-e84b5300-cbe5-11e8-9ef5-a4765a992327.png)

**Comment by paulray** [comment]
I wonder if this is the result of doing it with multiple zima calls?  Can you try it with a single call, using the --freq option?

**Comment by tcromartie** [comment]
Unfortunately that doesn't seem to be the issue. Same result.

**Comment by paulray** [comment]
Well it was worth a shot! :-)

**Comment by luojing1211** [comment]
Hi @tcromartie, 
Can you share the parfile for this simulation?

**Comment by tcromartie** [comment]
Here you go! I really appreciate y'alls help on this. Again, we aren't 100% convinced that this is a zima problem, but it might be...

[J0740+6620.12yrext.ELL1.par.txt](https://github.com/nanograv/PINT/files/2466610/J0740%2B6620.12yrext.ELL1.par.txt)

**Comment by tcromartie** [comment]
Actually @luojing1211 @paulray @scottransom, I'm now fairly convinced that this isn't a zima-specific issue, as I've just written code to simulate multifrequency TOAs with tempo only and I'm seeing the same issue. If anyone has experience simulating TOAs in a DMX bin your advice would be welcome, though!

**Comment by luojing1211** [comment]
That is good to know. It looks like a more fundamental issue right now.
