### ISSUE TITLE
PINT should fail on T2 binary model

### ISSUE THREAD

**Issue by kerrm** [nanograv/PINT#449]
PINT doesn't support T2 binary models but will happily ingest an ephemeris with one.  The only sign of trouble is it complains about some unrecognized parameters like PBDOT.  This can get lost in the noise, so I propose PINT should fail hard when given a T2 model.  (This could be generalized to failing hard on any unrecognized option.)

**Comment by luojing1211** [comment]
That is a good idea. I can fix it.

**Comment by kerrm** [comment]
Right on!

**Comment by paulray** [comment]
Did this ever get fixed?

**Comment by luojing1211** [comment]
I don't think so. It should be a small fix in the model builder.

-Jing

**Comment by aarchiba** [comment]
Really it should fail hard on any unknown binary model, shouldn't it?

**Comment by paulray** [comment]
This REALLY needs to be fixed. Another person was just caught by the fact that BTX is not supported and it just spits out a few warnings instead of failing. @luojing1211 can you fix this?

**Comment by aarchiba** [comment]
See PR #520 which solves this issue and several other validation concerns but is not complete.
