### ISSUE TITLE
remove_param method fails to remove M2 and SINI

### ISSUE THREAD

**Issue by tcromartie** [nanograv/PINT#453]
Removing M2 and SINI after fitting (i.e. `f.model.remove_param('M2')`), then trying to refit, does not actually remove those two parameters. Discussed with @luojing1211 via email. Setting them to 0 and freezing them works as a stopgap, however.

**Comment by abhisrkckl** [comment]
> Setting them to 0 and freezing them works as a stopgap, however.
This is the correct way to use this parameter.
