### ISSUE TITLE
Fermi phase 

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#467]
Hi @paulray @kerrm 
I see the ELONG and ELAT are converted to the 'barycentrictrueecliptical', I believe this is different than our 'pulsar_ecliptical' frame. Does Fermi use the 'barycentrictrueecliptical' frame?

Line of code. 
https://github.com/nanograv/PINT/blob/4b5403d9c97f65c9f37005c44e0db68cf36e6644/pint/scripts/fermiphase.py#L47

**Comment by paulray** [comment]
No Fermi doesn't use ecliptic coordinates at all. The target coord is only used in computing the photon weights, so it doesn't have to be precise at all. Fermi uses RAJ, DECJ, so this line was just to take care of the case when the par file was in ecliptic coordinates

**Comment by luojing1211** [comment]
I see. if it only needs a rough position. It will be fine. I think we can close this issue.
