### ISSUE TITLE
Is erfautils still necessary? Does it have to download IERS_B?

### ISSUE THREAD

**Issue by mhvk** [nanograv/PINT#469]
While testing using PINT to generate phase, I noticed that there is no way that with a clean install one could run without it downloading large files, e.g., the IERS_B file even for times which fall well within the default one packaged with astropy. Looking in more detail, I noticed `erfautils` is the culprit. With the astropy >=2.0 infrastructure, there should be no need to download IERS files automatically. Also, `EarthLocation` has a `get_gcrs_posvel` method - if that does not provide consistent results with `erfautils.gcrs_posvel_from_itrf`, we'd like to know...

I may try making a PR that just removes the cruft, if people are confident the tests will guard against regressions.

**Comment by aarchiba** [comment]
Let me note that at the moment the IERS_B file is downloaded with cache=True, so that it is not updated until the user's astropy cache is cleaned out. Which could be months later, since the cache is user-wide and shared across virtualenvs. (And machines at, say, NRAO, where there's a shared home directory.) So disposing of erfa would be valuable indeed.

**Comment by aarchiba** [comment]
The file downloading is relevant to PR #502 .

**Comment by aarchiba** [comment]
So the answer is, kinda yes? The plain astropy version uses the IERS A table, while the erfautils version uses IERS B. Although the IERS docs appear to say that the IERS B dX/dY values go into the IERS A table, the actual values differ. This produces different positions and velocities: the positions differ at the 5 cm level, and the velocities differ at the 0.4 mm/s level. When `tests/test_times.py` does its comparison of PINT with tempo2, the tolerance levels are set at 2 m and 0.02 mm/s - so the velocities astropy gets are about 20 times greater than the threshold there.

Whether even pulsar astronomers would care about a velocity difference less than a mm/s I don't know. I can see the spectroscopic exoplanet people tearing their hair and wishing astropy could use IERS B, though.

I'll also note that IERS B is used only in erfautils, not in any of the time conversions (for example). So there is a logical, if perhaps not a practical, inconsistency in how pint works if we use IERS B here.

**Comment by mhvk** [comment]
@aarchiba - the above is not quite correct; `astropy` does in fact copy information from the real `IERS-B` to its default table (see https://github.com/astropy/astropy/blob/master/astropy/utils/iers/iers.py#L770) because we found that the "IERS-B" values in IERS-A tables are not, in fact, identical to the real IERS-B values (I'm quite sure I sent an e-mail to the IERS-A people at the time, but never got a reply; great if someone who really cares follows up...). Note, however, that for this purpose, by default it uses the IERS-B table bundled with astropy, which is somewhat out of date (going only to end of 2017...)

One can also ensure that all operations use the IERS-B table using a variation of (from http://docs.astropy.org/en/latest/utils/iers.html)
```
from astropy.utils import iers
iers.conf.auto_download = False
iers.IERS.iers_table = iers.IERS_B.open(iers.IERS_B_URL) 
```

Note that I don't think any of this is super-handy - the whole `iers` module has become a bit hacky - but if we can think of ways to make it easier to use, I'd be quite happy to try to (help) make a PR.

**Comment by aarchiba** [comment]
My initial attempt was to use the IERS_Auto table and in particular its IERS_B values, but I got discrepancies large enough to fail our existing tests. So I'm not sure whether it's the age of the IERS_B data or some other problem but I did get discrepancies.

Downloading the IERS_B data every time PINT is run is definitely not the right answer. The right answer is, like for IERS_Auto, when a time is requested, if it's past the end of the final values, clear_download_cache(IERS_B_URL) and then re-download it into the cache.

This approach is probably worth using for all updating time series that can be updated automatically. This would ideally include observatory clock corrections, if those are published somewhere. 

One nuisance at the moment is that if a new IERS_B table is needed, the cache is cleared before finding out whether the internet URL is reachable. Unfortunately the astropy caching mechanism as it currently stands makes it difficult to avoid this. I have a PR on the astropy github addressing some limitations of the cache mechanism (and I have some local code that adds more) but it was flagged "needs discussion" and then no discussion happened.

**Comment by mhvk** [comment]
It would be good to find out if the IERS-B replacement mechanism is in fact not working...

For keeping IERS-B up to date, I guess one could make an `IERS_B_Auto` based on the current `IERS_Auto` class.

I did see you PR on astropy and even looked in some detail, as I liked the idea, but haven't had the time to look closer. Will comment there.

**Comment by aarchiba** [comment]
There's all sorts of weird stuff in the IERS B replacement (and in IERS B?!), but even if you clear that out you still get disagreements. I wrote the following test:
```
def test_IERS_B_agree_with_IERS_Auto():
    A = IERS_Auto.open()
    B = IERS_B.open(download_file(IERS_B_URL, cache=True))
    mjd = B['MJD'].to(u.day).value
    A.pm_xy(mjd) # ensure that data is available for this date

    # Let's get rid of some trouble values and see if they agree on a restricted subset
    # IERS Auto ends with a bunch of 1e20 values meant as sentinels (?)
    ok_A = abs(A['dX_2000A_B']) < 1e6*u.marcsec
    # For some reason IERS B starts with zeros up to MJD 45700? IERS Auto doesn't match this
    #ok_A &= A['MJD'] > 45700*u.d
    # Maybe the old values are bogus?
    ok_A &= A['MJD'] > 50000*u.d

    mjds_A = A['MJD'][ok_A].to(u.day).value
```
and get the following output:
```
======================================================================
FAIL: test_erfautils.test_IERS_B_agree_with_IERS_Auto
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/archibald/.virtualenvs/pint-dev3/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/archibald/projects/pint/PINT/tests/test_erfautils.py", line 92, in test_IERS_B_agree_with_IERS_Auto
    err_msg="Inserted IERS B values don't match current IERS B values")
  File "/home/archibald/.virtualenvs/pint-dev3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1510, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/archibald/.virtualenvs/pint-dev3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 836, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05
Inserted IERS B values don't match current IERS B values
Mismatch: 92.3%
Max absolute difference: 1.744
Max relative difference: nan
 x: array([-0.039,  0.002,  0.018, ..., -0.034, -0.039, -0.044])
 y: array([-0.043, -0.049, -0.058, ..., -0.035, -0.041, -0.045])

```
I don't know what's up with the disagreement. Is it possible to access the built-in IERS B table? Is it still possible after opening a newer one, or is the table somehow global? Doing IERS_B.open() in my test file just returns the same one I pulled in from the Net.

A bit of manual hacking reveals that the current IERS B file differs from the one built in to astropy on days in the older file; the amount is of the same order of magnitude as the value. (Which is very peculiar.)

**Comment by mhvk** [comment]
Seeing your results does remind me that I've seen differences between older and new IERS-B files before. Indeed, I recall I wrote about that too, and did get an answer in that case (the people at Meudon are quite helpful). It seems that they do reanalyze their data to make sure it is always the best possible (which is of course not great for reproducing earlier results, and maybe makes this whole discussion a bit moot...). 

So, for checking the procedure, I think it is important to compare `IERS_Auto` with the IERS_B file that it actually used. In order to access the built-in table, try `iers.IERS_B.open(iers.IERS_B_FILE)` (sorry that the IERS documentation is not all that great... I had to look up the actual `iers.py` as well to find this should work...)

As for other things: yes `1e20` is a sentinel value used by IERS_A, and I do recall the `dX_2000A` not being measured early on (maybe J2000 didn't quite exist? PM_x does get filled in) - but I'm afraid I no longer recall any of those details - the IERS documents are very long...

**Comment by aarchiba** [comment]
Still different, unless I'm doing something wrong.

Code:
```python
    def test_IERS_B_builtin_agree_with_IERS_Auto(self):
        A = IERS_Auto.open()
        B = IERS_B.open(IERS_B_FILE)
        mjd = B['MJD'].to(u.day).value
        A.pm_xy(mjd) # ensure that data is available for these dates

        # We're going to look up the OK auto values in the B table
        ok_A = A['MJD'] < B['MJD'][-1]
        # Let's get rid of some trouble values and see if they agree on a restricted subset
        # IERS Auto ends with a bunch of 1e20 values meant as sentinels (?)
        ok_A &= abs(A['dX_2000A_B']) < 1e6*u.marcsec
        # For some reason IERS B starts with zeros up to MJD 45700? IERS Auto doesn't match this
        ok_A &= A['MJD'] > 45700*u.d
        # Maybe the old values are bogus?
        ok_A &= A['MJD'] > 50000*u.d

        mjds_A = A['MJD'][ok_A].to(u.day).value
        i_B = np.searchsorted(B['MJD'].to(u.day).value, mjds_A)

        assert np.all(np.diff(i_B)==1), "Valid region not contiguous"
        assert_equal(A['MJD'][ok_A], B['MJD'][i_B], "MJDs don't make sense")
        assert_allclose(
                A['dX_2000A_B'][ok_A].to(u.marcsec).value,
                B['dX_2000A'][i_B].to(u.marcsec).value,
                atol=1e-5, rtol=1e-3,
                err_msg="Inserted IERS B values don't match IERS_B_FILE values")
```
Output:
```
_______________________________ TestERFAUtils.test_IERS_B_builtin_agree_with_IERS_Auto ________________________________

self = <test_erfautils.TestERFAUtils testMethod=test_IERS_B_builtin_agree_with_IERS_Auto>

    def test_IERS_B_builtin_agree_with_IERS_Auto(self):
        A = IERS_Auto.open()
        B = IERS_B.open(IERS_B_FILE)
        mjd = B['MJD'].to(u.day).value
        A.pm_xy(mjd) # ensure that data is available for these dates
    
        # We're going to look up the OK auto values in the B table
        ok_A = A['MJD'] < B['MJD'][-1]
        # Let's get rid of some trouble values and see if they agree on a restricted subset
        # IERS Auto ends with a bunch of 1e20 values meant as sentinels (?)
        ok_A &= abs(A['dX_2000A_B']) < 1e6*u.marcsec
        # For some reason IERS B starts with zeros up to MJD 45700? IERS Auto doesn't match this
        ok_A &= A['MJD'] > 45700*u.d
        # Maybe the old values are bogus?
        ok_A &= A['MJD'] > 50000*u.d
    
        mjds_A = A['MJD'][ok_A].to(u.day).value
        i_B = np.searchsorted(B['MJD'].to(u.day).value, mjds_A)
        assert np.all(np.diff(i_B)==1)
        assert_equal(A['MJD'][ok_A], B['MJD'][i_B], "MJDs don't make sense")
        assert_allclose(
                A['dX_2000A_B'][ok_A].to(u.marcsec).value,
                B['dX_2000A'][i_B].to(u.marcsec).value,
                atol=1e-5, rtol=1e-3,
>               err_msg="Inserted IERS B values don't match IERS_B_FILE values")
E       AssertionError: 
E       Not equal to tolerance rtol=0.001, atol=1e-05
E       Inserted IERS B values don't match IERS_B_FILE values
E       Mismatch: 88.8%
E       Max absolute difference: 1.624
E       Max relative difference: inf
E        x: array([-0.039,  0.002,  0.018, ..., -0.089, -0.07 , -0.052])
E        y: array([-0.011,  0.007,  0.042, ..., -0.093, -0.073, -0.054])

tests/test_erfautils.py:127: AssertionError
```

**Comment by aarchiba** [comment]
Er, shall I go file an astropy bug? The test case(s) make decent standalone code

**Comment by mhvk** [comment]
@aarchiba - just looked at your test more closely and realize that you are comparing values [we actually do not replace](https://github.com/astropy/astropy/blob/master/astropy/utils/iers/iers.py#L792): only `UT1_UTC_B`, `PM_X_B` and `PM_Y_B` are being overwritten (and those are then [used to construct](https://github.com/astropy/astropy/blob/master/astropy/utils/iers/iers.py#L429) `UT1_UTC`, `PM_x`, and `PM_y`).

I must say I think that is definitely a bug! (even though it is true that those 3 are the ones we actually use in astropy). Though I am also not sure it is all that great that in the replacement we do not use the latest IERS_B, but rather whatever we ship...

**Comment by aarchiba** [comment]
Oh! But wait, what does dX_2000A_B mean if not the value from IERS B? I guess that's in the original IERS A table as ostensibly from B?

**Comment by mhvk** [comment]
Yes, exactly, it is in the original table as ostensibly from B (like for PM_X_B, etc.). And unfortunately we overwrite only the ones that we end up using (which we should fix).

**Comment by aarchiba** [comment]
Updated tests show that indeed the PM_X_B matches what's in the IERS_B_FILE but what's in the IERS_B_FILE doesn't match the current IERS_B_URL values for the times they overlap. I'd love to use test fixtures to be a little more systematic about this but without converting to pytest (PR #509 hint hint) that's a pain.
