### ISSUE TITLE
Save results before plotting and avoid matplotlib-related issues

### ISSUE THREAD

**Issue by matteobachetti** [nanograv/PINT#470]
```
INFO: Starting pulse likelihood: -11894.110763 [pint.scripts.event_optimize]
INFO: Starting pulse phase: 0.259895 [pint.scripts.event_optimize]
INFO: New max: -11894.110763 [pint.scripts.event_optimize]
INFO:      PHASE:         0.259894504446033 [pint.scripts.event_optimize]
INFO: New max: -11894.110500 [pint.scripts.event_optimize]
INFO:      PHASE:         0.259950637675808 [pint.scripts.event_optimize]
INFO: New max: -11894.110001 [pint.scripts.event_optimize]
INFO:      PHASE:         0.259930782388578 [pint.scripts.event_optimize]
INFO: ~1% complete [pint.scripts.event_optimize]
INFO: ~2% complete [pint.scripts.event_optimize]
(...)
INFO: ~100% complete [pint.scripts.event_optimize]
Traceback (most recent call last):
  File "/Users/meo/anaconda/envs/py3/bin/event_optimize", line 11, in <module>
    load_entry_point('pint', 'console_scripts', 'event_optimize')()
  File "/Users/meo/devel/spyder_projects/PINT/pint/scripts/event_optimize.py", line 626, in main
    plot_chains(chains, file=ftr.model.PSR.value+"_chains.png")
  File "/Users/meo/devel/spyder_projects/PINT/pint/scripts/event_optimize.py", line 614, in plot_chains
    axes[ii].plot(chain_dict[name], color="k", alpha=0.3)
TypeError: 'AxesSubplot' object does not support indexing

```
After a couple days running, `event_optimize` has failed when plotting the results, apparently without saving anything. It would be good to dump the results of the fit and the chains before plotting. This would avoid to lose completely the results of jobs for one of the (frequent, I should add) problems related to the version of matplotlib used or the quirks of the matplotlib backend _du jour_.

**Comment by scottransom** [comment]
Huh.  Sorry about that!   That's surprising, because I know that (substantially) earlier versions did write stuff out first for exactly that reason...

**Comment by matteobachetti** [comment]
I've made some modifications to allow event_optimize to use NuSTAR data (PR soon), I'll check if doing this I've introduced some bug, but this happens much later than the code I've modified, so it's a little weird.
Anyway, I'm investigating the issue. If you can't reproduce the failure it would be difficult to find the (possible) bug. I prefered to open an Issue to see if there was some something obvious going on. Feel free to assign it to me. Thanks!

**Comment by devbhakt** [comment]
@abhisrkckl I do not think this is an active issue

**Comment by abhisrkckl** [comment]
@devbhakt Thanks for checking. I'll close this.
