### ISSUE TITLE
Intersphinx links suggest documentation is out of date

### ISSUE THREAD

**Issue by mhvk** [nanograv/PINT#471]
@luojing1211 - we're using `pint.toa.get_TOAs_list`, but trying to build documentation, sphinx cannot find it. Indeed, I don't see even the `toa` module in readthedocs. Is the documentation out of date?

**Comment by luojing1211** [comment]
@mhvk Indeed, PINT documentation is a big goal in 2019.

**Comment by aarchiba** [comment]
Can you check whether this is fixed by #510 ?

**Comment by mhvk** [comment]
I tried adding back some links to `pint` in our documentation, but it still doesn't work. Indeed, https://nanograv-pint.readthedocs.io/en/latest/pint.html#pint-toa-module does not seem to have any entries.

But perhaps it is just that the docs build is failing? (As inferred from https://nanograv-pint.readthedocs.io/en/latest/readme.html; definitely had problems myself with things somehow getting stuck in a broken state...)

**Comment by aarchiba** [comment]
Yes, I've been tearing my hair over readthedocs today. It seems to be building now, though I really don't feel the need for it to construct EPUB-format documentation, or PDF. Our ``objects.inv`` does exist at the expected https://nanograv-pint.readthedocs.io/en/latest/objects.inv , though I can't easily inspect it to check that it has the right contents.

And lo, we now have marginally-useful documentation! Goodness those red monospace names are jarring. Some CSS spelunking may be called for.

Would you mind taking another swing at the intersphinx test?

**Comment by mhvk** [comment]
:fireworks: Success! Now using it in https://github.com/mhvk/scintillometry/pull/125...
