### ISSUE TITLE
no way to write .tim file

### ISSUE THREAD

**Issue by paulthebaker** [nanograv/PINT#474]
Currently, `toas.write_TOA_file()` writes a minimal file containing only the center frequency, TOA, and TOA uncertainty.

I think there should be a method to write an actual `.tim` file that maintains the individual TOA flags.

**Comment by paulray** [comment]
I think this is fixed. Can it be closed @paulthebaker ?

**Comment by paulray** [comment]
I just did this with `toas.write_TOA_file('output.tim',format='Tempo2')` and it worked great, so I'm closing. It does write some flags that weren't in the original line, but I don't see the harm.  We might want to tweak write_TOA_file() a bit at some point.
