### ISSUE TITLE
orbital phase calculations should use barycentric times

### ISSUE THREAD

**Issue by scottransom** [nanograv/PINT#475]
I just noticed that for the GUI, the topocentric (usually0 times are used to compute binary phase.  But the ephemerides are in barycentric times, so that's what should be used.

This also applies to issue #111 

https://github.com/nanograv/PINT/blob/cda85493ab3f78ac67e42527bd617fb3323570fe/pint/pintk/pulsar.py#L132

**Comment by paulray** [comment]
Indeed, that sure is wrong!

**Comment by aarchiba** [comment]
Shouldn't it use times as measured at the binary barycenter? Is that even a notion in pint? 

That is, DM and transverse-velocity corrections should be made before using them to compute orbital phases.
