### ISSUE TITLE
scipy versions

### ISSUE THREAD

**Issue by adambrazier** [nanograv/PINT#478]
I was just installing psrsigsim, which depends on PINT, so I installed PINT but importing that (which happens when you import psrsigsim) breaks in the version of scipy I get (1.3, based on the requirements.txt specification of >= 0.18.1) when installing from the PINT requirements.txt, because scipy.misc.factorial isn’t in there any more (you should use scipy.special.factorial).

So, just an FYI that the current scipy version in requirements.txt, which is >= 0.18.1, either needs modifying to have a ceiling (1.0.0 seems to work, when I wrote it into requirements.txt) or the import would need to change and the version go to >=1.0.0 (but that might break other stuff!)

**Comment by paulray** [comment]
How can we figure out what version of scipy first included `scipy.special.factorial`?

I assume that the travis tests end up running with a scipy later than 1.0 given that requirements spec, so I assume we'd be fine just changing the import.

**Comment by adambrazier** [comment]
The deprecation of misc.factorial appears to have happened in 1.0.0 so I assume special.factorial appeared then (or at least that was when the advice to use it appeared).

 

Cheers

 

Adam

**Comment by adambrazier** [comment]
Oh, wait, it was also there in 0.14

 

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.special.factorial.html

 

Cheers

 

Adam

 

 

From: Adam Brazier <abrazier@astro.cornell.edu> 
Sent: Thursday, May 23, 2019 10:40 AM
To: 'nanograv/PINT' <reply@reply.github.com>; 'nanograv/PINT' <PINT@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [nanograv/PINT] scipy versions (#478)

 

The deprecation of misc.factorial appears to have happened in 1.0.0 so I assume special.factorial appeared then (or at least that was when the advice to use it appeared).

 

Cheers

 

Adam

**Comment by paulray** [comment]
I found an old version of scipy (0.19.1) and it includes `scipy.special.factorial`.
So, I'd say it is fine to change the import.

**Comment by luojing1211** [comment]
I can make a pull request.


-Jing

**Comment by aarchiba** [comment]
Closed by #479 can someone please mark this closed?
