### ISSUE TITLE
Location error when importing TOAs

### ISSUE THREAD

**Issue by nanograv-pire** [nanograv/PINT#48]
In the most recent commit if I try to read in the tim file from the example ipython notebook I get an error related to this:

    310         elif obs in observatories:
    311             if  location is not None:
    312                 raise ValueError("Specifying location for observatory TOAs is not currently supported.")
    313             if type(MJD) in [float, numpy.float64, numpy.float128]:

and complains that global location is not defined.

Any ideas Paul?  It's from the new block of code that you added in toa.py.  I assume that it just needs to be initialized somewhere but I can't sort out exactly where.

**Comment by paulray** [comment]
Closed with pull request #49
