### ISSUE TITLE
calc_chi2 does not use noise model

### ISSUE THREAD

**Issue by pennucci** [nanograv/PINT#482]
See also #375, but I think this is unrelated.  If there is a Noise Component, I think the calc_chi2 function should be using the Scaled TOA errors / ECORR; instead, it just pulls the raw TOA uncertainties.

**Comment by scottransom** [comment]
Note that they are not necessarily the raw TOA uncertainties.  If the EFAC/EQUAD is specified in the .tim file, then the errors are scaled as the TOAs are read in.  We will have to check for things like that.

**Comment by demorest** [comment]
Tim is right, the `resids.calc_chi2()` computation is not appropriate in the GLS case.  The chi2 returned by the `GLSFitter.fit_toas()` function is correct though.  We should figure out a less confusing way to deal with this.  Maybe `calc_chi2` should go away and chi2 should always be retrieved from the fitter?

**Comment by luojing1211** [comment]
Should we also provide a convenient function for computing the TOA errors
based on the timing model parameters?
-Jing

**Comment by scottransom** [comment]
Hmmm.  I'm not really keen on making chi^2 have to be computed using a fitter.  We should be able to properly compute chi^2 anytime we have a model and a TOAs.  Maybe there is a relatively easy way to make `resids.calc_chi2` always return the right thing?

**Comment by demorest** [comment]
For the GLS case I think that would mean duplicating a lot of the code (various matrix stuff) from `GLSFitter` into `resids`.  That doesn't seem like a great idea either..

**Comment by scottransom** [comment]
Is the only real issue when there are rednoise params?  If so, we could have `resids` check for that and give a warning or error that there will be a problem.

**Comment by demorest** [comment]
Red noise, and also ECORR.  We should have a generic method in noise model classes that tells whether there is any correlated noise components present (non-diagonal cov matrix).  If not, resids can apply the simple/standard chi2 calcuation.

**Comment by scottransom** [comment]
I like that idea.

**Comment by aarchiba** [comment]
In the more complicated case, can the fitter be called with all parameters held fixed or will it implode? Even if we're okay with it being an expensive call, the fitter will output the chi-squared *after* the fit was done, which isn't really what the user asked.

Alternatively, if a fit *has* been done, why not store the chi-squared value and return that?

**Comment by aarchiba** [comment]
Actually, if I'm not missing something, it looks like not much of the GLS code is needed - if you have an appropriate GLS object (`self` here), the relevant lines seem to be:
```
                cov = self.model.covariance_matrix(self.toas)
                cf = sl.cho_factor(cov)
```
And, using the current residuals as `newres`:
```
                chi2 = np.dot(newres, sl.cho_solve(cf, newres))
```
With a little code rearrangement one could just run GLS with maxiter=0... but this doesn't seem so bad to put in the residuals class.
