### ISSUE TITLE
get_flag() value for TOA

### ISSUE THREAD

**Issue by mtlam** [nanograv/PINT#487]
It would be useful to be able to get the values of a single flag for all TOAs. For example, if I want the frequencies, I can call get_freqs(), which returns the frequencies for all TOAs. If I want the frontend value for all TOAs, the useful function would be something like get_flag('fe'), of something along the lines of:

flags = toas.get_flags()
map(lambda x: x['fe'], flags)

**Comment by mtlam** [comment]
Similarly, since it is not obvious that the filename that generated a TOA is now a flag called "name", it would be useful to have another convenience function like get_name() that wraps this one.

**Comment by luojing1211** [comment]
Addressed by PR #489
