### ISSUE TITLE
Equivalent dmxparse.py script

### ISSUE THREAD

**Issue by mtlam** [nanograv/PINT#490]
As in TEMPO, which has a dmxparse.py script which will report reduced DMX-parameter uncertainties with respect to the systematic offset from the mean DM, it would be useful for a utility which would take the parameters and the covariance matrix and produce similar output. This should be done within the function calls rather than requiring a script to redirect to a text file. Personal preference is to do output the same format as TEMPO with a *.dmx filename extension as default.

**Comment by bshapiroalbert** [comment]
I've done a little work on this and have some functions written that use the PINT `toa` and `fitter` objects, and the covariance matrices to get the DMX values and uncertainties in the same way that `dmxparse` does, at least as far as I can tell. I've compared results on a few test cases and it seems to be consistent with results from `dmxparse`. I've attached a python script (as a text file cause it doesn't like .py files) that has the two functions in it here, if it's helpful for adding this feature in. [brent_utils.txt](https://github.com/nanograv/PINT/files/4199750/brent_utils.txt)
