### ISSUE TITLE
Ability to change PEPOCH, etc.

### ISSUE THREAD

**Issue by mtlam** [nanograv/PINT#491]
Given a new epoch, the code should be able to change the spin parameters accordingly. Similar functionality should be done for POSEPOCH and probably also DMEPOCH.

**Comment by luojing1211** [comment]
Just a short double-check:
Do you mean a function to change the related parameters when changing the epoch, based on the parameter value new?

**Comment by mtlam** [comment]
Yes. So for PEPOCH, if you change a new one, it should set a new F0, F1, etc. (including higher-order terms if available). DMEPOCH I guess does the same but with DM derivatives (DM001). And then POSEPOCH needs to rotate things according to the binary model.

So my thought is that there should be a function that would work like `model.change_epoch(57000)` and then the output would be the new parameters and PEPOCH, etc., set to 57000.

**Comment by luojing1211** [comment]
I have a question about the epoch time scale. For instance, PEOCH we have:
```
phase(t) = P0 + F0 * (t - PEPOCH - delay(t)) + 1/2 * F1 * (t - PEPOCH - delay(t)) ^2 
nu0(t) = d phase(t) /d (t - PEPOCH - delay(t)) = F0 +  F1 * (t - PEPOCH - delay(t)) 
``` 
If we change PEPOCH to PEPOCH', the new F0, let us call it F0', would be: 
```
F0' = nu0(PEPOCH') =  F0 + F1 * (PEPOCH' - PEPOCH - delay(PEPOCH')) + ...
```
My question is what the the time scale of PEPOCH' ? Is it a time at one observatory. If yes, which observatory should we choose? This is important for delay(PEPOCH') term.

**Comment by paulray** [comment]
Since it is evaluating the phase model, it must be MJD(TDB) transferred to the pulsar via all the delay terms, right?  If we ever support TCB, then it would be that instead.

**Comment by scottransom** [comment]
The "etc" also should include binary orbital phase (T0 or TASC updating)

**Comment by rossjjennings** [comment]
@luojing1211's current implementation of this for for PEPOCH doesn't work on a model object without TOAs. For example, if I run

```
import pint
from pint import toa, models, residuals, fitter
from astropy.time import Time

model = models.get_model('NANOGrav_12y/par/J1713+0747_NANOGrav_12yv2.gls.par')
t0 = Time(56000, scale='tdb', format='mjd')
model.change_pepoch(t0)
```
I get the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-9e9c684d9bf8> in <module>
----> 1 model.change_pepoch(Time(56000, scale='tdb', format='mjd'))

~/anaconda3/lib/python3.7/site-packages/pint/models/spindown.py in change_pepoch(self, new_epoch, toas, delay)
    148             new_epoch = Time(new_epoch, scale="tdb", format="mjd", precision=9)
    149         # make new_epoch a toa for delay calculation.
--> 150         new_epoch_toa = toa.get_TOAs_list([toa.TOA(new_epoch)], ephem=toas.ephem)
    151 
    152         if self.PEPOCH.value is None:

AttributeError: 'NoneType' object has no attribute 'ephem'
```
It looks like this is because the `toas` parameter is not actually optional -- it's being used even though it's set to the default value of `None`. I don't know why it's necessary to use it here, though. @luojing1211, can we just remove that line?

**Comment by luojing1211** [comment]
I think the flag "ephem" in the new_epoch_toa is unnecessary and you can remove it. Could you make a Pull Request? Any you could also add an unittest for this function. I am happy to work with you if you need help.

**Comment by rossjjennings** [comment]
I'll work on making a pull request. Do we need `new_epoch_toa` at all, though? It doesn't look like it's used anywhere else in the function.

**Comment by paulray** [comment]
I think this is done. Can it be closed?
