### ISSUE TITLE
 test_wrong_path fail

### ISSUE THREAD

**Issue by ktzhao** [nanograv/PINT#497]
ERROR: test_wrong_path (test_observatory.TestObservatory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/k/psrsoft/PINT/tests/test_observatory.py", line 82, in test_wrong_path
    _ = site.clock_corrections(self.test_time)
  File "/home/k/psrsoft/PINT/pint/observatory/topo_obs.py", line 192, in clock_corrections
    format=self.clock_fmt, obscode=self.tempo_code))
  File "/home/k/psrsoft/PINT/pint/observatory/clock_file.py", line 59, in read
    return cls._formats[format](filename, **kwargs)
  File "/home/k/psrsoft/PINT/pint/observatory/clock_file.py", line 95, in __init__
    mjd, clk, self.header = self.load_tempo2_clock_file(filename)
  File "/home/k/psrsoft/PINT/pint/observatory/clock_file.py", line 108, in load_tempo2_clock_file
    f = open(filename,'r')
IOError: [Errno 2]  No such file or directory : '/home/k/psrsoft/tempo2/T2runtime/clock/fake2gps.clk'

**Comment by luojing1211** [comment]
How did you run the tests?

-Jing

**Comment by scottransom** [comment]
@luojing1211 Note that @clp3ef and I have also recently seen this fake2gps.clk issue when running tests.  It is happening when running all the nosetests as per the instructions.

**Comment by scottransom** [comment]
And note that fake2gps.clk does not seem to be provided in TEMPO2 anymore.  That might be the issue.

**Comment by luojing1211** [comment]
Since this is the test for the wrong path, it should raise an error. It will catch the RuntimeError, but the error message gives an IOError. I think that is why.

**Comment by paulray** [comment]
Ah, I found this issue, which I'm having too.  Can we fix just by catching the right Exception? I'm not sure fake2gps.clk ever existed.

**Comment by aarchiba** [comment]
Since you can reproduce it, can you tell who is asking for it? pytest with the --pdb will drop you into the debugger wherever the IOError was raised and you can walk up and down the stack trying to figure out who wants it and why. Whatever wants it needs to be fixed.

**Comment by ktzhao** [comment]
I don't know if it is necessary for test the wrong path.
But it(1 test faill) will confuse beginners.

**Comment by paulray** [comment]
The problem is on line 80 of tests/test_observatory.py. It asserts that RuntimeError will be raised. In the example above from @ktzhao it raises IOError instead, and in my pytest run, it raises FileNotFoundError. So I'm not sure which Exception should be checked for.  I'm also not sure that we really need this test. @luojing1211 what is it really trying to test?

**Comment by paulray** [comment]
The difference is python2 vs python3. Is there a way to check for a different Exception class in the test for Python2 vs Python3?
```
% python2
Python 2.7.16 (default, Sep  7 2019, 20:09:55) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> f = open('xx','r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 2] No such file or directory: 'xx'
>>> 

% python3.6
Python 3.6.9 (default, Sep  7 2019, 20:24:16) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> f = open('xx','r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'xx'
```

**Comment by luojing1211** [comment]
This actually tests if the observatory object does not have the correct clock correction path, it should raise the right error. But there was a discussion about should we allow this to append. Some observatories do not update their clock correction files.

**Comment by paulray** [comment]
@luojing1211 I don't really get what you are saying. What exactly is this test supposed to show?  It is causing test failures in the current version so I think we should fix it.

**Comment by paulray** [comment]
I also don't understand how the most recent travis-ci builds of master show up as passing. Does the TEMPO2 that they use include fake2gps.clk?  That is the only way I think it should pass.

**Comment by aarchiba** [comment]
> This actually tests if the observatory object does not have the correct clock correction path, it should raise the right error. But there was a discussion about should we allow this to append. Some observatories do not update their clock correction files.

So there are two definitions of "path" in play at the moment. 

One is path in the sense of location of a file. Are you testing what happens if a needed clock correction file is missing? In that case we need to make sure some exception is raised that indicates to the user that an essential file is missing. In modern python that should be FileNotFoundError, while in python 2 it should probably be an OSError with an appropriate errno. This isn't too hard to write up as a test.

The other thing path could mean is path through the forest of possible clock correction files. After all, the code needs to somehow get from the observatory time scale to TAI via a series of clock corrections. We could reasonably (should!) test how this system behaves when no path is available, or when one path is available but missing a file but another fall-back path is available.

I *think* that this problematic test is of the former?

**Comment by aarchiba** [comment]
Aha. Okay. So one problem is that the test tries to look up the location of fake2gps.clk in the TEMPO2 environment variable, and if that's not set, you get a RuntimeError (which the test currently expects). But if the variable is set, you instead get an error about not being able to find the file. Which the existing code is surprised by, and fails the test. PR #544 fixes this. I'll see if I can set up Travis runs with and without usable external clock correction directories.

**Comment by luojing1211** [comment]
I see. So it is testing two failing cases right now, and we should really handle it one a time. However, I think this relates to a bigger question. Should we allow the case that a clock correction file is not given? For instance, CHIME did not publish its clock correction file for a while.

**Comment by paulray** [comment]
I guess if there are no clock corrections for an observatory, PINT should emit a warning and assume that UTC(obs) = UTC.  But, what to do if the TOAs go beyond the end of an existing clock correction file? Certainly warn, but maybe error unless the user explicitly acknowledges that the clock corrections will be extrapolated.  

Note that I think Anne has already noted that some clock correction files are poorly designed in that they use MJD 99999 (or 60000 or 100000) to indicate "infinitely into the future", which will make it hard to know when PINT is extrapolating.  utc2tai.clk is a prime offender.

**Comment by aarchiba** [comment]
> I guess if there are no clock corrections for an observatory, PINT should emit a warning and assume that UTC(obs) = UTC. But, what to do if the TOAs go beyond the end of an existing clock correction file? Certainly warn, but maybe error unless the user explicitly acknowledges that the clock corrections will be extrapolated.

I think if clock correction files are not available for an observatory PINT should refuse to correct times from that observatory. Prefer refusing to answer to producing wrong answers.

If the observatory actually produces already-corrected data, the user can specify that on observatory object construction. If the observatory publishes uncorrected data but not the clock corrections, PINT should summon a mob with pitchforks and torches. Failing that, a user can create a clock correction file with no actual information "extrapolating".

> Note that I think Anne has already noted that some clock correction files are poorly designed in that they use MJD 99999 (or 60000 or 100000) to indicate "infinitely into the future", which will make it hard to know when PINT is extrapolating. utc2tai.clk is a prime offender.

This is python, we can allow observatory constructors to specify that their clock files are poorly designed and/or detect such guard values and treat them as extrapolation.

We can (should!) also provide PINT with sensible default extrapolation, as well as sufficient caution to make sure that users are happy with using extrapolated data before doing so.
