### ISSUE TITLE
toa.get_mjds() Issue

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#52]
The get_mjds() has problem to get mjds. 
"""
Traceback (most recent call last):
  File "examples/fit_NGC6440E.py", line 22, in <module>
    xt=[x.value for x in t.get_mjds(high_precision=False)]
  File "/Users/jingluo/Research_codes/PINT/pint/toa.py", line 408, in get_mjds
    return numpy.array([t.mjd.value for t in self.table['mjd']])
AttributeError: 'float' object has no attribute 'value'
"""

**Comment by paulray** [comment]
This appears to have been fixed.  I no longer get errors like this. If anyone still gets this, please report your numpy and astropy versions.  Mine are:
```
In [3]: np.__version__
Out[3]: '1.10.1'

In [4]: astropy.__version__
Out[4]: u'1.0.5'
```
For now, I'm closing this issue.

**Comment by scottransom** [comment]
I think that's because I fixed it with a recent push...  I didn't even realize that this was listed as an issue!
