### ISSUE TITLE
np.float128 misleading and inefficient

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#525]
A number of places in the code we use the dtype np.float128. This is misleading, in that while float128 takes up 128 bits of space, it offers only 80 bits of precision. It is also inefficient: on 64-bit platforms, it is most efficient for computation to pack 80-bit floats into 128 bits so they align better with loads. But on 32-bit platforms, numpy's default type for 80-bit floats is np.float96, because there is no advantage to alignment and a considerable disadvantage to cache use to pad with four more bytes of zeros. We should not be using np.float96 or np.float128 but np.longdouble. 

The sole advantage to these more-specific types is that on machines with no 80-bit support in hardware, np.longdouble==np.float but np.float96 and np.float128 simply don't exist and thus any attempt to use them raises an error. To solve this we could create a type pint.extended_float that raises an error on import if there is no extended float type and otherwise provides whatever there is with at least eighteen decimal places.

**Comment by luojing1211** [comment]
Hi @aarchiba, I am revising the PITN paper now. There are several places I used np.float128. Should I change this to 80-bit floats as well? Or should I keep np.float128 for this version?

**Comment by aarchiba** [comment]
In the paper I think we should be very clear we are using hardware 80-bit floats. Unless you are mentioning API details that need np.float128, I think I wouldn't mention them at all. I should probably make a quick pull request that just introduces a high-precision float type, checks it supports enough precision for us, and then uses that throughout the code everywhere we now say np.float128 or np.longdouble. 

Of course, we actually use a mixture of 80-bit floats and the astropy Time object's "double-double" numbers (an implicitly-added pair of double-precision numbers). The Time objects support more precision but are slower and don't support all sorts of useful operations.
