### ISSUE TITLE
PINT does not support BTX model

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#537]
We need to add support for the BTX model, which is like BT but uses the FB0, FB1, ... expansion of orbital frequency instead of PB, PBDOT

**Comment by luojing1211** [comment]
I think we have it. Is there any problem to load them?

**Comment by paulray** [comment]
I think we support FBx on ELL1 but not BTX.  Also there is no BTX par file in the test suite.  Here is what I get
```
In [2]: m = pint.models.get_model('/Users/paulr/Documents/Fermi/RadioPulsarDiscoveries/MSP J1048+2339 (AO-Camilo:Cromartie)/deneva-2015-07-28/newBTX2.par')                                   
WARNING: Unrecognized parfile line 'FB0            4.6199972887529510957e-05 0  0.00000000001217995515' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'FB1            2.4480501361544716582e-17 0  5.6299996745955023763e-19' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'FB2 0' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'FB3            0' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'T0             56637.597474725421502     0  0.00004393694797218929' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'A1             0.83615247362289950729    0  0.00000647355362840258' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'OM             0' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'ECC            0' [pint.models.timing_model]
WARNING: EPHVER 5 does nothing in PINT [pint.models.timing_model]

```

**Comment by paulray** [comment]
In the above, note that there is no complaint that BTX is not recognized.

**Comment by aarchiba** [comment]
Let me note that there are two different notions of BTX - both extend BT, but one supports FBn and the other (also?) supports two Keplerian orbits. The latter is not present in TEMPO2.

Does PINT raise an exception for an unrecognized binary model? That is, if you tell it "BINARY BTX" does it raise an exception, silently give you an isolated pulsar, or actually implement BTX?

**Comment by luojing1211** [comment]
That is a bug in the model builder. I can take a look.

**Comment by luojing1211** [comment]
@aarchiba it should. If it is not, I believe there is a bug.

**Comment by aarchiba** [comment]
Let me add that I've been doing some work on the model builder - which is a mess - in #520 . Unfortunately the business of "prefix parameters" and "mask parameters" is very confusing and not well documented. So my current implementation, in get_model_new, can't yet cope with them. But I do have more thorough data validation.

**Comment by paulray** [comment]
I see that PR #356  claims to add BTX support but evidently does not?

**Comment by luojing1211** [comment]
@aarchiba I agree with you about the messy module builder. We should discuss this offline.

**Comment by aarchiba** [comment]
As a useful exercise - maybe not for the paper, but certainly for PINT documentation - could you write out how PINT decides which model components to use? Like, there are particular magic keywords that trigger AstrometryEcliptic rather than AstrometryEquatorial, but is it possible to find out what they are? What happens if both kinds of keyword are present? Neither?

**Comment by luojing1211** [comment]
@paulray I believe that PR was tested with BT model. But I will have to check.

**Comment by aarchiba** [comment]
> @aarchiba I agree with you about the messy module builder. We should discuss this offline.

Does PINT have a Slack, a Discord, an IRC channel, or any other quasi-real-time interaction mechanism between email/github and Zoom?

**Comment by paulray** [comment]
> > @aarchiba I agree with you about the messy module builder. We should discuss this offline.
> 
> Does PINT have a Slack, a Discord, an IRC channel, or any other quasi-real-time interaction mechanism between email/github and Zoom?

I don't think so. We could make a channel on the NANOGrav Slack, but I think that would limit the discussion to only NANOGrav folks

**Comment by aarchiba** [comment]
Gitter provides a Slack-like setup associated with a GitHub repository:
https://gitter.im/
Like Slack, it logs everything to the cloud.

**Comment by aarchiba** [comment]
With PR #520 merged, PINT now raises an exception on an invalid model or missing essential parameters so people will at least know BTX is missing. So I guess this bug becomes really "PINT doesn't support BTX" - the model name is not recognized. If there's an implementation, if our BT model can actually handle the variations you want, then it's just a matter of making it recognize BTX in par files. But that needs to be tested!

**Comment by scottransom** [comment]
Note that PINT *can* deal with FBX params.  So at least that part of the BTX model does work.  We've used it with Fermi timing.

**Comment by luojing1211** [comment]
This actually creates another question.
In the current setup, FBX is not tied to the BTX model. For instance, one
can use DD and FBX.  This creates two layers of validating a par file.

1. Check the BINARY
2. Check the FBX.

For the case of BTX, are we going to make a wrapper model component for
BT + FBX?


-Jing

**Comment by paulray** [comment]
Yes, a lot of the code is in there, so maybe it is just that 'BTX' is not recognized.
In fact, if I take a BTX par file and change it to 'BT' it does load but the m.params list has both PB and FB parameters.

**Comment by paulray** [comment]
@luojing1211 if PINT supports either PB/PBDOT or FBX within BT, then maybe just making "BTX" a synonym for "BT" is all we need?

**Comment by aarchiba** [comment]
Does BTX do everything BTX does in other software? In particular TEMPO's BTX handles multiple companions (ignoring their interactions). So I'm hesitant to make it a synonym, though at least PINT should soon complain about unexpected parameters (perhaps raise an exception rather than give the user the wrong model?)

There's also a risk in letting people use BT in PINT with parameters BT doesn't support elsewhere - that will result in par files when you take them to other machines (for example the GUPPI observing system that runs TEMPO).

I think BT should use the code it uses now but refuse to accept non-BT parameters. BTX would use the same code but accept the parameters BTX does. If we support things nobody else does, that can be BT-PINT.

**Comment by paulray** [comment]
I just ran into this again. "BINARY BTX" is not recognized by PINT, although it seems that the FBx parameters do work with the BT model.

**Comment by paulray** [comment]
This just came up yet again. @juliadeneva tried to use PINT for a par file with BTX.  We really need to get "BTX" recognized by the PINT model builder, or at an *absolute minimum* it should give a useful error that while BTX is not supported (e.g. the multiple companions part), BT does handle FB parameters in PINT.
