### ISSUE TITLE
PINT Post-Fit Covariance Matrix Output

### ISSUE THREAD

**Issue by bshapiroalbert** [nanograv/PINT#542]
I know PINT must compute the covariance matrix or some proxy when doing the parameter fitting, but I can't find where, or if, it saves the values, similar to how TEMPO outputs a matrix.tmp file. It would be useful if PINT saved this post-fit covariance matrix somewhere, or made it easily accessible. If this already exists and I just couldn't find it, I apologize.

**Comment by aarchiba** [comment]
I think you're right, the matrix is computed, the diagonals are extracted to compute the parameter uncertainties, and then the matrix is thrown away. It should probably be stored on the model object, alongside the parameter uncertainties.

**Comment by scottransom** [comment]
Exposing the post-fit parameter covariance matrix is part of PR #507, which will hopefully be merged within the next week-ish...  We are working on it!

**Comment by bshapiroalbert** [comment]
That's great to hear! Thanks so much for the quick reply!

**Comment by rossjjennings** [comment]
I've been looking at this recently as part of getting @bshapiroalbert's dmxparse code added to PINT (which will address #490). While PR #507 was eventually merged, the `get_covariance matrix()` function (in `residuals.py`) that would have done this died before that happened, so as far as I can tell we still don't have a way to do this.

**Comment by paulray** [comment]
I know we can now get covariance and correlation matrices, so I'm closing this.
