### ISSUE TITLE
Implement DMX model

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#55]
Add support for DMX (strided DM fit) model to PINT. Needs to be supported in the model builder as well.

**Comment by luojing1211** [comment]
I add a pull request called Prefix. It should be ok to do the job.

**Comment by luojing1211** [comment]
Do we have a simple DMX test data? Since we have the generic DM setup, we should have a good test on it.

**Comment by luojing1211** [comment]
DMX model is in place, so closing.
