### ISSUE TITLE
tim file commands must be UPPERCASE

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#555]
I tried using "include" in a .tim file to read in an included file. This works fine in Tempo2, but in PINT the parser does the comparison as cmd == "INCLUDE" so it requires the command to be all uppercase. Is this the desired behavior?  Should we support lower case commands, like Tempo2 does? Note that TEMPO seems to require all uppercase.

**Comment by aarchiba** [comment]
Here is somewhere I think we should accept as wide a range of options as possible but emit as narrow as we can - that is, read arbitrary ase but write upper only.

**Comment by paulray** [comment]
Concur
