### ISSUE TITLE
In TOA line, a flag can overwrite a positional value

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#558]
I just got a NRT TOA file whose lines look like this:
```
FORMAT 1
 nuppi_55804_1821-24_155239.F8Tp 1263.05500000 55804.81748030375163339 0.48700 ncyobs -i NUPPI -r ROACH -gof 1.32588 -tpl NUPPI_1484_smoothed.prof -freq 1484.0 -bw 512.0 -tobs 3718.6 -orig_nbin 2048 -orig_nsub 61 -orig_nchan 128 -obsnchan 144 -nsub 1 -nchan 8 -sublen 3718.6 -chanwidth 64.0 -snr 115.9 
 nuppi_55804_1821-24_155239.F8Tp 1324.48300000 55804.81748029492493046 0.40100 ncyobs -i NUPPI -r ROACH -gof 1.31246 -tpl NUPPI_1484_smoothed.prof -freq 1484.0 -bw 512.0 -tobs 3718.6 -orig_nbin 2048 -orig_nsub 61 -orig_nchan 128 -obsnchan 144 -nsub 1 -nchan 8 -sublen 3718.6 -chanwidth 64.0 -snr 115.9 
 nuppi_55804_1821-24_155239.F8Tp 1386.78300000 55804.81748028949086660 0.44300 ncyobs -i NUPPI -r ROACH -gof 1.26227 -tpl NUPPI_1484_smoothed.prof -freq 1484.0 -bw 512.0 -tobs 3718.6 -orig_nbin 2048 -orig_nsub 61 -orig_nchan 128 -obsnchan 144 -nsub 1 -nchan 8 -sublen 3718.6 -chanwidth 64.0 -snr 115.9 
```

Notice that one of the flags is `-freq`.  In `parse_TOA_line()`, it builds a dictionary of the positional values (`obs`,`freq`,`errror`) as well as all the flags. In this case the `-freq` flag silently overwrites the `freq` so the TOA gets 1484.0 MHz as the frequency instead of the correct 1263.055 MHz.  

I'm not sure if this counts as a PINT bug or a user error, but it should not happen.  Perhaps we should make "freq", "obs", and "error" reserved words that can't be used as flags?  Or we should change the names of those dictionary items to reduce the chance of a conflict (e.g. "_freq").

Thoughts?

**Comment by aarchiba** [comment]
Does anyone currently use those as actual flag values with meanings distinct from their positional meanings? If not (I suspect not) I think we should raise an exception on encountering a flag with the same name as a positional entry. This does mean giving the positional entries canonical names, which I suppose PINT already does in the form of table columns, but this pushes it out to a restriction on .tim files generally. Which I approve of.

It's an easy fix software-wise.

**Comment by paulray** [comment]
I believe the NRT folks are using the `-freq` flag to specify the observing band (I guess the receiver).

I agree that we can throw an exception in the case where a flag would overwrite a positional entry.

**Comment by scottransom** [comment]
Given that TOA lines have specific formats, they should trump any flags.  So why not just allow the flag to be parsed but with a slightly modified name (kind of like the "_freq" suggestion, but maybe something more obvious like "flag_freq"?  It should *definintely* not overwrite the frequency column, though.

**Comment by aarchiba** [comment]
> I believe the NRT folks are using the `-freq` flag to specify the observing band (I guess the receiver).

As distinct from the actual frequency of the TOA? Fantastic. Well we shouldn't break all their .tim files.

> I agree that we can throw an exception in the case where a flag would overwrite a positional entry.

It's not technically necessary that positional entries have names, exactly; they have column names within PINT, but apart from pulse number I don't think any of the flags get turned into columns on the TOA table (I could be wrong?). So it could be possible (but confusing!) to have both a -freq flag and a freq column on the same TOA, meaning different but similar things. Our reader implementation would need a change but that's nothing.

**Comment by aarchiba** [comment]
> Given that TOA lines have specific formats, they should trump any flags. So why not just allow the flag to be parsed but with a slightly modified name (kind of like the "_freq" suggestion, but maybe something more obvious like "flag_freq"? It should _definintely_ not overwrite the frequency column, though.

I think renaming flags is asking for trouble - people have their own custom flag names (as we are seeing) and will look for those in the per-TOA dictionaries. The column names are not especially public, which makes them easier to change in some sense, but it's also very reasonable for users to expect the (say) observing frequency column to be called the same thing it's called in the published descriptions of TEMPO2 format.

Just so I'm clear: a proper TOAs object has all its information stored in a Table object it contains, right? And the columns of that table are the standard TOA entries (obs, mjd, a precise mjd that is actually a Time object, freq, an mjd uncertainty, a siteid), possibly another column for pulse numbers and possibly not, and a column whose contents are dictionaries containing flags. Those columns all need to have different names, but the flags could have the same names as columns, right?

**Comment by scottransom** [comment]
yes, the flags *can* have the same names of the columns.  And, in general, those flags are not put in their own columns.  So I don't actually think they should overwrite the default columns.  @paulray did it actually do that?

**Comment by paulray** [comment]
Yep. Look at toa.py line 238, which sets the "freq" entry from the positional value:
```
        d["freq"] = float(fields[1])
```
Then look at how flags are stored in the same dict on line 251:
```
                    d[k] = float(v)
```
That overwrites `d["freq"]`.
Maybe it would be better to have two dictionaries or some other means of separating the positional values from flags.

**Comment by paulray** [comment]
Note that I got this reply from Lucas Guillemot:

> Interesting that the ‘-freq’ flag revealed a bug in PINT! Thanks for letting me know about this issue, I’ve modified my pipeline so that this no longer happens. I replaced ‘-freq’ by ‘-cenfreq’ to indicate the central frequency of the observation, hopefully this new flag isn’t going to create new problems in PINT or tempo2.

**Comment by aarchiba** [comment]
Cool! But we should still fix it. It's a bit cumbersome because the way we handle TOA and TOAs objects is awful, but it's not in principle difficult.
