### ISSUE TITLE
Implement JUMPs

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#56]
Add support for JUMPs in PINT models.

**Comment by luojing1211** [comment]
Hi @vhaasteren , I think this is a good time to implement JUMPs. How hard to implement this right now?

**Comment by luojing1211** [comment]
Can we close this issue, since we have implemented jumps in PINT.  About how to improve jumps, the discussion is open under the issue #142 .

**Comment by luojing1211** [comment]
We have jumps right now. So closing
