### ISSUE TITLE
MCMC based on emcee does not support long doubles

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#565]
The emcee sampler truncates all values to 64-bit floating-point. This means that, for example, TZRMJD cannot be fit to microsecond resolution by MCMCFitter.

**Comment by aarchiba** [comment]
Modern versions of `emcee` now support long doubles correctly. We should detect when a bogus version is being used and complain.

**Comment by paulray** [comment]
At what version of emcee did this support appear?

**Comment by aarchiba** [comment]
Er. When I put it in last fall? Not sure exactly which version. But `emcee` does support python 2 so I think it's probably fine to just require a recent enough version.

**Comment by aarchiba** [comment]
Version 3.0.1 supports long doubles.
