### ISSUE TITLE
Clean install doesn't work under python2.7

### ISSUE THREAD

**Issue by pennucci** [nanograv/PINT#566]
Not sure it was the intention given the imminent sunset, but I just tried a clean install of pint under python 2.7 and I get an error "error: 'egg_base' must be a directory name (got `src`)", which looks related to: https://github.com/pypa/setuptools/issues/1136

i.e., python2 vs python3, but elsewhere I read this might be a setuptools problem.

**Comment by scottransom** [comment]
@pennucci For me, at least, this was fixed by making sure that I was using up-to-date versions of both setuptools and pip.

**Comment by pennucci** [comment]
Ah!  I updated pip, but not setuptools.  That worked. Thanks!

**Comment by aarchiba** [comment]
This specific error is discussed in the current version of the docs. Did
you see that? Were the instructions there sufficient?

Anne

**Comment by pennucci** [comment]
I had not looked in the docs; it wasn't too long ago that I had 
successfully re-installed pint from scratch with no issue, and given the 
large number of recent changes I had assumed that the issue may have 
arisen from them.  Based on that, I didn't even think to look at the 
docs.  In short, it was my lack of due diligence; apologies!

**Comment by aarchiba** [comment]
No worries! I'm just trying to evaluate how effective the new docs and
their structure are.

Anne
