### ISSUE TITLE
TimingModel.replicate fails

### ISSUE THREAD

**Issue by kerrm** [nanograv/PINT#571]
Trying to replicate (copy) a TimingModel results in the error below.  This is trivial, but fixing it reveals a second error when copy_component is not True: calling setup_component once the new TimingModel object has components raises an Exception.  But this will always happen if a TimingModel has both Phase and DelayComponents!  So I suspect this is pretty old code that hasn't worked in a while, and I'm not sure what the correct way to actually replicate a TimingModel is, so I'm opening this issue rather than trying to fix it right away.

[ins] In [475]: modelin.replicate()                                             
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-475-b0faecec8bea> in <module>
----> 1 modelin.replicate()

~/python3_2/PINT/src/pint/models/timing_model.py in replicate(self, components, copy_component)
    403         new_tm = TimingModel()
    404         for ct in self.component_types:
--> 405             comp_list = getattr(self, ct + "_list")
    406             if not copy_component:
    407                 # if not copied, the components' _parent will point to the new

AttributeError: 'list' object has no attribute 'values'

**Comment by paulray** [comment]
Interesting, I was just using deepcopy(modelin), but I'm not sure if that is right. I didn't even know about .replicate.

**Comment by scottransom** [comment]
@kerrm Huh.  I don't even think I knew that a replicate method even existed.  Camryn and I used copy.deepcopy() for this in pintk and that definitely works.

**Comment by scottransom** [comment]
hahaha @paulray

**Comment by kerrm** [comment]
I was just trying to figure out if "FINISH" was stored anywhere in the TimingModel object (it's not) so I was tabbing through the namespace and saw it.

It's obviously not covered by tests, so I thought I'd win some brownie points by fixing the bug AND adding the test.  But alas.

**Comment by aarchiba** [comment]
The method seems to be gone.
