### ISSUE TITLE
What paths should be used for tests?

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#58]
The tests in the tests subdirectory make different, inconsistent, assumptions about the current working directory.  For example test_bt.py tries to read '../tests/J1955.par', while test_model.py tries to read 'tests/J1744-1134.basic.par'.  This means that test_bt.py runs correctly if you are in the main PINT directory (which is how it is run if you use the run-tests.sh script), while test_model.py runs correctly if your CWD is PINT/tests.

So, what is the preferred way to specify the path to files that need to be loaded by the scripts in the test suite?

**Comment by paulray** [comment]
The same issue comes up for the examples/fit_NGC6440E.py script.  It runs if you do:
`python examples/fit_NGC6440E.py`
from the PINT directory, but not if you do
`python fit_NGC6440E.py`
when your current working directory in PINT/examples.

**Comment by demorest** [comment]
This is fixed in PR #132
