### ISSUE TITLE
What is the minimum numpy required?

### ISSUE THREAD

**Issue by mhvk** [nanograv/PINT#584]
In testing in our `scintillometry` package, the runs with `numpy` at 1.14 stopped working with #549 by @aarchiba - I think this is not a problem and we needed to update our minimum version of numpy anyway, but I could't find what PINT's minimum numpy is (or, rather, IIRC, `requirements.txt` gives 1.11 or so and `requirements_dev.txt` doesn't list it).

**Comment by mhvk** [comment]
Just to be a bit clearer: the use of `np.nditer` as a context manager is only possible since numpy >=1.15. That does seem a reasonable minimum version, but it would be good to be explicit about this (and have a travis run that *tests* with the minimum supported version!).

**Comment by paulray** [comment]
Anyone know how to make a travis run that sets all the packages at the *minimum* supported version?

**Comment by mhvk** [comment]
@paulray - over at astropy, we've just switched over to setting up environments with `tox` (which I see PINT has started to use as well), and in `tox.ini`, there's:

https://github.com/astropy/astropy/blob/424b3fb21f8cdf61db7fccb16ceee4c8bc99a80e/tox.ini#L49-L53

which then gets used in `.travis.yml` as:

https://github.com/astropy/astropy/blob/424b3fb21f8cdf61db7fccb16ceee4c8bc99a80e/.travis.yml#L79-L88
