### ISSUE TITLE
Documentation missing in timing_model.py

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#590]
There are a bunch of methods defined in timing_model.py that are not at all documented and some are quite cryptic.  This needs to be fixed, especially for any functions that are supposed to be part of the public API for TimingModel

These include:

- `map_component`
- `get_component_of_category`
- `get_deriv_funcs` docs don't say what the allowed values of the `component_type` argument are
- `replicate`

In addition, in general the docstrings need to be more clear about what the arguments are. Are they a string naming something or an instance of something.

Finally, why is there an `add_component` but not a `remove_component`?

**Comment by abhisrkckl** [comment]
Better docstring for `get_deriv_funcs` in #1675 

The other docstrings already contain the requested information.

`replicate` function is no longer present.
