### ISSUE TITLE
Bad naming?

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#591]
For the parameter mapping, it uses "timing_model" for the top level, while all the other levels use their CamelCase class names.  Here is an example:
```
In [1]:  model2.get_params_mapping()

Out [1]: 
{'PSR': 'timing_model',
 'TRACK': 'timing_model',
 'EPHEM': 'timing_model',
 'UNITS': 'timing_model',
 'POSEPOCH': 'AstrometryEquatorial',
 'PX': 'AstrometryEquatorial',
 'RAJ': 'AstrometryEquatorial',
 'DECJ': 'AstrometryEquatorial',
 'PMRA': 'AstrometryEquatorial',
 'PMDEC': 'AstrometryEquatorial',
 'PLANET_SHAPIRO': 'SolarSystemShapiro',
 'DM': 'DispersionDM',
 'DM1': 'DispersionDM',
 'DMEPOCH': 'DispersionDM',
 'NE_SW': 'SolarWindDispersion',
 'SWM': 'SolarWindDispersion',
 'F0': 'Spindown',
 'F1': 'Spindown',
 'PEPOCH': 'Spindown',
 'F2': 'Spindown',
 'TZRMJD': 'AbsPhase',
 'TZRSITE': 'AbsPhase',
 'TZRFRQ': 'AbsPhase'}
```

This comes from this line in timing_model.py
https://github.com/nanograv/PINT/blob/b9bda477435b69c31a46c57a4764dcec10de4180/src/pint/models/timing_model.py#L476

I propose that this be changed to TimingModel instead of timing_model.  There are several places in the code that would need to be fixed.

**Comment by paulray** [comment]
@luojing1211 should we fix this or close it?

**Comment by luojing1211** [comment]
Let us change to TimingModel.

**Comment by abhisrkckl** [comment]
This is still in snake case.
