### ISSUE TITLE
What is delta_pulse_number?

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#592]
I just noticed the `delta_pulse_number` column that can be in a TOAs table. I don't see where this is documented. I think @clp3ef added it as part of her pintk improvements. 
It would be good to add some helpful docs.
For example, line 52 of residuals.py, please add some comments describing what is happening there.
It looks like the column always gets added if it was not there already.
And, I don't quite get what `set_pulse_nums` does. Could some explanation be added?

**Comment by scottransom** [comment]
Yeah, that needs better docs.  It is primarily used to implement PHASE commands to add or remove phase rotations from certain TOAs.  Usually that is done interactively, so that is why it was done as part of the pintk improvements.

**Comment by paulray** [comment]
Yeah, it isn't in the PINT paper or anywhere that I can find.  One problem with docstring-only type documentation is that it can be hard to find docs for things that aren't classes/functions or methods.  Maybe there should be more in the docstring of the TOAs object since it is that object that holds the table.  Probably all the columns in the table should be defined there.

You can tell that I'm actually trying to use PINT for something useful since I've been posting a lot of issues! :-)

**Comment by paulray** [comment]
Ack, there is some confusion about the column names in the TOAs table for pulse numbers.  Some places use "pn" as the column name and some use "pulse_number"!  This needs to be rectified.
The TOA flag is called "pn", but the column name should be "pulse_number", I think.
The "pn" column name is used in `write_toa_file()` as well as a couple places in pintk.

I'm just trying to load a model and TOAs, then compute pulse numbers and have it work. So far, I'm failing.

**Comment by aarchiba** [comment]
Are you running into #512 too?

**Comment by paulray** [comment]
> Are you running into #512 too?

I haven't tried that use case, sorry

**Comment by aarchiba** [comment]
This may be resolved in #815 - please check whether the table documentation there clears things up. It also fixes a bug to do with what pulse number columns are called.

**Comment by paulray** [comment]
My guess is this can be closed. @scottransom

**Comment by scottransom** [comment]
Yes, this can also be closed.  `delta_pulse_number` *is* used by `pintk` to add and remove individual (or multiple) phase wraps from the model-calculated pulse numbers.  And it works!  (at least now.)
