### ISSUE TITLE
provide a nice interface for orbit phase

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#598]
Currently, to get the orbit phase out, one has to do the following 
```
t = get_TOAs('.tim')
m = get_model('.par')
delay = m.delay(t)
orbit_phase = m.components['binary_model_name'].binary_instance.orbit()
```
Howevery this should be integerated to a convenient function.

**Comment by paulray** [comment]
I think it is `orbits()` instead of `orbit()`

**Comment by paulray** [comment]
Also see #475 
Is that corrected?

**Comment by paulray** [comment]
And to copy some comments from Slack:
* Add docstrings that explain what "phase" means (eccentric or mean anomaly)
* Add unit tests for both parameterizations (PB, PBDOT, and FBx)
* How is it getting the times? Are they cached in the model object? That seems very dangerous!  One could have one model object and multiple sets of TOAs!

**Comment by luojing1211** [comment]
@paulray, the last point deserves a separate issue, it is cached in the "stand along binaries".

**Comment by paulray** [comment]
Yep, I'll make an issue for that. On my flight yesterday I looked through the binary code, which I hadn't done in detail before. It is great that the orbital phase calculations are handled by their own object that can be extended! But, that caching of TOAs is scary and definitely can cause some bugs/unexpected  behavior.

**Comment by paulray** [comment]
See also #111, which probably can be closed.

**Comment by dlakaplan** [comment]
Would be great to also provide access to the various anomalies (mean, eccentric, true)

**Comment by dlakaplan** [comment]
Absolutely - I would use this for optical analysis.

**Comment by bshapiroalbert** [comment]
Has anything been done related to this yet? I think this would be really useful if possible, especially with the new epoch_averaging function. Right now if we want to plot the epoch averaged residuals from the `ecorr_average()` function against orbital phase right now we have to remake a set of TOA objects with the MJDs and frequencies that come out, which is do-able, but tedious.

**Comment by paulray** [comment]
Not that I'm aware of. This issue definitely needs someone's attention.

**Comment by aarchiba** [comment]
The code `kepler.py`, currently unused (#693) is capable of doing a number of conversions between anomalies.
