### ISSUE TITLE
Compute barycentered TOAs

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#60]
A common use case is to compute barycentered times from a TOA or set of TOAs.  PINT should support this in a user-friendly way!

Here, barycentered means converted to the time system TDB (or TCB when that is supported as an option) and the Solar System delay terms from the model should be applied.

Currently, this is not very easy to do.  The example in the sample notebook is only correct for isolated pulsars:
`tt['tdbld'] - m.delay(tt) / 86400.0`

I created a convenience routine to compute this quantity, but then realized that it uses _all_ the delay terms, including the binary delay terms, not just the Solar System delays. It seems that we need some metadata associated with delay terms that specify whether they are Solar System or binary delays. This would allow simple routines to apply the delays appropriate to the Solar System Barycenter, or the binary barycenter (which I think is what you get currently with the above code).

**Comment by luojing1211** [comment]
I the new DD generic model, I added a function called get_barycentricTOA() function in timing_model class. I believe it will match the requirement.

**Comment by paulray** [comment]
I believe this is resolved by `TimingModel.get_barycentric_toas()`, and the ipython notebooks have all been updated to call that, instead of the buggy code mentioned above.
