### ISSUE TITLE
Inconsistent defaults for ECL

### ISSUE THREAD

**Issue by rossjjennings** [nanograv/PINT#610]
Currently, the value used for the obliquity of the ecliptic is determined by the `obliquity` attribute of the `PulsarEcliptic` class. The default value specified in `ecliptic.dat` is equivalent to IERS2010, but when building a model with an `AstrometryEcliptic` component, the IERS2003 value (compatible with Tempo2) is used unless `ECL` is explicitly specified. We should have a consistent default. Probably this means changing the default for `AstrometryEcliptic` to IERS2010, but we might also go with IERS2003 to preserve Tempo2 compatibility.

**Comment by rossjjennings** [comment]
Also, the setting as currently implemented is global across all `PulsarEcliptic` instances. This can lead to some very surprising behavior. For instance, it means that once you call `get_psr_coords()` on *any* model object where `ECL` has not been explicitly specified, `PulsarEcliptic.obliquity` changes to the IERS2003 value for the rest of the session -- the global default is overridden.

**Comment by rossjjennings** [comment]
I think the best way of dealing with this would be to allow different `PulsarEcliptic` objects to have their own `obliquity` values. This matches how astropy treats parameters of other coordinate frames, like the equinox of `BarycentricTrueEcliptic`, and would allow things like reading in multiple par files with different `ECL` values in the same session.

**Comment by paulray** [comment]
Yes, it seems wrong to have the obliquity as a class attribute instead of a property of an instance.

**Comment by luojing1211** [comment]
The reason to make Obliquity a class method is the transformation function accepts a class instead of an instance.  I am not sure if this has been changed in the newer astropy version.

**Comment by rossjjennings** [comment]
Closing now that #613 is merged.
