### ISSUE TITLE
u.cycle is insane and causes astropy 4 to fail

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#615]
See my email to the list, but I think we should make Phases unitless instead of using u.cycle which has many unexpected behaviors. Currently it causes one of the tests to fail when using astropy 4.0 since the unit propagates into photonphase in a way it didn't use to

**Comment by rossjjennings** [comment]
@paulray -- I've tried to reproduce the weird behavior you wrote about in your email, and found that it isn't the default behavior in astropy 4.0. In an astropy 4.0 environment, if I just open up `ipython` and run
```
import astropy.units as u
int(20*u.cycle)
```
I get a `UnitConversionError`. But if I `import pint.models` before the second line, I get `125` as output, with no error.

**Comment by rossjjennings** [comment]
Aha! I think the culprit is `u.set_enabled_equivalencies(u.dimensionless_angles())` [here](https://github.com/nanograv/PINT/blob/a4b33eae5fce21a6010e8665bfeecf9caec8cf96/src/pint/models/stand_alone_psr_binaries/DDK_model.py#L13). This is the only place where it appears outside a `with` block.

**Comment by paulray** [comment]
Glad this is fixed!  But, I think we should have a discussion at some upcoming PINT telecon about whether it might be better to remove the u.cycle units on Phases.

**Comment by rossjjennings** [comment]
Should we close this now that #616 is merged?

**Comment by paulray** [comment]
I still think we should hold it open pending a discussion on whether to stop using u.cycle at all for pulsar phases.

**Comment by paulray** [comment]
Fix is #685

**Comment by Zac-HD** [comment]
FYI you can [put a comment in your PR description which auto-closes linked issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) :slightly_smiling_face:
