### ISSUE TITLE
AttributeError: 'J1744-1134.t2' object has no attribute 'F2'

### ISSUE THREAD

**Issue by vhaasteren** [nanograv/PINT#62]
In the PINT directory:
ipython
import pint.models as pm
m = pm.get_model('J1744-1134.t2.par')
m.read_parfile('J1744-1134.t2.par')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-b346b13aede4> in <module>()
----> 1 m.read_parfile('J1744-1134.t2.par')

/Users/vhaaster/research/code/PINT/pint/models/timing_model.pyc in read_parfile(self, filename)
    334         # combinations of parameters, etc, that can only be done
    335         # after the entire parfile is read
--> 336         self.setup()
    337 
    338 

/Users/vhaaster/research/code/PINT/pint/models/astrometry.pyc in setup(self)
     59 
     60     def setup(self):
---> 61         super(Astrometry, self).setup()
     62         # RA/DEC are required
     63         for p in ("RAJ", "DECJ"):

/Users/vhaaster/research/code/PINT/pint/models/spindown.pyc in setup(self)
     65         for ii in range(self.num_spin_terms, -1, -1):
     66             term = "F%d"%ii
---> 67             if getattr(self, term).value==0.0 and \
     68                     getattr(self, term).uncertainty is None:
     69                 delattr(self, term)

AttributeError: 'J1744-1134.t2' object has no attribute 'F2'

In [9]: exit()

**Comment by vhaasteren** [comment]
git blame says this is something Scott changes recently:

27f97934 pint/models/spindown.py (Scott Ransom         2015-11-05 14:06:37 -0500  67)             if getattr(self, term).value==0.0 and \

**Comment by vhaasteren** [comment]
By the way, I don't really understand why we are doing these checks here in a timing model class. Shouldn't we be detecting and assigning parameters in the model builder class? This seems like the wrong place for deleting attributes like that. The model is(/should be) fully specified in the parfile.

**Comment by scottransom** [comment]
Can you send me that parfile?  I'm not seeing this issue with other parfiles that I have.

**Comment by vhaasteren** [comment]
Ah, I thought this was one of the standard PINT parfiles, but you're right,
it is only on my machine.

Attached

On Wed, Nov 25, 2015 at 10:14 AM, Scott Ransom <notifications@github.com>
wrote:

> Can you send me that parfile? I'm not seeing this issue with other
> parfiles that I have.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nanograv/PINT/issues/62#issuecomment-159691635>.
>



-- 

______________________________________________________________________
 dr. Rutger van Haasteren, Einstein postdoctoral fellow
 Jet Propulsion Laboratory, Pasadena, USA
 E-mail: vhaasteren@gmail.com

**Comment by scottransom** [comment]
As for your question about deleting attributes, the reason is that each model constructor has parameters that it knows about.  And since the possible number of spin derivs is infinite, I wanted a way to only allocate and keep the params/attributes that are actually used in the model in question.  I'm not sure how you would do that with model_builder since that doesn't know specifics about the individual models....

**Comment by scottransom** [comment]
Are you seeing an error right when you read that parfile in with m.get_model?  Because it is working fine for me...

**Comment by vhaasteren** [comment]
No, it's when I read the parfile with m.read_parfile. I am on the latest upstream version...

(dev)[ vhaaster LMC-044086 ~/research/code/PINT (master) ] ipython
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pint.models as pm

In [2]: m = pm.get_model('J1744-1134.t2.par')

In [3]: m.read_parfile('J1744-1134.t2.par')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-b346b13aede4> in <module>()
----> 1 m.read_parfile('J1744-1134.t2.par')

/Users/vhaaster/research/code/PINT/pint/models/timing_model.pyc in read_parfile(self, filename)
    334         # combinations of parameters, etc, that can only be done
    335         # after the entire parfile is read
--> 336         self.setup()
    337 
    338 

/Users/vhaaster/research/code/PINT/pint/models/astrometry.pyc in setup(self)
     59 
     60     def setup(self):
---> 61         super(Astrometry, self).setup()
     62         # RA/DEC are required
     63         for p in ("RAJ", "DECJ"):

/Users/vhaaster/research/code/PINT/pint/models/spindown.pyc in setup(self)
     65         for ii in range(self.num_spin_terms, -1, -1):
     66             term = "F%d"%ii
---> 67             if getattr(self, term).value==0.0 and \
     68                     getattr(self, term).uncertainty is None:
     69                 delattr(self, term)

AttributeError: 'J1744-1134.t2' object has no attribute 'F2'

In [4]:

**Comment by scottransom** [comment]
Ah.  So why are you re-reading the parfile?  It was already read and parsed etc in line 2 (during get_model)...

I agree that things shouldn't fail if you re-read, but still seems kind of strange.

**Comment by scottransom** [comment]
Pull it and try it now

**Comment by vhaasteren** [comment]
Oh, shit, you're right. I was converting some old code, and I just changed the m = pm.StandardTimingModel to m = pm.get_model, but I left the read_model there. I knew that that second line was unnecessary if I had left my brain on.

Oh well, good way to make this foolproof :). The patch you made works, thanks!

**Comment by vhaasteren** [comment]
On Wed, Nov 25, 2015 at 10:22 AM, Scott Ransom <notifications@github.com>
wrote:

> As for your question about deleting attributes, the reason is that each
> model constructor has parameters that it knows about. And since the
> possible number of spin derivs is infinite, I wanted a way to only allocate
> and keep the params/attributes that are actually used in the model in
> question. I'm not sure how you would do that with model_builder since that
> doesn't know specifics about the individual models....
>
I think we can and should separate it. We just need to work a bit harder
for it. Especially for the JUMP and DMX parameters the current approach
would get a bit clunky (I tried). Below is my proposal. (Should we call
those PIPs? As in PINT Improvement Proposals?)

There are quite a few types of parameters that have some form of prefix
(Say, DMX_0001...), with after that a number. The logical thing would be to
have an extra list in the timing_model class besides m.params that stores
these. Say m.param_prefixes. Based on those, the model builder class can
identify whether a parameter in the parfile belongs to one of the model
components, as a prefix-type parameter

PIP:
- In the model builder init, we add an extra function between the lines
  > self.get_comp_from_parfile(self.parfile)
  >   <<new function call here>>
  > self.get_model_instance(self.parfile)
- In this new function, we will loop over self.param_inparF once more. For
every parameter that is not yet in the component.params list, we need to
check whether it is compatible with the component.param_prefix list. If so,
we record that in a dictionary. Similar to this:
self.prefix_dict[component][parname] = self.param_inparF[parname]

Then, once we actually build the model instance, we can add all the
'prefix' parameters from the dictionary that we built, and we are done.
Advantages:

- No more handling case-specific parameter suffixes in the timing_model
subclasses
- The timing model parameters with a prefix are unlimited
- The timing model parameters with a prefix do not need to be ordered, and
they can 'skip' a number

Disadvantages:
- We have to loop over all the parameters once more (but I don't think
that's ugly).

Rutger



-- 

______________________________________________________________________
 dr. Rutger van Haasteren, Einstein postdoctoral fellow
 Jet Propulsion Laboratory, Pasadena, USA
 E-mail: vhaasteren@gmail.com

**Comment by vhaasteren** [comment]
I can make this into an issue, btw.

On Wed, Nov 25, 2015 at 10:59 PM, Rutger van Haasteren <vhaasteren@gmail.com
> wrote:

>
> On Wed, Nov 25, 2015 at 10:22 AM, Scott Ransom <notifications@github.com>
> wrote:
>
>> As for your question about deleting attributes, the reason is that each
>> model constructor has parameters that it knows about. And since the
>> possible number of spin derivs is infinite, I wanted a way to only allocate
>> and keep the params/attributes that are actually used in the model in
>> question. I'm not sure how you would do that with model_builder since that
>> doesn't know specifics about the individual models....
>>
> I think we can and should separate it. We just need to work a bit harder
> for it. Especially for the JUMP and DMX parameters the current approach
> would get a bit clunky (I tried). Below is my proposal. (Should we call
> those PIPs? As in PINT Improvement Proposals?)
>
> There are quite a few types of parameters that have some form of prefix
> (Say, DMX_0001...), with after that a number. The logical thing would be to
> have an extra list in the timing_model class besides m.params that stores
> these. Say m.param_prefixes. Based on those, the model builder class can
> identify whether a parameter in the parfile belongs to one of the model
> components, as a prefix-type parameter
>
> PIP:
> - In the model builder init, we add an extra function between the lines
>   > self.get_comp_from_parfile(self.parfile)
>   >   <<new function call here>>
>   > self.get_model_instance(self.parfile)
> - In this new function, we will loop over self.param_inparF once more. For
> every parameter that is not yet in the component.params list, we need to
> check whether it is compatible with the component.param_prefix list. If so,
> we record that in a dictionary. Similar to this:
> self.prefix_dict[component][parname] = self.param_inparF[parname]
>
> Then, once we actually build the model instance, we can add all the
> 'prefix' parameters from the dictionary that we built, and we are done.
> Advantages:
>
> - No more handling case-specific parameter suffixes in the timing_model
> subclasses
> - The timing model parameters with a prefix are unlimited
> - The timing model parameters with a prefix do not need to be ordered, and
> they can 'skip' a number
>
> Disadvantages:
> - We have to loop over all the parameters once more (but I don't think
> that's ugly).
>
> Rutger
>
>
>
> --
>
> ______________________________________________________________________
>  dr. Rutger van Haasteren, Einstein postdoctoral fellow
>  Jet Propulsion Laboratory, Pasadena, USA
>  E-mail: vhaasteren@gmail.com
>



-- 

______________________________________________________________________
 dr. Rutger van Haasteren, Einstein postdoctoral fellow
 Jet Propulsion Laboratory, Pasadena, USA
 E-mail: vhaasteren@gmail.com

**Comment by scottransom** [comment]
yeah, this sounds reasonable.
