### ISSUE TITLE
"More than one component made use of par file line" warnings on NANOGrav par files

### ISSUE THREAD

**Issue by rossjjennings** [nanograv/PINT#627]
Whenever I load a NANOGrav par file using PINT, I get warnings like the following:

```
WARNING: More than one component made use of par file line 'T2EFAC -f L-wide_PUPPI   1.507': [('ScaleToaError', 'EFAC1'), ('ScaleToaError', 'EFAC2'), ('ScaleToaError', 'EFAC3'), ('ScaleToaError', 'EFAC4')] [pint.models.timing_model]
WARNING: More than one component made use of par file line 'T2EQUAD -f L-wide_PUPPI   0.25518': [('ScaleToaError', 'EQUAD1'), ('ScaleToaError', 'EQUAD2'), ('ScaleToaError', 'EQUAD3'), ('ScaleToaError', 'EQUAD4')] [pint.models.timing_model]
WARNING: More than one component made use of par file line 'ECORR -f 430_PUPPI   0.00601': [('EcorrNoise', 'ECORR1'), ('EcorrNoise', 'ECORR2'), ('EcorrNoise', 'ECORR3'), ('EcorrNoise', 'ECORR4')] [pint.models.timing_model]
```

It looks like the noise model components are stepping on each other's toes. In particular, these warnings aren't the result of bad/corrupted par files or unrecognized par file lines, but seem to be symptoms of a problem internal to PINT. Why is this happening and what would we need to do to get rid of it?

**Comment by rossjjennings** [comment]
Is this related to #620?

**Comment by luojing1211** [comment]
I don't think it is related to #620. But I am working on getting add parameters to work better. So it may solve the problem.

**Comment by paulray** [comment]
Any progress on this?  What is causing it?

I get this when reading a par file:
```
WARNING: More than one component made use of par file line 'JUMP -chanid asp_424 7.6456527699426e-07 1': [('PhaseJump', 'JUMP1'), ('PhaseJump', 'JUMP2'), ('PhaseJump', 'JUMP3'), ('PhaseJump', 'JUMP4'), ('PhaseJump', 'JUMP5'), ('PhaseJump', 'JUMP6'), ('PhaseJump', 'JUMP7'), ('PhaseJump', 'JUMP8'), ('PhaseJump', 'JUMP9'), ('PhaseJump', 'JUMP10'), ('PhaseJump', 'JUMP11'), ('PhaseJump', 'JUMP12'), ('PhaseJump', 'JUMP13'), ('PhaseJump', 'JUMP14'), ('PhaseJump', 'JUMP15'), ('PhaseJump', 'JUMP16'), ('PhaseJump', 'JUMP17'), ('PhaseJump', 'JUMP18'), ('PhaseJump', 'JUMP19'), ('PhaseJump', 'JUMP20'), ('PhaseJump', 'JUMP21')] [pint.models.timing_model]
```

**Comment by rossjjennings** [comment]
This started to bother me again when I was experimenting with the NANOGrav notebook server earlier today. I did some detective work and found the proximate cause: the function `TimingModel.read_parfile()` [checks](https://github.com/nanograv/PINT/blob/d21a6cc9312031501585c12ae171d9076a2725bd/src/pint/models/timing_model.py#L1261) the return value of each parameter's `from_parfile_line()` method on each line of the par file, to see if the line is relevant to the parameter type. The offending parameters are all `maskParameters`, so the method being called is [`maskParameter.from_parfile_line_mask()`](https://github.com/nanograv/PINT/blob/d21a6cc9312031501585c12ae171d9076a2725bd/src/pint/models/parameter.py#L1428). Every parameter of a given kind (T2EFAC, T2EQUAD, ECORR, JUMP), considers all lines of the same kind to be relevant, causing `read_parfile()` to complain. It all seems to get sorted out eventually, though -- the parameters all end up with the correct values once the par file is completely read in.
