### ISSUE TITLE
Create a 'libstempo'-like interface

### ISSUE THREAD

**Issue by vhaasteren** [nanograv/PINT#63]
Create an interface that is compatible with the libstempo interface. There is much demand for this for PTA analysis codes that currently already work with libstempo. A libstempo interface would make PINT a drop-in replacement.

Progress: ltinterface exists, but it currently has difficulties with units. Also, many features are still missing.

**Comment by paulray** [comment]
Note that this code is not covered by any testing and not functional. It needs some love. Do any PINT developers use libstempo @jellis18 ?

**Comment by jellis18** [comment]
@paulray, this has been on my list and is actually quite important for GW analysis codes. I will work on getting this up to speed. Once we have this, we can drop it in our analysis codes without having to write any new code to handle PINT. It will allow us to switch between PINT and tempo2 easily.

**Comment by paulray** [comment]
I think Enterprise and other NANOGrav codes are using PINT now. I'm not sure if they use the libstempo interface or not. Can we close this?
