### ISSUE TITLE
Test against minimum allowed versions of packages

### ISSUE THREAD

**Issue by rossjjennings** [nanograv/PINT#632]
We should have at least one Travis build set up that runs PINT with the minimum allowed version of each of our dependencies. This will make us notice when a change breaks on an older version of (say) numpy or astropy, and prevent issues like #584 from cropping up. If we do find something that breaks on an older version, we can always bump up the minimum supported version of that package, which will reduce the chances of getting a broken PINT install.

As per the discussion on #584, we should bump the minimum numpy version to at least 1.15. In trying to get a working python 2.7 environment, I ran into problems with astropy 2.0.9 -- it looks like there were some bugs fixed in 2.0.15 that PINT now relies on. So on python 2.7 we should require astropy>=2.0.15. Running a travis build with minimum versions of everything will catch more issues like this that would otherwise hide from the tests.

**Comment by paulray** [comment]
Concur! Maarten gave some tips on how astropy does that with tox in #584 
We should definitely do this. I just haven't found the time to play with it yet.
