### ISSUE TITLE
Stand-alone binary model retains 10 day default FB0

### ISSUE THREAD

**Issue by rossjjennings** [nanograv/PINT#639]
I ran into the following alarming state of affairs while trying to add a function to change the binary epoch. 

Try loading `J0023+0923_NANOGrav_11yv0.gls.par` from the `tests/datafile` directory:
```
In [1]: from pint import models
In [2]: model = models.get_model("tests/datafile/J0023+0923_NANOGrav_11yv0.gls.par")

In [3]: model.FB0.quantity
Out[3]: <Quantity 8.33872155e-05 1 / s>

In [4]: model.binary_instance.FB0
Out[4]: <Quantity 1.1574e-06 1 / s>
```
That last value (approximately 1/(10 days)), is a default set by the base class for the stand-alone binary models (`pint.models.stand_alone_psr_binaries.PSR_BINARY`). It is being retained by the `binary_instance` object even though `FB0` is specified in the par file! Right now it's going unnoticed because whenever PINT looks for `FB0` it looks in the first place (`model.FB0`), and finds the correct value, as specified in the par file. But if someone were to pull the "stand-alone" binary model out and ask it for the value of `FB0` (i.e., `binary_instance.FB0`), they would mysteriously get the wrong answer.

We really shouldn't have this default at all -- it's a reasonable enough value that it could get past a cursory inspection and get used in later computations, even though it has nothing to do with user input or the contents of any par file. At the very least, it needs to be overwritten when the par file actually specifies `FB0`.

**Comment by rossjjennings** [comment]
I plan on putting together a solution for this soon that should also address #633.

**Comment by paulray** [comment]
Holy cow! That is scary!

**Comment by demorest** [comment]
FWIW, I still think we should get rid of the "stand-alone" binary models entirely.

**Comment by rossjjennings** [comment]
Why do we have the "stand-alone" binary models to begin with?

**Comment by luojing1211** [comment]
Even we fixed the default problem, the cache is still there. The reason for it is that someone may just use the binary model for something else (like orbit searching).

**Comment by rossjjennings** [comment]
For a minute last night I thought it would be easy to solve this and #633 together (hence my earlier comment), but I was wrong, so you can disregard my first comment on this. I do still need (or at least want) this to be solved before I add the code to change the binary epoch, and I'm willing to work on it myself, but the solution is not obvious.

**Comment by luojing1211** [comment]
The solution is obvious, but it is very long and it will be a big PR. After PINT version 0.7. I am happy to work with you to solve it since I coded most of them.

**Comment by rossjjennings** [comment]
@luojing1211 Do you mean combining the stand-alone binary models with the regular ones, as I think @demorest would like? Or just removing the defaults and caching mechanism from the stand-alone models?

**Comment by luojing1211** [comment]
Make stand-along binaries to regular model component

**Comment by abhisrkckl** [comment]
This issue is no longer present. I am closing this.
