### ISSUE TITLE
Parameter values don't behave uniformly with units

### ISSUE THREAD

**Issue by vhaasteren** [nanograv/PINT#64]
Currently, the timing model parameters do not behave uniformly with units. For instance:

m = m = pm.get_model('J1909-3744_NANOGrav_dfg+12.par')

print(m.RAJ.value)
> 19h09m47.438s
print(m.RAJ.value.value)
> 19.163177231166664
print(m.F0.value)
> 339.3156927586801522
print(m.F0.value.value)
AttributeError ....

Of course, the reason is that RAJ.value and DECJ.value have astropy units. This is not the case for any other parameter. Of course, the units are consistently kept in m.xxx.units, but we need to decide whether the 'value' attribute will have the astropy units.

**Comment by luojing1211** [comment]
In the new binary model, it has a function called apply units. Basically it make parameter.value with unit.

**Comment by vhaasteren** [comment]
That is good, but it is not a 'proper' solution. First off, apply_units is a remedy for something that we should just 'fix' in the first place. Secondly, the issue also exists for models without a binary component.

I would propose to just dig into he code, and change the behavior of PINT regarding the model parameters. It should be a simple matter, although we might need some 'parse' lambda's

**Comment by scottransom** [comment]
yeah.  I agree with what Rutger said....

**Comment by luojing1211** [comment]
Hi folks, 

I did made a new pull request for this issue. I added bare_value and base_unit to the parameter class. bare_value will be updated with the value attribution. Please test it and break it, so I can find the potential bugs. Thank you.

**Comment by luojing1211** [comment]
Is this ok to close? Or should we close it after the new parameter api pull request get merged.

**Comment by paulray** [comment]
As far as closing, I think the best thing would be to make sure there is a test that demonstrates how the values/units "should" work, according to @vhaasteren . Then, if that test passes, this can be closed.

**Comment by vhaasteren** [comment]
Haha, am I being volunteered here? :)

Anyway, I agree that we need this, and it is little work. I could put something together Monday before the telecon.

**Comment by luojing1211** [comment]
We can add more tests in the test_parameters.py since there already have the test structure set up.

**Comment by luojing1211** [comment]
@vhaasteren  Do you think this issue is ready to be closed?

**Comment by vhaasteren** [comment]
Yep
