### ISSUE TITLE
Built-in F-test for parameter significance

### ISSUE THREAD

**Issue by mtlam** [nanograv/PINT#640]
Part of NANOGrav's workflow, and I believe useful to others more broadly and thus should probably go into PINT, is the ability to test the addition (or removal) of a timing model parameter or parameters. Therefore, I'd suggest it either takes a value or list of values, which I suppose could be `Parameter` objects but preferably for ease strings. I'm not sure where this function would live within PINT or even what the convention would be (it probably should return a boolean?)

This is performed via a standard F-test which will compare the number of degrees of freedom (`get_dof()`) and the chi-squared value (`calc_chi2()`) for each model. From these, it will calculate the F statistic. The function should take some value (e.g., often called `alpha`) that will act as the significance to compare against the p-value (in the NANOGrav datasets, we use 0.0027, i.e., "3σ"). The value could be set with a default and made optional.

Example usage:

    model.Ftest("XDOT") #check if XDOT is significant
    model.Ftest("XDOT", remove=True) #check if it is preferred to remove XDOT
    model.Ftest(["M2", "SINI"]) #check if adding M2 and SINI is significant
    model.Ftest("XDOT", alpha=0.05) #check if XDOT is significant, but at the "2σ" level

For the F-test, one can use `scipy.stats` in a fairly straightforward manner, e.g., https://stackoverflow.com/a/21503346; see the note on using `stats.f.sf` rather than `stats.f.cdf`. I am happy to discuss fuller code on this end, though this is probably the easiest part of the implementation of the test into PINT.

**Comment by paulray** [comment]
This is clearly a good functionality to support! However, I don't think it can be implemented as a method of a TimingModel object.  It requires re-fitting after modifying the model, so it needs a Fitter and a TOAs object as well.  Given that, it probably makes sense to make a higher level convenience function that takes a model, fitter, and TOAs and a list of parameters to test.
So, maybe `pint.Ftest(model, toas, fitter, "XDOT")`?  As this is quite separable from the details/internals of any of those classes, do you want to take a crack at writing this?

**Comment by scottransom** [comment]
Yeah, I think this is correct what @paulray wrote.  Although I think it could also be done as a part of the fitter class itself (for WLS and GLS instances).  That's because there is already a base model and TOAs assigned.

When Ftest is run, it could simply copy the current model and add "XDOT" as in Paul's example (f.Ftest("XDOT"), which is similar to how @mtlam was suggesting.  Or, a second way of calling it could be like:  f.Ftest(model2) where model2 is the changed model.

As a reminder, there is fully tested Ftest code here:  https://github.com/scottransom/presto/blob/bb7b5ec628aa96f2d8ff8173ce744ab032d97c82/python/presto/psr_utils.py#L1603

Note that we need to make sure that our degrees of freedom are the same as in TEMPO and Tempo2...  I'm not sure if that was ever made into an issue or not.

**Comment by mtlam** [comment]
I'm happy to take a crack at writing it. I can do so in consultation with @luojing1211 and others.

Doing both methods as @scottransom mentioned sounds reasonable to me, but it should at a minimum do the first way. It will be very cumbersome to have to build lots of models to test. Unless one wants to overload `__add__` for `add_param()` and the equivalent for `remove_param()`, but this still seems like unnecessary overhead.

Looking at `get_dof()`, it looks like the sensible definition though there might be a -1 that needs to be added for the mean subtraction of the residuals if that's not explicitly included as an arbitrary phase offset in `self.model`. If it's not in there, then I do think it needs the -1.

**Comment by demorest** [comment]
Given that F-test is technically only valid for nested models, I think it probably makes most sense to pass it a list of parameters to test, rather than an arbitrary `model2` instance.

**Comment by scottransom** [comment]
@demorest  Yeah.  We'd basically need to test that the models are nested.  But I think that is quite doable.  I just think that, for instance, when a new param gets added in pintk, you get a new model instance (actually, every time you do anything you get a new model instance, as they are pushed onto a stack so you can undo).  So being able to compare two (nested!) models seems useful.

**Comment by scottransom** [comment]
@mtlam what is the cumbersome part?  You don't need to build a new model from scratch.  You can simply copy the current one and and/remove as needed.  I kind of like that, actually, as you don't modify your input model unless you really want/need to.

**Comment by luojing1211** [comment]
@scottransom If one needs to switch the binary model, this needs to add_component() functions.

**Comment by scottransom** [comment]
@luojing1211 but switching the binary model doesn't make a nested model.  So we would reject that case for using the Ftest.  I think the check would be (fairly?) easy to make:  all of the params should be the same except some small number of new ones.  We check to see if the components are all the same, and that there are only a different number of params.  *Or* we check to see if a new component has been added or one has been removed.

**Comment by mtlam** [comment]
@scottransom Mostly that doing it in one line rather than multiple seems easiest, especially if one (i.e., NANOGrav) needs to do a bunch of F-tests. Yes, it could be looped, but it just seems a bit bulky for what one probably wants as an "is significant?" test.

Agreed on the nested checking. That seems fairly straightforward. Happy to take a tab at that too.

**Comment by scottransom** [comment]
@mtlam oh, I thought that @demorest was suggesting that the list of params would be applied to a *single* Ftest.  For example, testing both the adding of EPS1DOT and EPS2DOT at the same time (which you could argue is the right thing to do).  I wasn't thinking about the Ftest code doing multiple tests at once...

**Comment by mtlam** [comment]
@scottransom Oh, that's exactly what I was thinking: single F-test at a time. I just meant that doing one significance test in one line would be useful, rather than multiple.

**Comment by scottransom** [comment]
Ah, ok.  I think we are on the same sheet of music then.  I just think that being able to compare two different models is also useful (and would be used).  That does demand the testing for nestedness, though.

**Comment by bshapiroalbert** [comment]
This issue can probably be closed now, yay for checking things off of lists!
