### ISSUE TITLE
Document model classes

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#65]
On the wiki we have some [documentation of the TOA classes](https://github.com/nanograv/PINT/wiki/Code-Architecture). However, there isn't really anything on the model classes.  I suggest we add a wiki page on the models that has a few pieces of information/examples:
- An overview of the model classes philosophy, and a description of the useful methods
- An example of how to create a model object from a par file
- An example of how to create a model object from scratch
- A tutorial on how to add a new model (e.g. a new binary model)

The above might make the most sense after the pull requests that modify the binary model structure have been merged.  It seems that is being prevented by conflicts.  @luojing1211 can those be resolved?

**Comment by luojing1211** [comment]
Which branch are you merging from?

**Comment by paulray** [comment]
Hi, I didn't actually try the merging myself. I just noted that both pull requests show the message "This branch has conflicts that must be resolved" and I figured that was why they had not yet been accepted into the main branch. Is that right?

**Comment by luojing1211** [comment]
I see I will fix it.

**Comment by luojing1211** [comment]
In our wiki page section code architect, a section called model classes has been started. Right now it still has limited information. Please feel free to edit it and comment on it.

**Comment by luojing1211** [comment]
Is this issue able to close, since we improved our examples?
