### ISSUE TITLE
config.datapath() did not return None when file is missing

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#652]
config.datapath() should return None when the file is missing, according to the docstring, however it raises an error. This makes the searching for bipm clock correction file fail. What is the right way to do it? None vs Error? 

https://github.com/nanograv/PINT/blob/78596924eb36dbb31e74b8fafb53b4c9cd7c08bb/src/pint/config.py#L36

**Comment by demorest** [comment]
As I just said on the call, I'd vote for leaving the behavior of `config.datapath()` as it is, ie raise an error rather than return None.  We should change the docstring to correctly describe this behavior though.

**Comment by paulray** [comment]
I just ran into this problem when loading TOAs with `bipm_version="BIPM2017"`. That is supposed to try PINT first then fall back to $TEMPO2/clock if that is available. Instead the exception causes it to die. So `bipm_fullpath()` in topo_obs.py needs to be fixed to use try/except if we keep this, as @demorest suggested.

**Comment by paulray** [comment]
I made this fix in my copy and it works fine. I guess I'll make a PR for it at some point

**Comment by scottransom** [comment]
If it fixes the issue, feel free to to just push it up as a bugfix

**Comment by paulray** [comment]
Oops, I changed my mind. Looking at where `datapath()` is used in PINT, I think it should return None instead of raising an exception.

**Comment by paulray** [comment]
This has been dealt with.
