### ISSUE TITLE
Add tempo BIPM clock correction search 

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#653]
Currently, if PINT BIMP clock correction file is not found, it would only search TEMPO2 clock directory. We should also search in TEMPO directory. If tempo2 is not installed, we can still use the tempo clock correction file. 

https://github.com/nanograv/PINT/blob/78596924eb36dbb31e74b8fafb53b4c9cd7c08bb/src/pint/observatory/topo_obs.py#L180

**Comment by abhisrkckl** [comment]
No longer relevant
