### ISSUE TITLE
PINT incorrectly handles par files with mixed ecliptic and equatorial coords

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#654]
This is related to #304 

I made 4 par files using different combinations  of equatorial and ecliptic coordinates for the position (POS) and proper motion (PM). When both POS and PM are the same coordinate system all works fine. When POS is equatorial and PM is ecliptic, PINT runs but gives incorrect answers. When POS is ecliptic and PM is equatorial, PINT print some warnings and raises an exception:
```
WARNING: Unrecognized parfile line 'ELONG          192.7997211876664938878800371 1  0.00000102102277960435' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'ELAT           -9.9435557450403477515801787 1  0.00000664803199093257' [pint.models.timing_model]
pint.models.timing_model.MissingParameter: Astrometry.RAJ
```
For what is it worth, Tempo2 does not work correctly for either of the mixed system par files, but does not crash. It just reads the values and interprets them incorrectly.

So, I propose that PINT should raise an exception when the coordinate system for the POS is different from the PM.  And, it should probably cue off the POS coordinate system. So, if RA is specifies thes PMELONG or PMELAT should raise an exception, and if ELONG is specified then PMRA or PMDEC should raise an exception.

**Comment by paulray** [comment]
As a note, TEMPO does the **right thing**, as @demorest predicted:
```
% tempo -f TDB_ECLPOS_EQUPM.par TOAs_NUPPI_1484_F4Tp.tim
 TEMPO v 13.000 Princeton/ATNF Pulsar Collaboration
 Data from TOAs_NUPPI_1484_F4Tp.tim,   Input parameters from TDB_ECLPOS_EQUPM.par                                                                                                                                            
ERROR: cannot mix ecliptic and equatorial coordinates

% tempo -f TDB_EQUPOS_ECLPM.par TOAs_NUPPI_1484_F4Tp.tim
 TEMPO v 13.000 Princeton/ATNF Pulsar Collaboration
 Data from TOAs_NUPPI_1484_F4Tp.tim,   Input parameters from TDB_EQUPOS_ECLPM.par                                                                                                                                            
ERROR: cannot mix ecliptic and equatorial coordinates
```

**Comment by paulray** [comment]
Note that Tempo2 now does the *right thing*, as of this commit:
https://bitbucket.org/psrsoft/tempo2/commits/adb29f71a9f945d3773373df78929a0f63f608ca

**Comment by swiggumj** [comment]
I think this issue may also be related to https://github.com/nanograv/PINT/issues/750. In other words, one solution might be to re-work the `validate()` method.

Also, isn't #304 now fixed?

**Comment by paulray** [comment]
@champagne-cmd could you take a look at this one?

**Comment by champagne-cmd** [comment]
@paulray could you send me the par files you used?

**Comment by aarchiba** [comment]
Can I suggest these par files go into the test suite, one way or another?
