### ISSUE TITLE
Issues with the Dispersion classes

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#658]
I've been looking over `dispersion_model.py` and `solar_wind_dispersion.py` and there are some issues I think should be addressed.  My particular motivation was that I want to be able to query the model DM at any given time (or at least at the time of TOAs), so I can plot the modeled dispersion  measure as a function of time. I do not see a simple way to do this, but I may be missing something.
I guess what you do is this, given a `model` and `toas` object:
```
dmc = model.components['DispersionDM']
dm = 0.0*u.pc/u.cm**3
for dm_f in dmc.dm_value_funcs:
            dm += dm_f(toas)
```
It would be nice if this were wrapped up in a `dmc.total_dm(toas)` method, I think

There are several methods in dispersion_model.py that have no docstring and are not really obvious as to what they are and how they should be used. For example `dispersion_type_delay()` is an obscure name with no documentation, and `base_dm()` should really have a docstring explaining what is it doing. Also the docstring for `constant dispersion_delay()` is really obscure and doesn't explain why the word 'constant' is there when the DM is not constant.

However, this does not work for `SolarWindDispersion`. This is a subclass of `Dispersion`, but it does not correctly set `dm_value_funcs`.  This is a bug, I think. There does not seem to be any way to get the SW dispersion out of the model, only the delay.  This should be fixed too.

**Comment by luojing1211** [comment]
I agree I was planning to have an update on the dispersion base class and its subclasses after version 0.7 is set.

**Comment by abhisrkckl** [comment]
Already implemented.
