### ISSUE TITLE
Chi2 calculation possible bug

### ISSUE THREAD

**Issue by juliadeneva** [nanograv/PINT#661]
As far as I can tell chi2 here is always calculated based on prefit residuals from _all_ TOAs, while in the second line it is divided by the number of _selected_ TOAs. 

https://github.com/nanograv/PINT/blob/4ddc7b7b1fde974a0c4769933984d43161362542/src/pint/pintk/pulsar.py#L457-L458

Same problem but with postfit residuals when printing the results:

https://github.com/nanograv/PINT/blob/4ddc7b7b1fde974a0c4769933984d43161362542/src/pint/pintk/pulsar.py#L193-L194

I also think this code should work but it produces an array size mismatch error related to chi2 calculation when a subset of TOAs is used for fitting: 

`psr = Pulsar(parfile, timfile)`
`selected = `[mask based on selection criteria]
`psr.selected_toas.select(selected)`
`psr.fit(selected)`

**Comment by paulray** [comment]
I believe this has been fixed.
