### ISSUE TITLE
Incorrect uncertainties on RAJ, DECJ?

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#664]
I've been working with PINT and was making a pretty-printer for the results of a fit. In doing so I found that the uncertainties reported on RAJ and DECJ are VERY different than Tempo2, by many orders of magnitude. Something is wrong.  Attached here is a little notebook that fits the data in pint/examples and looks at the uncertainties, compared to a Tempo2 fit of the same.  
(You will have to change the paths and delete the .print_summary() cell if you want to re-run it since that is only in my branch).

To summarize here, tempo2 gives:
```
PARAMETER       Pre-fit                   Post-fit                  Uncertainty   Difference   Fit
---------------------------------------------------------------------------------------------------
RAJ (rad)       1.63071752883066          1.63071752883548          8.8177e-11    4.8146e-12    Y
RAJ (hms)       06:13:43.9756752           06:13:43.9756753         1.2125e-06    6.6205e-08   
DECJ (rad)      -0.0351355401430826       -0.0351355400811907       1.7101e-10    6.1892e-11    Y
DECJ (dms)      -02:00:47.22538           -02:00:47.22537           3.5273e-05    1.2766e-05   
```

PINT gives compatible fitted values, but the RAJ uncertainty is 2.4e-14 rad and the DECJ uncertainty is 4.6e-14 rad.

Any ideas?

[PositionTest.ipynb.zip](https://github.com/nanograv/PINT/files/4496886/PositionTest.ipynb.zip)

**Comment by paulray** [comment]
Update, I added 4 lines to that simple notebook to try the other 2 fitters and compare their uncertainties.  Both failed.
```
pow0613 = pint.fitter.PowellFitter(toas=ts0613,model=m0613)
pow0613.fit_toas()
```
This failed with an error about units.
```
UnitConversionError: '' (dimensionless) and 'mas' (angle) are not convertible
```
I thought maybe Powell was totally broken but it is used in test_glitch.py so it must be at least partially functional. It looks like an issue with angles. Actually I just froze all the angle parameters then it failed on DM. So the issue is more general. Ah! There are no fitted parameters in test_glitch.py so it doesn't really test PowellFitter.  This is a problem.
PowellFitter also doesn't set the covariance_matrix, or return chisq.  We should make all 3 Fitter classes behave the same, and they should for sure all work! 

Then:
```
gls613 = pint.fitter.GLSFitter(toas=ts0613,model=m0613)
gls613.fit_toas()
```
This failed with an exception:
```
AttributeError: 'TimingModel' object and its component has no attribute 'NoiseComponent_list'.
```
The docstring for GLSFitter doesn't mention anything about needed NoiseComponent_list. I assume this is created automatically  by `get_model()` if there is a noise component in the par file. Can GLSFitter only be used that way?  @demorest any suggestions or can GLSFitter be fixed somehow?

**Comment by paulray** [comment]
Update2: I was able to get GLSFitter to run by using `fit_toas(full_cov=True)`. This ran fine but for this fitter the uncertainties (on all parameters, not just angles) are orders of magnitude **larger** than Tempo2!

**Comment by demorest** [comment]
Yes, GLSFitter should be able to work even if there is no noise model.  In that case it should give same results as WLSFitter.  I think I probably introduced that bug in #648 (residual whitening), that part at least is an easy fix.

**Comment by paulray** [comment]
@luojing1211 was this broken recently? I was looking at some threads on the NANOGrav Slack and you made plots comparing PINT to Tempo2.  I see them as orders of magnitude different, when just running simple examples like fit_NGC6440E.py.
PINT gives this:
```
In [4]: print(f.model.as_parfile())                                                                                                           
PSR                            1748-2021E
EPHEM                               DE421
RAJ                     17:48:52.80034692 1 0.00000003756850254201
DECJ                   -20:21:29.38330649 1 0.00000912542586891751
PMRA                                  0.0
PMDEC                                 0.0
PX                                    0.0
POSEPOCH           53750.0000000000000000
F0                  61.485476554372500174 1 1.808608439278166708e-11
F1              -1.1813316417059333308e-15 1 1.4418540386147071531e-18
PEPOCH             53750.0000000000000000
PLANET_SHAPIRO                          N
NE_SW                                 0.0
SWM                                   0.0
DM                  224.11379727670829498 1 0.034938980494126012366
DM1                                   0.0
TZRMJD             53801.3860512007484954
TZRSITE                                 1
TZRFRQ                           1949.609
```
Tempo2 gives this:
```
RMS pre-fit residual = 1090.569 (us), RMS post-fit residual = 21.182 (us)
Fit Chisq = 59.57	Chisqr/nfree = 59.57/56 = 1.06368	pre/post = 51.4865
Number of fit parameters: 6
Number of points in fit = 62
Offset: -0.000227858 3.95351e-05 offset_e*sqrt(n) = 0.0003113 n = 62


PARAMETER       Pre-fit                   Post-fit                  Uncertainty   Difference   Fit
---------------------------------------------------------------------------------------------------
RAJ (rad)       4.66386519107664          4.66386885239923          1.0144e-08    3.6613e-06    Y
RAJ (hms)       17:48:52.75                17:48:52.8003468         0.00013949    0.050347     
DECJ (rad)      -0.355315098748368        -0.355316956943119        1.6426e-07    -1.8582e-06   Y
DECJ (dms)      -20:21:29.0               -20:21:29.38328           0.033882      -0.38328     
F0 (s^-1)       61.485476554              61.4854765543728          1.8653e-11    3.7276e-10    Y
F1 (s^-2)       -1.181e-15                -1.18133693257567e-15     1.4871e-18    -3.3693e-19   Y
PEPOCH (MJD)    53750                     53750                     0             0             N
POSEPOCH (MJD)  53750                     53750                     0             0             N
DMEPOCH (MJD)   53750                     53750                     0             0             N
DM (cm^-3 pc)   223.9                     224.113797691521          0.036034      0.2138        Y
START (MJD)     0                         53478.2858714192          0             53478         N
FINISH (MJD)    0                         54187.5873241699          0             54188         N
TZRMJD          53801.3860512007          53833.2978103022          0             31.912        N
TZRFRQ (MHz)    1949.609                  1949.609                  0             0             N
TZRSITE         1                        
TRES            0                         21.1816787727225          0             21.182        N
EPHVER          0                         TEMPO2                    0             5             N
NE_SW (cm^-3)   0                         0                         0             0             N
---------------------------------------------------------------------------------------------------

```

**Comment by demorest** [comment]
The problem with `GLSFitter` when you use it with `full_cov=True` and a par file with no noise model is a units issue on the TOA uncertainties.  In timing_model.py line 610, computing the covariacne matrix:
```
            result += np.diag(tbl["error"].quantity.value ** 2)
```
The uncertainties are used without converting units.  Generally these are us, whereas the fitter is working in seconds.

**Comment by demorest** [comment]
Probably `TimingModel.covariance_matrix()` should return a value with units.

**Comment by paulray** [comment]
I just checked with ELONG and ELAT and in that case the PINT uncertainties match with Tempo2. So this seems specific to RAJ and DECJ

**Comment by paulray** [comment]
OK, the problem seems to be that for RAJ and DECJ the par.units (degrees or hourangle) is different than par.uncertainty.units (arcsec or hourangle_second).
Then, the fitter calls this to set the uncertainty in the output model:
```
    def set_param_uncertainties(self, fitp):
        for k, v in fitp.items():
            getattr(self.model, k).uncertainty_value = v
```
But the value v will be in deg for DECJ but it is setting a value with units of arcsec.

I believe the reason @luojing1211 found that the ratio with Tempo2 was not exactly 3600 is that Tempo2 scales the uncertainties by sqrt(reduced chi2) but PINT does not (as far as I know -- do we want to add that?)

**Comment by scottransom** [comment]
Ah-ha.  Seems like the uncertainty unit should be the same.  That's probably a god policy, in general.   Especially since we are trying to use Astropy units as much as possible!

**Comment by paulray** [comment]
A "god" policy might be a bit extreme! :-)

But yes, using the same base units for par and uncertainty is probably good. And in printing you can choose any unit you want since they are astropy quantities.  
Are there any other parameters that have different units like this?  I guess this comes from the fact that Tempo par files use arcsec for uncertainties on the coordinates...

**Comment by scottransom** [comment]
Yeah, that's probably true.  But that is no reason for keeping the uncertainties as a different unit internally!  It just doesn't seem like a good (not god, :-) ) thing to do, in general.

**Comment by paulray** [comment]
Uncertainties are set here in the definition of AngleParameter
Line 925 of parameter.py:
```
        self._str_unit = units
        self.unit_identifier = {
            "h:m:s": (u.hourangle, "h", pint_units["hourangle_second"]),
            "d:m:s": (u.deg, "d", u.arcsec),
            "rad": (u.rad, "rad", u.rad),
            "deg": (u.deg, "deg", u.deg),
        }
```

**Comment by paulray** [comment]
If we change those, then probably something like `model.as_parfile()` will need to be changed. But if we don't we need to change the fitters that have to strip off and the reapply units to do their math.  

The alternative is to have `set_param_uncertainties` set the `uncertainty.quantity` instead using a quantity with the units used in the fitter calculations (which is the unit of the parameter rather than the uncertainty).

I'm not certain which is the best.  We should plan for a path where we never need to strip units from our quantities to do math, in the beautiful future.

**Comment by luojing1211** [comment]
The identifier is developed for reading the uncertainty from .par. So if the identifier is changed, we definitely need to change the from_parfile_line(). Which should not be too much.

**Comment by scottransom** [comment]
Are positions the only parameter where the uncertainty is a different unit (currently) from the value itself?  If so, then I *really* think we should change that.  We could even make parameters simpler by having a "unit" in general rather than two different units for the value and the uncertainty.

**Comment by paulray** [comment]
Yeah, I think I agree.  I believe that PR #670 should be a good thing whether we make that unit change or not, and it fixes the bug, so probably we can merge it first then sort out a larger change in units on parameter uncertainties

**Comment by luojing1211** [comment]
Aside from RA and DEC, the only other place could be the parameter rescaling by 1e-12 for EDOT, OMDOT, etc. I agree with the uncertain should be the same unit.

**Comment by paulray** [comment]
I thought it was PBDOT that was scaled by 1E-12 and weren't we going to get rid of that, except on reading par files, as per #597

**Comment by luojing1211** [comment]
I don't think we did it yet.

**Comment by paulray** [comment]
@demorest Are you going to make a quick PR to fix the GLS issues mentioned above? Or, should we make a separate issue to track it?

**Comment by demorest** [comment]
I was thinking about wrapping it into the other GLS fixing I'd planned to do (#662).  But if you need these smaller issues fixed quicker I could put in a quick PR for them.

**Comment by paulray** [comment]
Well, @luojing1211 would like to tag version 0.7 to be version of record for the paper. So, anything that we want in that version should get merged sooner rather than later. It would be good to have as few known bugs as possible in that version.

The good thing about tagging that version is that we will branch at that point and going forward the master branch won't need to support Python 2.7 or old astropy.  If we make other fixes that are good for both version, we can cherry-pick them to the python2lts branch (or whatever we call it).
