### ISSUE TITLE
PINT reports wrong number of degrees of freedom

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#668]
`fitter.resids.dof` returns an incorrect value and thus `fitter.resids.chi2_reduced` is also wrong. It seems that dof does not account for the hidden phase parameter.

For the trivial fit_NGC6440E.py example, here is what PINT gives:
```
Fitted model using weighted_least_square method with 5 free parameters to 62 TOAs
Prefit residuals 1090.580262221985 us, Postfit residuals 21.182038051610704 us
Chisq = 59.574 for 57 d.o.f. for reduced Chisq of 1.045
```
and here is Tempo2
```
RMS pre-fit residual = 1090.569 (us), RMS post-fit residual = 21.182 (us)
Fit Chisq = 59.57	Chisqr/nfree = 59.57/56 = 1.06368	pre/post = 51.4865
Number of fit parameters: 6
Number of points in fit = 62
Offset: -0.000227858 3.95351e-05 offset_e*sqrt(n) = 0.0003113 n = 62
```

**Comment by scottransom** [comment]
yeah, this has been known and discussed for a while.  I thought there was already an issue for it, but apparently not!  Thanks for bringing it up.  I think it is an easy fix, but we have to make sure that it is changed in all the relevant places.
