### ISSUE TITLE
Get fitter ready for release

### ISSUE THREAD

**Issue by vhaasteren** [nanograv/PINT#67]
Both the nonlinear and the weighted least-squares fitter should ready for prime-time.

At the moment the fitters do work, but not very elegantly due to the required checks for units of the timing model parameters. Especially the wls_fitter has troubles with this.

Once we have the units dealt with properly, polishing the fitters is easy.

**Comment by paulray** [comment]
@luojing1211 can this be closed?  It is not clear to me what needs to be done to close it.

**Comment by luojing1211** [comment]
I think this can be closed. If anything needs to be fixed, we will open a
new issue.

-Jing Luo
