### ISSUE TITLE
dmxparse requests

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#672]
Hi @bshapiroalbert 
I have a couple requests for `dmxparse()`.

1. Could you make it work even if there is no covariance_matrix? In that case it could just use the single parameter uncertainties, and maybe emit a `log.warning()` that it is doing that?
2. I haven't tried it but the code looks like it requires that the DMX bins be continuous from an index of 1 to the maximum. But, PINT supposed to support DMX ranges that aren't continuous (e.g. if you delete a DMX bin). So, this code should work even if you have just `DMX_001`, `DMX_002`, `DMX_004`, for example)

**Comment by scottransom** [comment]
@paulray How would we get the values without a covariance matrix?  I think that is basically *required* by the DMX methodology as there is a huge covariance with the average DM (and maybe a few other things).  Would like to hear from @demorest about this.  Note:  I totally agree with your #2, though.

**Comment by paulray** [comment]
Maybe it is a bad idea, but I figured that DMX_nnnn should have a single parameter .uncertainty that could be used if the covariance matrix is not available. I think it is (or should be) illegal to had DM not frozen when you fit for DMX.  I assume that would be a problem either way.

**Comment by bshapiroalbert** [comment]
I can definitely do number 2 right now. For number 1, I can have it output a `log.warning` and then have it try to just return any initial values of DMX instead that are already listed in the input par file, like the `DMX_nnnn.uncertainty` and `DMX_nnnn.value` and if it hasn't been fit for it should just return zero, right? But it wouldn't actually be the numbers that you want as Scott mentioned.

**Comment by paulray** [comment]
Cool, sounds good! I think there is value in being able to plot the DMX time series even if you have just read it in and there are either no errors or the errors are just the uncertainties read from the par file. Doing that, with a warning, seems preferable to just having it fail.
