### ISSUE TITLE
Why is frozen being changed?

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#681]
https://github.com/nanograv/PINT/blob/f9ee990aa09f94d566816929d6b071e5e7a5c5c2/src/pint/utils.py#L624-L633

@luojing1211 in the code above, I construct the parameter with `frozen=False`, but when I do that somehow frozen is being reset to True. I have to manually reset it to False. Any idea why?

**Comment by luojing1211** [comment]
That should not happen. Let me investigate.
-Jing

**Comment by luojing1211** [comment]
Found it. A bug deep in the code. 

https://github.com/nanograv/PINT/blob/f9ee990aa09f94d566816929d6b071e5e7a5c5c2/src/pint/models/parameter.py#L498

**Comment by paulray** [comment]
That should be `frozen=frozen` right?  I'll add that to  my next PR.

**Comment by luojing1211** [comment]
Yes. For other non-fitable parameters (i.e. strParameter, boolParameter), it is set to be True always. But floatParameter should be `frozen = frozen`. I really need to optimize/clean up the parameter.py.

**Comment by paulray** [comment]
Fixed in #683
