### ISSUE TITLE
Phase jumps/wraps

### ISSUE THREAD

**Issue by vhaasteren** [nanograv/PINT#69]
Phase jump is such a terrible name, but that's what it is called in the tempo(2) code: phaseJump. Really, it is a phase wrap, where the pulse number should be shifted by some integer.

These parameters have the id 'PHASE' in the par or the tim-file, and they indicate whether to have a positive (+1) or negative (-1) phase wrap.

We need to implement these in some way. However, ideally it is possible to add/remove phase jumps dynamically. How would we achieve this? The current setup of the timing model class does not really allow that to be done elegantly...

**Comment by paulray** [comment]
Yes, this is really important.  Recently Paulo Freire has been using a bash script he wrote with TEMPO that iterates and tries many, many different combinations of integer phase jumps inserted in gaps between blocks of TOAs, looking for the one where the fit has the best chi squared.  With this, over the past few weeks, he has solved about a half dozen of the Fermi MSPs that the people timing them had been unable to phase connect.  It made me jealous that PINT doesn't have this capability yet!

**Comment by vhaasteren** [comment]
That sounds like I need to get onto finishing my pulsar solver, too!

**Comment by matteobachetti** [comment]
One thing that is not directly the point of this Issue, but is related, is the following plotting strategy that I applied in the past: to plot multiple times the TOAs, shifted along Y by integers. Visually, it often permits to see patterns that are invisible by plotting a single series of residuals

**Comment by luojing1211** [comment]
Is this been addressed in the phase numbers?

**Comment by scottransom** [comment]
Yes.  This all works now.  This can be closed.
