### ISSUE TITLE
Add pulse numbers

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#709]
Maybe there is a way to do this that I'm just missing, but here is a use case.
I have a model and a set of TOAs. The model is phase connected. Now I want to change some parameters in a way that might cause phase wraps (e.g. setting F2 to 0, or whatever).  I want the pulse numbers to keep me from losing phase.  I don't see in PINT how to assign pulse numbers based on a model and then use then in subsequent fits.  I think we just need a way to set the 'pulse_number' column of a TOAs table based on a model, then set TRACK to -2 on any model you want to use them with.

**Comment by scottransom** [comment]
We've certainly done things *like* this.  And we can certainly assign pulse numbers to columns in a TOA table based on a model.  And we can use those pulse numbers in other fits.  So we must be really close to being able to do this the way you say.

If you have a TOAs instance t, and a model, you can compute the pulse numbers using:
t.compute_pulse_numbers(model)

Then, if TRACK is -2 (which is a TEMPO2 thing which I think we should handle for backwards compatibility, but we should *totally* change the parameter name to something meaningful in the model), then it uses those pulse numbers.

Have you tried that?  I'm pretty sure that @clp3ef and I have done fits this way....

**Comment by scottransom** [comment]
Were you expecting to see compute_pulse_numbers in the *model* instance rather than the TOA instance?  We could certainly put it there as well.  But you want to modify the TOA object, which is why I (I think it was me) put it there.

**Comment by paulray** [comment]
Oh yeah, I had just missed that `toas.compute_pulse_numbers()` existed!  We do support TRACK -2, so I think I have everything I need.  I *absolutely* agree that PINT should have a sensible name for TRACK -2 and only support that crazy nomenclature when reading a legacy par file, for backwards compatibility.  Have to think about the best way to do that.

**Comment by paulray** [comment]
For the record, your solution worked great. I wonder if that is in any of the documentation or example notebooks. It is VERY useful!

**Comment by scottransom** [comment]
Excellent.  We should just change that TRACK = -2 thing.  It really annoys me.  I think that your summer student from a couple years ago put that in.  So we can probably just change it.  I can guarantee you that no one is using it (yet).

**Comment by paulray** [comment]
I'll spawn an issue for discussion.
