### ISSUE TITLE
Support -padd flag

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#717]
It seems that TEMPO and Tempo2 support the -padd flag on their TOA lines, which applies a phase offsets to TOAs.  PINT does not support this. It does support the -to flag, which is the same but for TIME. It also does support the PHASE command in TOA files so most of the functionality is there.  Probably this is an easy fix.

I found this when trying to process EPTA data that used the -padd flag in their TOA files.

**Comment by luojing1211** [comment]
I would like some type of flag manger in the code. Maybe it will complicate our code. But know what flag is applied on which TOAs would be nice.

**Comment by scottransom** [comment]
@luojing1211 All the flags are listed for each TOA in the "flags" column.  And if those flags have an action, they they have been applied.  What additional functionality would you like?

re -padd, given that this is PHASE, which means that it depends on the timing model, I'm not sure that this is actually a super easy addition to PINT...

**Comment by paulray** [comment]
Well we support the PHASE TOA command. Those values get added to the "delta_pulse_number" table column. See line 1041 of toa.py.  I think we could just add in the value of this flag to that one.

**Comment by scottransom** [comment]
@paulray I had forgotten about that.  Then yes, I agree, it should be a very simile change (maybe only a one or two liner).  Sorry about that!

**Comment by luojing1211** [comment]
@scottransom Maybe a first and easiest one would be some type of summary. For example, -padd flags can be read by TOAs class without any problems. But I would never know this will be applied to PHASE. I believe something like this will help to increase the transparency of PINT.

**Comment by paulray** [comment]
Indeed, until today I had never heard of the padd flag!

**Comment by luojing1211** [comment]
If we can also have some tests for the descriptions of flags, it would be nice. But I understand how tricky it can be.

**Comment by paulray** [comment]
Hmm. I implemented a fix, but in editing the code I had to re-arrange some lines. I believe that PINT may not have been respecting PHASE TOA lines when pulse numbers were not being used.
I just looked in tests/datadir and there is no .tim file with a PHASE command in it, so I think is not being tested.

**Comment by paulray** [comment]
Indeed PINT was not respecting the PHASE TOA command unless pulse number tracking was on.  I fixed this and now it matches the behavior of TEMPO. But, Tempo2 does not seem to be applying the PHASE command. I just don't get it.  Anyway, it does what I think it should do now and I'm adding a test.
