### ISSUE TITLE
Performance issue with Ecliptic par files

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#721]
The benchmarking and profiling work of @champagne-cmd is already paying off!
I was browsing the html report from the bench_chisq_grid_WLSFitter.py benchmark and I noticed that a large amount of time was being spent in astropy coordinate transformations.  Changing the par file to use equatorial instead of ecliptic coordinates sped up the run time of the benchmark from 121 to 80 seconds!

The reason is this calculation of the barycentric radio frequency:
```
    def barycentric_radio_freq(self, toas):
        """Return radio frequencies (MHz) of the toas corrected for Earth motion"""
        tbl = toas.table
        L_hat = self.ssb_to_psb_xyz_ICRS(epoch=tbl["tdbld"].astype(numpy.float64))
        v_dot_L_array = numpy.sum(tbl["ssb_obs_vel"] * L_hat, axis=1)
        return tbl["freq"] * (1.0 - v_dot_L_array / const.c)
```
This corrects the radio frequency for the Doppler shift of the Earth's motion. Since the dot product is done in equatorial coords, the `ssb_to_psb_xyz_ICRS()` method must convert the ecliptic position to equatorial for every single TOA, every time it needs to evaluate the model. 
This issue is for a discussion of how to speed this up. Perhaps the best would be to add another TOA table column that had `ssb_obs_vel` in ecliptic coordinates, but maybe there are other ideas?

@scottransom @demorest @luojing1211 git says some combination of you wrote this part of the code.

**Comment by luojing1211** [comment]
At least we can do better at line:
https://github.com/nanograv/PINT/blob/dce9c94a038e041e171285bdeeae2a5c7c37c06a/src/pint/models/astrometry.py#L493

**Comment by paulray** [comment]
I don't understand @luojing1211 ? Right now the TOAs table has `ssb_obs_vel` as a column, which is the vector velocity of the observatory expressed in ICRS coordinates. This does not depend on the pulsar position.

I'm suggesting (1) add a column that has the `ssb_obs_vel_ecl` vector expressed in ECL coords, and (2) making an `ssb_to_psb_xyz_ECL()` method that computes the vector to the pulsar in ecliptic coordinates instead of ICRS. This would be used when the par file used AstrometryEcliptic and would avoid any transformations between coordinate frames.

**Comment by luojing1211** [comment]
Sorry, I miss understand you. Now I get you. It would work. But do we want all of our calculations based on the ICRS coordinate? I had this problem when developing the DDK model. We decide to have everything based on the same coordinate system.

**Comment by paulray** [comment]
I'm not suggesting any kind of global change, or any change to the fundamental coordinate system. It would basically just be a precomputation of a transformation that is done on the fly currently and it would then be doing the dot product in the same coordinate system as the Astrometry component is using.

**Comment by luojing1211** [comment]
It should be ok if it is the dot product part, which should be the same in any coordinate.  I would also add tests for it.
