### ISSUE TITLE
Solar wind dispersion broken

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#733]
https://github.com/nanograv/PINT/blob/3486bb7ede296008d868e727d3859c33e335a1cd/src/pint/models/solar_wind_dispersion.py#L111

This line uses the variable `AUdist`, which is not defined anywhere, so it fails when you try to fit.

**Comment by paulray** [comment]
I suppose it should be replaced with `const.au` and the unit tests should be updated to make sure that solar wind fitting works.

**Comment by paulray** [comment]
In addition, when I fit for NE_SW, I get a very different answer than Tempo2 gets, e.g. Tempo2 gives 4.9, while PINT gives -1.8.  I suspect the equations are wrong.

**Comment by luojing1211** [comment]
Is the derivative wrong or the delay function is wrong?

**Comment by paulray** [comment]
Perhaps both?

**Comment by paulray** [comment]
If I use the tempo2 "fake" plugin to make TOAs from a simple timing model with NE_SW 10 and then plot the residuals in PINT, I get this plot. Ugh. It looks like the solar wind in PINT is making both positive and negative contributions!

![fakeSW10](https://user-images.githubusercontent.com/1771428/85332209-87d97380-b4a5-11ea-97f7-51047873fc00.png)

**Comment by paulray** [comment]
@scottransom maybe this would be good for your student to look into since he's already doing the tropospheric delay?

**Comment by zimmyneutron** [comment]
@paulray To clarify, you are using tempo2 fake plugin for data, then using PINT to calculate the residuals between the model and the fake.tim data without fitting?

**Comment by paulray** [comment]
Yes, I think that is what I did to make that plot.
