### ISSUE TITLE
Change dispersion constant?

### ISSUE THREAD

**Issue by mtlam** [nanograv/PINT#742]
Inspired by discussions of https://arxiv.org/abs/2007.02886, the dispersion constant is defined as <a href="https://www.codecogs.com/eqnedit.php?latex=\frac{c&space;r_e}{2\pi}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{c&space;r_e}{2\pi}" title="\frac{c r_e}{2\pi}" /></a> (in the notation I more commonly use). This is equal to _K_ = 1.3445365918(9)-07 m^2/s, versus the value of 1.3447217e-07 m^2/s when running `DMconst.decompose()`, a difference of ~0.014%. This change would cause differences from previous timing packages but would be more fundamentally correct in terms of defintiions.

**Comment by paulray** [comment]
This certainly would need some thought and discussion.  Can you get the precise values used by TEMPO and Tempo2, for comparison?

I think for sure we could imagine adding a dispersion model that gives the "Dispersion Slope" (as Shri calls it) and avoids the constant altogether.

**Comment by mtlam** [comment]
It looks like both use the same 1/2.41 value, to some power of 10 depending on units.

I guess we could imagine adding in a different dispersion model but I was thinking at least for now just the notion of the fundamental value. The former falls into a similar category, at least in my brain, of being able to add in a gas temperature if someone so wanted, which I will say is less important for pulsars given the much lower plasma temperatures (he's concerned with ICM gas for FRBs). On the value of K, this definitely needs thought and discussion, no doubt, I don't think we should blindly implement it but given how other constants are used throughout the code versus hand-defined values, we should heavily consider it.

**Comment by scottransom** [comment]
There is a nice discussion of this going on in the FRB2020 meeting slack.  Most pulsar-related codes (including PRESTO, TEMPO, Tempo2, and PINT) use 1/0.241 as the DM constant.  SIGPROC uses 4.15.  Lorimer & Kramer recommend 4.148808, and the public FRB codes use a variety of things around 4.15....  *sigh*

**Comment by paulray** [comment]
https://github.com/nanograv/PINT/blob/d21a6cc9312031501585c12ae171d9076a2725bd/src/pint/models/dispersion_model.py#L14-L16

As evidenced by the big discussion happening among FRB2020 attendees, I think this comment should be expanded to explain the background for the choice of DMconst and the convention defined in Manchester and Taylor and how it is consistent among TEMPO, Tempo2 and PINT.

**Comment by scottransom** [comment]
There has now been a separate email thread about this and the overwhelming consensus among the pulsar people was that timing code (especially) should stick with the 1/2.41e-4 convention.  So I think that we should do that.  However, we might want to add a helper function that could convert "pulsar" DM to one that is based on some other DM constant if requested.

**Comment by paulray** [comment]
Agree with Scott.  I think the comments in the code should be updated to explain the consensus.

**Comment by aarchiba** [comment]
A note about this should probably be in https://nanograv-pint.readthedocs.io/en/latest/_autosummary/pint.models.dispersion_model.Dispersion.html#pint.models.dispersion_model.Dispersion and maybe also the overall-DM docs. An explanation for why we use this one would go under Explanation and be referenced from the above docs.
