### ISSUE TITLE
POSEPOCH UNSET?

### ISSUE THREAD

**Issue by swiggumj** [nanograv/PINT#770]
For some reason, when I load the following par file, POSEPOCH is reported as being UNSET. I would have thought the normal behavior would be to default to PEPOCH (and in fact this is what happens for another pulsar -- can post that par file too if useful).

```
PSR             J2039-3616
RAJ      20:39:16.58366129  1          0.00016614
DECJ     -36:16:17.1980261  1           0.0021073
F0    305.3396375052649887  1  0.0000000003582430
F1     -8.783038619061D-16  1  2.622048190188D-17
PEPOCH        57537.417052
START            57535.435
FINISH           57850.660
DM               23.962515  1            0.000063
SOLARN0              10.00
EPHEM               DE421
#CLK                 UNCORR
CLK                 TT(BIPM)
UNITS               TDB
TIMEEPH             FB90
T2CMETHOD           TEMPO
CORRECT_TROPOSPHERE N
PLANET_SHAPIRO      N
DILATEFREQ          N
NTOA                   177
TRES                  7.07
TZRMJD  57538.39625245799456
TZRFRQ             350.012
TZRSITE                  1
MODE                     1
NITS                     1
BINARY            ELL1
A1             3.397588549  1         0.000000637
PB        5.78996369798269  1    0.00000001158898
TASC       57538.603316060  1         0.000000396
EPS1         -0.0000056519  1        0.0000003196
EPS2         -0.0000049732  1        0.0000004470
JUMP -fe Rcvr1_2       0 1
INFO -f
```

**Comment by swiggumj** [comment]
E.g.

```
TimingModel(
  AbsPhase(
    MJDParameter(   TZRMJD              57538.3962524579945602 (d) frozen=True),
    strParameter(   TZRSITE             1                 frozen=True),
    floatParameter( TZRFRQ              350.012           (MHz) frozen=True)),
  AstrometryEquatorial(
    MJDParameter(   POSEPOCH            UNSET,
    floatParameter( PX                  0.0               (mas) frozen=True),
    AngleParameter( RAJ                 20:39:16.58366129 (hourangle) +/- 0h00m00.0002s frozen=False),
    AngleParameter( DECJ                -36:16:17.19802610 (deg) +/- 0d00m00.0021s frozen=False),
    floatParameter( PMRA                0.0               (mas / yr) frozen=True),
    floatParameter( PMDEC               0.0               (mas / yr) frozen=True)),
...
```

**Comment by swiggumj** [comment]
I think I see the issue here. POSEPOCH = PEPOCH doesn't happen unless one/both of the PM parameters are non-zero (see below). If we agree this is not the intended behavior, I will open a PR. Proposed fix would be to remove the conditional based on PM params being non-zero.

```
    def validate(self):
        """ Validate the input parameter.
        """
        super(AstrometryEquatorial, self).validate()
        # RA/DEC are required
        for p in ("RAJ", "DECJ"):
            if getattr(self, p).value is None:
                raise MissingParameter("Astrometry", p)
        # If PM is included, check for POSEPOCH
        if self.PMRA.value != 0.0 or self.PMDEC.value != 0.0:
            if self.POSEPOCH.quantity is None:
                if self.PEPOCH.quantity is None:
                    raise MissingParameter(
                        "AstrometryEquatorial",
                        "POSEPOCH",
                        "POSEPOCH or PEPOCH are required if PM is set.",
                    )
                else:
                    self.POSEPOCH.quantity = self.PEPOCH.quantity
```

**Comment by swiggumj** [comment]
Code block above is found in https://github.com/nanograv/PINT/blob/master/src/pint/models/astrometry.py.

**Comment by paulray** [comment]
That sounds good to me. If POSEPOCH is None and PEPOCH is not, then set POSEPOCH to PEPOCH.

Just a tip, too. In GitHub you can select a range of line numbers in the code then click the little "..." button and select "Copy Permalink" to be able to reference code in a comment, like this:
https://github.com/nanograv/PINT/blob/eb9426591604ad24c06ff71bdd38175c1f8530b2/src/pint/models/astrometry.py#L228-L246

**Comment by swiggumj** [comment]
Oh nice! I'll try to remember that...

Ok, I'll get going on a PR.

**Comment by paulray** [comment]
As a further comment, I think this should raise a warning when it happens. People should be encouraged to set POSEPOCH to what they want explicitly in their par file and not just rely on it defaulting to PEPOCH. But, I agree it is useful to have it not fail.

**Comment by swiggumj** [comment]
@paulray can you point me to where other warnings like this have been implemented? Logging isn't already implemented in astrometry.py.

**Comment by paulray** [comment]
```
from astropy import log
log.warning("Set your own PEPOCH!")
```

**Comment by swiggumj** [comment]
Awesome thanks. I just found similar examples in toa.py, but now realize I used `import logging` in modelutils.py. Probably should fix this at some point too to be consistent.

**Comment by swiggumj** [comment]
I did run some tests to make sure it's working as expected: https://github.com/nanograv/PINT/pull/771

Bracing myself for "make unit tests!"
