### ISSUE TITLE
Black 20.8 reformats docstrings

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#778]
The new version of `black` pulled in by `pip install` reformats docstrings and a few other things (that were badly formatted to start off), so `master` no longer passes the blackening test.

**Comment by scottransom** [comment]
Ugh.  This sucks.  I have to admit that I don't like having Travis fail for completely legit and even PEP8-compliant code.  I'm all for having blacken'd code, but requiring it via failures doesn't seem like the right thing to me.

**Comment by paulray** [comment]
Yeah, I thought the benefit of black was that it didn't change
