### ISSUE TITLE
par files output by model.as_parfile() should work with TEMPO and Tempo2

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#78]
Currently, there are some issues with the par files output by model.as_parfile() that should be dealt with.
The first is there is no "UNITS" line, so Tempo2 assumes it to be TCB, which is wrong.  Since PINT only supports TDB so far, this is an easy fix, and I added "UNITS TDB" to the output produced by as_parfile().

In addition, the binary model should output the "BINARY BT" line.  This has to be implemented differently since it breaks the 1 par file line per parameter paradigm that as_parfile() assumes.

There may be some other control-type parameters that should be included in the output as well (CLK, MODE, etc...).  I haven't thought this all through yet, but I wanted to capture it as an issue.

**Comment by scottransom** [comment]
Should be smartly sorted as well!

**Comment by paulray** [comment]
I just found, thanks to Pablo Saz Parkinson, that when the binary model is written to the par file, it writes the OM line in DD:MM:SS.s format, not decimal degrees. This is not compatible with Tempo2, I believe.  This needs fixing.

**Comment by luojing1211** [comment]
Hi Paul, 

Which branch are you in? I did not find this problem. 
![screen shot 2016-07-29 at 10 44 01 am](https://cloud.githubusercontent.com/assets/5324931/17254260/aa99db7e-5579-11e6-8e54-f4b391b50c03.png)

**Comment by paulray** [comment]
Interesting. I didn't try it myself, I just saw the par file generated by Pablo. Possibly he is just running an older version of PINT and it is now fixed.

**Comment by paulray** [comment]
@kerrm just found that this issue was causing him pain.  Its priority should probably be elevated.

**Comment by paulray** [comment]
PR #236 should fix at least the writing of the binary model name.

A more complete solution seems like it would require more code, perhaps by making the parameter names somehow be grouped by what model they apply to.  This could, for example, be by adding the name of the TimingModel subclass to the Parameter.  Then, `model.F0.model_class` could be `Spindown` or something like that. And, the as_parfile() method could print all the Spindown parameters together, then all the BinaryBT parameters together, etc...

**Comment by paulray** [comment]
@kerrm just pointed out that the error on RAJ and DECJ is supposed to be in arcseconds. This is how it is interpreted by TEMPO, Tempo2, and even PINT. But, when writing with `as_parfile()`,  PINT outputs the errors in degrees. This is a bug.

**Comment by luojing1211** [comment]
I am just about to fix the AngleParameter. I think this can be fixed today.

**Comment by luojing1211** [comment]
Just a quick question. RAJ's unit is hourangle. Does the error of RAJ in
hourangle seconds or arcsecond?

-Jing Luo

**Comment by paulray** [comment]
The error on both RAJ and DECJ should be in arcseconds, not hourangle seconds.

**Comment by kerrm** [comment]
My understanding is that they were both arcseconds.  However, I just
checked the tempo2 code, and it looks like RAJ is treated as an hourangle
second, there.  I will double check with George -- the code is not
straightforward.

Cheers,
Matthew

**Comment by paulray** [comment]
OK, I deleted my previous comment, which seems to have been incorrect.

When I look at my par files from my timing paper, indeed all of the RAJ uncertainties are about a factor of 15 smaller than the DECJ uncertainties, and my plotting code multiplies by 15 to convert hourangle seconds to arcseconds when. 

So, I'm pretty certain that RAJ uncertainty is in hourangle seconds and DECJ uncertainty is in arcseconds. Sorry for my earlier misinformation.

**Comment by luojing1211** [comment]
@kerrm and @paulray, Can you test this out? If it still have problem, please let me know.

**Comment by paulray** [comment]
I tested it on all the par files in the examples directory and PINT produced usable and nicely formatted par files, including all the parameters we support. Obviously they were not identical to the input par files since PINT doesn't handle all parameters yet, especially the control parameters.  Closing this. People can add issues for particular incompatibilities that show up.

**Comment by kerrm** [comment]
It seems that PEPOCH is missing from the ephemeris output now, at least in my simple test case of reading and writing a tempo2 ephemeris.

**Comment by paulray** [comment]
Hmm. Can you provide an example? It comes out for me after reading a model and it did with the glitch test I just ran.  It does come out in a funny order, though.
```
In [5]: print(m.as_parfile())
PSR                            1748-2021E
RAJ                     17:48:52.75000000 1 0.00000000000000000000
DECJ                   -20:21:29.00000000 1 0.00000000000000000000
PMRA                                  0.0
PMDEC                                 0.0
PX                                    0.0
POSEPOCH            53750.000000000000000
F0                  61.485476554000000001 1 0.0
F1                             -1.181e-15 1 0.0
TZRMJD              53801.386051182230000
PEPOCH              53750.000000000000000
DM                                  223.9 1 0.0
PLANET_SHAPIRO                          N
UNITS TDB
TIMEEPH FB90
```

**Comment by paulray** [comment]
Also, I don't see how `tests/test_parfile_writing.py` could work if PEPOCH was not being written out.

**Comment by kerrm** [comment]
You're right :(  I somehow managed to overlook it in both of my test cases.  I'll grep next time!

**Comment by kerrm** [comment]
I came across a related issue today.  Lines like this:

 RAJ                     13:11:45.72364152 1 0.01000000000000000021

cause pint to break in utils.py

/home/kerrm/packages/PINT/pint/utils.py in str2longdouble(str_data)
    319     """
    320     input_str = str_data.translate(maketrans('Dd', 'ee'))
--> 321     return str2ldarr1(input_str.encode())[0]
    322
    323

TypeError: 'NoneType' object has no attribute '__getitem__'

This is apparently because str2ldarr1 is a stub!

 def str2ldarr1(*args, **kwargs):
     pass

**Comment by paulray** [comment]
I am not sure why `pint/str2ld.py` exists, with that stub. The actual function is defined in the cython code in `pint/cutils/str2ld_py.pyx`.   The .so should get built when you build and install PINT, but I don't exactly understand how the flow works.

**Comment by paulray** [comment]
@jellis18 you added pint/str2ld.py just a couple of months ago as part of "Read The Docs" integration. Why is it needed? Having it there seems to just be confusing. 

Although it doesn't seem to actually be causing a problem. This recent issue was caused by Matthew not having built PINT so the cython code didn't get compiled.

**Comment by jellis18** [comment]
@paulray, I added that stub for the documentation because to build the docs on the fly it needs to be able to import all of the packages (or at least custom packages). I'm not exactly sure why this is the case but the docs will fail without that stub. Although when the code is installed it should not use it but instead used the compiled python code.

So I just said the same thing as you. Bottom line is that if the stub is not there the docs will fail.

**Comment by paulray** [comment]
Ok, so there is no issue here.  Closing this again. Discussion now on the mailing list regarding getting rid of the last cython dependency in str2ld so PINT can be pure python.
