### ISSUE TITLE
Example notebooks break CI

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#782]
Someone needs to take a look at the example notebooks and see what is going wrong; they seem to be breaking our CI builds.

**Comment by aarchiba** [comment]
For example https://travis-ci.org/github/nanograv/PINT/jobs/723437499

**Comment by paulray** [comment]
This is fixed in master. Let me know if you still see problems after merging/rebasing on master.

**Comment by paulray** [comment]
I think this can be closed, right?
