### ISSUE TITLE
"zero phase" instantiation in glitch model is nonstandard/slow

### ISSUE THREAD

**Issue by kerrm** [nanograv/PINT#789]
glitch_phase begins the phase calculation by instantiation a "zero" vector as follows:

174         tbl = toas.table
175         phs = u.Quantity(np.zeros_like(tbl, dtype=np.longdouble))

This idiom doesn't make sense to me.  What does it mean to make zeros "like" a table?  Naively I'd expect to get an array with nrows x ncolumns.  But it does actually return the desired thing, an array with shape (ntoas,).  And it's very slow, at least for large numbers of TOAs (370,500 here):

timeit np.zeros_like(ts.table,dtype=np.longdouble)                                                                
**1.22 s** ± 20.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
 
timeit np.zeros(ts.ntoas,dtype=np.longdouble)    
**694 µs** ± 220 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)

It's a simple fix, replace line 175 with
175         phs = u.Quantity(np.zeros(toas.ntoas, dtype=np.longdouble))

**Comment by paulray** [comment]
This seems like a no-brainer.

**Comment by scottransom** [comment]
Yup.  Should just merge that.
