### ISSUE TITLE
Incorrect calculation of RMS residuals in pintk

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#794]
https://github.com/nanograv/PINT/blob/47f6fbe080995e9e9fa632eb5488a4e7c63d90c7/src/pint/pintk/pulsar.py#L186-L189

This code in pintk is wrong. It is reporting chi2/ntoas as the weighted RMS.  This happens for the pre-fit residuals as well.
It should use `resids.rms_weighted()` instead.  Similarly for when it prints out the residuals after reading in the toas initially.

**Comment by paulray** [comment]
Thanks to @juliadeneva for reporting this!

**Comment by juliadeneva** [comment]
`            "RMS PINT residuals are %.3f us\n"
            % self.prefit_resids.time_resids.std().to(u.us).value`

This line should also be changed to use `rms_weighted()`

**Comment by scottransom** [comment]
good catch!

**Comment by luojing1211** [comment]
This is fixed in the PR #876
