### ISSUE TITLE
Want round-trip tests for .tim file writing

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#798]
To check that we can write .tim files reliably we should be able to create a family of tests that load a .tim file (from a string in the test module is probably easiest) into a TOAs object t1, write that out to a temporary file (string if possible), read that back in to a new TOAs object t2, and compares t1 to t2. Cases worth considering:

- EFAC/EQUAD in the .tim file
- long double precision in the TOAs - round trip should be exactly the same floating-point number, or at most a few floating-point epsilon away
- .tim files originally loaded with the `ephem` parameter set to something weird
- .tim files containing barycentered TOAs (and a mix)
- .tim files (or TOA objects) with weird and/or excessive TOA flags
- .tim files with pulse numbers for all or some TOAs (-pn TOA flag)
- various clock correction weirdnesses (e.g. clock corrections applied/not applied to a TOAs object, an observatory with no clock corrections, TOAs before the beginning/past the end of the clock corrections)
- .tim files with INCLUDEs
- .tim files with SKIP, JUMP, commented TOAs, EMIN, EMAX, FMIN, FMAX, PHASE, START, END, TIME, PHA1, PHA2, TRACK, MODE, INFO
- .tim files in each format
- .tim files with shuffled lines

Probably good for some of these to check that the loaded TOAs object is what the original .tim intended, too, but a check-round-trip test is easy to write.

**Comment by aarchiba** [comment]
Currently it looks like PINT never writes any commands to the output file; every line is either an initial FORMAT 1 or a TOA line. It un-applies clock corrections if they have been applied. It also does some weird jiggery-pokery with the pulse numbers that will leave you with a -pn flag and a pulse number column both if an exception occurs while writing a file.

**Comment by aarchiba** [comment]
The documentation for `format_toa_line` is confusing and misleading - it does not and should not undo things like TIME. What is done with `clkcorr` should be checked, though.

**Comment by scottransom** [comment]
I think that it is basically impossible to make this work for all .tim files given the nature of old-school TOA-file commands, which we basically need to handle at some level.  That's because things like SKIP and END (and even EMAX and EMIN) actually change the way the file is *read*.  So the internal TOAs can't ever replicate what was in the file.

As long as we are fine with making sure that we write correct TOAs, and "fix" things that we know that we can and should fix (like the application of clock corrections), I do like the idea of having tests for that.  But having general tests that work for all .tim files probably isn't going to work.

**Comment by aarchiba** [comment]
Indeed this test is separate from whether we read ancient `.tim` files correctly - it starts from a loaded TOAs object, writes it out, and reads it back in. So it's testing the writing code and the reading code are compatible. There are lots of places this might not work - for example TOAs objects have a list `toa.commands` which presumably records the commands, in some format or other, observed in the original file, and these are not written out in any way. So these are lost in the write->read sequence. If they are used by some part of PINT, the user may be chagrined.
