### ISSUE TITLE
Allow usage on Windows

### ISSUE THREAD

**Issue by theXYZT** [nanograv/PINT#802]
There are currently only Linux and OSX builds provided on the conda-forge channel. It would be nice to have a Windows build for those using a Windows system. If possible, a cross-platform "noarch" build would suffice, I think.

I understand that an overwhelming majority of academics use Linux and OSX and Windows support is almost never a priority. However, it would be nice to have for those few of us who use Windows systems.

Given #522 and #526, this has been explicitly denied as `pint-pulsar` refuses to load on a platform that doesn't support > 64-bit floating-point precision. However, is it not better for the package to run at slightly reduced precision than to not run at all? There are many uses of `pint-pulsar` that aren't adversely affected by the lack of a > 64-bit floating point number. For example, the `polycos` submodule. Why not let the user decide?

It would be in the spirit of EAFP (easier to ask for forgiveness than permission) to allow this.

**Comment by theXYZT** [comment]
However, given #522 and #526, I am assuming the answer here is a hard: No.

**Comment by paulray** [comment]
I have no problem with having a conda build of PINT that works on Windows, but I don't have or use Windows, so it would require someone else to figure out how to do it and make a pull request.

**Comment by theXYZT** [comment]
For now, this could start with reverting #526, which at least allows the user to use `pint-pulsar` on Windows at their own risk. I would be happy to submit a pull request for this.

**Comment by paulray** [comment]
OK, maybe change the exception to a `log.error()` statement. Or maybe make it raise an exception on all platforms, except Windows where it gives a `log.warning()` explaining that it is running at reduced precision.
