### ISSUE TITLE
Bad code in format_toa_line

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#805]
As noted in a code comment:

https://github.com/nanograv/PINT/blob/cf70c57efeb7e74f958e442f501f626314d01bfa/src/pint/toa.py#L357-L361

this code is bad. It assumes that all observatories use the UTC timescale except for the barycenter.  This decision should be made by the Observatory object, which already has a `obs.timescale` parameter. So this should use it, rather than having this observatory-dependent code here. Thanks to @kerrm for pointing this out.

**Comment by luojing1211** [comment]
That makes sense. It seems an easy fix. What do you think @scottransom ?

**Comment by scottransom** [comment]
I think that is fine...  Although I'm not sure it makes any difference at all in practice as obs.timescale is defined to be "utc" for all of our observatories, I think!

**Comment by paulray** [comment]
True it won't change anything immediately, but Matthew and I were talking about adding an observatory at the geocenter with a timescale of TT for spacecraft data and that is how we found that you'd have to change both the observatory class and this special casing in toa.py, which is bad form.

**Comment by scottransom** [comment]
Fair enough!  I'm certainly not opposed to changing it....
