### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by matteobachetti** [nanograv/PINT#81]
Hi all, 
I reinstalled PINT in a linux (Ubuntu 14.04) virtual machine. PySPICE compiled correctly, `setup.py` modified accordingly. PINT installed both "in place" and with the standard `setup.py install`. But when I try to use PINT, I get the following error:
```
In [1]: import pint.toa  
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-24f6be3bb6b2> in <module>()
----> 1 import pint.toa

/software/PINT/pint/__init__.py in <module>()
      9 import astropy.constants as c
     10 import astropy.time as time
---> 11 from . import utils
     12 
     13 # light-second unit

/software/PINT/pint/utils.py in <module>()
      9 import astropy.units as u
     10 from astropy import log
---> 11 from spice_util import str2ldarr1
     12 
     13 class PosVel(object):

ImportError: ./spice_util.so: undefined symbol: furnsh_c
```
do you have the same problem? How did you solve it, in this case?

**Comment by luojing1211** [comment]
Did you change your PySPICE path in the Setup.py file? Check your setup.py file at line 13.

**Comment by matteobachetti** [comment]
Sure, I did it.

On Sat, Jan 2, 2016 at 6:05 PM, luojing1211 <notifications@github.com>
wrote:

> Did you change your PySPICE path in the Setup.py file? Check your setup.py
> file at line 13.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nanograv/PINT/issues/81#issuecomment-168407313>.
>



-- 
*********************************************
Matteo Bachetti

www.matteobachetti.it

"I would love to change the world,
but they won't give me the source code"
*********************************************

**Comment by luojing1211** [comment]
Hi Matteo, 
I can not reproduce the error. But it could be a SPICE issue. Could you run 
>>import spice
>>spice.furnsh
see what it returns. 

-Luo Jing

**Comment by matteobachetti** [comment]
No problem there.
```
In [2]: import spice

In [3]: spice.furnsh
Out[3]: <function _spice.furnsh>
```

**Comment by matteobachetti** [comment]
Ok. I finally managed to track down the origin of the problem. It was due to bad permissions in a shared directory. Thanks for your help, it wasn't related to PINT after all.
