### ISSUE TITLE
fitter.set_fitparams() cannot take the output of fitter.get_fitparams() 

### ISSUE THREAD

**Issue by pennucci** [nanograv/PINT#816]
The output of get_fitparams is an Odict of key,val pairs, but set_fitparams appears to work only on a list/tuple of param names.  Passing the output of get_fitparams to set_params raises no warning, and fixes/freezes all parameters.  There's even a comment in set_fitparams: "# TODO, maybe reconsider for the input?"

This issue can easily raise problems for users that are making reasonable assumptions about the API.

**Comment by aarchiba** [comment]
wait why does a fitter let you change the parameters that are fit? Shouldn't this be a method on the models?

**Comment by aarchiba** [comment]
Is there a method that lets you set which parameters are free on a model, the way this does on a fitter?

**Comment by pennucci** [comment]
I think these are both questions of the code's API philosophy and syntax.  I got so used to the "fit" terminology as a verb meaning "to set this model parameter as a free parameter", that I didn't see it as potentially confusing.  i.e., setting which parameters are "fit for" could be seen as specifying what parameters should be included as part of a model (irrespective of free/frozen/'fit'), which is a function that should be, I think, a method on the model class.  I think changing which parameters are free/frozen should be a method on the fitter.  This point of confusion/contention was discussed on the previous PINT telecon, I think.

**Comment by aarchiba** [comment]
Indeed there is explicit API discussion happening on the PR #822 . As it stands, the free/frozen status of a parameter is recorded as part of the model object, and setting them one by one must be done on the model object. But as it stands now, setting them in bulk requires putting the model into a Fitter, which also requires a collection of TOAs. I could imagine an argument that the free/frozen status information should be moved into the Fitter (though I do not think they should), but having the individual settings in the model but the bulk setting in the Fitter does not make sense to me.

**Comment by scottransom** [comment]
As mentioned [here](https://github.com/nanograv/PINT/pull/823#discussion_r528434633), you *can* set params in bulk in the model with a one-liner.

Given that a Fitter has an associated model with it, that models can potentially be fit, and that we are stuck (from TEMPO/Tempo2) with having models have fit flags, I don't see why both the fitter and the model classes couldn't have bulk setters and getters for free and/or frozen params (heck, there could be an alias for "fit" params == "free" params for T/T2 users).  They are only syntactic sugar since they can be implemented as one-liners (the Fitter's method could simply call the Model's), but they would certainly be useful for users in both places.

Is that a problem for some reason?

**Comment by scottransom** [comment]
Heck, while we are at it, we could add helper functions to add/remove individual free/frozen params from the current set of free/frozen params.  Those are each also one-liners and would be really useful (both in the fitter and in the model instances).

**Comment by pennucci** [comment]
I see no problem with any of that, I agree with it all, actually, at face value.  I would have guessed that one set of methods actually just calls the other's (i.e, the fitter.set_frozen method actually calls the model's) in the first place, to avoid code duplication, since a fitter needs a model.

**Comment by aarchiba** [comment]
> As mentioned [here](https://github.com/nanograv/PINT/pull/823#discussion_r528434633), you _can_ set params in bulk in the model with a one-liner.
> 
> Given that a Fitter has an associated model with it, that models can potentially be fit, and that we are stuck (from TEMPO/Tempo2) with having models have fit flags, I don't see why both the fitter and the model classes couldn't have bulk setters and getters for free and/or frozen params (heck, there could be an alias for "fit" params == "free" params for T/T2 users). They are only syntactic sugar since they can be implemented as one-liners (the Fitter's method could simply call the Model's), but they would certainly be useful for users in both places.
> 
> Is that a problem for some reason?

I think the problem with having the bulk setter/getters on the Fitter objects also is the proliferation of functions in the API, where the "one-liner" involves no actual logic: `f.free_params` versus `f.model.free_params`. By contrast the code required to implement the setter for `free_params` involves a loop, `getattr`, and the use of `match_param_aliases`: https://github.com/nanograv/PINT/pull/822/files#diff-7cbfb3877d78c1fbb69c8d3e37bf61c30f2bf40de4934ad13675f1064686b003R278

**Comment by scottransom** [comment]
> I think the problem with having the bulk setter/getters on the Fitter objects also is the proliferation of functions in the API, where the "one-liner" involves no actual logic: `f.free_params` versus `f.model.free_params`.

I'm not seeing a problem with that, especially if `f.free_params` calls `f.model.free_params`.  If I was going to modify the fit/free params *the* place I'd look to do that is in the fitter.  However, if you are a "I'd look in the model" person, doing there would work as well.

I don't see that as proliferation at all. It is simply making a useful bit of code available where people are most likely to find it.  It doesn't cost us anything.

**Comment by aarchiba** [comment]
So this is somewhat rearranged now, but you can use `model.get_params_dict("free","num")` to get a dictionary with the numeric values of the free parameters, and then `model.set_params()` to set those parameters to those values. Setting *which ones* are free isn't something you want a dictionary for, and so you just use `model.free_params = ["F0", "STIGMA", "CAPYBARA"]`.
