### ISSUE TITLE
Downloading .par files

### ISSUE THREAD

**Issue by Midooka** [nanograv/PINT#819]
Just after installing PINT, I'm trying to run "photonphase" using FITS file obtained with RXTE (OBS ID 60081; Good Xenon mode). 
Question: Where can I download the appropriate .par file? 
Although I used the /PINT/tests/datafiles/PSR_J0218+4232.par, I failed to reproduce coherent pulses.  
Even if I also used the ATNF ephemeris, which UNIT was converted from TCB to TDB, pulses were not seen.
https://www.atnf.csiro.au/people/pulsar/psrcat/

**Comment by paulray** [comment]
I would not use the test files in PINT for science.  You can find several per files for J0218 here:
https://fermi.gsfc.nasa.gov/ssc/data/access/lat/ephems/

Are you barycentering the RXTE data first?  photonphase should actually work either way, as long as you provide the FPorbit file.

**Comment by paulray** [comment]
The Fermi second pulsar catalog par file is also available here: https://fermi.gsfc.nasa.gov/ssc/data/access/lat/2nd_PSR_catalog/

**Comment by paulray** [comment]
This paper talks about the RXTE analysis: https://ui.adsabs.harvard.edu/abs/2004AdSpR..33..507K/abstract

**Comment by Midooka** [comment]
I appreciate your quick response!
I've read the paper, thank you for your kindness.

I have three types of light curve files; with/without barycentering and with barycentering&binary correction with my python script.
One of reasons to use PINT is to verify the validity of the script by an independent method.
In this purpose, is the better approach to use RXTE data before barycentric correction with the FPorbit file?

**Comment by Midooka** [comment]
How should I determine the best par file?

**Comment by paulray** [comment]
Look at START and FINISH in the par file. If your data are within that range, you are certainly fine. If not, it depends on how well the ephemeris extrapolates. For MSPs you can often extrapolate quite a way.

**Comment by Midooka** [comment]
I understand now, I appreciate your support a lot!
