### ISSUE TITLE
Proper motion evaluation changes epoch time frame

### ISSUE THREAD

**Issue by kerrm** [nanograv/PINT#820]
I recently noticed models with a proper motion were taking much longer to evaluate phase.  Profiling reveals the slowdown is in delay calculations like the solar system geometry delay and solar system Shapiro delay, which (in my timing model), invoke AstrometryEquatorial.ssb_to_psb_xyz_ICRS.  That in turn ultimately calls AstrometryEquatorial.get_psr_coords, which uses astropy and the apply_space_motion method of SkyCoordinate to compute the position at the provided epochs.

In ssb_to_psb_xyz_ICRS, this is invoked like this:

`L_hat = self.ssb_to_psb_xyz_ICRS(epoch=tbl["tdbld"].astype(numpy.float64))`

get_psr_coords takes a kwarg epoch (default None).  If it is not already an instance of astropy.Time, as is the case with the above call, it does this:

`newepoch = Time(epoch, format="mjd")`

The default scale for time is TAI, but the obstime attribute of the pulsar SkyCoordinate has scale=='tdb'.  Calculating the deltas in apply_space_motion is then very slow, and moreover, seems like it's in error since the argument was already in TDB.  This can be checked by requesting the pulsar coordinates at POSEPOCH: doing so yields a position that's off by about 0.13 mu-as in my test.

I propose the simplest possible fix, namely adding

`newepoch = Time(epoch, scale="tdb",format="mjd")`

and adding some documentation to indicate that if the epoch is passed as float MJDs they need to be TDBs.  This speeds up the calculation substantially and results in a <2e-4 mu-as offset when checking against POSEPOCH.  (It *should* be 0, but -- see below.)

Questions/issues:
(1) Do you agree with the solution?
(2) Should other coordinate systems also expect their epoch to be TDB?  I think so.
(3) In testing this out, I found out that astropy fails a very simple sanity check, namely

`c0.apply_space_motion(dt=0*u.day).separation(c0).to(u.microarcsecond)                                                              
Out[5]: <Angle 0.00019839 uarcsec>`

Is this a problem?  If so, we might want to raise an issue.  I'm considering adding this to the PINT test suite, but it's obviously going to fail until it's fixed upstream.
(4) Any thoughts on other tests?

I'm happy to put together a PR.

**Comment by aarchiba** [comment]
That looks like an Astropy bug, and maybe one indicative of a subtle coordinate conversion. It seems worth filing. If there's some numerical precision issue there I assume they'll explain. I would suggest adding something to the PINT test suite to check the bug behaviour, but setting the numerical tolerance to 1e-3 uas (or something) - we are not actually troubled by this much discrepancy and we can turn down the threshold if Astropy fixes their bug.

**Comment by kerrm** [comment]
Thanks Anne, I agree with adding a loose-ish test.  I reported the issue on astropy, I don't think they're too impressed with the importance, but that's OK :)
