### ISSUE TITLE
get_model_new should not exist

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#827]
The function `get_model_new` should not be part of PINT. It was created to support development of a procedure to read parfiles and make models in a way that was more robust than the original, in terms of `.par` file validation (possibly preventing things like #813 ?) and the ability to (for example) read from `StringIO`. It is also intended to be clearer to read and obey easier to explain `.par` file deduction rules than the existing `get_model`. If it is better than `get_model`, it should replace `get_model` and a lot of code can go. If it's not better, it should probably be removed.

**Comment by abhisrkckl** [comment]
get_model_new seems to have been removed. closing.
