### ISSUE TITLE
TimingModel objects produce and suppress RecursionError while being copied

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#828]
The `__getattribute__` machinery in TimingModel objects interacts with `copy.deepcopy` in such a way that RecursionErrors are generated. This is suppressed by a bare `except` in `TimingModel.__getattr__`. The bare `except` has the side effect of making any exception in a property look like a missing attribute, so this causes other problems, in addition to the wastefulness of running the stack twenty levels deep or whatever Python's limit is. This can be triggered by `tests/test_fitter.py`.

With a custom warning added I can display:
```
tests/test_fitter.py::test_fitter
tests/test_fitter.py::test_ftest
  /home/archibald/projects/pint/PINT/src/pint/models/timing_model.py:222: UserWarning: Exception <class 'RecursionError'> maximum recursion depth exceeded while calling a Python object was raised in __getattr__(components)
    warnings.warn("Exception {} {} was raised in __getattr__({})".format(type(e), e, name))
```

**Comment by aarchiba** [comment]
This cropped up in #795 making the error hard to understand

**Comment by luojing1211** [comment]
I believe this error comes from the way that `__getattr__` works in both `TimingModel` object and `Component` object. To enable the feature that one can access any attribute from both TimingModel level and Component level, `__getattr__` in the timing model searches for the attributes from the components if it is not in the `TimingModel` object. Then the component `__getattr__` will look for it in the component. If it is not there, `Component` will search for it in the parent TimingModel object. If one attribute in the TimingModel search for its own name in the components and if the components do not have that name, it will fall into that loop. 

I know this is very problematic. My proposal is to use a dictionary to log all the accessible attributes in the TimingModel. But I know it is not perfect either.

**Comment by aarchiba** [comment]
Just to be clear, as I understand it, there are two reasons one might want __getattr__ on a TimingModel object:

- So that m.F0 works - Parameters are accessible as attributes of the TimingModel.
- So that m.coords_as_GAL() works - methods on Components are accessible as methods on TimingModel.

Does that cover it? Are there any reasons one might want __getattr__ on a Component? Any reason a Component should inherit from TimingModel?

**Comment by luojing1211** [comment]
Both reasons are valid, and there is a third reason. 
* One can access the other component's attributes from one component. For instance, m.component['DDK'].PMRA, where PMRA is in the Astrometry component. 

Component is not a inherit from TimingModel. This is to avoid the duplicated attribute names.

**Comment by aarchiba** [comment]
> Both reasons are valid, and there is a third reason.
> 
>     * One can access the other component's attributes from one component. For instance, m.component['DDK'].PMRA, where PMRA is in the Astrometry component.
> 
> 
> The `Component` is not a inherit from TimingModel. This is to avoid the duplicated attribute names.

This last seems like it could be handled just as well by the component accessing the TimingModel, which makes available all the parameters? This would remove the need for __getattr__ on Components and dramatically reduce the problems working with them.

**Comment by aarchiba** [comment]
Making parameters accessible as if they were attributes of the TimingModel/Component has the downside that programmatic access forces users to use `getattr`, which is always cumbersome. I have been thinking about whether providing __getitem__ as an alternative would be helpful? This would allow `m["F0"]`, or

```python
for p in params:
    m[p].frozen = True
```

It would also provide a means independent of __getattr__ to obtain parameters - so __getattr__ would never call anyone else's __getattr__ (or __getattribute__) and recursion might be preventable. One could do the same with a function with a normal name instead, though that would be more cumbersome to write.

**Comment by scottransom** [comment]
> > The `Component` is not a inherit from TimingModel. This is to avoid the duplicated attribute names.
> 
> This last seems like it could be handled just as well by the component accessing the TimingModel, which makes available all the parameters? This would remove the need for **getattr** on Components and dramatically reduce the problems working with them.

How does that work practically?  Is there a simple toy example of this?  We've wrestled with this since the very beginning.

And we've considered **getitem** as well.  Are you suggesting using it *instead* of **getattr** or as an other option (i.e. to make it easier for those programming)?  Having the parameters visible as if they were attributes was really to make interactive work nicer and to shrink the size of timing related functions etc.  I do agree that using getattr() is kind of a pain.

**Comment by aarchiba** [comment]
> > > The `Component` is not a inherit from TimingModel. This is to avoid the duplicated attribute names.
> > 
> > 
> > This last seems like it could be handled just as well by the component accessing the TimingModel, which makes available all the parameters? This would remove the need for **getattr** on Components and dramatically reduce the problems working with them.
> 
> How does that work practically? Is there a simple toy example of this? We've wrestled with this since the very beginning.
> 
> And we've considered **getitem** as well. Are you suggesting using it _instead_ of **getattr** or as an other option (i.e. to make it easier for those programming)? Having the parameters visible as if they were attributes was really to make interactive work nicer and to shrink the size of timing related functions etc. I do agree that using getattr() is kind of a pain.

I don't have a complete solution. But since m.F0 is well established now I'm not proposing getting rid of it. But if m["F0"] did the same thing, that would remove almost all the situations where users now need to use `getattr`. My hope is that the implementation of `__getattr__` could then be simplified - instead of using `super().__getattribute__`, which is deep magic indeed and I don't understand why it's the right answer, and then recursing, `__getattr__` would then just look things up with `[]`.

Unfortunately this doesn't address the problem of making Component methods accessible on TimingModel objects. But I think if the problem is clearly defined we could evolve a more comprehensible solution to this problem of delegation, as well as some tests that confirmed that it presented no surprises.

I think that the `RecursionError` problem fundamentally comes about because `TimingModel.__getattr__` needs to access a bunch of attributes of `self`, for example `components`, and if those don't exist yet - for example part-way through construction - `__getattr__` is called. Implementing `__getattr__` opens a serious can of worms, and the more elaborate the implementation the bigger the can. (As another example, properties that accidentally raise AttributeError are treated as if they weren't found.) We can't get rid of `__getattr__` but the more we can simplify it the better.

**Comment by aarchiba** [comment]
We might be able to abolish the `__getattr__` on `Component` objects - it seems like it's mostly used to access Parameters from other Components and we could maybe do away with that.

**Comment by aarchiba** [comment]
So with a bit of examination, there is a circular problem in the definition: If you ask a timing model for the nonexistent attribute `capybara`, then by definition, the timing model should look in all its components for `capybara`. But If you ask a component for the nonexistent attribute `capybara`, it will look in the timing model that contains it for `capybara`. This naturally enough hits the recursion limit. But PINT relies upon catching RecursionErrors to try the next component.

I don't actually see a way to break this definitional loop, other than making Components not implicitly look in their parents. Unfortunately they were written to do things like use `self.DM` rather than `self._parent.DM`, and while the exceptions can be cleaned up, there are some very peculiar errors that arise.

**Comment by aarchiba** [comment]
I'll point out that the RecursionError triggers about a thousand function calls deep, and finding something - a parameter value say - in the nth component requires something like n*(n-1)/2 RecursionErrors to be caught, so this is a performance issue.

**Comment by scottransom** [comment]
Is it possible for a component, when it asks the parent timing model if it has a parameter, to pass its (i.e. the component's) name/ID/hash with it so that the timing model won't query it again and only look in the *other* components?  Seems like the parent model could keep track of which components it has asked.

**Comment by luojing1211** [comment]
I was thinking to have the component attributes register to at the parent class, so that everything is visible to the parent class and not need to go and ask the components. However, if one adds an attribute on the fly, this would not work.

**Comment by aarchiba** [comment]
> Is it possible for a component, when it asks the parent timing model if it has a parameter, to pass its (i.e. the component's) name/ID/hash with it so that the timing model won't query it again and only look in the _other_ components? Seems like the parent model could keep track of which components it has asked.

Not if we're using getattr. And without some extremely devious stack trickery, then you just bounce between two Components. 

I really think just making Components have to ask their `_parent` for any attribute they don't contain themselves is a better answer.

**Comment by aarchiba** [comment]
That is, remove `Component.__getattr__` entirely, and use `self._parent.DM`. For one thing anything you're relying on the parent for might be missing if the model doesn't have the right other Components, so Component writers should stop and think about doing this.

**Comment by aarchiba** [comment]
So far most of the problems have been manageable, but `test_ddk.py` mysteriously fails - no exception, just inaccurate values - with `Component.__getattr__` disabled.

**Comment by aarchiba** [comment]
> So far most of the problems have been manageable, but `test_ddk.py` mysteriously fails - no exception, just inaccurate values - with `Component.__getattr__` disabled.

Mysteriously went away. All tests pass now.
