### ISSUE TITLE
pickles are not regenerated if ephem parameter is changed

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#837]
The `usepickle` argument is meant to provide a transparent cache of TOAs objects. So if the `.tim` file changes, they should be regenerated. But if the `ephem` argument to `get_TOAs` is changed, the pickle is silently loaded and contains data processed with the old `ephem` value. The pickle should be considered invalid and either regenerated or at least raise an exception if it does not use the `ephem` value the user requested.

**Comment by paulray** [comment]
Yeah, that looks to be true. The restored pickle file will have its `ephem` attribute set to the value that was used when the pickle was made, so the `ephem` argument to `get_TOAs()` is ignored when there is a pre-existing pickle file.  

There is already a check like this for the version of PINT that was used to create the pickle file.  A check for consistent `ephem` could easily be added.
https://github.com/nanograv/PINT/blob/894ec0d8bf12bcd16ff29a6987758b5e159056a3/src/pint/toa.py#L1627-L1632
