### ISSUE TITLE
.tim files cannot record full information required to load them repeatably

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#841]
The full TOAs object obtained from a `.tim` file depends on the value of `ephem` passed to `get_TOAs`; similarly several clock correction parameters. NANOGrav folks would like to be able to encapsulate these options in some canonical way, in the interest of replicability. The relevant options could be recorded as TOA flags, if those TOA flags were respected upon loading of `.tim` files. One would have to think through what to do with files for which, say, `ephem` was specified only for some TOAs, or for which conflicting values of `ephem` were specified.

**Comment by paulray** [comment]
Perhaps a command that applied to all TOAs, instead of TOA flags, would be better.
So, `EPHEM DE436` in the par file, could be respected.  Only one would be allowed, and one would have to decide which takes precedence if `ephem` is specified in the `get_TOAs()` call.

**Comment by aarchiba** [comment]
It's tricky because as we manage it the ephemeris is needed to load TOAs, before a par file even becomes relevant.

**Comment by paulray** [comment]
Indeed, but @scottransom was going to write a method that loaded TOAs with those kind of options coming from a particular model (EPHEM, PLANET_SHAPIRO). That would solve the NANOGrav problem.

**Comment by scottransom** [comment]
Yes, that should happen this week!  Note that I think any command line options should trump options in a parfile.  But parfile options should trump the default get_TOAs() values.  Let me know if you disagree!

**Comment by scottransom** [comment]
And note that I'm not sure that I like anything that is not truly related to the TOAs to be put into .tim files.  For instance, TOAs are completely valid without any direct reference to a timescale for the model (i.e. BIPM2019).  And similarly whether PLANET_SHAPIRO is calculated or not.  However, those things *are* relevant when the TOAs are combined with a full timing model.  And I *think* that if we use a new method that loads a .par file and then a .tim file appropriately, all of the relevant things should be accounted for.

**Comment by paulray** [comment]
Yes, I agree

**Comment by scottransom** [comment]
> It's tricky because as we manage it the ephemeris is needed to load TOAs, before a par file even becomes relevant.

Not sure why you say that...  Once again, TOAs are completely valid (i.e. if from an Earth-based observatory, they are defined to be MJD UTC) without all the bells and whistles that can (optionally) be in a parfile.  So you can use "regular" TOAs to bootstrap a full timing solution (which is, of course, exactly what we do in practice).

**Comment by aarchiba** [comment]
> > It's tricky because as we manage it the ephemeris is needed to load TOAs, before a par file even becomes relevant.
> 
> Not sure why you say that... Once again, TOAs are completely valid (i.e. if from an Earth-based observatory, they are defined to be MJD UTC) without all the bells and whistles that can (optionally) be in a parfile. So you can use "regular" TOAs to bootstrap a full timing solution (which is, of course, exactly what we do in practice).

Well, as it stands now our TOA objects include Earth positions and velocities, and these cannot be computed without an ephemeris object. (This does seem to pose issues for things like BayesEphem that want to vary the ephemeris as part of the fitting, but it seems people can work around this structure in PINT.) But I have no personal stake in how the problem of storing and sharing reproducible timing solutions is solved, apart from hoping we can offer something better than pickled TOAs objects.

**Comment by scottransom** [comment]
Ah.  Gotcha, you were talking about our TOAs() objects/instances.  I was talking about the TOAs themselves in the .tim files (sorry for the nomenclature overlap!).  I'm leery of storing this kind of thing in the .tim files.  But I think it is completely appropriate to store it some other way (i.e. in .par files) or programmatically  via a script/notebook that specifies the appropriate options/flags upon loading of the .par/.tim files.  I think that should satisfy what we want to do in NANOGrav.
