### ISSUE TITLE
conda-forge package tries to downgrade astropy

### ISSUE THREAD

**Issue by theXYZT** [nanograv/PINT#846]
Hi,

When trying to install `pint-pulsar` via conda-forge, the package specifications try to downgrade astropy from 4.2:

```
The following packages will be DOWNGRADED:

  astropy                                4.2-py38h497a2fe_0 --> 4.0-py38h1e0a361_2
```

Seems like there's an error in the conda-forge recipe and probably should be fixed.

**Comment by theXYZT** [comment]
I suppose this is me just asking for a new release. Since, the `master` branch currently behaves well with `astropy=4.2` and I see the `requirements.txt` was only changed 3 months ago, after the last official release (0.7).

**Comment by paulray** [comment]
Yep, we are trying to get 0.8 out very soon, with a bunch of new features. Note that it drops Python 2.7 support.

**Comment by paulray** [comment]
Version 0.8 and 0.8.1 have now been released. The astropy 4.x series is now supported (and required, in fact)
