### ISSUE TITLE
Bugs in Polyco writer

### ISSUE THREAD

**Issue by theXYZT** [nanograv/PINT#847]
Here's a comparison between Polyco entries generated with the same parameters between `tempo2` and `PINT`:

```
# tempo2 -tempo1 -f test.par -polyco ...

B1937+21    5-May-18  223000.00   58243.93750000000            71.022344 -0.715 -6.258
 146695203280.882825  641.928232294317   ao   72   12   327.000                
  7.58475477599393022e-07  2.75691843068349529e+00  1.05182499406509443e-04
 -5.53800809293190177e-08 -1.79274838947070341e-10 -1.40505010500570550e-12
  1.44770018627411138e-14  2.02242076264123854e-15 -1.29392880277010108e-17
 -1.27054996558261958e-18  3.76553463657722022e-21  2.91010567554812097e-22

# pint.polycos.Polycos.write_polyco_file()

B1937+21  06-May-18 003600.00 58244.025 71.02227638          0.0   0.0
146700056607.221987 641.928232294317  ao   7      12   327.0                0.0  
4.21842087313951317e-08  2.77946124184379206e+00  6.89972511753701793e-05  
-1.30719833893706870e-07 -1.21324048857498680e-10 1.49527601758533278e-14  
1.17225403493628147e-14  1.20414395241383120e-16  -1.05153148084523127e-17 
-3.95887144140585074e-20 3.32837169386443349e-21  -6.16403723498682311e-25 
```

PINT's Polyco file writer fail to match the [format specification](http://tempo.sourceforge.net/ref_man_sections/tz-polyco.txt) in terms of positions and lengths of segments.

But an even more serious bug: The `nspan` value which should be `72` gets truncated to `7` in PINT's output!

I would be happy to submit a pull request to fix these issues. If there are additional thoughts/suggestions on these bugs, I'd be happy to incorporate them in my PR.

PS: Funnily, `tempo2`'s output doesn't exact follow the format specification either (and the specs seem to be incomplete as well when it comes to binary orbit parameters)! I would love to know if there exists a better, more updated specification for the Polyco format.  Weirdly, even the comments on `polyco.C` in the current `tempo2` repository on bitbucket are also incorrect!

**Comment by aarchiba** [comment]
Oh dear. The messy conflicting implementations are disappointing, but I'm afraid not surprising. A PR would be very welcome, especially if it included a few test cases, including some round-trip tests (does a polyco written out and read back in produce the same values?).

**Comment by paulray** [comment]
Yes, polycos got implemented in PINT a while back but I think have been barely tested. Having someone work on them would be MOST welcome!

**Comment by theXYZT** [comment]
Can someone confirm for me what the minimum Python 3 version supported for the next release will be (with Python 2 being dropped), I am wondering if I can use f-strings or not.

**Comment by scottransom** [comment]
It will probably be 3.7 since I believe numpy is likely dropping 3.6 very soon.

**Comment by paulray** [comment]
Currently we support 3.6, but I'd be ok with dropping that at the next release.

**Comment by demorest** [comment]
I don't think we should drop python 3.6 unless there is a good reason to.

**Comment by scottransom** [comment]
@demorest there was a big discussion on the numpy developers mailing list recently.  They are almost certainly going to drop it ASAP, and most packages that follow numpy will likely immediately follow suite.  So that means scipy, matplotlib, and astropy.  Those are pretty good reasons.

**Comment by scottransom** [comment]
Oops.  I was wrong.  It has already happened:  http://numpy-discussion.10968.n7.nabble.com/Python-3-6-has-been-dropped-from-NumPy-1-20-td48649.html

**Comment by scottransom** [comment]
And I found the document that numpy is pushing for the whole scientific python enterprise to follow:  https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by demorest** [comment]
So if PINT requires numpy 1.20 which in turn requires py3.6, I'd say that's a good reason to drop py3.6.  If not I don't see why we need to rush to drop support for it.

**Comment by paulray** [comment]
Yeah, if PINT still works with a version of numpy that requires 3.7, then we could keep support for 3.6.
I guess it just depends on whether we adopt bleeding edge features of numpy, scipy or astropy that force us to stop supporting older versions.

**Comment by theXYZT** [comment]
One feature of 3.7 that might be useful for this package is guaranteed order-preserving dictionaries.

**Comment by paulray** [comment]
According to this, that appeared in 3.6: https://pymotw.com/3/collections/ordereddict.html

But, if we write code that assumes ordering, isn't it better to explicitly use OrderedDict?

**Comment by theXYZT** [comment]
> According to this, that appeared in 3.6: https://pymotw.com/3/collections/ordereddict.html
> 
> But, if we write code that assumes ordering, isn't it better to explicitly use OrderedDict?

The built-in dict is faster and more memory efficient (by factors of 2-3 each), and OrderedDict will likely get deprecated in the future. That being said, I doubt this really affects PINT since I don't see large dictionaries being used here where any of this would matter. I just used OrderedDict in my refactoring of the polyco module.
