### ISSUE TITLE
DMJUMP fitting is not working

### ISSUE THREAD

**Issue by pennucci** [nanograv/PINT#851]
In some cases, just freeing the DMJUMP parameters and iterating appears stable, in others it goes off the rails.  Perturbing the DMJUMP parameters is similar.  In all cases, the uncertainties on the DMJUMP and DMX parameters become very large and all nearly identical (out to 7 or 8 decimal places).  So something is out of whack.

**Comment by aarchiba** [comment]
Can you tell whether it's in the fitter or the model? Do the right things happen to the residuals when you tweak DMJUMP?

**Comment by pennucci** [comment]
I can look into this tomorrow a bit more, but I think it's in the fitter.  The reason I say this is that when keeping DMJUMPs fixed to their best-fit values (as determined by enterprise in the 12.5-year results), the TOA and DM residuals, and their chi2's and rms's, agree with what tempo produces.

**Comment by aarchiba** [comment]
Actually it looks like WidebandDMResiduals already have the problem - if I change the DMJUMPs, the Residuals do not change in the obvious way. (Add i+1 to the ith DMJUMP parameter, the corresponding DM values in the residuals should increase by i+1.)

**Comment by pennucci** [comment]
@aarchiba isn't this just a result of the residuals being mean-subtracted?  I find that the DMJUMPs get applied appropriately other than that.  I guess that shouldn't happen prefit / if there's no fit and the residuals should reflect the absolute addition of the DMJUMPs.

**Comment by aarchiba** [comment]
How is it correct to mean-subtract DM residuals? That can't be right. DM is a parameter, as is DMJUMP, any mean subtraction is going to interfere with fitting for one or both parameters.

**Comment by pennucci** [comment]
I don't think it's correct, but that appears to be what's happening.  I just had a look to confirm:
`class WidebandDMResiduals(Residuals):
    """Residuals for independent DM measurement (i.e. Wideband TOAs)."""

    def __init__(
        self,
        toas=None,
        model=None,
        residual_type="dm",
        unit=u.pc / u.cm ** 3,
        subtract_mean=True,
        use_weighted_mean=True,
        scaled_by_F0=False,`
I'm not sure how that gets used elsewhere, but that could be part of the issue.

**Comment by aarchiba** [comment]
Do you have a tidy test case where DMJUMP fitting goes wrong? I can see that the WidebandTOAFitter does not turn off mean subtraction (but it would be easy to add it).

**Comment by luojing1211** [comment]
Ok, I see. We should not do mean-subtract on DM residuals. Let me make a PR to set it to False as default.

**Comment by aarchiba** [comment]
I can fold that into #861 .

**Comment by luojing1211** [comment]
That will be great. I just tested it out. One test in the residual will fail. But should be straightforward to fix. It is at PINT/tests/test_residuals.py:60.

**Comment by pennucci** [comment]
> Do you have a tidy test case where DMJUMP fitting goes wrong? I can see that the WidebandTOAFitter does not turn off mean subtraction (but it would be easy to add it).

Frustratingly, not the simple one from last week.  I cannot reproduce the simple wrongness I saw earlier.  The fact that the uncertainties on DMX and DMJUMP parameters are way larger than you would expect still holds, though.  I was also previously perturbing DMJUMP parameters and then it would break, but now there's no simple, tidy example that I think is 'general'.  One line of thought to keep in mind is that if WB TOAs have two bands and the TOA frequencies do not vary greatly, the JUMPs and DMJUMPs can be highly correlated because the value of the JUMP can change the mean DMX parameter value, in turn changing the DMJUMPs.

**Comment by aarchiba** [comment]
I have a test case that seems obviously wrong: https://github.com/nanograv/PINT/pull/861/files#diff-f55fe8ee2b68f58a8c9409c4fc2fcb07f2e1540c64b599975ab42b4ab046d9c8R180

**Comment by aarchiba** [comment]
No, I think that test case is sort of fine? Hmm. All the TOAs are nominally at the same frequency so I didn't expect them to constrain the DM at all but I guess the Earth Doppler shift is enough to overwhelm the initially very weak DM constraints. Now it it seems to very crudely work. Still looking for examples that can trigger problems; the fitting is complicated internally.

**Comment by aarchiba** [comment]
Would an expansion of make_fake_toas to include wideband TOAs provide a useful tool for testing this out? There are some statistical tests one can use to check error bars, or one could construct an example where the error bars made sense. (The statistical tests might have to live outside the test suite, they'll take some time to run, but they can provide ground truth on error bars.)
