### ISSUE TITLE
clock correction file directories

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#856]
Our observatory class has the ability to set the observatory clock correction files (any arbitrary directory ). 

https://github.com/nanograv/PINT/blob/4c2f1ad9d669187b2cb59523135c30b4c521bf30/src/pint/observatory/topo_obs.py#L52-L57

However there is no straight ward APIs in the toa module. We should fix this.

**Comment by dlakaplan** [comment]
#1247 fixed this
