### ISSUE TITLE
compute_pulse_numbers is failing

### ISSUE THREAD

**Issue by almcewen0** [nanograv/PINT#858]
recently updated my PINT install, and I am working on timing a pulsar from scratch. in order to deal with phase wraps, I am trying to use pulse numbers (there was recently an update to allow the fitters to use this). however, compute_pulse_numbers is throwing two ValueErrors:
 
ValueError: cannot broadcast a non-scalar to a scalar array
ValueError: attribute obstime should be scalar or have shape (), but is has shape (1,) and could not be broadcast.

**Comment by scottransom** [comment]
@almcewen0 Can you please show how this is happening and when?  Are you passing pulse numbers in a .tim file?  Or doing something else?  And how many TOAs are in your fit?

**Comment by almcewen0** [comment]
I am trying to just do this after loading the TOAs and the model. so I create both of those and then use toas.compute_pulse_numbers(model), which fails. I have 243 TOAs in my fit, and it is a long-period binary pulsar with quasi-initial guesses (been timing it a while, but still haven't gotten all of them nailed down yet). would it be useful for me to attach the .tim and .par files?

**Comment by scottransom** [comment]
Are you sure that the .par file is valid?  i.e. can you run a fit with it or compute .phase using it?  I just tried t.compute_pulse_numbers(m) with the fit_NGC6440E.py example and it works fine.  So something is strange.

**Comment by almcewen0** [comment]
i can compute phase just fine, but the fitting fails and throws an error that "ValueError: Latitude angle(s) must be within -90 deg <= angle <= 90 deg, got 4226.879063133337 deg" which I also don't understand, because I don't have latitude in my model and i'm not trying to fit for position.

**Comment by aarchiba** [comment]
Yes, please, it would help to attach `.par` and `.tim` files and a simple series of python commands that trigger the problem. If you don't want the data to be public and can simplify it down so that it still triggers the problem that would be even better.

**Comment by almcewen0** [comment]
here is the par file...
[ell1_113020.txt](https://github.com/nanograv/PINT/files/5654679/ell1_113020.txt)

and here is the tim file. sorry for the weird extensions, GH won't let me post them with their normal extensions.

[CHIME_J2038+35_tempo2.txt](https://github.com/nanograv/PINT/files/5654701/CHIME_J2038%2B35_tempo2.txt)

**Comment by aarchiba** [comment]
The following test passes:
```python
def test_bug_858():
    parfile = os.path.join(datadir, "ell1_113020.par")
    timfile = os.path.join(datadir, "CHIME_J2038+35_tempo2.tim")

    model = get_model(parfile)
    toas = get_TOAs(timfile)
    toas.compute_pulse_numbers(model)
```
Have you got a current copy of the PINT from git? Have you run `pip install -e .` on it recently?

(P.S. are you okay with your `.tim` and `.par` files taking up permanent residence in PINT's test suite? If not, and we find the bug, I can come up with simplified versions that still trigger it. (Then fix the bug; the test is to make sure it doesn't come back.)

**Comment by almcewen0** [comment]
i have a developer cloned branch, and I did:

git fetch upstream 
git checkout master
git merge upstream/master

is this not to appropriate way to update to the newest version on the NG GH server? re: saving the files, i think it's fine for them to stay (if this turns out to be a real bug, that is!).

**Comment by aarchiba** [comment]
You might try `pip install -e .` in the PINT base directory, just to make sure you're using this version of PINT. Can you report whether running the commands I posted works for you or not?

**Comment by almcewen0** [comment]
Okay, I tried using pip and rerunning - no dice. It looks like the problem occurs after this step: "INFO: Computing PosVels of observatories and Earth, using DE421 [pint.toa]"

**Comment by almcewen0** [comment]
For reference, here is the code I am running:

import pint.toa as toa
import pint.models as mod

par='ell1_113020.par'
merged_toas='CHIME_J2038+35_tempo2.tim'
toas=toa.get_TOAs(merged_toas,usepickle=False)
model=mod.get_model(par)

toas.compute_pulse_numbers(model)

**Comment by paulray** [comment]
I just ran this and it worked fine:
```
#!/usr/bin/env python
from pint.models import get_model
from pint.toa import get_TOAs
from pint.fitter import WLSFitter

parfile = "ell1_113020.par"
timfile = "CHIME_J2038+35_tempo2.tim"

model = get_model(parfile)
toas = get_TOAs(timfile)
toas.compute_pulse_numbers(model)

ftr = WLSFitter(toas=toas,model=model,track_mode="use_pulse_numbers")
ftr.fit_toas()
ftr.print_summary()

```

Can you do `git checkout upstream/master` and try again?  If it fails, paste in the full error output.

**Comment by almcewen0** [comment]
still no good. here is the full traceback:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/opt/anaconda3/envs/pintdev/lib/python3.6/site-packages/astropy-4.1rc1-py3.6-macosx-10.9-x86_64.egg/astropy/coordinates/attributes.py in __get__(self, instance, frame_cls)
    111                         out = out._apply(np.broadcast_to, shape=instance_shape,
--> 112                                          subok=True)
    113                     else:

~/opt/anaconda3/envs/pintdev/lib/python3.6/site-packages/astropy-4.1rc1-py3.6-macosx-10.9-x86_64.egg/astropy/time/core.py in _apply(self, method, format, *args, **kwargs)
   1446         if apply_method:
-> 1447             jd1 = apply_method(jd1)
   1448             jd2 = apply_method(jd2)

~/opt/anaconda3/envs/pintdev/lib/python3.6/site-packages/astropy-4.1rc1-py3.6-macosx-10.9-x86_64.egg/astropy/time/core.py in <lambda>(array)
   1436         if callable(method):
-> 1437             apply_method = lambda array: method(array, *args, **kwargs)
   1438 

<__array_function__ internals> in broadcast_to(*args, **kwargs)

~/opt/anaconda3/envs/pintdev/lib/python3.6/site-packages/numpy-1.19.1-py3.6-macosx-10.9-x86_64.egg/numpy/lib/stride_tricks.py in broadcast_to(array, shape, subok)
    179     """
--> 180     return _broadcast_to(array, shape, subok=subok, readonly=True)
    181 

~/opt/anaconda3/envs/pintdev/lib/python3.6/site-packages/numpy-1.19.1-py3.6-macosx-10.9-x86_64.egg/numpy/lib/stride_tricks.py in _broadcast_to(array, shape, subok, readonly)
    117     if not shape and array.shape:
--> 118         raise ValueError('cannot broadcast a non-scalar to a scalar array')
    119     if any(size < 0 for size in shape):

ValueError: cannot broadcast a non-scalar to a scalar array

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-6-5913ce5c7082> in <module>
----> 1 toas.compute_pulse_numbers(model)
      2 #toas.table['pulse_number'][toas.table['mjd']>Time(59030,scale='utc',format='mjd')]+=1

~/pint_development/PINTdev/src/pint/toa.py in compute_pulse_numbers(self, model)
   1238         # paulr: I think pulse numbers should be computed with abs_phase=True!
   1239         delta_pulse_numbers = Phase(self.table["delta_pulse_number"])
-> 1240         phases = model.phase(self, abs_phase=True) + delta_pulse_numbers
   1241         self.table["pulse_number"] = phases.int
   1242         self.table["pulse_number"].unit = u.dimensionless_unscaled

~/pint_development/PINTdev/src/pint/models/timing_model.py in phase(self, toas, abs_phase)
    981                 )  # TODO:needs timfile to get all toas, but model doesn't have access to timfile. different place for this?
    982                 self.validate()
--> 983             tz_toa = self.get_TZR_toa(toas)
    984             tz_delay = self.delay(tz_toa)
    985             tz_phase = Phase(np.zeros(len(toas.table)), np.zeros(len(toas.table)))

~/pint_development/PINTdev/src/pint/models/absolute_phase.py in get_TZR_toa(self, toas)
    102             include_gps=clkc_info["include_gps"],
    103             ephem=toas.ephem,
--> 104             planets=toas.planets,
    105         )
    106         self.tz_cache = tz

~/pint_development/PINTdev/src/pint/toa.py in get_TOAs_list(toa_list, ephem, include_bipm, bipm_version, include_gps, planets, tdb_method)
    268         t.compute_TDBs(method=tdb_method, ephem=ephem)
    269     if "ssb_obs_pos" not in t.table.colnames:
--> 270         t.compute_posvels(ephem, planets)
    271     return t
    272 

~/pint_development/PINTdev/src/pint/toa.py in compute_posvels(self, ephem, planets)
   1581                 ssb_obs = site.posvel(tdb, ephem, grp)
   1582             else:
-> 1583                 ssb_obs = site.posvel(tdb, ephem)
   1584 
   1585             log.debug("SSB obs pos {0}".format(ssb_obs.pos[:, 0]))

~/pint_development/PINTdev/src/pint/observatory/topo_obs.py in posvel(self, t, ephem)
    329         earth_pv = objPosVel_wrt_SSB("earth", t, ephem)
    330         obs_geocenter_pv = gcrs_posvel_from_itrf(
--> 331             self.earth_location_itrf(), t, obsname=self.name
    332         )
    333         return obs_geocenter_pv + earth_pv

~/pint_development/PINTdev/src/pint/erfautils.py in gcrs_posvel_from_itrf(loc, toas, obsname)
    243     t = ttoas
    244 
--> 245     pos, vel = loc.get_gcrs_posvel(t)
    246     r = PosVel(pos.xyz, vel.xyz, obj=obsname, origin="earth")
    247     if unpack:

~/opt/anaconda3/envs/pintdev/lib/python3.6/site-packages/astropy-4.1rc1-py3.6-macosx-10.9-x86_64.egg/astropy/coordinates/earth.py in get_gcrs_posvel(self, obstime)
    690         """
    691         # GCRS position
--> 692         gcrs_data = self.get_gcrs(obstime).data
    693         obsgeopos = gcrs_data.without_differentials()
    694         obsgeovel = gcrs_data.differentials['s'].to_cartesian()

~/opt/anaconda3/envs/pintdev/lib/python3.6/site-packages/astropy-4.1rc1-py3.6-macosx-10.9-x86_64.egg/astropy/coordinates/earth.py in get_gcrs(self, obstime)
    664         from .builtin_frames import GCRS
    665 
--> 666         itrs = self.get_itrs(obstime)
    667         # Assume the observatory itself is fixed on the ground.
    668         # We do a direct assignment rather than an update to avoid validation

~/opt/anaconda3/envs/pintdev/lib/python3.6/site-packages/astropy-4.1rc1-py3.6-macosx-10.9-x86_64.egg/astropy/coordinates/earth.py in get_itrs(self, obstime)
    642         # do this here to prevent a series of complicated circular imports
    643         from .builtin_frames import ITRS
--> 644         return ITRS(x=self.x, y=self.y, z=self.z, obstime=obstime)
    645 
    646     itrs = property(get_itrs, doc="""An `~astropy.coordinates.ITRS` object  with

~/opt/anaconda3/envs/pintdev/lib/python3.6/site-packages/astropy-4.1rc1-py3.6-macosx-10.9-x86_64.egg/astropy/coordinates/baseframe.py in __init__(self, copy, representation_type, differential_type, *args, **kwargs)
    599                 # Validate attribute by getting it.  If the instance has data,
    600                 # this also checks its shape is OK.  If not, we do it below.
--> 601                 values[fnm] = getattr(self, fnm)
    602             else:
    603                 setattr(self, '_' + fnm, fdefault)

~/opt/anaconda3/envs/pintdev/lib/python3.6/site-packages/astropy-4.1rc1-py3.6-macosx-10.9-x86_64.egg/astropy/coordinates/attributes.py in __get__(self, instance, frame_cls)
    118                         "attribute {} should be scalar or have shape {}, "
    119                         "but is has shape {} and could not be broadcast."
--> 120                         .format(self.name, instance_shape, out.shape))
    121 
    122                 converted = True

ValueError: attribute obstime should be scalar or have shape (), but is has shape (1,) and could not be broadcast.

**Comment by paulray** [comment]
Hmm. I know we've had some problems with python3.6 in travis recently. I think it may have some trouble with certain versions of astropy/numpy.  I see you are using an anaconda python install. You don't have the pint-pulsar conda package installed, do you?

I would try upgrading astropy and numpy and see if the problem goes away.  Otherwise, can you try using python 3.7 or 3.8?

**Comment by scottransom** [comment]
Note:  this is *not* a Python 3.6 issue.  I just ran successfully the script that @paulray had above with Python 3.6.  However, it *could* be an astropy or some other dependency issue, I guess.

Here are my versions:

```
Python 3.6.9 (default, Sep 11 2019, 15:18:54) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy
>>> astropy.__version__
'4.1'
>>> import numpy
>>> numpy.__version__
'1.17.4'
```

**Comment by almcewen0** [comment]
Within the conda environment, I cloned the pint repo and then did `python ./setup.py develop`. I will try updating my other packages

**Comment by aarchiba** [comment]
I'm not sure it's actually different, but can you try installing with `pip install -e .` instead? That will ensure all dependencies are versions accepted by PINT (and also do an editable install like `develop`).

**Comment by almcewen0** [comment]
yep, that's what I did earlier, but I'm still getting the error. 

Also, my numpy version is 1.19.1, and my astropy version is 4.1rc1

**Comment by dlakaplan** [comment]
I don't know - this worked for me.
```
conda create -n pint_test python=3.7
source activate pint_test
pip install -Ur ~/pythonpackages/PINT/requirements_dev.txt 
(pint_test) margle[~/pythonpackages]$ git clone git@github.com:nanograv/PINT.git PINT_alex
(pint_test) margle[~/pythonpackages]$ cd PINT_alex/
(pint_test) margle[~/pythonpackages/PINT_alex]$ pip install -e .
In [1]: import pint.toa as toa
   ...: import pint.models as mod
In [2]: par='ell1_113020.par'
   ...: merged_toas='CHIME_J2038+35_tempo2.tim'
In [6]: toas=toa.get_TOAs(merged_toas,usepickle=False)
In [7]: model=mod.get_model(par)
In [8]: toas.compute_pulse_numbers(model)
```

**Comment by dlakaplan** [comment]
Or more compactly:
```
conda create -n pint_test python=3.7
source activate pint_test
git clone git@github.com:nanograv/PINT.git PINT_alex
pip install -Ur PINT_alex/requirements_dev.txt
cd PINT_alex && pip install -e . && cd ../
python -c "import pint.toa as toa; import pint.models as mod; par='ell1_113020.par'; merged_toas='CHIME_J2038+35_tempo2.tim'; toas=toa.get_TOAs(merged_toas,usepickle=False); model=mod.get_model(par); toas.compute_pulse_numbers(model)"
```
runs fine for me.  The astropy version is 4.2

**Comment by paulray** [comment]
My bet is that 4.1rc1 is the problem

**Comment by almcewen0** [comment]
Okay, so i made a whole new conda environment and a new PINT install, and I've finally made it past this error. A bit unsatisfying, but at least it is fixed. thanks for all the help!
