### ISSUE TITLE
scaled_by_F0 is not used correctly

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#866]
https://github.com/nanograv/PINT/blob/5d4002fa4f619b45d8aae202aa4f97e244b4588e/src/pint/residuals.py#L252-L256

I commented on this in another PR, but `scaled_by_F0` has been broken.  It seems it was prior to the PR I commented on so I'm repeating here.

That is NOT intended to say whether time or phase residuals are being computed! It is a setting for how time residuals are computed from phases in calc_time_resids(). The default is to do it the way TEMPO/Tempo2 do it and convert from phase to time using model.F0. This is usually a good approximation for many pulsars. However, for some pulsars the current F can be a long way from F0 because of large frequency derivatives. In this case, the conversion should be done using get_PSR_freq(modelF0=False) which is MUCH slower but returns the local frequency using d_phase_d_toa.

**Comment by paulray** [comment]
Clearly what is needed is a test that shows the difference, e.g. using a par file with huge F1 (see NGC300 ULX-1).

**Comment by aarchiba** [comment]
I'm inclined to implement this in wideband_improvements (off-topic as it is). But just to check: the idea is that when converting phase to time or vice versa, the choice is between using the model F0 or the spin frequency predicted by the model at the time of the TOA? Both risk producing headaches during fitting, as they introduce an additional dependency of the residuals on F0.

**Comment by aarchiba** [comment]
I'm also worried that the assumption of constant F0 is baked into our process at other stages as well - for example, FFTFIT computes a phase shift, and the conversion to a TOA assumes something about the spin frequency.

**Comment by aarchiba** [comment]
This seems connected to #713 - perhaps I'll just remove the wrong implementation in #865

**Comment by aarchiba** [comment]
Wrong implementation removed. A correct implementation that solves the problem is a bigger challenge and maybe should be addressed under its own bug?

**Comment by paulray** [comment]
Closing this. Providing options for the phase->time conversion will be left for #713
