### ISSUE TITLE
Mask parameter does not alway keep the flag values in the same type

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#878]
The current maskParameter does not have the same format of flag values. This causes the problem of JUMP adding in the Nanograv timing analysis. 

Here is the line. 
https://github.com/nanograv/PINT/blob/ab6c0016e8edebc774a0e52e63b8ce004911169f/src/pint/models/parameter.py#L1369-L1370

**Comment by abhisrkckl** [comment]
Fixed.
