### ISSUE TITLE
fitter.model.scaled_toa_uncertainty_funcs problem

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#880]
I'm getting TOA uncertainties of 0.0 which is causing my fitter to crash. I tracked that to 
`fo.model.scaled_toa_uncertainty_funcs`, which is this:
```
[<bound method ScaleToaError.scale_toa_sigma of ScaleToaError(
     maskParameter(EFAC1 -f 430_PUPPI 1.069 ()),
     maskParameter(EQUAD1 -f 430_PUPPI 2.22629 (us)),
     maskParameter(TNEQ1 UNSET,
     maskParameter(EFAC2 -f L-wide_PUPPI 1.132 ()),
     maskParameter(EQUAD2 -f L-wide_PUPPI 1.22559 (us)))>]
```
The problem seems to be that I have TOAs at 327 MHz as well.  Apparently if you don't have an EQUAD/EFAC for a receiver, instead of leaving the error unscaled, it sets them to 0.0

**Comment by aarchiba** [comment]
I'm working on this.
