### ISSUE TITLE
Backwards-compatibility for writing tempo parfiles label:"feature request" 

### ISSUE THREAD

**Issue by pennucci** [nanograv/PINT#886]
What I'm thinking of is something that complements `model.as_parfile()`, which might be `model.as_tempo_parfile()`.  Or if a parfile-writing utility exists in PINT, then something like `write_parfile(model, format='tempo')`.  This would require adding the `CLK`, `TIMEEPH`, `T2CMETHOD`, and (probably) `INFO -f` lines, and if the fitter is `WidebandTOAFitter` (or, perhaps, if there is `DMJUMP` in the model), adding `DMDATA 1`.  There might be one or two other necessary lines to add (for tempo, not tempo2) that I've forgotten.  The would greatly facilitate sanity cross-checks with tempo (especially for wideband fitting) where appropriate.

**Comment by aarchiba** [comment]
I think the `CLK` is solved with #889 ; the others can probably be fixed by just adding them as Parameters.

**Comment by pennucci** [comment]
So is there a preference not to bloat PINT with convenience functions that would do this automatically?

**Comment by aarchiba** [comment]
Well, yes, but I think if we add them as Parameters then they are read in, manipulated, and written out as per normal. If there remain features of parfiles that are needed to maintain TEMPO/TEMPO2 compatibility upon writing, we could add a compatibility argument to `.as_parfile`.

**Comment by pennucci** [comment]
Oh, I understand now.  "adding them as Parameters" means in the actual code as recognized things upon reading an input parfile.  I read that reply a different way, as adding them as mystery parameters to an existing instantiated model object by hand, which could then be written.  Yeah, that makes sense.  It still does imply that you have to read in a tempo parfile _first_, as opposed to using PINT to do whatever with WB TOAs, run a fit with WidebandTOAFitter, and then being able to immediately do something like model.write_tempo_parfile.

**Comment by aarchiba** [comment]
Well, the way it will probably look is that if you read some random PINT par file, you'll get a model that has the parameter `T2CMETHOD` unset. If you write it out, unset parameters don't get written. But if you set `model.T2CMETHOD = "flying_monkeys"`, then it will be set and when the parfile is written there will be a helpful line to ensure TEMPO2 compatibility.

**Comment by pennucci** [comment]
Ok, that's sensible.
