### ISSUE TITLE
output parfiles can contain bogus CLOCK values

### ISSUE THREAD

**Issue by scottransom** [nanograv/PINT#896]
Now that CLOCK is recognized as a valid parameter, it will get written out (for example, `.as_parfile()`).  However, PINT only internally uses (I believe) TT(TAI) if we specify `include_bipm` = False or a TT(BIPMXXXX) if we specify the BIPM version (where XXXX is a year).

However, if we fit using TT(BIPMXXXX), the CLOCK parameter value does not get updated to TT(BIPMXXXX)

This is related to #886

**Comment by aarchiba** [comment]
Perhaps Fitter objects, at the end of their run, should set various parameters in the model, like START, FINISH, CLOCK... probably all the TOA-loading parameters should be set to match the ones in the TOAs object.
