### ISSUE TITLE
Availability of planet-SSB and planet-obs vectors for ephemeris modeling

### ISSUE THREAD

**Issue by Hazboun6** [nanograv/PINT#903]
In order to use `Pint`-based pulsars in `enterprise` along with the `BayesEphem` ephemeris model we need access to various solar system barycenter position vectors with respect to the Earth and various planets at each of the TOAs. This Issue directly relates to [Issue 238](https://github.com/nanograv/enterprise/issues/238) on the `enterprise` GitHub repo. @paulray has already submitted PR #901 to add the position vectors for Neptune. `BayesEphem` requires planet-ssb vectors, which can be calculated from the ssb-observatory and obs-planet vectors available in `Pint`. However we also need the earth-ssb vector for the ephemeris model, which can either be furnished directly or calculated from the obs-earth vector.

**Comment by Hazboun6** [comment]
There are use cases for other planet-ssb vectors, for instance PR [232](https://github.com/nanograv/enterprise/pull/232) adds in a modeling for perturbations from all planets. The minimal use for getting BayesEphem working for the 15 year data set is now the Earth-obs or Earth-ssb vector.

**Comment by luojing1211** [comment]
I think these two functions are what you need. 
https://github.com/nanograv/PINT/blob/88546389f0a3af4e943660bee2ff4b5754aca337/src/pint/solar_system_ephemerides.py#L203-L276

**Comment by aarchiba** [comment]
I think the request is that TOAs objects have, or be able to have, pre-computed vectors. This is close enough to true for all the non-Earth planets - there is the observatory-planet vector and the SSB-observatory vector - but there isn't a precomputed column that says anything about the geocenter.
