### ISSUE TITLE
Epoch averaging residuals doesn't work without ECORR

### ISSUE THREAD

**Issue by bshapiroalbert** [nanograv/PINT#909]
If we use the `epoch_average()` function in the `residuals` class and there is no `ECORR` in the model, it will crash with a warning. But if there is no ECORR, I have been told that this should end up being basically the limit of ECORR->0 and so should be just a weighted average of the residuals. It would be great if that functionality could be added so that you can epoch average the residuals without ECORR in the model. This will be particularly useful for the NANOGrav 15yr data pipeline for new pulsars.

**Comment by aarchiba** [comment]
I'm a little unclear on this - as I understand it, "epoch average" is meant to average all the TOAs that are grouped by ECORR. Is the intent to provide a default grouping?

**Comment by pennucci** [comment]
It looks like the relevant function is `ecorr_average`, not `epoch_average`; I'm not familiar with it, but I was involved in the discussion with @bshapiroalbert.  The relevant equations are Equations 36 & 37 in Appendix D of the NANOGrav 9-year data paper, which may be what's implemented in this function.  The 'problem' I guess is that if ECORR is not in the model, then there is no U matrix which can be used to get the binning/grouping of TOAs in an epoch for the weighted average.  So maybe, yes, @aarchiba, the intent is to make use of whatever default grouping the ECORR model uses.  The result @bshapiroalbert is looking for is what `ecorr_average` returns if all ECORRs are arbitrarily small.
