### ISSUE TITLE
TT(BIPM) does not recognised by get_model_and_toas()

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#911]
The models.get_model_and_toas() does not support the par file input TT(BIPM), which I think is for the latest version in TEMPO. It has BIPM in the string but without the version/year, this will search the BIPM file named"bipm" instead.

**Comment by scottransom** [comment]
This is kind of problematic right now.  Should TT(BIPM) load the latest or the default BIPM?  In PINT, those are currently different.  We could make them the same as a policy.  That might be good.

**Comment by luojing1211** [comment]
As long as we have one policy, it would be great.

**Comment by aarchiba** [comment]
I think making default-is-the-most-recent policy is a good idea; easy to implement and manage. And people who are concerned about replicability can't rely on defaults.

**Comment by scottransom** [comment]
I'm testing this on my local machine now.  If it works, I'll push it up.

**Comment by scottransom** [comment]
tox ran cleanly except for 2 issues with the test_widebandTOA_fitting.py.  And they fail due to the change of `bpim_default` from BIPM2015 to BIPM2019.  It seems that the tolerances on those tests are likely too stringent.
