### ISSUE TITLE
Add script to reproduce the performance table in the PINT paper

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#923]
We should make a script to produce the performance tables from the paper. It can be done similarly to this script, which shows how to use tempo_utils and tempo2_utils to call out to TEMPO and Tempo2: 
https://github.com/nanograv/PINT/blob/master/docs/examples-rendered/paper_validation_example.ipynb

**Comment by luojing1211** [comment]
This should be addressed by @champagne-cmd. Can you @paulray confirm and close it?
