### ISSUE TITLE
Problem with set_params

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#93]
My code is crashing when trying to print a model as a parfile after doing some fitting (with my own fitter).
The issue seems to come down to `set_params()` in fitter.py.  A simple example is below.
```
myfit = pint.fitter.fitter(toas=ts,model=modelin)
myfit.set_params({'T0':55000.0})
myfit.model.as_parfile()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-e212f792c2fb> in <module>()
----> 1 myfit.model.as_parfile()

/Users/paulr/src/PINT/pint/models/timing_model.pyc in as_parfile(self)
    328         result = ""
    329         for par in self.params:
--> 330             result += getattr(self, par).as_parfile_line()
    331         # Always include UNITS in par file. For now, PINT only supports TDB
    332         result += "UNITS TDB"

/Users/paulr/src/PINT/pint/models/parameter.pyc in as_parfile_line(self)
    198         if self.value is None:
    199             return ""
--> 200         line = "%-15s %25s" % (self.name, self.print_value(self.value))
    201         if self.uncertainty is not None:
    202             line += " %d %s" % (0 if self.frozen else 1, str(self.uncertainty))

/Users/paulr/src/PINT/pint/utils.pyc in time_to_mjd_string(t, prec)
    133     astropy does not seem to provide this capability (yet?).
    134     """
--> 135     jd1 = t.jd1 - erfa.DJM0
    136     imjd = int(jd1)
    137     fjd1 = jd1 - imjd

AttributeError: 'float' object has no attribute 'jd1'
```

Of course, it works if instead I do this:
```
myfit.set_params({'T0':astropy.time.Time(55000.0,scale='utc',format='mjd')})
```

But fitters usually work with bare numbers, not quantities (or times or angles). So, should `set_params` be setting `num_value` instead of value?  I'm not sure how it is  supposed to work with all the new changes recently.

Thoughts?

**Comment by paulray** [comment]
@luojing1211 and @vhaasteren - did you see this?  Fitters usually work with a vector of numerical values and call `set_params` repeatedly.  At least with `T0` if this is done, it ends up with an invalid value for the parameter (a `float` or `float128` instead of a `Time`)

**Comment by luojing1211** [comment]
I can see it. I have not test the set_params using num_value. But the idea for the num_value is to make fitter easier to operate. I can make a quick test.

**Comment by scottransom** [comment]
I'll try to take a look at this today.  Given the new params changes, there is quite a bit of fitter.py that can be cleaned up, I think.

**Comment by luojing1211** [comment]
I realize that MJDparameter class has a bug inside. The value is not set correctly. I am fixing it right now. After I fix it, it is easier to test fitter.

**Comment by scottransom** [comment]
I'm actually not convinced that we even need the MJDparameter class anymore....  Why can't MJDs just be part of the normal parameter class?  That can already handle other "strange" parameters like angles...

**Comment by luojing1211** [comment]
I think it make user a lot easier to handle MJD kind parameter. As the set up right now with a normal parameter class, user has to do like Parameter(...., get_value=time_from_longdouble, print_value=time_to_string, get_num_value=time_to_longdouble). It is kind of a lot work.

**Comment by demorest** [comment]
MJDParameter is part of the normal Parameter class (it's a derived class).  It's mainly just a convenience to avoid having to explicitly set the parse/print functions to the MJD-specifc ones every time.

**Comment by scottransom** [comment]
yeah, I'm not hugely against using derived classes and inheritance.  Although I think we should probably either do it for all of the "strange" params (i.e. Angles, times, MJDs) or none at all.

**Comment by paulray** [comment]
Stop calling some parameters "strange"! How do you think that makes them feel? 

:-)

**Comment by scottransom** [comment]
I keep looking for the "like" button...

**Comment by vhaasteren** [comment]
I agree with @scottransom. We should handle all custom (!) parameters with inheritance, or none. Either way would work for as far as I am concerned.

Design pattern wisdom says that if you can fix a problem with composition (properties would fall under that I suppose) rather than inheritance, we should.

**Comment by luojing1211** [comment]
In that sense, does prefixParameter have to become normal? Or a normal parameter should "grow" the properties of  prefixParameter.

**Comment by vhaasteren** [comment]
Right now, prefixParameter is an extension of the normal Parameter class. I think that is fine, and it is the logical reasoning.

Since prefixParameter should get all its functionality from Parameter, it makes sense that all the functionality of the custom parameters, like MJDParameter, are obtained through composition. Then prefixParameter can inherit those all from Parameter.

**Comment by scottransom** [comment]
OK, @vhaasteren ....  I've bee reading up on composition vs inheritance and I don't see why one would prefer composition to inheritance if the derived class only changes one or two methods from the parent class.  Seems like inheritance has a lot less code to write in those cases.  What am I missing?

**Comment by paulray** [comment]
I'd love to know where i could gain some design pattern wisdom

**Comment by vhaasteren** [comment]
In our specific case, the difference is probably not going to matter. As you say, we are only changing one or two methods from the parent class. So:
Inheritance: We derive a new class, and overwrite the method(s)
Composition: Simply overwrite the method (because it is Python after all). In C++, we would have a member object that contains the functionality we want (conversion of value), and we would have to change the type of that member object.

For us, since we are already working with those lambda functions that we provide at init of the Parameter, we can add/change functionality through those. No derivative classes needed.

As I said, it does not matter much. Thinking about it, it would probably be best to arrange things through composition, and have MJDParameter as a derived class for convenience, so it sets all the properties and attributes for the MJDParameter. MJDParameter could then also be an initialization function, rather than a derived class, to achieve the same thing.

I got my design pattern knowledge from this book, btw: http://www.amazon.com/Design-Patterns-Elements-Reusable-Object-Oriented-ebook/dp/B000SEIBB8
Not a Python oriented book, so perhaps not the best one to recommend right now.

**Comment by luojing1211** [comment]
It is kind of annoying when add parameters we have to input arguments like parse_value, print_value, and get_value every time.

Can we do something like if the unit is 'MJD', Parameter class will switch to MJD mode, which has the right lambda functions setup, like Rutger said. Correct me if I misinterpret what you said.

**Comment by scottransom** [comment]
But with composition, for the methods that you don't override, don't you have the extra overhead of having to call them via the embedded "parent" class?  For example, if the "parent" class is initialized as .self.parent in the child class, then to call the non-overrided methods, you have to do self.parent.method() rather than just self.method() if you had used inheritance....

@luojing1211 For those methods, you should only have to specify them when you have something strange, IMO.  Otherwise they should all expect floats (or long doubles possibly).

**Comment by demorest** [comment]
Yes, I was going to write a similar reply as Rutger.. Parameter already works mainly by composition, you replace the default parse/print functions to get different behavior.  I guess MJDParameter didn't really need to be a derived class, it could have just been a function that returns a normal Parameter with its properties set correctly for MJDs (this is all it's doing now actually).

I think the main thing we want to avoid is adding a bunch of special-case if/then type code to the basic Parameter class to deal with different parameter types...

**Comment by luojing1211** [comment]
New update with MJDparameter issue. #95

**Comment by vhaasteren** [comment]
Agreed with @demorest. By the way, MJDParameter is definitely useful as a convenience. We can add several others like MJDParameter as well. But we don't have to rely on inheritance to provide the functionality.

@scottransom, I am not quite sure I understand what you are saying. For composition, you never have to go through the 'parent'. You just change the attribute/member of the current class. So you just do self.method. (or in C++ you do self.obj.method). That is the way we are doing it already, so nothing really changes.

**Comment by scottransom** [comment]
@vhaasteren   What I meant was like the Composition example found here at the bottom of this page.  http://learnpythonthehardway.org/book/ex44.html

They override a method like you would do with inheritance.  But if you want to call a different method from the parent class, you need to make a "helper" method like self.implicit() that calls the parent method.  Or you could call it directly with self.other.implicit().  But both of those things seem less useful than just inheriting the method and being able to use it.

Am I missing something?

**Comment by vhaasteren** [comment]
@scottransom Yes, that is true. You would need a 'helper' method. But that is true for inheritance as well if you do it the true OOP way, where you have an abstract base class. Then you define an abstract/virtual prototype of that function, and fully define it in the child class. I don't think composition is less useful, or straining in terms of overhead. It is just a different approach that is often easier in the long term.

Fortunately, in Python that is moot. We can just replace the actual function (what we do with the lambdas), which in a way is a form of composition.

**Comment by luojing1211** [comment]
I believe this issue has been fixed now. Can we close it?

**Comment by paulray** [comment]
At least on the master branch, my example above now generates this error:
```
In [14]: myfit.set_params({'T0':55000.0})
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-b06fff610108> in <module>()
----> 1 myfit.set_params({'T0':55000.0})

/Users/paulr/src/PINT/pint/fitter.py in set_params(self, fitp)
     54             if modval is None:
     55                 raise RuntimeError('Paramter ' + p + ' is non-fitable.')
---> 56             getattr(self.model, p).num_value = val
     57 
     58     def minimize_func(self, x, *args):

/Users/paulr/src/PINT/pint/models/parameter.py in num_value(self, val)
    174                 self.value = self._num_value*self.num_unit
    175             else:
--> 176                 self.value = self.get_value(self._num_value)
    177 
    178     # Setup num_unit property

/Users/paulr/src/PINT/pint/models/parameter.py in <lambda>(x)
    272         self.parse_value = lambda x: time_from_mjd_string(x, time_scale)
    273         self.print_value = time_to_mjd_string
--> 274         self.get_value = lambda x: longdouble_from_mjd_string(x, time_scale)
    275         self.get_num_value = time_to_longdouble
    276         self.paramType = 'MJDParameter'

NameError: global name 'longdouble_from_mjd_string' is not defined

```

I can't find where `longdouble_from_mjd_string` is defined anywhere.

**Comment by luojing1211** [comment]
whoops. That is a typo bug. Let me fix it.

**Comment by luojing1211** [comment]
It should be fine right now.

**Comment by paulray** [comment]
Agreed, closing

**Comment by paulray** [comment]
Oops, the example fit fails.  Maybe another typo?
```
INFO: Reading toas from 'examples/NGC6440E.tim.pickle.gz'... [pint.toa]
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/table/column.py:268: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  return self.data.__eq__(other)
Fitting...
Traceback (most recent call last):
  File "examples/fit_NGC6440E.py", line 33, in <module>
    f.call_minimize()
  File "/Users/paulr/src/PINT/pint/fitter.py", line 88, in call_minimize
    method=method)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/optimize/_minimize.py", line 434, in minimize
    return _minimize_powell(fun, x0, args, callback, **options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 2331, in _minimize_powell
    fval = squeeze(func(x))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 285, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Users/paulr/src/PINT/pint/fitter.py", line 69, in minimize_func
    self.set_params(fitp)
  File "/Users/paulr/src/PINT/pint/fitter.py", line 56, in set_params
    getattr(self.model, p).num_value = val
  File "/Users/paulr/src/PINT/pint/models/parameter.py", line 161, in num_value
    self.value = self.get_value(self._num_value)
  File "/Users/paulr/src/PINT/pint/models/parameter.py", line 287, in <lambda>
    self.get_value = lambda x: Angle(x * self.separator[units.lower])
KeyError: <built-in method lower of str object at 0x10c5a1120>
```

**Comment by paulray** [comment]
Also many of the tests are failing.  For example:
```
mcxr2 : 148>py tests/test_parameter.py
Before assigning param1 value.
param1 num value is  None
param1 value is       None With type  <type 'NoneType'>
param1 unit is        H:M:S
param1 num unit is   hourangle
After assigning param1 value.
param1 num value is  19.5144444444
param1 value is       19h30m52s With type  <class 'astropy.coordinates.angles.Angle'>
param1 unit is        H:M:S
param1 num unit is   hourangle
Change num_values
param1 num value is  10.0
param1 value is       10.0 With type  <type 'float'>
param1 unit is        H:M:S
param1 num unit is   hourangle
Traceback (most recent call last):
  File "tests/test_parameter.py", line 38, in <module>
    parse_value=lambda x: time_from_mjd_string(x, scale='tdb'))
TypeError: __init__() got an unexpected keyword argument 'parse_value'
```

and

```
mcxr2 : 147>py tests/test_prefix.py

** (process:10890): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:10890): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:10890): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
WARNING: Unrecognized parfile line 'EPHVER              5' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'MODE                1' [pint.models.timing_model]
INFO: Applying clock corrections. [pint.toa]
INFO: Getting IERS params and computing TDBs. [pint.toa]
INFO: Computing observatory positions and velocities. [pint.toa]
INFO: SPICE loaded planetary constants. [pint.spiceutils]
INFO: SPICE loaded leap seconds. [pint.spiceutils]
INFO: SPICE loaded Earth rotation parameters. [pint.spiceutils]
INFO: SPICE loaded DE421 Planetary Ephemeris. [pint.spiceutils]
INFO: Loading /Users/paulr/src/PINT/datafiles/de421.bsp ephemeris. [pint.toa]
Traceback (most recent call last):
  File "tests/test_prefix.py", line 18, in <module>
    rs = pint.residuals.resids(t, m).phase_resids
  File "/Users/paulr/src/PINT/pint/residuals.py", line 10, in __init__
    self.phase_resids = self.calc_phase_resids()
  File "/Users/paulr/src/PINT/pint/residuals.py", line 21, in calc_phase_resids
    rs = self.model.phase(self.toas.table).frac
  File "/Users/paulr/src/PINT/pint/models/timing_model.py", line 87, in use_cached_results
    result = function(*args, **kwargs)
  File "/Users/paulr/src/PINT/pint/models/timing_model.py", line 141, in phase
    phase += Phase(pf(toas, delay))
  File "/Users/paulr/src/PINT/pint/models/glitch.py", line 82, in glitch_phase
    dphs = getattr(self, "GLPH_%d"%ii).value
AttributeError: 'prefixtest' object has no attribute 'GLPH_1'
```

**Comment by luojing1211** [comment]
L

**Comment by luojing1211** [comment]
Let me checkout the example. But the other two tests should be fine when we merge the prefix branch.

**Comment by luojing1211** [comment]
Can you try the example right now? The tests in tests file already get updated in prefix pull request.  After prefix pull request merged, you should see 3 failure due to some other reason.

**Comment by paulray** [comment]
Yep, the example runs now.  After prefix gets merged, we should track down all the test failures. Closing again.
