### ISSUE TITLE
DMJUMP and DMX uncertainties appear much too large

### ISSUE THREAD

**Issue by pennucci** [nanograv/PINT#932]
@aarchiba here is a pair of par/tim files demonstrating the issue I'm coming across when using DMJUMPs and DMX.  The solution has already converged in Tempo (albeit not with the fitting of DMJUMPs, that was done in Enterprise).  When freezing DMJUMPs (as in the parfile), the DMX uncertainties are ~several e-5, which is the expected level.  When one DMJUMP is freed, they remain similar in scale, and the DMJUMP has a similar uncertainty.  With both DMJUMPs free, however, the uncertainties of all DMX and DMJUMP parameters are all remarkably similar (down to ~single float precision), and are much too large (several hundred).  Freeing both DMJUMPs should not be degenerate w.r.t. DMX and a regular JUMP, provided the wideband TOAs contain a sufficient constrain on the mean DMX value.

```
from pint.models import get_model 
from pint.toa import get_TOAs 
from pint.fitter import WidebandTOAFitter

toas = get_TOAs("toas.txt")
model = get_model("parfile.txt")

fitter = WidebandTOAFitter(toas, model)
postfit_chi2 = fitter.fit_toas()
fitter.get_fitparams_uncertainty()  # quick look at uncertainties; agrees with TEMPO

model.free_params += ['DMJUMP1']  # free first DMJUMP
fitter = WidebandTOAFitter(toas, model)
postfit_chi2 = fitter.fit_toas()
fitter.get_fitparams_uncertainty()  # uncertainties still OK

model.free_params += ['DMJUMP2']  # free second DMJUMP
fitter = WidebandTOAFitter(toas, model)
postfit_chi2 = fitter.fit_toas()
fitter.get_fitparams_uncertainty()  # uncertainties totally whacky
```

[toas.txt](https://github.com/nanograv/PINT/files/5747732/toas.txt)
[parfile.txt](https://github.com/nanograv/PINT/files/5747733/parfile.txt)

**Comment by luojing1211** [comment]
This should be fixed. Can you confirm @pennucci ?

**Comment by pennucci** [comment]
Yeah, this is fixed (at least at face value!).
