### ISSUE TITLE
CI does not run make docs

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#935]
Tox only runs make docs if python 3.7 is available, which it isn't on our github-action. 

Ideally, a fix would not only run make docs to see if it worked but make available the generated docs to people reviewing the PR - we see a lot of changes with broken docstrings, and it's not easy to inspect new docs in un-merged PRs (I have a hack set up with readthedocs but it doesn't scale).

**Comment by paulray** [comment]
I just pushed a change to the Action to use Py3.7 for the docs run. That should at least be a partial solution.

**Comment by aarchiba** [comment]
oh, er, oops, I was pushing to change the tox run to use py38 (#936) :-P but thanks that should fix the docs run. I'll do some reading and see if I can get published docs out.

**Comment by paulray** [comment]
My quickfix failed....

https://github.com/nanograv/PINT/runs/1652302338

**Comment by paulray** [comment]
So, it is probably better to continue with your PR and make the docs compile under 3.8 and make the Action use 3.8

**Comment by paulray** [comment]
Note that on my local machine `tox -e docs` fails with both 3.7 and 3.8.  But, `make docs` works.

**Comment by aarchiba** [comment]
there's a dependency problem I think, chasing it now. Also I think maybe I know how to make the built docs available?

**Comment by aarchiba** [comment]
https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html We may want to have readthedocs build and serve docs for PRs - this might remove the necessity for this task. I can serve up docs built as part of Github Actions but they are available only as a zip file, which is not convenient. Unfortunately I think someone with Special Powers needs to turn on the readthedocs PR building.
