### ISSUE TITLE
No way to access data files for example code

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#942]
There is no easy way for users to locate example `.par` and `.tim` files, for example if they want to run our example notebooks or other sample code. The tests internally have a function meant to locate suitable `.par` and `.tim` files but these files are not installed as part of PINT and they can't easily be located from user code. 

It would be nice if the following worked, for any user with a working PINT installation:
```python
m = get_model(example_directory() / "NGC6440E.par")
```
One could then update the tests to behave this way also.

**Comment by dlakaplan** [comment]
Yes, this is actually something I was thinking of more broadly.  Can't we have the sample data installed in a similar way to how the ephemeris etc. are (make a `data/` stub in the installation area)?

**Comment by aarchiba** [comment]
The `setup.py`/`setup.cfg` machinery does have support for installing files that aren't python source code; we use this for observatory clock files already. We could arrange to have the example notebooks (?), python files (?), and input data installed somewhere when users `pip install`, and make a function `example_directory()` that knew how to locate them.

**Comment by aarchiba** [comment]
> Yes, this is actually something I was thinking of more broadly. Can't we have the sample data installed in a similar way to how the ephemeris etc. are (make a `data/` stub in the installation area)?

We certainly can; I have forgotten how we did it for the ephemeris stuff, maybe our code already just picks up every non-python file lying around? If it lives inside our source tree I believe we can find it programmatically using `__file__` and the like.

**Comment by dlakaplan** [comment]
In another project I'm part of it's installed through `pyproject.toml` which has a line:
```
include = ["vasttools/data", "example_notebooks"]
```
And then we reference it with:
```
BASE_MOC_PATH = pkg_resources.resource_filename(
    __name__, "./data/mocs/"
)
```
I think we can do something similar.

**Comment by dlakaplan** [comment]
OK, I have a WIP to address this in #1103 .  I haven't moved all of the files there but it works and we could choose appropriate name(s) to make `examples/`, `tests/`, etc all work.

**Comment by abhisrkckl** [comment]
This feature is now available via `pint.config.examplefile`.

**Comment by dlakaplan** [comment]
Yes, this is done
