### ISSUE TITLE
Incorrect docs

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#943]
https://github.com/nanograv/PINT/blob/e8ae8bf5067f69ed87cbbcb4a1ef475ce80b9cba/src/pint/observatory/__init__.py#L219-L220

I think the actual allowed values are 'default' and 'ephemeris', not 'astropy'.  @kerrm isn't that right?

**Comment by kerrm** [comment]
I agree, but only via inspection of the code -- I haven't looked at the
functionality to use a different ephemeris.

**Comment by aarchiba** [comment]
There isn't any functionality; only "default" works right now.
