### ISSUE TITLE
compare_model() fails when newly added parameter does not have uncertainty

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#951]
compare_model() compares the uncertainty difference between pre and post-fit model. However if the profit model has newly added parameter without any uncertainty, comparison will fail.

**Comment by pennucci** [comment]
We definitely would like this fixed for further v0 timing.  I made a local hack with a try/except clause, printing 0.0 instead of complaining about no error, but it's definitely not a fix.  @almcewen0, have you had a chance to look at this?

**Comment by almcewen0** [comment]
my apologies, last week became suddenly busy and I lost track of this. will work on it today.

**Comment by pennucci** [comment]
No worries, thanks!

**Comment by almcewen0** [comment]
okay, so i made a new branch in my repo called "compare_fix" and I think that I have addressed the problem. if someone would like to test it out, that would be great.

**Comment by pennucci** [comment]
@almcewen0 Perhaps you can open a WIP PR?

**Comment by almcewen0** [comment]
https://github.com/nanograv/PINT/pull/972

**Comment by pennucci** [comment]
Thanks!

**Comment by aarchiba** [comment]
I think this is fixed between #972 and #997 - and is covered by a test case in #997. Can it be closed?

**Comment by almcewen0** [comment]
yes, i believe it can.
