### ISSUE TITLE
Fitting ELL1H when H3, H4 are both zero

### ISSUE THREAD

**Issue by bshapiroalbert** [nanograv/PINT#956]
This issue stems from some issues that have come about from the F-testing with timing models that include the ELL1H binary model as part of the NANOGrav 15-yr dataset. I have tried to replicate as many errors as possible, but the major sticking point seems to be that if the ELL1H model has both H3 and H4, and they are both set to zero and are both frozen, there is a value error in the fit. If just H3 is in the model, the fit runs fine whether or not the starting value is zero and it is fit for or frozen. In general this error makes sense, as if you have H3 set to zero, you should not have H4, but it would be nice if you could have both of them set to zero without running into this error. An example par and tim file are attached here.

[Par_tim_Example.zip](https://github.com/nanograv/PINT/files/5844523/Par_tim_Example.zip)

<img width="1038" alt="Screen Shot 2021-01-20 at 1 29 16 PM" src="https://user-images.githubusercontent.com/33037158/105219105-0d98cc80-5b24-11eb-937f-4e6c64f753a5.png">

**Comment by luojing1211** [comment]
@pennucci Do you mean even without H3, H4 parameter, we can still use the ELL1H model? If they do not exist, it is just ELL1 model

**Comment by pennucci** [comment]
Yeah; I *think* one should still be able to use ELL1H even if H3 is not in the parfile, but right now, PINT throws an error.  I could be wrong, but I am also under the impression that the pseudo code could just be "if binary_model == 'ELL1H' and  'H3' not in model.params": use ELL1.  This would permit the easy adding/testing of H3 and H4 to low-eccentricity binaries that only just begin to show DS (i.e., H3).

**Comment by aarchiba** [comment]
Implementation-wise, PINT runs different code for ELL1 and ELL1H, implemented in different classes, so switching back and forth isn't so easy. If H3=H4=0 and frozen worked, you could just switch to ELL1H with just a one-letter change in the par file.

**Comment by pennucci** [comment]
I expected that PINT runs different code for ELL1 and ELL1H, but I must be missing something, because I don't see why ELL1H should not work if H3 is not included in a parfile specifying the ELL1H model any more than ELL1 should not work if M2 and SINI are not included in a parfile (but it does, of course).

**Comment by luojing1211** [comment]
#963 should fix this issue

**Comment by abhisrkckl** [comment]
Fixed
