### ISSUE TITLE
Degrees of freedom is wrong when model has red noise

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#960]
Whenever a fit is done with a model with red noise, there are a number of sinusoids fit out. These sinusoids' coefficients should be counted against the number of degrees of freedom on the resulting residuals, but they are not.

**Comment by pennucci** [comment]
I'm not sure about this.  I don't have a great reason or technical explanation, though.  The GLS fit is not actually fitting the red noise, which is modeled by a power-law with two fixed parameters and some specified number of components that probably should be specified in the model (the number of sinusoids; I think enterprise, tempo, and tempo2 had different defaults for this).  So at least in that sense, those parameters don't count against the DoF, as they are not allowed to vary.

**Comment by aarchiba** [comment]
Indeed the red-noise parameters in the par file are not fit for. But the coefficients of all those sinusoids are - and they must therefore be counted against the number of degrees of freedom.

**Comment by aarchiba** [comment]
I believe that if the assumptions are met then our non-`full_cov` is a good approximation to the `full_cov` fit, which does have the expected number of degrees of freedom, so I *think* this is not a problem.
