### ISSUE TITLE
numpy 1.20.0 causes failures

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#964]
As @champagne-cmd discovered, numpy 1.20.0 is out and our CI tests started using it. This causes some problems.

`numpy.genfromtext()` changed how it works and that causes `test_jump.py` to fail because it returns a list of arrays instead of just an array.

Also, we get lots of deprecation warnings from using `np.int` and `np.float` which they now recommend against.

Here are the full numpy 1.20 release notes:
https://numpy.org/devdocs/release/1.20.0-notes.html

**Comment by paulray** [comment]
Here are examples of some of the new warnings and deprecations. I think we should just fix these. There seems to be no downside.

tests/test_ddk.py:63
  /home/runner/work/PINT/PINT/tests/test_ddk.py:63: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if type(par).__name__ is "boolParameter":

tests/test_utils.py:312
  /home/runner/work/PINT/PINT/tests/test_utils.py:312: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.int,

tests/test_utils.py:314
  /home/runner/work/PINT/PINT/tests/test_utils.py:314: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.float,

**Comment by paulray** [comment]
I pushed a fix that solves the crash in the test, but @champagne-cmd would you mind going through and making a PR that fixes those deprecated uses of np.float and np.int?

**Comment by champagne-cmd** [comment]
Yes I will get on that!

**Comment by champagne-cmd** [comment]
@paulray is there preference for using `np.int64` or `np.int32` or `int`? Using the built-in `int` will have its precision vary based on the operating system being run on, whereas `np.int64` and `np.int32` specify their respective precision and don't vary based on os.

**Comment by aarchiba** [comment]
Is this resolved by #965? That is, can it be closed?
