### ISSUE TITLE
Issue with pint.models

### ISSUE THREAD

**Issue by physicsranger** [nanograv/PINT#97]
When trying to run the examples, I run into an issue every time it gets to the import pint.models step.  In model_builder.py there is a line "from .dd_wrapper import DDwrapper"
but in the pint/model directory there is no dd_wrapper.py file, though there is a dd.py file.

**Comment by physicsranger** [comment]
Looking at the code online here, that file is still under the pint/models directory, maybe I did something wrong in my download and install?

**Comment by luojing1211** [comment]
​Hi physicsranger,

Did you run setup.py already? If not try to do that first.

​

**Comment by physicsranger** [comment]
Hi Jing,
  Thanks for the quick reply.  Yes, I have run that to build and then install.  Is that the best way?  I can always try to uninstall and then reinstall things fresh.
  Tyrel

**Comment by luojing1211** [comment]
That should not matter. But we are in a major update now. So I recommend you wait for a little bit time. We will let you know when we done.

**Comment by paulray** [comment]
Closing for now.  Let us know if this problem occurs with the new model code.
