### ISSUE TITLE
UltraNest support

### ISSUE THREAD

**Issue by JohannesBuchner** [nanograv/PINT#971]
Would you be interested to add support for https://johannesbuchner.github.io/UltraNest/ ?

UltraNest is a very reliable tuning-parameter-free algorithm. It should be very faster than emcee in low-dimensional problems.

It also supports resuming from disk and MPI parallelisation, if that is useful to you.

**Comment by scottransom** [comment]
Possibly.  I have a student who is going to investigate this.  I saw your post about UltraNest on Facebook a couple weeks ago.

**Comment by aarchiba** [comment]
What would be required to make PINT easy to use from UltraNest? It seems to me that one might well want to use a sampler at the top level, possibly through MPI, and have it use PINT for likelihood evaluation (and maybe also obtaining a list of parameters to fit, possibly including priors) - what is needed to make that easy? Perhaps just a log-likelihood function that takes a vector of parameter values and returns the log-likelihood including noise models? Derivatives? Presumably analytical marginalization can't avoid a certain amount of custom code.

**Comment by JohannesBuchner** [comment]
You probably want to write a program like here: https://johannesbuchner.github.io/UltraNest/performance.html#usage-in-a-program which defines prior&likelihood using PINT, passes these to ultranest and does something with the output. So ultranest does not need to be at the top level.

Running with MPI is explained at the end of that page.

Derivatives are not needed.

**Comment by aarchiba** [comment]
It seems as if, generically, nested samplers need a log_likelihood and a transforming form of the priors; while emcee and the like need the same log_likelihood and a log-prior-probability function. These should be easy for PINT to provide, making plugging it into most samplers very easy.

emcee has "blobs", additional data that can be associated with an accepted sample and kept around for later analysis. I found this quite useful for storing results that were computed as part of the (expensive) likelihood calculation, for example maximum-likelihood values of analytically-marginalized-out parameters. Can UltraNest store such blobs?

**Comment by JohannesBuchner** [comment]
Yes, additional columns can be added (derived_param_names), should be computed in the transform function and are then available to the likelihood function.

As it is not as commonly used, this is not the most tested part of the code. If you run into issues, bug reports are appreciated.

**Comment by abhisrkckl** [comment]
The recently introduces `pint.bayesian` module can be used to combine PINT with UltraNest.
