### ISSUE TITLE
pint.toa.get_highest_density_range() not functioning with default arguments

### ISSUE THREAD

**Issue by poneill129** [nanograv/PINT#979]
If no arguments are passed to the get_highest_density_range() method; the default argument of ndays=7 is a unitless quantity meaning np.searchsorted tries to add a dimensionless quantity to an mjd quantity. Producing a UnitConversionError by default. Passing ndays as a quantity with unit 'days' rectifies this issue, so should probably do this by default. 

Possible fix is included below. Extra lines of the function

`def get_highest_density_range(self, ndays=7*u.d):`  <- Changed default argument to "7\*u.d"
`     """Print the range of mjds (default 7 days) with the most toas"""`
`        sorted_mjds = np.sort(self.get_mjds())`
`        s = np.searchsorted(sorted_mjds, sorted_mjds + ndays)` #<- Without change UnitConversionError occurs when computing sorted_mjds+ndays

**Comment by scottransom** [comment]
@clp3ef This is worthwhile for you to take a look at.  And I'll take a peek as well.  Maybe the proposed fix is good to go.

**Comment by aarchiba** [comment]
The proposed fix should fix the problem, and also signal to users that they should pass in a time with units. This would be a good first pull request maybe?

**Comment by aarchiba** [comment]
The code is here: https://github.com/nanograv/PINT/blob/941fca8b36d32fd0ba5cd0886ee01febb320ec52/src/pint/toa.py#L1487
