### ISSUE TITLE
Unnecessary info/warnings reported by compare_models

### ISSUE THREAD

**Issue by swiggumj** [nanograv/PINT#984]
There are INFO/WARNING statements currently output by `compare_models` which are either too verbose/redundant, logging level is too high, or the language used doesn't quite make sense. I've attached a screenshot of one example, which can be reproduced on the psr/b1855+09/jks branch in timing_analysis. By default, I don't think START/FINISH/NTOA/CHI2 should be reported, but they could be info statements if verbosity is increased. If kept, changing the language would be a good idea, e.g.:
```
INFO: Parameter START has changed between these models
```
For T/F (or Y/N) parameters like `CORRECT_TROPOSPHERE` and `PLANET_SHAPIRO`, the language should change and info statements here would be better than warnings. I'd suggest something like:
```
INFO: Parameter CORRECT_TROPOSPHERE has changed (turned ON in model 2)
```

<img width="1123" alt="Screen Shot 2021-02-24 at 9 37 26 AM" src="https://user-images.githubusercontent.com/4108303/109025042-f9487200-7683-11eb-8423-576fa022ecfd.png">

**Comment by swiggumj** [comment]
Also it there's a spelling mistake in the "Check verbosity -- ..." line: with should be will.

**Comment by swiggumj** [comment]
Also it would be *really* nice to have info statements that say exactly where model1 and model2 come from (e.g. par file names, if available).

**Comment by almcewen0** [comment]
> Also it would be _really_ nice to have info statements that say exactly where model1 and model2 come from (e.g. par file names, if available).

is there some way to retrieve this info from a model? my impression is that there was not. otherwise, i agree

**Comment by paulray** [comment]
It would be nice if when a model was loaded from a par file there was some metadata kept with the object saying what file it was loaded from.  @luojing1211 ?

**Comment by scottransom** [comment]
Yeah, I'm surprised this isn't already in there.  model_builder has a .name method that defaults to an empty string.  One possibility would be that get_model() sets name equal to the input parfile name.  That is a one-line addition to the code and could be pushed up now if people wanted it.

**Comment by scottransom** [comment]
That is actually kind of a nice solution as it lets "name" be used for whatever you want if you create a model from scratch.  But if you use get_model() or get_model_and_toas(), which both read parfiles explicitly, it uses that attribute that is already there to hold the filename.
